### PR TITLE
De-duplicate code within InductionVariable.cpp

### PR DESCRIPTION
**Pull request by amankumar1**
De-duplicate code from `TR_LoopStrider::examineTreeForInductionVariableUse()` and create the function `TR_LoopStrider::examineOpCodesForInductionVariableUse()` for it.

### CODE REVIEW

**Comment by mgaudet** [comment]
We should get these two commits squashed before merge. 

As well, can we make sure Vijay approves this before merge?

**Comment by mgaudet** [comment]
The commit message could use some work. Take a look at CONTRIBUTING.md for guidance.

**Comment by mgaudet** [comment]
(To be specific, the header line is far too generic)

**Comment by amankumar1** [comment]
Made the required changes

**Comment by mgaudet** [comment]
Hey @vijaysun-omr -- You're probably the best person to look at this and verify the new function name makes sense. 

There is a small change introduced here as well -- in the duplicated code section, they differed slighly in where they queried for bitness: In the terms of the extracted method -- one copy checked `replacementNode`, the other checked `node` -- the hypothesis here is that it shouldn't matter, but we want to be sure.

**Pull request merged**
