### PR TITLE
Remove github credentials

### PR DESCRIPTION
**Pull request by jdekonin**
Signed-off-by: Joe deKoning <joe_dekoning@ca.ibm.com>

### CODE REVIEW

**Comment by jdekonin** [comment]
Jenkins build zos

**Comment by jdekonin** [comment]
Jenkins build zos

**Comment by jdekonin** [comment]
Jenkins build zlinux

**Comment by jdekonin** [comment]
Jenkins build zlinux,zos

**Comment by AdamBrousseau** [comment]
Jenkins build zos

**Comment by AdamBrousseau** [comment]
@0xdaryl this is a functioning workaround. Likely only tested on machine 9 so far, which seems to have failed tests. It's a new machine. I should be able to make it work on the existing machines (3,4).

**Comment by AdamBrousseau** [comment]
Jenkins build all

**Comment by jdekonin** [comment]
Resolved via #6250

**Pull request closed without merging**
