### PR TITLE
Create OMR_<LANG>_WARNINGS_AS_ERROR_FLAG CMake variables

### PR DESCRIPTION
**Pull request by fjeremic**
See each commit for a description of what was done and why. Also see #6053 for an explanation of why we had to change to a per language flag definition.

Closes: #6053

### CODE REVIEW

**Comment by fjeremic** [comment]
Jenkins build all

**Comment by fjeremic** [comment]
Jenkins build all

**Comment by fjeremic** [comment]
Jenkins build all

**Comment by fjeremic** [comment]
@dnakamura could you please review? We can continue adding more flags for other languages as we move forward. This just sets up the foundation of how to do it and uses four examples (C/C++/NASM/MASM).

**Comment by fjeremic** [comment]
@dnakamura gentle nudge about the review request above.

**Review by dnakamura — APPROVED** [review]
Looks good.

**Review by dsouzai — APPROVED** [review]

**Pull request merged**
