### PR TITLE
Remove duplicate and non-extended methods in Instruction

### PR DESCRIPTION
**Pull request by jamesgua**
setOpCodeValue is void since most setters are void

Signed-off-by: Tao Guan <james_mango@yahoo.com>

### CODE REVIEW

**Comment by jamesgua** [comment]
Keep getter/setter of OpCode methods at OMR::Instruction level and remove duplicated ones in each platform, for setOpCodeValue, checked that no references is checking the return value so remove it from each platform.

**Comment by knn-k** [comment]
Jenkins build all

**Comment by knn-k** [comment]
Segmentation fault with ppc linux.  It looks the same as Issue #6556.

```
03:58:25  30: [0;32m[----------] [m16 tests from AbsVPValueTest
03:58:25  30/30 Test #30: compunittest ......................***Exception: SegFault  0.35 sec
```

**Review by knn-k — APPROVED** [review]
LGTM.

**Comment by knn-k** [comment]
I am going to merge this PR tomorrow if there are no other comments.

**Pull request merged**
