### PR TITLE
WIP: Add C version of the Simple example to Jitbuilder sample programs

### PR DESCRIPTION
**Pull request by daytonallen**
The C version of the Simple example in this commit serves as a proposal
of how the C API would work. The main aim is to gain community feedback
and foster discussions surrounding the ergonomics of the API.

Issue: #3197
Signed-off-by: Dayton J Allen daytonjallen@gmail.com

### CODE REVIEW

**Comment by Leonardo2718** [comment]
Thanks @daytonallen.

Following our [contribution guidlines](https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md), please update the following:

- Make the title of the commit message and PR less than 70 characters long
- Use the imperative mood for the commit message title
- Wrap the body of the commit message to 72 characters
- Sign the [ECA](https://accounts.eclipse.org/user/login?destination=user/eca)

**Comment by mstoodle** [comment]
Since `TDInit()` and `MBInit()` seem to be allocating the memory for a `TypeDictionary` and `MethodBuilder`, respectively, how do these structures get deallocated?  I don't see corresponding `TDDestroy()` and `MBDestroy`, or similarly named, functions called before shutting the JIT down, so are you assuming that `JBshutdownJit()` destroys them automatically?

**Comment by daytonallen** [comment]
@Leonardo2718 I've gone ahead and made the updates. Not sure what the issue is with the ECA since I've already signed and verified it on the ECA validation tool.

Thanks for the catch @mstoodle I've gone ahead and added the respective destructors.

**Comment by Leonardo2718** [comment]
Instead of two commits, can you squash them, using the commit message from the second commit, and force push?

The ECA issue may just be a delay in the Eclipse system.

**Comment by daytonallen** [comment]
Done.

**Comment by 0xdaryl** [comment]
Thanks for the contribution.  The source file also requires a copyright header, similar to other files but indicating your authorship.  See the sample at the end of CONTRIBUTING.md.

**Comment by daytonallen** [comment]
@0xdaryl I've now added the copyright header

**Comment by Leonardo2718** [comment]
@daytonallen 

I'm not sure why the IP validation keeps failing. I've manually checked the email and Eclipse does find a valid ECA for you.

**Comment by daytonallen** [comment]
@Leonardo2718 I've check the details of the log just now and it says 
`The following users have invalid Signed-off-by footers:
daytonjallen@gmail.com`

Not sure what's wrong with the footer I used though.

**Comment by Leonardo2718** [comment]
Oh I think I got it. The format is not quite right. Did you sign-off the commit using `git commit -s`?

**Comment by daytonallen** [comment]
@Leonardo2718 That was the problem, thanks! I incorrectly manually signed off.

**Comment by mstoodle** [comment]
Shouldn't you destroy the method builder before you destroy the type dictionary? just to keep things scoped consistently? (and since the methodbuilder has a pointer to the type dictionary...)

**Comment by daytonallen** [comment]
@mstoodle I've gone ahead and made the change

**Comment by daytonallen** [comment]
Closing since this is being contributed in #3859.

**Pull request closed without merging**
