### PR TITLE
Memoize getLongestPathOfDAG() to run in O(nlogk)

### PR DESCRIPTION
**Pull request by jdmpapin**
where n is the number of nodes in the subtree, and k is the number of nodes found by getLongestPathOfDAG() in the same extended block.

The previous implementation was O(n^2 logn) because it allowed each node to be queued multiple times, up to the max path length.

### CODE REVIEW

**Comment by jdmpapin** [comment]
This survived tests in J9 with a `TR_ASSERT_FATAL` checking that the results are always the same as the previous implementation

**Comment by vijaysun-omr** [comment]
@andrewcraik should also review this

**Comment by andrewcraik** [comment]
The implementation itself looks good. I do see that there can be a number of calls to this since this helper is called from isSafeToReplaceNode and was wondering if there would be an opportunity to cache results between calls to save re-computation, but I don't think that is likely given the current usage of isSafeToRepalceNode. @jdmpapin do you agree with this assessment?

Otherwise I think the code looks fine and is a good bit of clean-up.

**Comment by jdmpapin** [comment]
Now that you mention it, I think the results for each node can be memoized if they're computed bottom-up instead of top-down. Marking this WIP for the moment

**Comment by jdmpapin** [comment]
Updated to remember the value for each node within the extended block

**Comment by andrewcraik** [comment]
LGTM from me over to @vijaysun-omr since he is familiar with this part of the compiler.

**Comment by vijaysun-omr** [comment]
New implementation looks equivalent. Merging.

**Pull request merged**
