### PR TITLE
Add `lint` make target

### PR DESCRIPTION
**Pull request by noryb009**
Add an `lint` make target. This target builds and runs the OMR linter.

The OMR linter checks for common pitfalls, such as not using `self()->` when accessing methods of extensible classes from within another method of the class. Enabling the linter as a make target allows the linter to be more easily run, and can be easily integrated into continuous integration systems.

This PR also enables running the linter in Travis CI. It is currently only run on one build, since I do not believe linting the small amount of code different between x86-64 and x86 is worth slowing down more Travis CI builds for.

### CODE REVIEW

**Comment by rwy0717** [comment]
Why not just add a `make lint` target, and invoke that from travis? I don't think a configure option is necessary here.

**Comment by charliegracie** [comment]
I tend to agree with @rwy0717 comment and I am also worried about adding another "Env" to the current Travis builds.  Our builds are already getting behind since it appears we can only have 3 concurrent jobs running.  I actually have a todo to open an issue discussing removing one of the current linux specs if there is actually a limit on the number of concurrent jobs.

**Comment by noryb009** [comment]
@charliegracie This doesn't add another row to the build matrix, it changes an existing row to include running the linter. There is still only 4 build configurations tested.

I agree with your suggestion, @rwy0717 .

**Comment by charliegracie** [comment]
Sorry misread the diff so you can ignore my comment about adding an extra build environment.

**Comment by youngar** [comment]
LGTM!

**Pull request merged**
