### PR TITLE
Update and expand the commit guidelines

### PR DESCRIPTION
**Pull request by rwy0717**
Elaborate on the style guidelines for commit messages. These new
guidelines style reflect the conversation found in #124.

The guidelines are changed to:
- Provide guidance on how to write a good first line.
- Elaborate on formatting requirements.
- Relax the advice on using issues for nontrivial commits.
- Move issue references from the first line to the message footer.
- Encourage contributors to put more information into the commit
  message.

Issue: #124
Signed-off-by: Robert Young <rwy0717@gmail.com>

### CODE REVIEW

**Comment by mstoodle** [comment]
Looks pretty good, Robert!

Could you include an example of a well constructed commit (save time: maybe use the message you used for this one :) ) . If you're in a really good mood, you could also include some example(s) of commit message forms you would specifically like to avoid along with short constructive critiques. I think that would help make the document more concrete for people.

**Comment by rwy0717** [comment]
I added one good example, and one very bad one. We can expand it later, but for now I included a link to http://chris.beams.io/posts/git-commit/, where the author does a really good job of going over commit style.

**Comment by mstoodle** [comment]
I like it, though you hit a personal pet peeve on the phrase "way too little" :) .  But no worries.  I'll leave this open for a day to give others a chance to comment. If there are no additions, I'll merge it tomorrow.

Thanks, Robert!

**Comment by rwy0717** [comment]
Haha, what would you change it to?

**Comment by mstoodle** [comment]
"not enough meaningful" or something along those lines, maybe?

**Comment by charliegracie** [comment]
+1 I am good with these changes

**Comment by rwy0717** [comment]
I'll just change the one line to "There is not enough information for the commit message to be useful."

**Comment by mstoodle** [comment]
Thanks, Robert!

**Pull request merged**
