### PR TITLE
Use OSR method info to check for OSR blocks

### PR DESCRIPTION
**Pull request by jdmpapin**
IL (intermediate language) generation sometimes assumed that the IL for a method has OSR (on-stack replacement) code and catch blocks whenever `getOSRPoints()` is nonempty for that method. However, it's possible that all OSR points for the method belong to other inlined call sites, since the set of OSR points can differ when IL is generated for a single method repeatedly. For instance, symbol references that are unresolved when first inlining a method may be resolved when later inlining the same method again.

This commit changes IL generation to determine the presence or absence of the OSR code and catch block based on the OSR method info for the current inlined site index, without consulting `getOSRPoints()`.

### CODE REVIEW

**Comment by andrewcraik** [comment]
@ncough your two cents - looks good to me.

**Comment by ncough** [comment]
We base another decision on the size of `getOSRPoints()` in `genInduceOSRCall()` for the late addition of OSR infrastructure, however, this should never happen as indicated by the comment near that code. LGTM

**Comment by jdmpapin** [comment]
Was AppVeyor going to run anything using OSR? And if so, can we restart it? It just failed to check out the commit

**Comment by vijaysun-omr** [comment]
Just so I am completely clear, the case where the check that was being done originally would have been incorrect is if we had 2 different calls to the same method and these calls use the same symbol. We want to inline both calls and when we generate IL for the first call, we do not find any OSR points but when we generate IL for the second call, something (e.g. resolution) has changed leading to an OSR point being encountered. Since the symbol is the same, the second IL gen has now overwritten what the symbol had in the OSR points list from the first IL gen which leads to the wrong answer for the first inlined site. This commit gets the info from the OSR data instead and since that is specific to each inlined site, this fixes the problem.

**Comment by vijaysun-omr** [comment]
@jdmpapin is my understanding correct ?

**Comment by jdmpapin** [comment]
That's close. We don't clear out `getOSRPoints()`. Instead it holds the OSR points for *every* call site where the method was inlined. Each OSR point has bci that identifies the site it belongs to.

The problem scenario I saw does involve inlining the same method twice, sharing the same `ResolvedMethodSymbol`, but where the *first* site has at least one OSR point, and the *second* has none. When this happens, no OSR blocks are created for the second site, because they're unnecessary. Without this change, we would nonetheless attempt to attach the second site's (nonexistent) OSR blocks to the trees, simply because there are OSR points on the method symbol (belonging to the first site).

An OSR point can disappear when we have an unresolved symref resulting in a `ResolveCHK` where there would otherwise not have been an OSR point. When generating IL for the same method again later, we may no longer have an unresolved symref, because (say) a Java constant pool entry has been resolved in the meantime.

There could be other sources of variability in the set of OSR points generated by Java's IL generator, although I'm not aware of any. IL generators for other projects should probably be free to generate different sets of OSR points based on run-time state as well.

**Comment by vijaysun-omr** [comment]
Thanks, makes sense to me.

**Comment by jdmpapin** [comment]
Is there anything further I need to do before this can be merged? I [asked about AppVeyor](https://github.com/eclipse/omr/pull/1454#issuecomment-319750337) above, since I suspect that it might not test OSR anyway. Please let me know how to proceed

**Comment by vijaysun-omr** [comment]
I am merging because the appveyor "failure" is not a real issue.

**Pull request merged**
