### PR TITLE
Fix throw to goto transformation

### PR DESCRIPTION
**Pull request by jdmpapin**
When transforming throw into goto, VP (value propagation) now passes the
exception object to the predicted handler in `ExceptionMeta`, rather
than in an auto. This avoids problems in case the handler reads
`ExceptionMeta` more than once, or in case it overwrites the auto.
Additionally, the transformation can now succeed for every predicted
handler, regardless of the code within the handler.

The two calls to `performTransformation()` are now collapsed into a
single call. Previously the second call could have caused the
transformation to be abandoned when it was already partially done.

When `specializedDesyncCatchBlock` is set, VP now transforms the throw
unconditionally, instead of using `performTransformation()` to ask
permission. Previously an assertion would fail if permission were
denied.

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
Requesting @andrewcraik review this too.

**Comment by andrewcraik** [comment]
This looks good to merge - the performingTransformation logic clean up is good and I think the store to ExceptionMeta should be fine - it is certainly better than the store to the auto solution implemented previously. As long as @vijaysun-omr isn't aware of any issue using ExceptionMeta this way I think this should be good to merge.

**Comment by vijaysun-omr** [comment]
I do not have concerns from a functional standpoint. 

Our global dead store elimination pass probably does not operate on meta data sym refs (though in principle it could be taught to handle them as well). Neither does our escape analysis pass have any awareness of meta data sym refs being thread-local (and so a store to such a sym ref should not cause the object to escape). 

I wonder if this means that optimizations that might have been successful in eliminating an exception object completely (including potentially expensive operations like populating stack trace information in the exception object) would no longer be able to do so with this change.

**Comment by andrewcraik** [comment]
Given the functional issues with the previous implementation we should probably go for correctness and merge this to avoid the functional issues we have seen.

I do wonder if we could do some kind of debug counter to determine if we were able to completely eliminate the exception object as you suggested. One hack that jumped to mind would be to count in EA the number of objects with type names ending in Exception that are eliminated and see if that varies with and without this change...

**Comment by andrewcraik** [comment]
One side-effect of this change is that the exception object will no longer be in a temp - it will be in the ExceptionMeta object. @jdmpapin is going to do a few experiments to see if this change negatively affects common cases where this transform is currently used. Alternatives if we do find this clean-up negatively affects the result are to either make a more targeted bug fix or keep this fix and do some kind of ExceptionMeta -> temp transformation pass where possible.

@jdmpapin can you mark this as WIP until the experiments are done?

**Comment by andrewcraik** [comment]
@jdmpapin any update on this?

**Comment by jdmpapin** [comment]
@andrewcraik @vijaysun-omr Any performance impact from this change should be quite small. I've removed the WIP marker and rebased to bring it up to date (although it seems there have been a few merges in the meantime).

**Comment by vijaysun-omr** [comment]
@jdmpapin Thanks for doing the experiments to get to this point. I am merging this now.

**Pull request merged**
