### PR TITLE
Remove declaration and definition of movedObjectHashCode

### PR DESCRIPTION
**Pull request by KenCox94**
please see this [issue](https://github.com/eclipse/omr/issues/5851)

### CODE REVIEW

**Comment by bragaigor** [comment]
The changes look good. Here are some nitpicks so that the changes conforms with Eclipse guidelines. 
- Please remove the `+` at the beginning of the commit title.
- Instead of `Removed` please update to `Remove` (present tense)
- Fix typo "decleration" -> "declaration"

**Review by bragaigor — CHANGES_REQUESTED** [review]
The changes look good. Here are some nitpicks so that the changes conforms with Eclipse guidelines.
- Please remove the + at the beginning of the commit title.
- Instead of Removed please update to Remove (present tense)
- Fix typo "decleration" -> "declaration"

**Comment by KenCox94** [comment]
do I need to make a new pull request or can these changes be made here?

**Comment by bragaigor** [comment]
They can be done here. You'll have to rebase your commit and reword your commit message. This might help: https://docs.github.com/en/github/committing-changes-to-your-project/changing-a-commit-message

**Comment by bragaigor** [comment]
You're almost there, the `Signed-off-by: ` part must be it's own line. And commit lines cannot go beyond 70 characters I believe (they cannot be too long)

**Comment by KenCox94** [comment]
gotcha, give me a few. I need to change some settings so that I am signing with the correct email. apologies for all this.

**Comment by bragaigor** [comment]
That's okay, no rush!

**Comment by bragaigor** [comment]
Hi @KenCox94 . I was wondering if you completed the steps highlighted under "Legal considerations" here: https://github.com/eclipse/openj9/blob/master/CONTRIBUTING.md ?

**Comment by KenCox94** [comment]
Yes, I created my account with eclipse and signed the ECA.

**Comment by bragaigor** [comment]
If you click details on the right side of "eclipsefdn/eca" in `Details`, could you try to revalidate the ECA. For some reason the check above is not seeing you as ECA compliant (it checks against the email)

**Pull request closed without merging**
