### PR TITLE
Rename Test namespace to TestCompiler

### PR DESCRIPTION
**Pull request by noryb009**
The name "CompilerTest" is more suited to the contents of the previous "Test" namespace - the Test compiler.

While this is a large commit, the changes in each file are trivial.

### CODE REVIEW

**Comment by mgaudet** [comment]
But everywhere else we call it the 'Test Compiler'... shouldn't it be `::TestCompiler` then? (PS: Not strongly convinced of this one way or the other, but it's definitely the first thought that popped in my head)

**Comment by fjeremic** [comment]
I agree, we should go one way or the other, but not both.

**Comment by 0xdaryl** [comment]
This came from the historical convention of naming the namespace after the top-level directory the project resided in.  In this case, its following the established convention of directory names under `fvtest/`.

However, the directory-namespace mapping precedent is already broken since the compiler technology now resides in the top-level `compiler/` directory rather than `omr/'.  I'm indifferent, but `TestCompiler` is more of a noun than a verb and perhaps a more suitable choice for a namespace.

**Comment by noryb009** [comment]
I agree with the suggestion, and have updated the commits.

**Comment by noryb009** [comment]
@0xdaryl I've rebased and resolved the merge conflicts.

**Pull request merged**
