### PR TITLE
Change to not use "dos" line breaks

### PR DESCRIPTION
**Pull request by groeges**
Some files in util/hookable were modified to not use "dos" line breaks,
ie ^M which caused issues when building omr for OpenJ9 on an AIX
platform

Signed-off-by: Steven Groeger <groeges@uk.ibm.com>

### CODE REVIEW

**Comment by groeges** [comment]
This is a PR for issue: https://github.com/eclipse/omr/issues/1801

**Comment by DanHeidinga** [comment]
@charliegracie @0xdaryl @rwy0717 Can on the of the OMR committers restart the travis build?  The clang job fails for what looks like a machine config issue:
```
The command "if [ $TRAVIS_OS_NAME = osx ]; then brew install ccache ; fi" failed and exited with 1 during .
```

**Comment by charliegracie** [comment]
Travis OS X jobs that use homebrew are all broken with the latest updates to the build infrastructure by Travis.  @rwy0717 is working on a solution.  ALL PRs that currently have the homebrew failures will need to be rebased on the changes in his PR once it gets accepted

**Comment by charliegracie** [comment]
genie-omr build all

**Comment by charliegracie** [comment]
accepting without rebasing for the OS X fix since all other platforms worked successfully and this PR contains no OS X specific changes.

**Pull request merged**
