### PR TITLE
Convert non UTF-8 platform error string to UTF-8 on AIX.

### PR DESCRIPTION
**Pull request by hangshao0**
-Add support of platform encoding to UTF-8 conversion into
omrstr_convert().
-Fix convertMutf8ToPlatform() that is leaking iconv object.
-Covert the platform error string to UTF-8 if it is not UTF-8 on AIX.

issue: #470

Signed-off-by: Hang Shao <hangshao@ca.ibm.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
@hangshao0 Thanks.  Is it possible for this type of issue to be present on other platforms when we try to print out error messages?

**Comment by hangshao0** [comment]
The documentation of strerror() on AIX explicitly says that the error message is based on the current value of the LC_MESSAGES. We have this issue on AIX. And the documentation of strerror() on z/OS says it does not produce a locale-dependent error message string. We do not have this issue on z/OS.

Linux is somewhere in between, its documentation says: 
"**possibly** using the LC_MESSAGES part of the current locale to select the appropriate language. "

As nobody has ever complained on Linux, I have not changed anything on Linux. @charliegracie, I can include Linux in the fix if you think we need to.

**Comment by hangshao0** [comment]
Actually on Linux in the case the platform error string encoding is not based on current locale setting, converting the string from current locale encoding to UTF-8 will mess up the message. So this fix should only apply to AIX.

**Comment by hangshao0** [comment]
I have added the comment in.

**Pull request merged**
