### PR TITLE
WIP: Metronome cycle start tracing

### PR DESCRIPTION
**Pull request by amicic**
Introducing new trace points that may help with debugging long pauses
at the beginning of a GC cycle.

Signed-off-by: Aleksandar Micic <amicic@ca.ibm.com>

### CODE REVIEW

**Comment by amicic** [comment]
Setting as WIP for now, until I figure out if I can share this with a user in a custom diagnostic build.

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by amicic** [comment]
@charliegracie chances are I will not need this merged. I provided a custom build to a user and awaiting results. If it works out, we can cancel this. But if you see more general value (there is an accompanying OpenJ9 change)  we can merge it.

**Comment by charliegracie** [comment]
@amicic any decision on this PR?

**Comment by amicic** [comment]
The investigation was complete with a custom build. We can close this without merging.

**Comment by charliegracie** [comment]
As per Aleks comments I am closing

**Pull request closed without merging**
