### PR TITLE
Disable PriorityInterrupt on Linux riscv64

### PR DESCRIPTION
**Pull request by babsingh**
Related https://github.com/eclipse/omr/issues/6665

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by babsingh** [comment]
jenkins build riscv(env:'GTEST_FILTER=*PriorityInterrupt.*')

**Comment by babsingh** [comment]
jenkins build all

**Comment by babsingh** [comment]
jenkins build all

**Comment by babsingh** [comment]
jenkins build win

**Comment by babsingh** [comment]
@dsouzai Can you help merge this PR?

**Review by dsouzai — APPROVED** [review]

**Pull request merged**
