### PR TITLE
GC: update comment in MarkingDelegate::scanRoots()

### PR DESCRIPTION
**Pull request by janvrany**

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@amicic : please review this small change.

**Review by amicic — APPROVED** [review]

**Comment by amicic** [comment]
You may want to expand the comment (both in code and commit message) and say that markObject() besides obviously marking the object (if already not marked by another root) will push the object to the working stack for further scanning.

**Comment by amicic** [comment]
You may want to expand the comment (both in code and commit message) and say that markObject() besides obviously marking the object (if already not marked by another root) will push the object to the working stack for further scanning.

**Comment by 0xdaryl** [comment]
@amicic : do you want @janvrany to add that comment before this is merged?

**Comment by janvrany** [comment]
I have just updated the code.

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
