### PR TITLE
Create a C API for OMR low-level IL interface

### PR DESCRIPTION
**Pull request by dibyendumajumdar**
While there is a higher level JIT interface in the form of JITBuilder
api for which a C api is being worked on, having a C api for the lower
level IL interface is useful. In particular, the C api that is part of
this pull request was used to implement JIT backends for C as well as
Ravi, a derivative of Lua 5.3.

Signed-off-by: Dibyendu Majumdar <mobile@majumdar.org.uk>

### CODE REVIEW

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by dibyendumajumdar** [comment]
thank you @charliegracie  will look at the failures. At least one appears to be due to missing <mutex> header.

**Comment by Leonardo2718** [comment]
@dibyendumajumdar have you rebased recently?

**Comment by dibyendumajumdar** [comment]
I refreshed on the 23rd Feb so it is fairly recent

**Comment by pfalcon** [comment]
+1

**Pull request closed without merging**
