### PR TITLE
Cmake: Add OS helper variables

### PR DESCRIPTION
**Pull request by dnakamura**
Add OMR_OS_XYZ helper variables in cmake. This is inline with the
OMR_ARCH_XYZ variables

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@rwy0717 , would you mind reviewing please?

**Comment by rwy0717** [comment]
LGTM

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by charliegracie** [comment]
@genie-omr build win

**Pull request merged**
