### PR TITLE
Update to EPLv2 (now with correct license)

### PR DESCRIPTION
**Pull request by DanHeidinga**
Update the license as per the outcome of the vote in issue #1596.

This can't be accepted until all contributors in #1606 have signed off on the relicensing their contributions.

Updated to the correct version of the EPLv2 license:
```
Copyright (c) %s, %s IBM Corp. and others

This program and the accompanying materials are made available under
the terms of the Eclipse Public License 2.0 which accompanies this
distribution and is available at https://www.eclipse.org/legal/epl-2.0/
or the Apache License, Version 2.0 which accompanies this distribution and
is available at https://www.apache.org/licenses/LICENSE-2.0.

This Source Code may also be made available under the following
Secondary Licenses when the conditions for such availability set
forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
General Public License, version 2 with the GNU Classpath 
Exception [1] and GNU General Public License, version 2 with the
OpenJDK Assembly Exception [2].

[1] https://www.gnu.org/software/classpath/license.html
[2] http://openjdk.java.net/legal/assembly-exception.html

SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
```
and remove the 'contributor' sections based on email guidance from the Eclipse Foundation.

The following directories and files have been addressed in this PR:
```
lib
nls
omr
omr.rc.in
omr_glue_static_lib
omr_static_lib
omrcfg.CMakeTemplate.h
omrmakefiles
omrsigcompat
omrtrace
omrversionstrings.CMakeTemplate.h
perftest
port
run_configure.mk
scripts
third_party
thread
tools
util
```

### CODE REVIEW

**Comment by DanHeidinga** [comment]
FYI @keithc-ca

**Comment by charliegracie** [comment]
This will have to be rebased before it can be merged

**Comment by DanHeidinga** [comment]
Rebase complete.

**Comment by mstoodle** [comment]
The requirement in #1606 has been met: when it's ready, this PR can be merged.

**Comment by charliegracie** [comment]
Closing as the other PR containing these commits has been merged.

**Pull request closed without merging**
