### PR TITLE
Relocate createOrFindClonedNode, _uncommmonedNodes to OpenJ9

### PR DESCRIPTION
**Pull request by shivammittal99**
Closes: #2068 

Signed-off-by: Shivam Mittal <shivammittal99@gmail.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
ping @0xdaryl and @mstoodle

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by mstoodle** [comment]
there's a dependent PR at OpenJ9 which seems like it would be needed or else merging this could break openj9, so I'll be nice to them and not "just" merge this one even though it seems ready.

In future, maybe we could try to stage changes like this by first making the OMR code #ifdef J9_PROJECT_SPECIFIC, then copy it to OpenJ9, and then remove it from OMR. I know that's more pull requests and more work on the writing of commits, but it would certainly simplify and streamline the process to merge this kind of change.

**Comment by 0xdaryl** [comment]
Thank you for the contribution.  This work was subsumed by #3857.  Closing.

**Pull request closed without merging**
