### PR TITLE
Revert "Created Function Prototypes for OMRSocketAPI"

### PR DESCRIPTION
**Pull request by rwy7**
Reverts eclipse/omr#4346

### CODE REVIEW

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by Leonardo2718** [comment]
What's the reason for this revert?

**Comment by rwy0717** [comment]
Oh sorry, I should have said why in the first place.

The new header is including system headers, which in turn define symbols (`NO_DATA`), which conflict with symbols defined in J9. While arguably, J9 should be prefixing/namespacing all it's symbols, the compilation failure has raised a new issue. The use of system headers should be an implementation detail, and should have never been included into our publicly in the first place.

So now, I'm reverting the PR and the author is going to look at refactoring the omrportsock.h header to hide the system types.

**Pull request merged**
