### PR TITLE
Fix code cache segment race condition

### PR DESCRIPTION
**Pull request by mpirvu**
The first two fields of a TR::CodeCache data structures are `_warmCodeAlloc` and `_coldCodeAlloc` and they used by a third party (e.g. the JVM) to compute the amount of free space in the code cache. During the TR::CodeCache initialization we populate the _warmCodeAlloc and _coldCodeAlloc fields and then write a pointer to the TR::CodeCache structure at the beginning of the segment that provides memory for the code cache itself. Just before writing this pointer we need to issue a write memory barrier to ensure that the values of _warmCodeAlloc and _coldCodeAlloc are seen by another thread at the time when the pointer to the TR::CodeCache is written at the begining of the memory segment.

### CODE REVIEW

**Comment by mpirvu** [comment]
@dsouzai Could you please review and merge this PR? Thanks

**Review by dsouzai — APPROVED** [review]

**Comment by dsouzai** [comment]
@mpirvu the travisci builds are failing:
```
[ 60%] Building CXX object jitbuilder/CMakeFiles/jitbuilder.dir/__/compiler/runtime/OMRCodeCacheManager.cpp.o
/home/vsts/work/1/s/compiler/runtime/OMRCodeCache.cpp: In member function ‘bool OMR::CodeCache::initialize(TR::CodeCacheManager*, TR::CodeCacheMemorySegment*, size_t)’:
/home/vsts/work/1/s/compiler/runtime/OMRCodeCache.cpp:419:4: error: ‘issueWriteBarrier’ was not declared in this scope
  419 |    issueWriteBarrier();
      |    ^~~~~~~~~~~~~~~~~
```

**Comment by dsouzai** [comment]
Now failing with 
```
[ 69%] Building CXX object jitbuilder/CMakeFiles/jitbuilder.dir/__/compiler/x/codegen/OMRInstOpCode.cpp.o
/usr/bin/ld: ../../compilertest/libtestcompiler.a(OMRCodeCache.cpp.o): in function `OMR::CodeCache::initialize(TR::CodeCacheManager*, TR::CodeCacheMemorySegment*, unsigned long)':
OMRCodeCache.cpp:(.text+0xbf1): undefined reference to `issueWriteBarrier'
collect2: error: ld returned 1 exit status
make[2]: *** [fvtest/tril/tril/CMakeFiles/tril_dumper.dir/build.make:99: fvtest/tril/tril/tril_dumper] Error 1
make[1]: *** [CMakeFiles/Makefile2:4503: fvtest/tril/tril/CMakeFiles/tril_dumper.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs...
```
Hm, I wonder if the JITBuilder build includes compiling AtomicFunctions.cp... @mstoodle what do you recommend doing here?

**Comment by dsouzai** [comment]
Maybe it's best to just use `VM_AtomicSupport::writeBarrier()` and include `AtomicSupport.hpp`?

**Comment by mpirvu** [comment]
> Maybe it's best to just use VM_AtomicSupport::writeBarrier() and include AtomicSupport.hpp?

ok, will try that

**Comment by mpirvu** [comment]
It compiles fine with `VM_AtomicSupport::writeBarrier()` and `#include "AtomicSupport.hpp"`

**Review by dsouzai — APPROVED** [review]

**Comment by dsouzai** [comment]
Jenkins build all

**Pull request merged**
