### PR TITLE
Init allocation stats fields

### PR DESCRIPTION
**Pull request by tajila**
This PR ensures that the cumulativeAllocationBytes field is initialized.

### CODE REVIEW

**Comment by tajila** [comment]
@amicic Please take a look

**Comment by tajila** [comment]
@babsingh please review

**Review by amicic — APPROVED** [review]

**Comment by babsingh** [comment]
jenkins build all

**Comment by babsingh** [comment]
jenkins build riscv,win

**Review by babsingh — APPROVED** [review]
Only known issues are observed, which are unrelated to this PR:
- https://github.com/eclipse/omr/issues/6905
- #6516

**Pull request merged**
