### PR TITLE
Fix AIX CMake compiles

### PR DESCRIPTION
**Pull request by charliegracie**
- remove omrcore when it is not actually required
- DDR blob reader requires omrutil
- sigtest requires fvtest/util on the include path
- thread needs to handle adding pthread for AIX

Signed-off-by: Charlie Gracie <charlie.gracie@gmail.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
This PR allows you to compile AIX 64 bit OMR using CMake.  I did not test with the COMPILER flag on since I did not have access to a machine with flex installed or the ability to install it.

**Comment by charliegracie** [comment]
This is the command line I used to run CMAKE:
`cmake -Wdev -DCMAKE_XL_CreateExportList="/usr/vac/bin/CreateExportList -X64" -C../cmake/caches/Travis.cmake ..`

**Comment by charliegracie** [comment]
FYI @rwy0717 and @dnakamura

**Comment by dnakamura** [comment]
LGTM

**Pull request merged**
