### PR TITLE
WIP: Remove J9 specific recognized method lists

### PR DESCRIPTION
**Pull request by noryb009**
This is used by the inliner to determine if a given method should be inlined. All of the old entries dealt with J9-specific methods, so for non-J9 projects, the method simply returned false.

As it stands, there is only one `suppressInliningOfRecognizedMethod` method in `OMR::CodeGenerator`, which simply returns false. It is an option to remove this method entirely, and let each downstream project implement a similar system however they want.

### CODE REVIEW

**Comment by Krovatkin** [comment]
@noryb009 may i suggest changing

> inlining opcode lists

 (in the title) to maybe **recognized-method lists used by Inliner**

opcodes typically mean `TR::Node` opcodes. (e.g. `loadaddr`, `icalli`, `iload`, etc)

**Comment by noryb009** [comment]
Thanks @Krovatkin for catching my mixup. Since we are trying to keep commit titles shorter, I kept the (IMO) more important "J9 specific" in the title, moving where it is used to the commit message.

**Comment by mstoodle** [comment]
May I ask after current status here, please? Are you finding value in having a WIP merge request open here, or could we close it until such time as you're ready to complete it?

**Comment by noryb009** [comment]
If I recall correctly, this depends upon an inverse pull request in J9. As of the end of last year, those changes were not merged. If it has been merged since then, this can be unmarked as WIP and merged as well.

**Comment by mgaudet** [comment]
There were concerns about functional verification on the J9 side. IMO, best to close this one, and we'll work on resuscitating when we have a better answer on how to verify this functionally (or are willing to have someone spreadsheet out the truthtable 😂 )

**Comment by noryb009** [comment]
Fair enough, closing.

**Pull request closed without merging**
