### PR TITLE
FIX #25 : Add OMR coding standard

### LINKED ISSUE #25: Add OMR coding standard

### PR DESCRIPTION
**Pull request by alin00**
Signed-off-by: Angela Lin <angela_lin@ca.ibm.com>

### CODE REVIEW

**Comment by alin00** [comment]
This pull request modifies no code.

The Travis build is failing for an unrelated reason.

�[0;32m[ RUN ] �[mThreadCreateTest.NumaSetAffinity
omrthread_monitor_init(&monitor, 0)
omrthread_create_ex(&thread, J9THREAD_ATTR_DEFAULT, 0, numaSetAffinityThreadMain, &data)
omrthread_numa_get_node_affinity(omrthread_self(), &currentAffinity, &nodeCount)
Setting thread numa affinity to 2
Failed to set affinity to 2
createTest.cpp:1046: Failure
Value of: status
Actual: 262144
Expected: (uintptr_t)0
Which is: 0
Failed with Code: 40000
�[0;31m[ FAILED ] �[mThreadCreateTest.NumaSetAffinity (0 ms)
�[0;32m[ RUN ] �[mThreadCreateTest.NumaSetAffinitySuspended
omrthread_create_ex(&thread, J9THREAD_ATTR_DEFAULT, 1, numaSetAffinitySuspendedThreadMain, &data)
Setting thread numa affinity to 2
omrthread_numa_get_node_affinity(thread, &expectedAffinityBeforeStart, &nodeCount)
omrthread_monitor_enter(monitor)
omrthread_monitor_enter(monitor)
omrthread_numa_get_node_affinity(omrthread_self(), &currentAffinity, &nodeCount)
Affinity different from expected. Expected:2 Actual:1
omrthread_monitor_notify_all(monitor)
omrthread_monitor_wait(monitor)
createTest.cpp:1160: Failure
Value of: status
Actual: 262144
Expected: (uintptr_t)0
Which is: 0
Failed with Code: 40000
�[0;31m[ FAILED ] �[mThreadCreateTest.NumaSetAffinitySuspended (1 ms)

**Comment by mstoodle** [comment]
Hi Angela, could you add the usual copyright message to the top of the file?

The usual Eclipse rules require me to fill out a CQ for this contribution because it's > 1000 lines :) . I'll see if I need to do that for this kind of contribution.

The build failure could not be caused by this commit so I'm not going to hold it back for that reason.

**Comment by alin00** [comment]
Copyright notice added.

**Comment by alin00** [comment]
According to http://www.eclipse.org/legal/EclipseLegalProcessPoster.pdf  I think this falls into the "Figure 1" case + all the "yes" answers, so CQ shouldn't be required. We just need to "record the contribution in our project IP log."

**Comment by mstoodle** [comment]
I agree, that poster suggests a CQ isn't required. But I'm surprised not to see a reference to the 1000 line threshold I know exists for new contributions. I'm going to be safe and submit the CQ. I do not think that needs to block us applying the coding standard. I just won't merge it until the IP folks have confirmed that's ok.

CQ can be found at https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11134

**Comment by alin00** [comment]
The 1000 line threshold appears on the Figure 3 path.

**Comment by mstoodle** [comment]
Note that I have been told we need the CQ, so we will need to wait for the IP team before I can accept the merge request.

Reviewers will continue to apply and can reference the coding standard document referenced here.

**Comment by mstoodle** [comment]
Eclipse IP team has allowed us to check in the code under the parallel IP process, so I'm merging the standard to enable others to submit changes against it as separate requests. Thanks for your patience, Angela.

**Pull request merged**
