### PR TITLE
Revert "Add Xgc options for suballocator heap size and quick allocation"

### PR DESCRIPTION
**Pull request by pshipton**
Reverts eclipse/omr#7414

See https://github.com/eclipse/omr/pull/7414#issuecomment-2265837658

### CODE REVIEW

**Comment by pshipton** [comment]
@0xdaryl pls take a look

**Comment by jdmpapin** [comment]
Jenkins build all

**Review by jdmpapin — APPROVED** [review]

**Comment by jdmpapin** [comment]
```
All nodes of label ‘compile:xwindows’ are offline
```
I believe Windows builds have been timing out due to this lately. Instead of waiting for the timeout, I've cancelled the job. All other checks have passed.

**Comment by pshipton** [comment]
Ya, Windows is broken atm. We could remove it from "all", but I'm not going to do it today. On the plus side plinux seems to be working again. We don't have too many machines but maybe enough for PR testing.

**Pull request merged**
