### PR TITLE
Improve handling of invalid CUDA device identifiers

### PR DESCRIPTION
**Pull request by keithc-ca**
In some (newer?) versions of the CUDA runtime, calling some functions (e.g. cudaSetDevice) with a bad deviceId returns 101 (CUresult CUDA_ERROR_INVALID_DEVICE) instead of 10 (cudaError_t cudaErrorInvalidDevice) as expected.

Avoid this problem by always checking the deviceId before making any device-specific calls.

### CODE REVIEW

**Comment by keithc-ca** [comment]
I reported the underlying problem to NVIDIA: https://developer.nvidia.com/nvidia_bug/2718068.

**Comment by youngar** [comment]
@genie-omr build all

**Comment by youngar** [comment]
@keithc-ca Is this ready to be merged?

**Comment by keithc-ca** [comment]
Yes, this is ready to be merged.

**Pull request merged**
