### PR TITLE
Remove CodeGenerator param from createConstantInstruction

### PR DESCRIPTION
**Pull request by AustinWells**
Closes: #5140

Signed-off-by: Austin Wells <austin.wells@mail.utoronto.ca>

### CODE REVIEW

**Comment by fjeremic** [comment]
@AustinWells looks good, just one minor change to make in the commit title [1]:

> The first line describes the change made. It is written in the imperative mood, and should say what happens when the patch is applied. Keep it short and simple. The first line should be less than 70 characters, where reasonable, and _**should be written in sentence case**_ preferably not ending in a period. Leave a blank line between the first line and the message body.

[1] https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md#commit-guidelines

**Comment by AustinWells** [comment]
Hi @fjeremic, sorry by commit title do you mean the header of the commit or to the title of the pull request itself ie. "remove CodeGenerator param from createConstantInstruction"?

**Comment by fjeremic** [comment]
I meant the commit itself. The PR title should typically match the commit if there is only a single commit. Commits are what will show up in the git history.

**Comment by AustinWells** [comment]
Just amended, the commit to fix the casing.

**Comment by fjeremic** [comment]
@genie-omr build zlinux,zos

**Comment by fjeremic** [comment]
Looks good, thanks! You don't have to fix this here but it appears your most recent commit has two authors, both of which are you. GitHub distinguishes between who authored the commit vs. who committed to the repository. Usually this is a problem with your local git config not matching the username and email you used on GitHub. To fix this all you have to do is ensure you change either your local git config to match that of GitHub or vice versa and that will resolve the issue on the GitHub end.

You can do this on a future work item. We'll merge this one as is since the builds are already half way to completion. Thanks for the contribution!

**Comment by AustinWells** [comment]
I think the author difference comes from switching machines for my most recent commit, don't usually do any development on this one so I probably have my ssh key and nothing else, but I will fix make sure to set it up for the future.

**Pull request merged**
