### PR TITLE
x86: Use forward memory copy for arraycopy instructions

### PR DESCRIPTION
**Pull request by a7ehuo**

### CODE REVIEW

**Comment by a7ehuo** [comment]
@0xdaryl May I ask you to review this change? Thank you!

@vijaysun-omr @hzongaro fyi

**Comment by 0xdaryl** [comment]
Jenkins test xlinux,win,osx,x32linux

**Comment by 0xdaryl** [comment]
Jenkins build xlinux,win,osx,x32linux

**Comment by 0xdaryl** [comment]
Jenkins build xlinux,win,osx,x32linux

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
