### PR TITLE
Relocated FrontEnd.hpp and modified relevent directives

### PR DESCRIPTION
**Pull request by Yuehan-Lin**
Issue: #4504 
Could be built on Linux, ready for tests
Signed-off-by: Yuehan-Lin <Yuehan.Lin@ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by Leonardo2718** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by Leonardo2718** [comment]
For some reason, the status of the Travis build is stale. I've manually checked the build it has passed successfully. All the other tests have also passed so I am going to merge this.

**Pull request merged**
