### PR TITLE
Prevent addition of null global VP constraint

### PR DESCRIPTION
**Pull request by BradleyWood**
Issue: eclipse-openj9/openj9#14489

Signed-off-by: BradleyWood <bradley.wood@ibm.com>

### CODE REVIEW

**Comment by BradleyWood** [comment]
Jenkins build all

**Comment by BradleyWood** [comment]
FYI, @0xdaryl

**Comment by 0xdaryl** [comment]
Can you provide a few more details on the problem?  In particular, although this PR prevents adding a null constraint, is it acceptable that the constraint is null in the first place?

@hzongaro : FYI, I will ultimately ask for your help in reviewing this PR.

**Comment by BradleyWood** [comment]
I believe applyGlobalConstraints() returns null because it fails to join the constraints at some point. It looks like the original intent was to return null if 'TR_FixIntersect' is true. Otherwise there is null-check assertion prior to returning the constraint.

https://github.com/BradleyWood/omr/blob/e3a15a993c8aba80582aa1d6f3071e122acbd4c4/compiler/optimizer/OMRValuePropagation.cpp#L1486-L1494

**Comment by vijaysun-omr** [comment]
Getting a null constraint in VP from intersecting is a sign of something having gone wrong at a deeper level, since the result of an intersection ought to only be an improvement in what we know about a particular value number. So if at least one of the constraints being intersected was non-null, the result of the intersection ought not to be null.

**Comment by BradleyWood** [comment]
Copying in my comment from the issue.

Based on debugging information from core file, [applyGlobalConstraints()](https://github.com/BradleyWood/omr/blob/81bc4828b290775674a6500d752670947455d3e6/compiler/optimizer/ValuePropagationCommon.cpp#L505-L506) fails join two constraints which causes a failure when adding the global constraint.

At [TR::VPConstraint::intersect(...)](https://github.com/BradleyWood/omr/blob/3f54ab0a786f4b850dfa378224a5a78230b0534f/compiler/optimizer/VPConstraint.cpp#L2736-L2741) (called from [applyGlobalConstraints(...)](https://github.com/BradleyWood/omr/blob/3f54ab0a786f4b850dfa378224a5a78230b0534f/compiler/optimizer/OMRValuePropagation.cpp#L1487-L1487) )
'this' is a VPNullObject(_mergePriority=4) and 'other' is VPClass (_mergePriority=10)

Therefore, we end up at [TR::VPClass::intersect1(...)](https://github.com/BradleyWood/omr/blob/3f54ab0a786f4b850dfa378224a5a78230b0534f/compiler/optimizer/VPConstraint.cpp#L3160-L3160)

Since both constraints are not a class object and one is a VPNullObject, we end up [here](https://github.com/BradleyWood/omr/blob/3f54ab0a786f4b850dfa378224a5a78230b0534f/compiler/optimizer/VPConstraint.cpp#L3189-L3194).

At this point, (this (VPClass))->_presense is a VPNonNullObject so the call to [isNonNullObject()](https://github.com/BradleyWood/omr/blob/3f54ab0a786f4b850dfa378224a5a78230b0534f/compiler/optimizer/VPConstraint.cpp#L435-L440) returns true. Therefore the result of the intersection is null.

With the information available it is not easy to see how we go into this state.

**Comment by 0xdaryl** [comment]
Since #6619 has been merged as the fix for the original problem I suggest this PR be closed.

**Pull request closed without merging**
