### PR TITLE
Rename MasterGCThread files to MainGCThread

### PR DESCRIPTION
**Pull request by theresa-m**
Merge to be coordinated with: https://github.com/eclipse/openj9/pull/10139
Related to: https://github.com/eclipse/openj9/issues/10071

I'm starting with renaming files since this is a refactor, name replacements for master will come in a later pr to make it easier to review.

Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>

### CODE REVIEW

**Comment by youngar** [comment]
Hey @theresa-m thank you so much for this change!

I think it would be best if we can avoid creating dependent changes by splitting this work across three PRs.

1. Change to `MasterGCThread` to `MainGCThread` in OMR

Rather than deleting the original header, `gc/base/MasterGCThread.hpp`, rewrite it so that it's contents are:

```c++
#if !defined(MASTERGCTHREAD_HPP_)
#define MASTERGCTHREAD_HPP_

#include "MainGCThread.hpp"

/* ideally this would be a typedef, but typedefs can't be used with friend declarations */
#define MM_MasterGCThread MM_MainGCThread

#endif /* defined(MASTERGCTHREAD_HPP_) */
```

2. Change `MasterGCThread` to `MainGCThread` in OpenJ9.

3. Delete the original header `gc/base/MasterGCThread.hpp` from OMR.

**Comment by youngar** [comment]
It looks like we're okay with dependent changes for this https://github.com/eclipse/openj9/pull/10139#issuecomment-656351425

@genie-omr build all

**Comment by rwy0717** [comment]
If you do what andrew suggests, you'll have to fix the include guards in MasterGCThread.hpp in this PR as well. And copyrights too :)

**Comment by theresa-m** [comment]
> 1. Fix header guards in `MainGCThread.hpp`
> 
> ```
> #if !defined(MASTERGCTHREAD_HPP_)
> #define MASTERGCTHREAD_HPP_
> ```
> 
> 1. Fix copyright in `MainGCThread.hpp`

Updated.

**Comment by youngar** [comment]
@genie-omr build all

**Comment by youngar** [comment]
I don't think the windows failure has anything to do with your change.  I'm not going to bother relaunching it since it compiled fine.
```
15:15:03  13: [----------] 1 test from PortTtyTest
15:15:03  13/23 Test #13: porttest ..........................***Exception: SegFault 35.62 sec
```

**Pull request merged**
