### PR TITLE
Add and use CodeGenerator factory function

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Add factory create() function to CodeGenerator class

* Call factory create() function to instantiate a CodeGenerator

Issue: #3235

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Un-WIPing as downstream dependencies have merged.

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
Would a committer mind reviewing and merging this please?

**Review by Leonardo2718 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
