### PR TITLE
Correct Copyright header

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Add Corp. to IBM and others

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@pshipton for review. Do I need to update the copyright year for this type of change?

**Comment by 0xdaryl** [comment]
> Do I need to update the copyright year for this type of change?

My opinion is yes because you are altering the name of the author in the very copyright itself.  But others may have a firmer legal grasp on this.  @mstoodle

**Comment by pshipton** [comment]
I don't think anybody would ague against changing the copyright end date, might as well just do it.

**Comment by 0xdaryl** [comment]
Ping @AdamBrousseau.  Ironically, seems all this needs is a copyright change.

**Comment by AdamBrousseau** [comment]
Updated @0xdaryl

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
