### PR TITLE
Remove isAOT check in order to enable relo logging for JITServer

### PR DESCRIPTION
**Pull request by dchopra001**
Signed-off-by: Dhruv Chopra <Dhruv.C.Chopra@ibm.com>

### CODE REVIEW

**Comment by dchopra001** [comment]
@mpirvu

**Comment by dchopra001** [comment]
@mpirvu The constructor in OMR's CodeGenerator class initializes `_aheadOfTimeCompile` too NULL. 

The `z`, `p`, `aarch64` and `x` codgens in OpenJ9 unconditionally set the `aheadOfTimeCompile` field. Here's an example on Power:
https://github.com/eclipse/openj9/blob/14754c255f9b47bb3d7f664196612e48c1a2adb7/runtime/compiler/p/codegen/J9CodeGenerator.cpp#L54

So I guess technically it's possible for `cg->getAheadOfTimeCompile()` to be non-null. I didn't see this issue because I've only debugged in OpenJ9 for `x`, `p`, and `z` so far.

So I've guarded this check with a `cg->getAheadOfTimeCompile()`. This should allow relocation tracing to be enabled for remote as well as AOT compiles.

**Comment by dchopra001** [comment]
@mpirvu 
I just ran a test with the following command line options:

```
jvm/jre/bin/java -Xjit:count=0,{*HashMap*}\(traceFull,traceCG,log=trace.log,traceRelocatableDataCG,traceRelocatableDataDetailsCG,traceRelocatableDataDetailsRT,traceRelocatableDataRT,traceReloCG\),verbose,vlog=vlog,rtlog=rtlog_name,aotrtDebugLevel=9 -version
```

and I see the following output
```
<relocatableDataCG>
Code start =        0, Method start pc = b41356fc, Method start pc offset = 0xb41356fc
No relocation data allocated
</relocatableDataCG>
```

So it looks like we should be okay to merge this.

**Comment by fjeremic** [comment]
@genie-omr build all

**Pull request merged**
