### PR TITLE
Prepare for privatization in versioner

### PR DESCRIPTION
**Pull request by jdmpapin**
This is a series of cleanups, fixes, and refactorings in preparation for changes that allow versioner to version w.r.t. memory writable by other threads, e.g. fields, in the absence of synchronization.

- A number of transformations are modified to use `performTransformation()` correctly.
- `collectAllExpressionsToBeChecked()` no longer removes checks.
- The entry of the preheader of the cold loop is remembered so that it doesn't have to be passed to every function.
- `collectAllExpressionsToBeChecked()` is changed to use a checklist.
- An old loop transfer implementation is removed. It has been disabled for a very long time.
- `getOriginalUnimprovedSymRef()` is implemented to allow "removing" analysis results from a symref, which will be important for recognizing occurrences of privatized expressions within loops.
- Finally, some minor changes to checklist to implement a set-containment query because versioner will want to assert that one checklist is a subset of another.

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@genie-omr build osx

**Comment by vijaysun-omr** [comment]
OSX build failure needs to be addressed before this can be reviewed further.

**Comment by jdmpapin** [comment]
```
12:18:16  /Library/Developer/CommandLineTools/usr/include/c++/v1/map:818:5: error: static_assert failed "Allocator::value_type must be same type as value_type"
12:18:16      static_assert((is_same<typename allocator_type::value_type, value_type>::value),
12:18:16      ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
12:18:16  /Users/jenkins/workspace/PullRequest-osx_x86-64/compiler/compile/OMRSymbolReferenceTable.hpp:718:40: note: in instantiation of template class 'std::__1::map<int, int, std::__1::less<int>, TR::typed_allocator<std::__1::pair<int, int>, CS2::shared_allocator<CS2::heap_allocator<65536, 12, TRMemoryAllocator<TR_AllocationKind::heapAlloc, 12, 28> > > > >' requested here
12:18:16     OriginalUnimprovedMap               _originalUnimprovedSymRefs;
12:18:16                                         ^
```
It looks like this is just due to the missing `const` in the allocator type for `OriginalUnimprovedMap`.

I don't think I understand the following errors about the relationship between `OMR::SymbolReferenceTable` and `TR::SymbolReferenceTable`. Some of them are in code that I haven't edited. I'm hoping that they're just cascading from the static assertion failure.

**Comment by fjeremic** [comment]
The builds are pretty quick, we can kick off another build with the `const` fix and check.

**Comment by jdmpapin** [comment]
Added `const` to the allocator type.

**Comment by fjeremic** [comment]
@genie-omr build osx

**Comment by fjeremic** [comment]
Looks like the cascade effect worked. Launching all builds now again to verify other platforms.

@genie-omr build all

**Comment by vijaysun-omr** [comment]
Checks have passed and I have reviewed these mostly cleanup commits. There is some new infrastructure added but it's in preparation for a following PR it seems. So I am merging this.

**Pull request merged**
