### PR TITLE
CMake: Detect git SHA

### PR DESCRIPTION
**Pull request by dnakamura**
If git is found (and source dir is a git repo) set OMR_VERSION_STRING
to the git SHA. Otherwise fall back to old behavior of "<Unknown>"

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
@dnakamura  If we tag the repo (for a release, etc.) and you checkout the tag will this pick up the tag name or just the SHA value?

**Comment by dnakamura** [comment]
just the SHA

**Comment by charliegracie** [comment]
sadness.  It would have been great if it would be the SHA for a normal checkout and if you checked out a TAG that the tag would show up.  Oh well this is better than what we had :)

**Comment by dnakamura** [comment]
Its probably doable, I just need to dig into the docs for the various git commands. I just stole this from `openj9-openjdk-jdk9`

**Pull request merged**
