### PR TITLE
RISC-V: rename extensible header files

### PR DESCRIPTION
**Pull request by janvrany**
This PR simply follows changes done earlier in 1dc02ce and in 3f45b69

### CODE REVIEW

**Comment by 0xdaryl** [comment]
The file changes look fine to me.  However, I think you can squash to a single commit and use a commit title/body such as this:

```
Rename RISC-V TreeEvaluatorTable.hpp

Use conventional extensible class naming scheme.
```

**Comment by janvrany** [comment]
> think you can squash to a single commit and use a commit title/body such as this:

I can do that if you prefer, but then git won't detect file rename properly. Using `git blame` on `OMRTreeEvaluator.hpp` would be less useful. This is the reason why it was done in two commits originally ( 1dc02ce and 3f45b69 ).

Do you still want to have this in 1 commit? My personal preference would be 2 commits because of the above but I'm fine with 1 commit too.

**Comment by 0xdaryl** [comment]
Sure, two commits is fine.  But please change the commit titles and bodies.

**Comment by janvrany** [comment]
Just pushed with commit message modified. Hope it's OK like this.

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
No need to wait for CI as this is purely a RISC-V specific change.  Merging.

**Pull request merged**
