### PR TITLE
Change type of variable `updates` 

### PR DESCRIPTION
**Pull request by gza060625**
Proper fix for compiler warning treated as error (potential loss of data) from using a mix of different size types.
(https://github.com/eclipse/openj9/pull/8626/files)
Change MM_ScavengerCopyScanRatio::UpdateHistory::updates
from uint64_t to uintptr_t.
This modification eliminates the need to cast in:
openj9/runtime/gc_trace/TgcParallel.cpp

Signed-off-by: Enson <enson.guo@ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
There are so many unrelated commits in this PR.

**Comment by RSalman** [comment]
@gza060625 is working on cleaning commit history... seems like it got messed up with rebase/merge

**Comment by gza060625** [comment]
Re-open after cleaning up unrelated commits.

**Comment by gza060625** [comment]
@rwy0717  Could you have a look at this?

**Comment by rwy0717** [comment]
@genie-omr build all

**Pull request merged**
