### PR TITLE
Add instruction encoding for some vector operations on Power

### PR DESCRIPTION
**Pull request by hjooybar**
Here is  a list of instruction encoding added in this commit:
```
VMULOUW 	Vector Multiply Odd Unsigned Word
VMULEUW 	Vector Multiply Even Unsigned Word
VADDUQM 	Vector Add Unsigned Quadword Modulo
VADDCUQ 	Vector Add & write Carry Unsigned Quadword
VADDEUQM	Vector Add Extended Unsigned Quadword Modulo
VADDECUQ 	Vector Add Extended & write Carry Unsigned Quadword
VSUBUQM 	Vector Subtract Unsigned Quadword Modulo
VSUBCUQ 	Vector Subtract & write Carry Unsigned Quadword
VSUBEUQM 	Vector Subtract Extended Unsigned Quadword Modulo
VSUBECUQ 	Vector Subtract Extended & write Carry Unsigned Quadword
```

### CODE REVIEW

**Comment by mgaudet** [comment]
You'll want to shorten the commit message title (see CONTRIBUTING.md) and sign the commit (`git commit --amend --signoff && git push --force`)

**Comment by vijaysun-omr** [comment]
@zl-wang and @ymanton Please review and approve before I merge this.

**Comment by ymanton** [comment]
Since you have two independent changes here I suggest you split them into two separate commits; one to add the vector instructions and the other to add the helper entries. It makes things like cherrypicking, bisecting, etc work better. Otherwise it looks OK to me.

**Comment by zl-wang** [comment]
Looks fine.  This enabled to restore crypto enhancements.

**Comment by 0xdaryl** [comment]
@ymanton, I'm not sure these changes are sufficiently distinct to warrant two separate commits.  I'm fine either way.

Please remote the "." after your commit title as per the CG.

**Comment by hjooybar** [comment]
I separate the commit into two parts and also fixed the title.
check PR #686 .

**Comment by mgaudet** [comment]
I don't think anyone would make you undo this: But for future reference, the two commits could well have stayed on the same branch, and been merged as part of the same pull request. A Pull Request can pull in many many different commits in one fell swoop.

**Comment by vijaysun-omr** [comment]
Thanks for making the changes and to the reviewers. I'll merge this in.

**Comment by vijaysun-omr** [comment]
...once the CI build passes :)

**Pull request merged**
