### PR TITLE
Document purpose of "toolchain bug" label

### PR DESCRIPTION
**Pull request by 0xdaryl**
[ci skip]

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Maybe this label should be renamed to "toolchain bug" to make it more general???

**Comment by nbhuiyan** [comment]
I think `toolchain bug` would be a better name for this label so that it can be used for labelling issues/workarounds for bugs in any other tools used for building/debugging. I don't expect there to be many issues/PRs needing to use the `build compiler bug` label, so I think a more general label would be more appropriate.

**Comment by Leonardo2718** [comment]
:+1: for `toolchain bug` as a label.

**Comment by 0xdaryl** [comment]
OK, latest proposal renames this to "toolchain bug".  Of course the link doesn't work because we haven't renamed the label yet, but that's easy to do once there's consensus.

**Comment by 0xdaryl** [comment]
```
if (committer != 0xdaryl) {
   ping();
}
```

**Pull request merged**
