### PR TITLE
Add option to enable/disable compilation before a checkpoint

### PR DESCRIPTION
**Pull request by dsouzai**

### CODE REVIEW

**Comment by dsouzai** [comment]
jenkins build all

**Comment by dsouzai** [comment]
@a7ehuo could you please review?
@babsingh do you mind being committer?

**Comment by dsouzai** [comment]
```
[2022-09-06T17:36:54.672Z]          MSBUILD : error MSB4166: Child node "2" exited prematurely. Shutting down. Diagnostic information may be found in files in the temporary files directory named MSBuild_*.failure.txt.
```
looks infra related

**Comment by babsingh** [comment]
> https://ci.eclipse.org/omr/job/PullRequest-win_x86-64/3447/

Yes, it is an infra issue. Ref: https://docs.microsoft.com/en-us/answers/questions/343645/error-msb4166-child-node-34234-exited-prematurely.html.

**Comment by babsingh** [comment]
jenkins build win

**Review by a7ehuo — APPROVED** [review]
LGTM

**Review by babsingh — APPROVED** [review]

**Pull request merged**
