### PR TITLE
Skip NULLCHK that has already been optimized away in Loop Versioner

### PR DESCRIPTION
**Pull request by hzongaro**
In `TR_LoopVersioner::versionNaturalLoop`, a `NULLCHK` might be specialized away.  However, it will still appear among the list of treetops that are tracked in `nullCheckTrees`.  When subsequent operations iterate over that list, they must skip `NULLCHK` nodes that no longer take effect.

Signed-off-by:  Henry Zongaro <zongaro@ca.ibm.com>

### CODE REVIEW

**Comment by hzongaro** [comment]
Vijay @vijaysun-omr and Liqun @liqunl, may I ask you to review?  I've just submitted a personal build to test out this change.

**Comment by liqunl** [comment]
Looks good to me.

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by Leonardo2718** [comment]
AppVeyor build failed due to infrastructural issues so I restarted it.

**Comment by vijaysun-omr** [comment]
This is a pretty safe change; it just checks if the entry in the list of null check trees still has the opcode that is expected (namely a null check) before going forward. The case when it may not be a null check was investigated and we can skip processing the entry in the list in that case and so that's what is being done via this commit. 

Checks have also passed. I will await the WIP to be taken off before merging this.

**Pull request merged**
