### PR TITLE
CMake: use OMR_JITBUILDER and OMR_TEST_COMPILER feature flags

### PR DESCRIPTION
**Pull request by rwy0717**
/cc @dnakamura @mgaudet

### CODE REVIEW

**Comment by mgaudet** [comment]
Looks good to me.

**Comment by rwy0717** [comment]
This enables the test compiler and jitbuilder on Travis, leaving them disabled on Appveyor, where the compiler isn't building yet. Both components are disabled by default, so developers working locally won't be affected by these changes.

**Comment by charliegracie** [comment]
@rwy0717 the commit named "Respect the OMR_TEST_COMPILER flag" does not appear to be signed off

**Comment by rwy0717** [comment]
D'oh! Fixed.

**Pull request merged**
