### PR TITLE
CMake: Add ability to treat warnings as errors

### PR DESCRIPTION
**Pull request by dnakamura**
Enable this on appveyor builds. Travis still isnt ready yet.
Note linker warnings are still not treated as errors

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
@dnakamura the appveyor build failed for an infrastructure reason and I do not appear to have permission to restart it.  Can you push an update to get it to run again?  Thanks

**Comment by dnakamura** [comment]
Looks like this is blocked on #1380 
https://ci.appveyor.com/project/dnakamura/omr/build/1.0.222

**Comment by charliegracie** [comment]
Ok, once the fix for #1380 has been accepted can you rebase to get that fix?  Thanks

**Comment by charliegracie** [comment]
You should be ok to rebase now and then the appveyor build should pass

**Comment by charliegracie** [comment]
sigh appveyor failed all builds last night / this morning for some reason.  Can you force push again as I have no way to restart that build :(

**Comment by charliegracie** [comment]
I closed / re-opened the PR to get the AppVeyor build to run again

**Comment by dnakamura** [comment]
Appveyor queue seems to be stuck. Will try pushing to get it going again

**Comment by charliegracie** [comment]
Thank you for getting things change ready!

**Pull request merged**
