### PR TITLE
Enable basic Travis.ci build for linux_x86-64

### PR DESCRIPTION
**Pull request by DanHeidinga**
Very basic Travis.ci build that compiles and runs make test for the linux_x86-64 spec.

Note, the .travis.yml file must have consistent delimiters - mixing spaces / tabs will cause the build to fail. https://lint.travis-ci.org/ can be used to validate the yml file without needing to commit the file and see the build fail.

The build still has three errors:
?[0;31m[ FAILED ] ?[mPortDumpTest.dump_test_create_dump_with_NO_name
?[0;31m[ FAILED ] ?[mPortDumpTest.dump_test_create_dump_with_name
?[0;31m[ FAILED ] ?[mPortDumpTest.dump_test_create_dump_from_signal_handler
which will need to be resolved under separate issue

Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>

### CODE REVIEW

**Comment by alin00** [comment]
These are your builds? https://travis-ci.org/DanHeidinga/omr

@mgaudet was working on a similar patch, but his build & test has no failures.
https://github.com/mgaudet/omr/blob/TravisIntegration/.travis.yml
https://travis-ci.org/mgaudet/omr/builds/114525846

Is there anything useful you can see from his patch?

**Comment by DanHeidinga** [comment]
Looking... It may be related to the use of apt-get update.  I aimed for the container-based infrastructure that doesn't allow the use of sudo: https://docs.travis-ci.com/user/workers/container-based-infrastructure/ so I may be missing a dependency.

I could speculate wildly but I'll keep poking at the travis build to see what the difference is

**Comment by DanHeidinga** [comment]
Example failure output:
Starting test omrdump_test_create_dump_with_NO_name
  calling omrdump_create with empty filename
JVMPORT030W 
omrdumpTest.cpp line  168: omrdump_test_create_dump_with_NO_name omrdump_create returned: 1, with filename: The core file created by child process with pid = 8555 was not found. Expected to find core file with name "core"
		LastErrorNumber: 0
		LastErrorMessage: 

Ending test omrdump_test_create_dump_with_NO_name
testHelpers.cpp:147: Failure
Value of: 0 == numberFailedTestsInComponent
  Actual: false
Expected: true
Test failed!
[  FAILED  ] PortDumpTest.dump_test_create_dump_with_NO_name (5438 ms)
[ RUN      ] PortDumpTest.dump_test_create_dump_with_name
https://api.travis-ci.org/jobs/115853738/log.txt?deansi=true

**Comment by DanHeidinga** [comment]
Current suspicion: the core_pattern can't be changed in the docker image and is redirecting cores where we can't get them.  See https://github.com/travis-ci/travis-ci/issues/3754

**Comment by DanHeidinga** [comment]
Debugging build: https://s3.amazonaws.com/archive.travis-ci.org/jobs/115860124/log.txt
shows: 
[0K$ cat /proc/sys/kernel/core_pattern
|/usr/share/apport/apport %p %s %c %P

There's an apt whitelist request for apport: https://github.com/travis-ci/apt-package-whitelist/issues/2642 which may allow modifying the apport settings to not eat our core file

**Comment by alin00** [comment]
Dan, are you still debugging this commit?

**Comment by DanHeidinga** [comment]
Yes, still debugging.

**To recap:** The tests fail because the core_pattern is set to pipe the core to /usr/share/apport/apport which doesn't exist in the containerized environment.  We need sudo to be able to write to core_pattern but sudo isn't allowed in containerized builds.  The apport package doesn't exist (yet) in the whitelist of apt packages for containerized builds.

So we're SOL on having these tests pass in the containerized build.

If we want to pursue the container builds, we'll need a way to detect that we're in a container and skip the tests.

**Comment by DanHeidinga** [comment]
I've excluded the core file tests so that the build goes green.  If this is acceptable, they can be re-enabled when travis.ci allows setting the core_pattern or adds apport to the whitelist.

Passing build: https://travis-ci.org/DanHeidinga/omr

**Comment by alin00** [comment]
Excluding the tests means we'll need to patch the code to enable the tests when we want to run them in our production build environment?

**Comment by DanHeidinga** [comment]
The exclude is in the .travis.yml and done using the googletest filter:
export GTEST_FILTER=-*dump_test_create_dump_*

The tests will continue to run for everyone other than the travis build.

**Comment by alin00** [comment]
Thanks, that's a reasonable solution then.

Can you add a copyright notice to the top of the file?

**Comment by DanHeidinga** [comment]
copyright notice has been added.

**Comment by alin00** [comment]
Thanks!

**Pull request merged**
