### PR TITLE
Deprecate global allocator and misc. cleanup

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Misc. source formatting cleanup in CallStack.cpp
* Replace globalAllocator with TR::CompilerEnv rawAllocator
* Remove deprecated GlobalAllocator
* Remove deprecated GlobalSingletonAllocator
* Remove deprecated CS2::stat_allocator

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@dsouzai : I would appreciate a review from you please.

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Review by dsouzai — APPROVED** [review]
LGTM

**Comment by 0xdaryl** [comment]
Would any committer mind taking this cleanup item?  @mstoodle @Leonardo2718 @fjeremic

**Review by fjeremic — APPROVED** [review]

**Pull request merged**
