### PR TITLE
Add testing framework for compiler tools

### PR DESCRIPTION
**Pull request by Leonardo2718**
Add a small testing framework for OMRChecker and OMRRewriter as well
as some test cases for the tools.

Signed-off-by: Leonardo Banderali <leob@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Please add the dual-license (EPL & Apache 2.0) header comment to the beginning of each of the new files.  Looks good otherwise.

**Comment by Leonardo2718** [comment]
Fixed the the license header.

**Comment by 0xdaryl** [comment]
For all the copyright headers that have a single date, please use the date range syntax:

* (c) Copyright IBM Corp. 2016, 2016

This will make updating copyright headers easier in the future.

**Comment by Leonardo2718** [comment]
Done.

**Pull request merged**
