### PR TITLE
Simplify widened and operations

### PR DESCRIPTION
**Pull request by fjeremic**
When a widening (extension) operation is found under an and with a constant value such that the constant being anded will never overlap with the unwidened value then such a tree can be folded to zero.

### CODE REVIEW

**Comment by fjeremic** [comment]
CC @andrewcraik / @vijaysun-omr for review.

**Comment by fjeremic** [comment]
Thanks for the heads up @xliang6. Perhaps this ought to wait until #375 is merged and I can rebase my change on top and amed the use of `OMR_CT_EXEPCT_EQ`.

**Comment by xliang6** [comment]
Sounds good, thanks.

**Comment by andrewcraik** [comment]
I think this looks good from my perspective - Vijay is the logical committer to do a second check before merging.

**Comment by vijaysun-omr** [comment]
One suggestion I have is to consider doing this kind of a change in the value propagation pass (maybe in addition to what you have in the simplifier, no need to throw this code away since you have it already). 

The advantage in value propagation is that you will base the optimization on constraints (ranges of values that a certain expression/node can take) rather than on tree pattern matching and so it might give you the chance have it apply more generally.

**Comment by fjeremic** [comment]
Thanks @vijaysun-omr for the review. I have opened #396 to improve upon this solution. Do you agree that there is benefit to having a slightly constrained version in the simplifier as we are not guaranteed to run value propagation at low optimization levels?

**Comment by vijaysun-omr** [comment]
Yes the simplifier does run more often than value propagation and there would be benefit at lower opt levels too as you said. So there is room for doing it in both places especially given that it's a relatively simple and cheap transformation to do.

**Pull request merged**
