### PR TITLE
Introduce a Linkage post binary encoding operation

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Introduce a Linkage post binary encoding operation
* Add calls to linkage performPostBinaryEncoding in each doBinaryEncoding

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
@fjeremic @ymanton : I'd appreciate a review from at least one of you.

The background behind this is that I'm adding support for encoding the linkage info on AArch64 for OpenJ9.  I'm ultimately trying to make that a linkage responsibility but at the moment it is engrained in each OMR code generators.  This PR is one step in that direction by providing a means for performing some linkage-specific operation at the end of binary encoding.  I expect that all the "return type instruction" encoding in each `doBinaryEncoding` to be folded into this function for JIT private linkage in OpenJ9 at some point.

**Comment by 0xdaryl** [comment]
@knn-k fyi

**Comment by fjeremic** [comment]
> I expect that all the "return type instruction" encoding

Just to clarify, do you mean the expansion of `TR::InstOpCode::ret` type pseudo-instructions into the epilogue sequence?

**Comment by 0xdaryl** [comment]
No.  I was thinking of the "linkage info word" that Java private linkage encodes.  It is the 4-byte word that sits before the interpreter entry point.  The upper 16 bits is the size of the interpreter entry area (i.e., address of jitted entry point - address of interpreted entry point) and the lower 16 bits encodes the return type of the instruction.  The information to encode this isn't known until after binary encoding (until the instruction locations are known), and it is arguably something the linkage should handle.

**Comment by 0xdaryl** [comment]
The "ret" expansion should probably still happen during doBinaryEncoding  as the binary encoding loop will need to walk those instructions produced and actually generate a binary encoding for them.

**Comment by fjeremic** [comment]
Thanks for the clarification.

**Pull request merged**
