### PR TITLE
Move control flow evaluators out of UnaryEvaluator.cpp

### PR DESCRIPTION
**Pull request by midronij**
Block of control flow evaluators in UnaryEvaluator.cpp were moved to
their correct location, in ControlFlowEvaluator.cpp.

Signed-off-by: Jackie Midroni <jackie.midroni@mail.utoronto.ca>

### CODE REVIEW

**Comment by Leonardo2718** [comment]
@genie-omr build plinux, aix

**Comment by Leonardo2718** [comment]
@midronij 

The commit message says this PR closes #64 but that's a PR that was close a long time ago.

I haven't seen an issue about this in OMR so maybe the `close` tags in the commit message and PR aren't needed?

**Comment by midronij** [comment]
@Leonardo2718 

Whoops, I think I just used the wrong link. The issue was #64 for the ZenHub board internal to the power team. I'll get rid of it, since it's not relevant to this issue.

My bad!

**Comment by 0xdaryl** [comment]
@genie-omr build plinux

**Pull request merged**
