### PR TITLE
Stop using std::numeric_limits<>::max() for global initializers

### PR DESCRIPTION
**Pull request by dnakamura**
XLC does not seem to properly perform constant propagation across function
calls.  This means that any global constant which is initialized via a
function call results in a global variable and a call to a static
initializer at program load (even if the function returns a constant)

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by rwy0717** [comment]
Nice catch and, sorry :)
@genie-omr build all

**Comment by hzongaro** [comment]
Is this guideline documented anywhere?  For instance, should we have a section in https://github.com/eclipse/omr/blob/master/doc/SupportedC++Features.md describing C++ features to avoid in certain situations along with the rationale?

**Comment by andrewcraik** [comment]
@dnakamura / @rwy0717 / @0xdaryl - is this something we could include in the compiler linter to stop accidental reintroduction? It will be an easy thing to forget...

**Comment by youngar** [comment]
@dnakamura seems like a real failure on z/os
```
18:01:38  "/openzdk/jenkins/workspace/PullRequest-zos_390-64/include_core/OMR/Bytes.hpp", line 107.24: CCN5274 (S) The name lookup for "SIZE_MAX" did not find a declaration.
18:01:38  CCN0793(I) Compilation failed for file /openzdk/jenkins/workspace/PullRequest-zos_390-64/compiler/codegen/OMRCodeGenerator.cpp.  Object file not created.
```

**Comment by youngar** [comment]
It's supposed to be defined in `<stdint.h>`, i'm not sure why it failed.

**Comment by dnakamura** [comment]
@youngar except this is the c++ compiler. which *should* be using a newer language standard

**Comment by dnakamura** [comment]
Note: merging this should be held off until eclipse/openj9#9091 merges 
@genie-omr build all

**Comment by dnakamura** [comment]
@genie-omr build all

**Comment by rwy0717** [comment]
@genie-omr build zos

**Comment by dnakamura** [comment]
@genie-omr build zos

**Comment by youngar** [comment]
@dnakamura Is this good to go?

**Comment by dnakamura** [comment]
yup

**Pull request merged**
