### PR TITLE
Get Windows version information from registry if major version is 10

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Fixes https://github.com/eclipse/omr/issues/3644

Signed-off-by: Peter Bain <peter_bain@ca.ibm.com>

### CODE REVIEW

**Comment by pdbain-ibm** [comment]
Running personal builds.  IBM Java 8 compiles and passes sanity tests.  OpenJ9 compiles successfully, sanity and extended tests are in progress.

**Comment by pdbain-ibm** [comment]
Ready for review.

**Comment by pshipton** [comment]
@pdbain-ibm Please don't take this out of draft state, it needs more discussion. I don't think this solution is compatible with what Java expects. Java has compatibility related expectations for the values that omrsysinfo_get_OS_type() returns (i.e. it expects the names which are already hard coded). If this changes, then Java will need to change as well so it continues to use the expected names.

**Comment by pshipton** [comment]
The expected value for Server 2019 is "Windows Server 2019".

**Comment by pdbain-ibm** [comment]
> Java has compatibility related expectations for the values that omrsysinfo_get_OS_type() returns (i.e. it expects the names which are already hard coded). If this changes, then Java will need to change as well so it continues to use the expected names.

Possible solutions:

1. get the `ReleaseId` from the registry and map the resulting strings to a product name, e.g. "1809" or "1803" -> "Windows Server 2019".
2. get the "ProductName" from the registry and match on that, e.g. strncmp() on "Windows Server 2019", "Windows 10", etc. and return a hard-coded name.
3. let OMR return the actual version and do the mapping in the JVM runtime code.

Option 1 is slow (many strcmps()) and hard to maintain with a faster release cadence.  Option 2, while kludgy, seems the most practical.

**Comment by pshipton** [comment]
Is the ProductName always in English, even for localized versions of Windows?

**Comment by pdbain-ibm** [comment]
> Is the ProductName always in English, even for localized versions of Windows?

Good point: not necessarily.  From "https://docs.microsoft.com/en-us/windows/desktop/sysinfo/structure-of-the-registry":

> Key names are not localized into other languages, although values may be.

According to https://techcommunity.microsoft.com/t5/Windows-Server-Insiders/Windows-Server-2019-version-info/td-p/234472:

> Windows Server 2016 will always be 1607. Once a product is released, that ID will not change.

Looks like we will need to parse the `ReleaseId` and look for known releases.

**Comment by pdbain-ibm** [comment]
Proposal:
If the `ReleaseId` is "1607", return "Windows Server 2016", if "1809", "Windows Server 2019"
Options for handling other values:
1. treat the version as unknown and return the ProductName property
2. treat anything after 1809 as `Server 2019`
3. return a string of the form "Windows Server, version <ReleaseId>".  This handles customers on the Semi-Annual Channel. 

I favour 3.

> Java has compatibility related expectations for the values that omrsysinfo_get_OS_type() returns (i.e. it expects the names which are already hard coded). 

@pshipton : Apart from dtfj, where else do we check against hard-coded strings?

**Comment by pshipton** [comment]
@pdbain-ibm this seems to be out of draft state. Please set it as WIP, it doesn't look ready for review yet.

By "Windows Server, version" do you mean for example "Windows Server, 1809" for Server 2019? If so I suggest "Windows Server, ReleaseId 1809" for an unknown release.

If you are asking about the Java use of omrsysinfo_get_OS_type(), the value is used to set the os.name system property, which any application could be checking.

**Comment by pdbain-ibm** [comment]
> By "Windows Server, version" do you mean for example "Windows Server, 1809" for Server 2019? If so I suggest "Windows Server, ReleaseId 1809" for an unknown release.

Sorry: I misformatted the comment.  I have fixed it. 
Per the format used in https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info, I suggest `Windows Server, version 1709` for unrecognized release.  Known releases such as 1809 will have hard coded names, in this case `Windows Server 2019`

**Comment by pdbain-ibm** [comment]
I downloaded the HotSpot Java 11 and tested it on Windows Server 2019:

>openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.2+9)
OpenJDK Server VM AdoptOpenJDK (build 11.0.2+9, mixed mode, emulated-client)
os.name = Windows Server 2016
os.version = 10.0

**Comment by pdbain-ibm** [comment]
Tested and ready for review.

**Comment by pshipton** [comment]
Looking at the example, from a Java perspective the comma in `Windows Server, version 1607` isn't ideal and may cause issues.

**Comment by pdbain-ibm** [comment]
> Looking at the example, from a Java perspective the comma in `Windows Server, version 1607` isn't ideal and may cause issues.

Okay.  Comma removed.

**Comment by charliegracie** [comment]
@genie-omr build win

**Comment by pdbain-ibm** [comment]
Then failure in the CI build doesn't look related.  Could we re-run the test to rule out machine problems?

**Comment by charliegracie** [comment]
@genie-omr build win

**Pull request merged**
