### PR TITLE
Add IBM i specfic process for retrieving memory and CPU infos

### PR DESCRIPTION
**Pull request by gaolibj**
Add IBM i specfic process for retrieving memory and CPU infos.

### CODE REVIEW

**Comment by gaolibj** [comment]
@youngar @charliegracie  Could you help to review the pull request changes?  Thanks.

**Comment by youngar** [comment]
@genie-omr build all

**Comment by youngar** [comment]
Out of curiosity, where are all the `Xj9*` functions defined? Are they public?

**Comment by gaolibj** [comment]
@youngar  FYI.  Those code are stored in a private repo https://github.ibm.com/runtimes/closedj9/pull/75.

**Pull request merged**
