### PR TITLE
Rename Symbol::staticName to staticFieldName

### PR DESCRIPTION
**Pull request by nanjekyejoannah**
Rename Symbol::staticName to staticFieldName

This PR renames staticName  to staticFieldName.

Closes: #3034

Signed-off-by: nanjekyejoannah <nanjekyejoannah@gmail.com>

### CODE REVIEW

**Comment by nanjekyejoannah** [comment]
@andrewcraik , I understand the implications of this change after this review. Thanks for the insight. Could I have misunderstood the issue? or there is  a better solution to fix the issue?

 If it is long term that requires downstream users to migrate their code to the new API as you say , then am glad to close this as it does not seem feasible for now.

**Comment by andrewcraik** [comment]
I don't think you need to close this as such - I would suggest you do the change in two steps - in this commit do the rename as you have done, but add a staticName which calls staticFieldName. This way downstream  consumers can continue to use the old API for a period of time. The downstream projects (primarily Eclipse OpenJ9 in this case I think) can update to use the new staticFieldName method. Once that migration is done you can delete the staticName delegating methods you added for compatibility as a second pull request.

The rename as descried in #3034 is certainly something we would like to see done and it is great that you are helping out. Even if you just do step one above it would be progress towards getting rid of the somewhat misleading staticName method.

**Comment by nanjekyejoannah** [comment]
@andrewcraik +1 for that. 

I will look at this in 10 days as am currently abit busy atm

**Comment by Leonardo2718** [comment]
@nanjekyejoannah any updates? :slightly_smiling_face:

**Comment by 0xdaryl** [comment]
@nanjekyejoannah, there hasn't been an update on this PR in some time.  Are you still planning on making progress with it in the near future?  If not, I suggest closing it while you work on it in your private fork and then re-open when it is ready for review.  There are downstream dependencies to this change as well (i.e., in OpenJ9) so this PR will need to take on a bit of a different form (as discussed above) to accommodate staging those changes so that builds don't break.

**Comment by nanjekyejoannah** [comment]
Closing this as am short on bandwidth at the moment. I can't promise to look at this now. When I do in the future, I will reopen.

**Comment by 0xdaryl** [comment]
OK, thanks.  Closing.

**Pull request closed without merging**
