### PR TITLE
Adding new Test cases to Tril

### PR DESCRIPTION
**Pull request by mgaudet**
New test cases for unary opcodes `iabs` and `ineg`.

### CODE REVIEW

**Comment by charliegracie** [comment]
genie-omr build plinux

**Comment by mgaudet** [comment]
Comments addressed, though, I wish to note a wince of protest at the request to reword the commit messages for the individual opcode tests. In my opinion, that level of driven consistency isn't worth pursuing, and could drive contributors away.

**Comment by 0xdaryl** [comment]
omr-genie build all

**Comment by 0xdaryl** [comment]
genie-omr build all

**Pull request merged**
