### PR TITLE
Remove references of deprecated Add/Sub IL Opcode

### PR DESCRIPTION
**Pull request by wbh123456**
Remove any references to deprecated Add/Sub IL Opcode by mapping to their signed version.

Issue: #2657
Signed-off-by: Bohao(Aaron) Wang <aaronwang0407@gmail.com>

### CODE REVIEW

**Comment by wbh123456** [comment]
Passed extended testings. This PR is ready for a review.

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by wbh123456** [comment]
Passed extended testings, this PR is ready for a review. @fjeremic

**Comment by fjeremic** [comment]
I'll give it a day or so to see if anyone else wants to review.

**Comment by wbh123456** [comment]
@fjeremic Ping.

**Pull request merged**
