### PR TITLE
x86: Support multiple instruction prefixes

### PR DESCRIPTION
**Pull request by BradleyWood**

### CODE REVIEW

**Comment by BradleyWood** [comment]
jenkins build all

**Comment by BradleyWood** [comment]
@0xdaryl Can you review?

**Comment by 0xdaryl** [comment]
I just want to confirm with you that there is no code somewhere that uses this that assumes that a "prefix" will always be one byte in length.  I looked through the code but didn't spot anything obvious, but I'd like you to confirm please.

**Comment by BradleyWood** [comment]
> I just want to confirm with you that there is no code somewhere that uses this that assumes that a "prefix" will always be one byte in length. I looked through the code but didn't spot anything obvious, but I'd like you to confirm please.

Now that I think of it, this would impact the binary length estimation logic

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
