### PR TITLE
Reduce scratchSpaceLimit to 16 MB under `-Xtune:virtualized` option

### PR DESCRIPTION
**Pull request by mpirvu**
`-Xtune:virtualized` is an option used by a downstream project (openj9)
and geared towards virtualized/cloud environments where low memory and
CPU consumption is a desired feature, even if it comes at the expense of
a small throughput degradation.
During a compilation, the JIT is allowed to allocate memory for its
internal needs up to a `scratchSpaceLimit`, which is currently set at
256 MB. As a side effect, large transient spikes in memory usage can
be triggered, which forces the user to use large (Docker) containers
to account for these possible spikes.
This commit lowers the `scratchSpaceLimit` to 16 MB when
`-Xtune:virtualized` option is in effect. We have measured small
throughput degradations from this change (2-3%) in some Java EE
benchmarks, but also reductions in CPU consumed by compilation threads
in the range of 8-31%. Memory usage spikes due to JIT compilations are
of course capped to 16 MB.
Note that when a compilation fails because it cannot be performed within
the memory space alloted, it will be retried at a lower optimization level
which typically consumes (much) less memory.

Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by mpirvu** [comment]
Attn @vijaysun-omr

**Comment by vijaysun-omr** [comment]
I notice a change to `DEFAULT_SCRATCH_SPACE_LOWER_BOUND_KB` from 32 to 30. Is there a reason why the lower bound is even needed ? I guess I'm concerned about someone trying an even lower scratch space limit by using the -Xjit option and discovering that their option does not get applied.

**Comment by mpirvu** [comment]
The lower bound is used in two situations:
1) The activation of a new compilation threads is allowed only if the free physical memory is  larger than some `safeReserve` plus `DEFAULT_SCRATCH_SPACE_LOWER_BOUND_KB`
```
   // Do not activate if we are low on physical memory
   bool incompleteInfo;
   uint64_t freePhysicalMemorySizeB = computeAndCacheFreePhysicalMemory(incompleteInfo);
   if (freePhysicalMemorySizeB != OMRPORT_MEMINFO_NOT_AVAILABLE &&
       freePhysicalMemorySizeB <= (uint64_t)TR::Options::getSafeReservePhysicalMemoryValue() + TR::Options::getScratchSpaceLowerBound())
      return TR_no;
```
2) If `-Xjit:enableSelfTuningScratchMemoryUsageBeforeCompile` is specified, fail a compilation from the start if free physical memory is less than some safeReserve plus `DEFAULT_SCRATCH_SPACE_LOWER_BOUND_KB`
```
            // Check to see if there is sufficient physical memory available for this compilation
            if (compiler->getOption(TR_EnableSelfTuningScratchMemoryUsageBeforeCompile))
               {
               bool incompleteInfo = false;
               // Abort the compile if we don't have at least getScratchSpaceLowerBound()
               // available, plus some safe reserve
               // TODO: we may want to use a lower value for third parameter below if the
               // compilation is deemed cheap (JNI, thunks, cold small method)
               uint64_t physicalLimit = compInfo->computeFreePhysicalLimitAndAbortCompilationIfLow(compiler,                                                                                       incompleteInfo, TR::Options::getScratchSpaceLowerBound());
```
Thus, the user can still specify a lower amount of scratchSpaceLimit.

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by mpirvu** [comment]
From some discussions with @ashu-mehra it appears that the scratchSpaceLimit is effectively a multiple of of our scratch segment with a value of 16MB. Thus, 30MB may be the same as 16MB. 
We may want to hold off this item until we sort it out.

**Comment by mpirvu** [comment]
PR https://github.com/eclipse/openj9/pull/9153 will fix the issue described in comment https://github.com/eclipse/omr/pull/5015#issuecomment-608107311.
Is the limit set by this PR (30MB) still acceptable?

**Comment by vijaysun-omr** [comment]
Yes I feel the limit we have in this PR is acceptable (effectively 16mb). Do you want to make that clearer by just setting it to 16mb in the code rather than 30mb as it is now ?

**Comment by mpirvu** [comment]
I have changed the limit to 16MB

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by vijaysun-omr** [comment]
Do you feel we should apply the scratch space limit to JIT compiles but not AOT compiles under -Xtune:virtualized ? In some sense, the most relevant use case is the warm run where AOT code has already been generated rather than the cold run where AOT code is being generated.

**Comment by mpirvu** [comment]
> Do you feel we should apply the scratch space limit to JIT compiles but not AOT compiles under -Xtune:virtualized ?

No, if the goal is to keep the peak memory low to allow for smaller containers.

> In some sense, the most relevant use case is the warm run where AOT code has already been generated rather than the cold run where AOT code is being generated.

Even warm runs have some AOT compilations and any of these could push the peak memory over the container limit.

**Comment by vijaysun-omr** [comment]
Okay it seems a bit of a shame that we might fail an AOT compile in the very first (cold) run for example because of the scratch space limit being low; note that such a cold run may be done at container build time in some cases, and therefore does'nt affect the deployment time memory usage at all.

**Comment by mpirvu** [comment]
> note that such a cold run may be done at container build time in some cases

The creator of the container could increase the scratch space at build time, provided it knows how to do it.

**Comment by vijaysun-omr** [comment]
Thanks for the answers, I think I'm accepting enough of them :) to go ahead with this merge now since checks have also passed.

**Pull request merged**
