### PR TITLE
x86: Support NAN handling on AVX-512 hardware

### PR DESCRIPTION
**Pull request by BradleyWood**

### CODE REVIEW

**Comment by BradleyWood** [comment]
jenkins build all

**Comment by BradleyWood** [comment]
jenkins build all

**Comment by BradleyWood** [comment]
jenkins build all

**Comment by BradleyWood** [comment]
@0xdaryl Can you review?

**Comment by BradleyWood** [comment]
jenkins build all

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
