### PR TITLE
adjust ranges of expected property values for newer GPUs

### PR DESCRIPTION
**Pull request by keithc-ca**
We have observed the following values on a Windows 10 machine equipped with a GTX 960:
* MAXIMUM_SURFACE2D_HEIGHT = 65536
* MAXIMUM_SURFACE3D_DEPTH = 4096
* MAXIMUM_TEXTURE2D_LINEAR_HEIGHT = 65536
* MAXIMUM_TEXTURE2D_LINEAR_WIDTH = 65536

This adjusts the ranges of expected device property values in tests to include these obsevations.

### CODE REVIEW

**Comment by charliegracie** [comment]
@keithc-ca Can you update the commit message to limit the first line to 50 characters?  Thanks

**Comment by keithc-ca** [comment]
Only the commit message was changed. @charliegracie perhaps you can cancel the CI build.

**Comment by fjeremic** [comment]
> @keithc-ca Can you update the commit message to limit the first line to 50 characters? Thanks

Also the commit header should be sentence cased (capitalize the first letter).

**Comment by keithc-ca** [comment]
Commit header adjusted (again).

**Comment by keithc-ca** [comment]
I don't believe the CI failure is related to this change: it passed twice already with the identical content.

**Comment by youngar** [comment]
@keithc-ca I'll restart the build

**Pull request merged**
