### PR TITLE
Clean up TR_AOT and TR_(En|Dis)ableCompilationThread

### PR DESCRIPTION
**Pull request by dsouzai**
`TR_AOT` is a legacy option that isn't the way AOT compilations are controlled in downstream projects. `TR_EnableCompilationThread`/`TR_DisableCompilationThread` is no longer need in OpenJ9.

Needs to be merged together with https://github.com/eclipse-openj9/openj9/pull/13304 to prevent an OpenJ9 build break.

### CODE REVIEW

**Comment by dsouzai** [comment]
@fjeremic do you mind being committer for this?

**Review by fjeremic — APPROVED** [review]

**Comment by fjeremic** [comment]
Jenkins build all

**Comment by AdamBrousseau** [comment]
jenkins build zos

**Comment by fjeremic** [comment]
jenkins build riscv

**Pull request merged**
