### PR TITLE
x86: Support f/d vmin/vmax at 128 and 256 bits

### PR DESCRIPTION
**Pull request by BradleyWood**
NaN handling for vmin/vmax f/d is supported for 128 and 256-bit vectors. 512-bit vectors are not supported because the compiler does not support write mask registers.

### CODE REVIEW

**Comment by BradleyWood** [comment]
Jenkins build all

**Comment by BradleyWood** [comment]
Jenkins build all

**Comment by BradleyWood** [comment]
Jenkins build all

**Comment by BradleyWood** [comment]
Jenkins build all

**Comment by BradleyWood** [comment]
Jenkins build all

**Comment by BradleyWood** [comment]
Jenkins build all

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
