### PR TITLE
Deleted unused methods issue #2452

### PR DESCRIPTION
**Pull request by sam0208**

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@sam0208: just wondering if you have a status update on this one and that the next steps are clear enough.  Thanks!

**Comment by sam0208** [comment]
@0xdaryl Sorry, I thought you would take care of the issue because you self-assigned it. The steps look clear though so i would like to try and send another PR.

**Comment by 0xdaryl** [comment]
This PR has been inactive for some time now.  I'd like to propose you close this PR while you work on it and then re-open when its ready again.

**Comment by 0xdaryl** [comment]
I am closing this based on my previous comment.  Please open a new PR once this commit is ready for review/merging.  Thanks.

**Pull request closed without merging**
