### PR TITLE
Move all definitions for J9VMSTATE_GC to OMR

### PR DESCRIPTION
**Pull request by dmitripivkine**
Consolidate all J9VMSTATE_GC states in OMR. Replace JVM specific
J9VMSTATE_GC_UNLOADING_DEAD_CLASSLOADERS to neutral
J9VMSTATE_GC_CLEANING_METADATA

Signed-off-by: Dmitri Pivkine <Dmitri_Pivkine@ca.ibm.com>

### CODE REVIEW

**Comment by dmitripivkine** [comment]
@charliegracie FYI

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by charliegracie** [comment]
@dmitripivkine this is ready to go?

**Comment by dmitripivkine** [comment]
I launched personal build to double check there is no compilation problems

**Comment by dmitripivkine** [comment]
I believe it should be ok

**Pull request merged**
