### PR TITLE
Runtime compressed refs work

### PR DESCRIPTION
**Pull request by gacholio**
Remove the automatic definition of OMR_GC_FULL_POINTERS and update the
example config files.

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by youngar** [comment]
@genie-omr build xlinux

**Comment by youngar** [comment]
@genie-omr build all

**Comment by youngar** [comment]
@genie-omr build all

**Comment by mstoodle** [comment]
@gacholio @youngar Can I ask for a little more justification for why this change was warranted?

**Comment by youngar** [comment]
This change is one piece of a set of changes to allow "compressed references" to be a dynamic startup decision instead of a compile (or configure) time decision. The current model is that at least one of `OMR_GC_COMPRESSED_POINTERS` or `OMR_GC_FULL_POINTERS` must be enabled.  If both are enabled it becomes a runtime decision.  This change in particular enables `OMR_GC_FULL_POINTERS` for all OMR testing builds.

**Comment by mstoodle** [comment]
I guess I meant, the change to no longer enable `OMR_GC_FULL_POINTERS` by default but rather to add it explicitly to all our *automated* build scenarios (leaving manual ones and any missing automated scenarios with problem).

I was a little surprised to see this kind of change made, which impacts everyone who builds OMR with little explanation, justification, or discussion in the PR before it was merged.

**Comment by youngar** [comment]
The plan is to make `OMR_GC_FULL_POINTERS` enabled by default.  This will keep the OMR behavior consistent with the past.  I don't think there are any objections to this, but if there are any concerns please let me know.

This is probably not the best justification, but the reason this was done this way was keep Openj9 builds from exploding.  Openj9 needs to add the option to disable `OMR_GC_FULL_POINTERS` before we can default the feature to `ON`.

In the past I have done this 'repo dance' many times to try to keep OpenJ9 builds running.  This means I have made temporary changes which are not great for OMR, with the plan of fixing things later.  I see how this can negatively affect users of OMR who are not OpenJ9.  Should I change my personal policy to avoid build breakages?  It seems unfair that I give OpenJ9 such priority.

**Pull request merged**
