### PR TITLE
Add omrsysinfo_processor_disable_feature API

### PR DESCRIPTION
**Pull request by harryyu1994**
This API is used for disabling features in OMRProcessorDesc.

Issue: #4339

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
Actually, having second thought on this one, this API may not be necessary.. Going to put this on hold and see how the review for https://github.com/eclipse/omr/pull/4744 goes.

**Comment by harryyu1994** [comment]
@rwy0717 This item is ready for review. Thanks!

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by harryyu1994** [comment]
@rwy0717 Hi Robert, tests passed, could we merge this?

**Pull request merged**
