### PR TITLE
Enable vxor, vor, and vand IL opcodes on PPC

### PR DESCRIPTION
**Pull request by midronij**
Enable vxor, vor, and vand for all integer vector types (byte, short, int, long), which will allow the vectorization of various integer-only vector operations (such as logical opersations) to occur.

### CODE REVIEW

**Comment by midronij** [comment]
@gita-omr could you please review when you have a moment? The change itself is very small so it shouldn't take too long.

**Comment by gita-omr** [comment]
@midronij could you please put a pointer to the code where those opcodes are implemented (evaluators) and will get activated by this change?

**Review by gita-omr — APPROVED** [review]

**Comment by midronij** [comment]
@knn-k when you have a chance could you please review and (if everything looks alright) merge?

**Comment by knn-k** [comment]
Jenkins test sanity plinux,aix jdk17

**Comment by knn-k** [comment]
Jenkins build plinux,aix

**Review by knn-k — APPROVED** [review]

**Pull request merged**
