### PR TITLE
Cmake: add Unix Makefile CMake builds

### PR DESCRIPTION
**Pull request by rwy0717**
* Parameterize the cmake generator
* Disable all osx/cmake builds
* Use cmake to build the project

Signed-off-by: Robert Young <rwy0717@gmail.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
Have @dnakamura or @mgaudet reviewed this yet?  Looking for a thumbs up

**Comment by dnakamura** [comment]
Any particular reason you are disabling the osx cmake builds?

**Comment by rwy0717** [comment]
They're already disabled, and when I wrote this, osx builds were still busted. Enabling osx is happening in a different PR.

**Comment by charliegracie** [comment]
I believe it was disabled before.  The change is just disabling the new CMake build right?

**Pull request merged**
