### PR TITLE
Enable simplifying conditional store in CFG simplifier on x, p,…

### PR DESCRIPTION
**Pull request by Charlmzz**
Ternary used in cfg simplifier is only supported on x, p and z
now, so a codegen capability query for ternary support is added. 
Capability check to guard ternary generation in CFGSimplifier is thus added in
so that simplifying conditional store is turned on for those three platforms.
   
Signed-off-by: Yiling Han <Yiling.Han@ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
FYI @fjeremic since I am going to be away from mid-tomorrow for a bit could you have a look and shepherd this one?

**Comment by 0xdaryl** [comment]
Please create an issue to track the work to enable this on ARM, AArch64, and RISC-V so it is not forgotten.

**Comment by Charlmzz** [comment]
Issue #4682 has been created as a reminder to enable this on ARM, AArch64, and RISC-V.

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
What confuses me is the wording of the commit title and message.  Unless I'm completely misreading the code, this PR isn't about enabling CFGSimplifier for three platforms.  It's about restricting certain analyses and transformations that CFGSimplifier does because we can't generate code for ternary opcodes on certain platforms.  If that's the case, I request that the commit text be made clearer before merging.

**Comment by 0xdaryl** [comment]
Also, please be aware of #4578, which is renaming the "ternary" opcodes to "select".  If that PR lands first then your queries should be changed to refer to "select" opcodes rather than "ternary" opcodes.

**Comment by fjeremic** [comment]
> Also, please be aware of #4578, which is renaming the "ternary" opcodes to "select". If that PR lands first then your queries should be changed to refer to "select" opcodes rather than "ternary" opcodes.

#4578 looks to have halted waiting for reviews to be addressed for a few weeks. I think we'll proceed with this one first and make a note there to fixup the new uses.

**Pull request merged**
