### PR TITLE
Remove blockindex

### PR DESCRIPTION
**Pull request by a7ehuo**
Deprecate blockIndex in codegen
    
Closes: #5293

### CODE REVIEW

**Comment by a7ehuo** [comment]
Change the status to `WIP` until eclipse/openj9#12584 is merged.

**Comment by fjeremic** [comment]
Jenkins build all

**Comment by fjeremic** [comment]
@a7ehuo does this fix #5293?

**Comment by a7ehuo** [comment]
> @a7ehuo does this fix #5293?

Yes, this PR deprecates all blockIndex related APIs. 

I'm not sure the PR build would pass. This PR removes the APIs used by eclipse/openj9#12584 which should be merged first.

**Comment by fjeremic** [comment]
Ok, thanks. I've updated the PR message to use the [GitHub keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword).

**Comment by fjeremic** [comment]
@a7ehuo downstream dependencies have been merged. We should be ok here.

Jenkins build all

**Review by fjeremic — APPROVED** [review]

**Pull request merged**
