### PR TITLE
Phony: Testing the genie

### PR DESCRIPTION
**Pull request by rwy0717**
/cc @youngar

### CODE REVIEW

**Comment by youngar** [comment]
genie-omr build

**Comment by charliegracie** [comment]
genie-omr build

**Comment by youngar** [comment]
genie-omr build

**Comment by charliegracie** [comment]
genie-omr build

**Comment by charliegracie** [comment]
genie-omr build

**Comment by charliegracie** [comment]
genie-omr build

**Comment by rwy0717** [comment]
sudo @genie-omr build

**Comment by charliegracie** [comment]
add to whitelist

**Comment by charliegracie** [comment]
genie-omr build

**Comment by youngar** [comment]
genie-omr build

**Comment by youngar** [comment]
genie-omr build

**Comment by charliegracie** [comment]
genie-omr build

**Comment by youngar** [comment]
genie-omr build

**Comment by youngar** [comment]
genie-omr build

**Comment by youngar** [comment]
genie-omr build

**Comment by charliegracie** [comment]
genie-omr build

**Comment by youngar** [comment]
genie-omr build

**Comment by youngar** [comment]
genie-omr build

**Comment by charliegracie** [comment]
test this please

**Comment by charliegracie** [comment]
ok to test

**Comment by charliegracie** [comment]
test this please

**Comment by youngar** [comment]
Closing, I think we're done here. Thanks @rwy0717.

**Pull request closed without merging**
