### PR TITLE
Revert "Migrate processor/feature detection from OpenJ9 to OMR Part 1"

### PR DESCRIPTION
**Pull request by rwy0717**
Reverts eclipse/omr#4503

4503 introduced new CPU introspection utilities from OMR. This code was donated from OpenJ9. Part of this change added public symbols to the port library which were not part of the API. Because these symbols were not part of the public API, they weren't renamed, which caused duplicate symbols during linking in J9. I am reverting the original PR so we can revisit the organization and naming of the private helper functions.

### CODE REVIEW

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
Can you provide a reason or link to an issue for why this revert is necessary please?

**Comment by AidanHa** [comment]
I know what the Issue is, the port library functions that I have moved over from OpenJ9 to OMR have the same name. Renaming the functions should fix it. I tdon't think there is a need to revert.

**Comment by AidanHa** [comment]
https://github.com/eclipse/omr/pull/4656

Rather than reverting, I've added changes here that should fix the compile failure.

**Comment by rwy0717** [comment]
Updated @0xdaryl! Sorry I just wanted to get the tests rolling before I wrote the motivation.

**Comment by 0xdaryl** [comment]
Thanks Rob!

**Pull request merged**
