### PR TITLE
Fix hang in omrrastest

### PR DESCRIPTION
**Pull request by dnakamura**
If testTICpuLoad fails, agent aborts without detaching thread. This
results in a hang at shutdown while we wait for all outstanding threads
to shutdown.

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by dnakamura** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
Wondering if this is in any way related to #4746?

**Comment by dnakamura** [comment]
@fjeremic unfortunately no. It seems alot of our test code doesn't properly handle tests failing

**Comment by youngar** [comment]
@genie-omr build all

**Pull request merged**
