### PR TITLE
Update target windows  version to win 7

### PR DESCRIPTION
**Pull request by dnakamura**
Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by Leonardo2718** [comment]
@genie-omr build win

**Comment by youngar** [comment]
Change looks good.  I would consider putting an explanation of why we upgraded (for `GetCurrentProcessorNumberEx`)

**Comment by charliegracie** [comment]
@samolisov If I remember correctly you added the code to require XP. Does this change break anything in your environment?

**Comment by charliegracie** [comment]
@genie-omr build win

**Comment by youngar** [comment]
> @samolisov If I remember correctly you added the code to require XP. Does this change break anything in your environment?

That change set it to WindowsXP because that is how it was in the old build system, and I think it was missing in cmake.

@dnakamura [It looks like openj9 is still using 0x501](https://github.com/eclipse/openj9/blob/ede34ef90806363e8ccae5abcb8f99bbdacc6761/runtime/makelib/targets.mk.win.inc.ftl#L186), is this going to be a problem?

**Pull request merged**
