### PR TITLE
Document C++ features usable in OMR

### PR DESCRIPTION
**Pull request by rwy0717**
This is an old document that i've been keeping around for myself, and I figured it was about time to polish up and share with others. There is a good chance that there are some inaccuracies, but its a good starting point.

Signed-off-by: Robert Young <rwy0717@gmail.com>

### CODE REVIEW

**Comment by Leonardo2718** [comment]
Nice! This is definitely something we need.

While you're at it, maybe you could also remove/merge the related content that is at the bottom of [the compiler's README](https://github.com/eclipse/omr/blob/master/compiler/README.md)?

In the past, I've had problems with some of the C++11 features you listed as supported because they were not fully supported by some compilers. It's been a while since I ran into those problems though so they could be fixed now. One of the problems was MSVC incorrectly parsing decltype statements of the form `decltype(expr)::member`. I only have vague recollections of the other problems so I would have to test them out again.

**Comment by rwy0717** [comment]
Does the compiler need to track it's own set of supported compilers, or can I just delete the entire section?

**Comment by Leonardo2718** [comment]
This is a documentation-only change so no need for a build. Merging now.

**Comment by 0xdaryl** [comment]
Thanks for pulling this together @rwy0717.

I think this file should be referenced somewhere (like the Contribution Guidelines).  Otherwise, how will someone new know that it exists?

Also, the filename is very 8.3 DOS-like.   How about something (a little) more descriptive like "SupportedCXXFeatures.md" for those that happen to come across it in the directory?

**Comment by rwy0717** [comment]
Sure, since this PR was already merged, I'll open a new PR tomorrow with the suggested changes.

**Pull request merged**
