### PR TITLE
Remove redundant/unneeded stack map and atlas methods

### LINKED ISSUE #2619: Remove redundant / unneeded stack map alias methods from JitBuilder's FrontEnd
I understand that following are not needed:

```
  void encodeStackMap(
     TR_GCStackMap *map,
     uint8_t *location,
     bool encodeFourByteOffsets,
     uint32_t bytesPerStackMap,
     TR::Compilation *comp);

  bool mapsAreIdentical(
     TR_GCStackMap *mapCursor,
     TR_GCStackMap *nextMapCursor,
     TR::GCStackAtlas *stackAtlas,
     TR::Compilation *comp);

  uint8_t *createStackAtlas(
     bool encodeFourByteOffsets,
     uint32_t numberOfSlotsMapped,
     uint32_t bytesPerStackMap,
     uint8_t *encodedAtlasBaseAddress,
     uint32_t atlasSizeInBytes,
     TR::Compilation *comp);

  uint32_t
     calculateSizeOfStackAtlas(
     bool encodeFourByteOffsets,
     uint32_t numberOfSlotsMapped,
     uint32_t bytesPerStackMap,
     TR::Compilation *comp);
```

### PR DESCRIPTION
**Pull request by nidhi1605**
Fixes #2619

Removed redundant / unneeded stack map alias methods from JitBuilder's FrontEnd and fvtest

Signed-off-by: Nidhi Gupta <itsnidhi16@gmail.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by nidhi1605** [comment]
@0xdaryl Could you please review this.

**Comment by 0xdaryl** [comment]
I'm not sure where "alias" comes into the picture here (you haven't removed anything to do with aliasing).  I *think* you mean to say "and atlas" rather than "alias".  Do you agree?  Please change the commit title and body to avoid confusion.  Code looks fine.

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Pull request merged**
