### PR TITLE
Remove unnecessary files for building JitBuilder

### LINKED ISSUE #1537: Un-necessary objects in JitBuilder builds?
Building JitBuilder on OS/X the archiver warns about objects it believes to be empty. 

* `compiler/x/codegen/Trampoline.cpp` 
* `compiler/codegen/OMRRegisterDependency.cpp` 

Cursory inspection suggests these warnings are correct and we can even probably delete these files, but that needs validation.

### PR DESCRIPTION
**Pull request by rbanerjee**
These files only lead to the creation of empty objects.

Note that this change is dependent on https://github.com/eclipse/openj9/pull/616 and should only be merged once the OpenJ9 PR is merged.

Fixes Issue #1537

Signed-off-by: Rwitaban (Ray) Banerjee <rayb@ca.ibm.com>

### CODE REVIEW

**Comment by mgaudet** [comment]
You'll also have to edit the Makefile based build story for OMR -- see `jitbuilder/build/files/*`

**Comment by rbanerjee** [comment]
Oops! Sorry about that. Should be good now.

**Comment by mgaudet** [comment]
This likely is a breaking change for downstream projects like OpenJ9, which will reference the deleted file in their own makefiles. 

Probably need to prepare the paired dependency resolving change on the OpenJ9 side.

**Comment by 0xdaryl** [comment]
@rbanerjee , just confirming this is ready to merge.  If @mgaudet 's [comment](https://github.com/eclipse/omr/pull/1740#issuecomment-332957475) applies, please add `WIP:` to the PR title until this is ready to merge.

**Comment by 0xdaryl** [comment]
There hasn't been an update on this for a month.  Are the issues preventing this PR from being merged going to be addressed soon?

**Comment by rbanerjee** [comment]
@0xdaryl  As for 
> Are the issues preventing this PR from being merged going to be addressed soon?

I will need to submit a dependency resolving change to OpenJ9. I will ping you once that's done.

**Comment by rbanerjee** [comment]
@0xdaryl ptal. This - https://github.com/eclipse/openj9/pull/616, resolves the paired dependency on the OpenJ9 side.

Keeping the `WIP` for now. Will remove once the OpenJ9 PR goes through.

**Comment by rbanerjee** [comment]
https://github.com/eclipse/openj9/pull/616 has now been merged. Removing the `WIP` tag.

**Comment by 0xdaryl** [comment]
genie-omr build all

**Pull request merged**
