### PR TITLE
CMake: update cross compilation support

### PR DESCRIPTION
**Pull request by dnakamura**
- Introduce OMR_CROSSCOMPILING which mirrors CMAKE_CROSSCOMPILING but
   ignores the case of building for windows from cygwin

 - Automatically attempt to find a version of qemu to launch executables
   if required.

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by dnakamura** [comment]
@0xdaryl  can you take a look at this? thx

**Comment by 0xdaryl** [comment]
Jenkins build all

**Comment by 0xdaryl** [comment]
@dnakamura : see the RISC-V CI failure.  I think the zOS failure is infrastructural and not related to this PR.

**Comment by dnakamura** [comment]
@0xdaryl  Updated the aarch64 build definition, and it should now work (at least it seems to on my attempted replica of the CI env).

**Comment by 0xdaryl** [comment]
Minor nit: can you update the copyright headers to 2022 on the changed files please?  Previous CI testing passed so there is no need to re-run it.

**Review by 0xdaryl — APPROVED** [review]

**Comment by keithc-ca** [comment]
This breaks builds of OpenJ9 on Windows:
* https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-32_windows_OMR/174/
* https://openj9-jenkins.osuosl.org/job/Build_JDK8_x86-64_windows_OMR/176/

```
13:07:45  CMake Error at /cygdrive/f/Users/jenkins/workspace/Build_JDK8_x86-64_windows_OMR/omr/cmake/modules/OmrDDRSupport.cmake:36 (message):
13:07:45    DDR is not supported when cross-compiling.  Use -DOMR_DDR=OFF to disable
13:07:45    DDR.
```

**Pull request merged**
