### PR TITLE
Deprecate unused indirectMethodMetaUses and regStarAsmUses bitvectors

### PR DESCRIPTION
**Pull request by fjeremic**
Both of these bitvectors are initialized using the default constructor
and are only queried via the `IsZero` API and are never set. Thus the
code being guarded by queries to these bitvectors is dead and can be
removed to simplify the implementation.

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Suggesting @vijaysun-omr or @andrewcraik as committers for this one. This cleanup is in preparation for documentation of dataflow analysis. I'm considering using liveness as a potential example to do a code walk-through as part of the documentation.

**Comment by andrewcraik** [comment]
@vijaysun-omr I think you are the better one to take this

**Comment by vijaysun-omr** [comment]
I agree with the proposed cleanup. Running checks and I will merge once they pass.

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by Leonardo2718** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@genie-omr build all

**Pull request merged**
