### PR TITLE
CMake: Add some new utilities

### PR DESCRIPTION
**Pull request by rwy0717**
This adds a new cmake module, OmrUtility, with some convenience functions for manipulating strings as flags.

The additions are:
`omr_remove_flags`: Renamed version of `omr_remove_option`. Accepts multiple flags.
`omr_stringify`: Stringify a list to a space separated string of items.
`ome_append_flags`: Append a list of flags to a string, intended to be used with `CMAKE_<LANG>_FLAGS` variable.

### CODE REVIEW

**Comment by charliegracie** [comment]
Has @dnakamura or @mgaudet reviewed this yet?  Looking for a thumbs up

**Comment by rwy0717** [comment]
Whoops, should have CC'd. That explains why nothing's going on.

**Comment by dnakamura** [comment]
I feel like there was a reason I made `omr_remove_option` a macro, but im not sure why. But I guess it wasn't really a valid reason if it still works.

**Comment by dnakamura** [comment]
LGTM

**Comment by rwy0717** [comment]
I'm guessing it was done as a macro instead of using `PARENT_SCOPE`.

**Comment by dnakamura** [comment]
actually it was probably So I could avoid the `set()` all together and just rely on `string(REGEX REPLACE` to do all the work

**Pull request merged**
