### PR TITLE
Add relo type for a pointer to an inlined method

### PR DESCRIPTION
**Pull request by dsouzai**
Signed-off-by: Irwin D'Souza <dsouzai.gh@gmail.com>

### CODE REVIEW

**Comment by dsouzai** [comment]
@mstoodle could you please review/merge.

**Review by mstoodle — CHANGES_REQUESTED** [review]
lgtm, and no cross-platform issues that need testing. Can you please update at least the commit message to describe the new relocation record type's purpose?

**Comment by mstoodle** [comment]
Just recording that all the default tests have run and passed at this point, and I think that's good enough to merge this PR (once the commit message is updated).

**Comment by dsouzai** [comment]
@mstoodle updated commit message.

**Comment by mstoodle** [comment]
thx @dsouzai !

**Pull request merged**
