### PR TITLE
Set OMR_ENV_DATA64 when configuring build tools

### PR DESCRIPTION
**Pull request by youngar**
Build tools require to be configured according to the current host
platform. This variable currently defaults to the target platform, which
causes cross compilation issues.

issue: #1955

Signed-off-by: Andrew Young <youngar17@gmail.com>

### CODE REVIEW

**Comment by rwy0717** [comment]
LGTM, but you might as well also `AC_SUBST` the 32bit flag as well, right?

**Comment by youngar** [comment]
`OMR_ENV_DATA32` is not a flag that we use.  It looks like it was added in the cmake build system though:
```
cmake/modules/OmrDetectSystemInformation.cmake:69:      if(NOT (OMR_ENV_DATA64 OR OMR_ENV_DATA32))
cmake/modules/OmrDetectSystemInformation.cmake:75:                      set(OMR_ENV_DATA32 ON)
cmake/modules/OmrDetectSystemInformation.cmake:83:                      #TODO assert OMR_ENV_DATA32 is not also set
cmake/modules/OmrDetectSystemInformation.cmake:85:              elseif(OMR_ENV_DATA32)
cmake/modules/platform/toolcfg/msvc.cmake:63:elseif(OMR_ENV_DATA32)
```

**Comment by rwy0717** [comment]
Oh OK, don't worry about it then :)

**Comment by charliegracie** [comment]
Is this PR ready?

**Comment by youngar** [comment]
I haven't tested it properly with a Java build. My builds have been failing every time for various unrelated issues (e.g. machine issues). I don't see why it shouldn't be okay, but I want to test it first.

**Comment by youngar** [comment]
@charliegracie good to go

**Comment by charliegracie** [comment]
genie-omr build zlinux

**Pull request merged**
