### PR TITLE
WIP: Relicense the thread & omrmakefiles directories to EPLv2 & Apache v2

### PR DESCRIPTION
**Pull request by DanHeidinga**
Update the license as per the outcome of the vote in issue #1596.

This can't be accepted until all contributors in #1606 have signed off on the relicensing their contributions.

### CODE REVIEW

**Comment by mgaudet** [comment]
Commit message says EPL V3 :)

**Comment by charliegracie** [comment]
This will need to be updated to the latest message as be the issue, rebased and the commit messages need to be updated to say EPL V2.  Thanks

**Comment by DanHeidinga** [comment]
Closing this in favour of #1622 which has the correct copyrights.

**Comment by DanHeidinga** [comment]
Closing

**Pull request closed without merging**
