### PR TITLE
Tril tests for iffcmpeq, etc.

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds Tril test cases for floating-point conditional
branches, such as iffcmpeq and ifdcmpgt.

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
This will conflict with #3388.

**Comment by Leonardo2718** [comment]
@knn-k Please resolve merge conflicts, now that #3404 has been merged.

**Comment by knn-k** [comment]
Resolved merge conflicts.

**Comment by Leonardo2718** [comment]
@genie-omr build all

**Pull request merged**
