### PR TITLE
Improve x86 code generation for constant null compression sequences

### PR DESCRIPTION
**Pull request by jdmpapin**
...as they occur in plain stores (as opposed to write barriers, or elsewhere). Usually a compression (not decompression) sequence feeds directly into some kind of store, and usually write barriers storing null should have already been changed into plain stores before code generation.

Consider this sequence of stores that set an object's fields to null:

    foo.f1 = null;
    foo.f2 = null;
    foo.f3 = null;

We've been generating code that looks something like this:

    xor ecx, ecx
    mov rdx, rcx
    shr rdx, 0x03
    mov dword ptr [rax+0x8], edx
    mov rdx, rcx
    shr rdx, 0x03
    mov dword ptr [rax+0xc], edx
    shr rcx, 0x03
    mov dword ptr [rax+0x10], ecx

With this commit we'll now use immediates, like so:

    mov dword ptr [rax+0x8], 0
    mov dword ptr [rax+0xc], 0
    mov dword ptr [rax+0x10], 0

or, if the null constant has already been evaluated into a register, then that register will be used directly, like so:

    mov dword ptr [rax+0x8], edi
    mov dword ptr [rax+0xc], edi
    mov dword ptr [rax+0x10], edi

This eliminates the unnecessary shift (if present) and a reg-reg move that would previously result from evaluating `a2l`.

Additionally, only because it was easy to make the improvement slightly more general, any other compression sequence that occurs as the child of a plain store and that doesn't contain a shift is also improved through the direct use of the register from the original reference node, eliminating a reg-reg move. This will only benefit small heaps and for the most part only in GC modes that don't require write barriers.

### CODE REVIEW

**Comment by jdmpapin** [comment]
@0xdaryl please review

**Comment by 0xdaryl** [comment]
This code won't be exercised very well in OMR.  Can you be sure you run at least sanity.functional and sanity.openjdk (the OMR acceptance build criteria) in OpenJ9 on x86 with this change please (and confirm that it runs successfully)?

**Comment by 0xdaryl** [comment]
Do you have an update on the requested testing status?

**Comment by jdmpapin** [comment]
I was delayed in starting my build. I waited a short time to pick up eclipse-openj9/openj9#17970, since I expected it to fix the timeouts in the vector tests. Then it turned out that along with that change I had also picked up a build break, so I had to get eclipse-openj9/openj9#17986 too

I now have a personal build running that corresponds to
> J... test sanity.functional,sanity.openjdk xlinux,xmac,win,win32 jdk8,jdk11,jdk17,jdk21

By now most of the jobs have passed, but I've had to restart some due to infrastructure problems, and I'm still waiting for the last few

**Comment by jdmpapin** [comment]
The tests have passed

**Comment by 0xdaryl** [comment]
Jenkins build xlinux,win,osx,x32linux

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
