### PR TITLE
Add AArch64 to UtProcessorInfo

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds AArch64 to UtArchitecture and Armv8-A to UtSubtype.

### CODE REVIEW

**Comment by knn-k** [comment]
Jenkins build aarch64,amac

**Comment by knn-k** [comment]
The failures on x86-64 macOS are independent of this PR.

**Comment by 0xdaryl** [comment]
This seems reasonable to me.  @pshipton : can you (or delegate) review in case you disagree?

**Comment by pshipton** [comment]
Looks fine to me. 
@babsingh

**Comment by babsingh** [comment]
Only known failures are seen in the PR builds:
- #7181
- https://github.com/eclipse/omr/issues/6905

**Review by babsingh — APPROVED** [review]

**Pull request merged**
