### PR TITLE
Revert "Add OMR::XXX::Machine::getXXXRealRegister()"

### PR DESCRIPTION
**Pull request by samolisov**
This reverts commits with titles such as "Add OMR::XXX::Machine::getXXXRealRegister()"

The wrapper methods 'getXXXRealRegister()' is not required since all
uses of the methods are changed to the 'getRealRegister()' one.

If the methods are still in the codebase, there forever will be a temptation for everyone to use a  platform specific method instead of the generic one.

The PR should be merged after eclipse/openj9#2936.

### CODE REVIEW

**Comment by samolisov** [comment]
The builds are successful and eclipse/openj9#2936 is merged, so I've removed the 'WIP' marker. @Leonardo2718 @fjeremic  @0xdaryl, this is the last step of the `getRealRegister()` cleanup process.

**Comment by Leonardo2718** [comment]
Given that all they do the same thing as `OMR::Machine::getRealRegister()`, are the architecture-specific overrides really needed? Shouldn't these just be removed?

**Comment by samolisov** [comment]
@Leonardo2718, you are absolutely right! I just forgot about the commit where all methods were consolidate. Return 'WIP' back.

**Comment by samolisov** [comment]
@Leonardo2718, you are absolutely right! I just forgot about the commit where all methods were consolidated.  Return 'WIP' back.

**Comment by samolisov** [comment]
@Leonardo2718 I've updated the commits, not they just remove the `getXXXRealRegister` methods from the codebase. Could you have a look?

**Comment by Leonardo2718** [comment]
@genie-omr build all

**Comment by samolisov** [comment]
@0xdaryl The PR is approved by @Leonardo2718 and @fjeremic Can you merge it, please?

**Pull request merged**
