### PR TITLE
[ci skip] Update the README.md to include the AIX build badge

### PR DESCRIPTION
**Pull request by charliegracie**
Signed-off-by: Charlie Gracie <charlie.gracie@gmail.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
* Please update the copyright header to 2018.

* While it's fine to add AIX to this list, other than hovering over the badges how do you tell what build it's for?  We now have 5 builds that look the same.  I guess its only the failing ones that you'd care about clicking on.

**Comment by charliegracie** [comment]
Updated the copyright

**Comment by charliegracie** [comment]
Anything else required @0xdaryl ?

**Comment by charliegracie** [comment]
Ping?

I agree that the project could probably do a better job of describing the builds / badges but I just want to make sure that all of the current builds are listed on the main page.  If the project comes up with a better story we can change all of them at the same time.

**Pull request merged**
