### PR TITLE
Defer versioning to allow privatization

### PR DESCRIPTION
**Pull request by jdmpapin**
This series implements the framework within which versioning transformations (including improvements to the loop and the emission of versioning tests) will be reified and deferred. It then updates the logic for each type of versioning transformation to take advantage of the new framework. This is done because some transformations are only correct if certain loads in the loop are privatized. Deferral makes it possible to express the fact that the transformation relies on privatization, and to skip the transformation if privatization turns out not to be possible. For more details, see the doc comment on `TR_LoopVersioner`, and the individual commit messages.

### CODE REVIEW

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by jdmpapin** [comment]
Whoops, `isConversionWithFraction()` is J9-specific:
```
../../compiler/optimizer/LoopVersioner.cpp:8882:26: error: no member named
      'isConversionWithFraction' in 'TR::ILOpCode'
   if (node->getOpCode().isConversionWithFraction())
```

**Comment by jdmpapin** [comment]
Updated to put `isConversionWithFraction()` behind `#ifdef J9_PROJECT_SPECIFIC`

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
Windows builds covered by OMR CI, not waiting for AppVeyor for this one.

**Pull request merged**
