### PR TITLE
Make sure LoopVersioner creates async check guard tests safely

### PR DESCRIPTION
**Pull request by ymanton**
This patch set fixes LoopVersioner so that it will create guard tests for `asynccheck` versioning safely by making sure that any duplicated trees have their flags reset. The first patch introduces a new `OMR::Node` method that duplicates trees for the purposes of inserting them arbitrarily; the second patch uses it in `LoopVersioner`; the third is cosmetic and cleans up the surrounding code in `LoopVersioner` to improve readability.

Issue: #717

### CODE REVIEW

**Comment by ymanton** [comment]
> There seem to be several calls to duplicateTree from other parts of LoopVersioner.cpp unrelated to async check versioning. In many of those cases, the same sort of code motion is being done after duplicating a node.
Is there a reason for limiting your change to the async check versioning case ?

Considered that, but I wasn't sure that it would be justified. The case addressed by this PR is a verified problem that fixes a failing downstream Java test. There are many uses of `duplicateTree()` in this part of the code, changing so many of them could expose other functional and performance bugs for downstream.

Never the less, I can make the change if we think it's worthwhile.

**Comment by vijaysun-omr** [comment]
Since the implications relate to functional correctness I would like to see us try and fix those other places as well. However, I do not want to hold up this PR since what you have here is obviously better than what we had before and will fix the test case failure you mentioned. 

My suggestion would be to open a new PR and organize the changes logically (i.e. different kinds of versioning you are changing the code for) in terms of different commits in that PR so that it is easier for someone doing a binary search in case there is a problem. Please create that new PR and paste a link in here (even if it's a WIP) and I will merge this in.

**Comment by ymanton** [comment]
I've opened #723 to fix the other cases.

**Comment by vijaysun-omr** [comment]
Thanks I have merged this PR now.

**Pull request merged**
