### PR TITLE
Implemented divide by zero check in BinaryEvaluator

### PR DESCRIPTION
**Pull request by hsoontie**
WIP Implementing divide by zero check in BinaryEvaluator

Signed-off-by: Hillary Soontiens <hsoontie@unb.ca>

### CODE REVIEW

**Comment by hsoontie** [comment]
Please note that this PR borrows code from #3517 .

**Comment by hsoontie** [comment]
@0xdaryl Fixed conflicts with master, squashed and removed WIP. This should now be good for review!

**Comment by aarongraham9** [comment]
This should be a good for a review @0xdaryl.

**Comment by 0xdaryl** [comment]
An integer division-by-zero operation is undefined.  I imagine different language environments will choose to handle it differently.  Hence, it is not clear to me what your expected result is when a division by zero is detected.  You avert any kind of hardware exception by checking for a zero divisor, but then you allocate a register and don't initialize it with anything.  This will lead to all sorts of strange behaviour.  What behaviour were you trying to achieve?  I'm not sure if we could come up with a standardized response to a division by zero that would make sense.

Also, the division-by-zero case is also exceptional.  Any sort of handling of it should not pollute the mainline code, which is why the processing of it should live in an out-of-line instruction sequence or a snippet.

The preferred way of handling integer division is by performing it under a `DIVCHK` node (an IL generator would have to enforce this).  This separates the divisor check from the actual division operation and different language environments can choose to implement the check differently depending on their environment's semantics.  The DIVCHK nodes can have a symbol reference that represents a function to call in the language environment for processing.  If performing an explicit test for a zero divisor (as you have done), then the test and branch in the mainline path would take you to a snippet (off the mainline path) to likely call back into the language environment for processing.  The optimizer already knows about DIVCHKs as well and can eliminate them if proven safe.

**Comment by hsoontie** [comment]
@0xdaryl It's been a while, but I think I was just trying to skip calling the evaluator in the case of division by zero. 
The code does include some unnecessary register allocation, and if using DIVCHK is the right way to go, I am happy with just closing this one and moving on if you are, Daryl.

**Comment by 0xdaryl** [comment]
Yes, I think this issue should be closed.  Individual language environments need to implement `TR::DIVCHK` evaluators to handle division-by-zero cases in a manner unique to their environment.

**Pull request closed without merging**
