### PR TITLE
Split J9STR_CODE_PLATFORM into _PLATFORM_RAW and _PLATFORM_OMR_INTERNAL

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Update string conversion to replace J9STR_CODE_PLATFORM into _PLATFORM_RAW 
(native format used by OS) and _PLATFORM_OMR_INTERNAL (code into which OMR 
implicitly translates certain system outputs)

Issue: #41
Signed-off-by: Peter Bain <pdbain@ca.ibm.com>

### CODE REVIEW

**Comment by alin00** [comment]
Is there an issue associated with this work item?  Please amend the commit comment to reference it.

**Comment by alin00** [comment]
See #49. Due to a bug in fvtest/porttest/makefile, the string regression tests are not being compiled or run. Please enable those tests and confirm that this patch passes them on all platforms.

If you have performed regression testing of this patch in some other way, please indicate how.

**Comment by alin00** [comment]
Please note that it is insufficient to simply reference the issue # in the pull request discussion comments. For us to match the commits to the issue, the git commit comment needs to contain the issue #.

**Comment by pdbain-ibm** [comment]
You mean like this?
commit 37ffad3b2551bf1447a5b5a34b12b8b21a357661
Author: Peter Bain <pdbain@ca.ibm.com> 2016-03-28 11:20:20
Committer: Peter Bain <pdbain@ca.ibm.com> 2016-03-31 08:14:29
Parent: 474c5e7877a162a0fdee9f8cd6a779bd769f29e6 (Merge pull request #38 from keithc-ca/fix-issue-37)
Branches: rework_string_conversion

Split J9STR_CODE_PLATFORM into _PLATFORM_RAW and _PLATFORM_OMR_INTERNAL

Issue: #41
Signed-off-by: Peter Bain <pdbain@ca.ibm.com>

**Comment by alin00** [comment]
Yes.

**Comment by pdbain-ibm** [comment]
commit message updated.  Many thanks for your help, Angela.
Waiting for https://github.com/eclipse/omr/pull/49 so I can test the string changes.

**Comment by alin00** [comment]
#49 has been merged.

**Comment by alin00** [comment]
The proposed branch looks like an incorrect rebase, and can't be merged.

**Pull request closed without merging**
