### PR TITLE
Remove deprecated x87 features

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Remove deprecated needToClearFPStack and related functions
* Remove deprecated _mayNeedToPopFPRegisters
* Remove NeedsPrecisionAdjustment Node flag
* Remove mayNeedPrecisionAdjustment register flag
* Remove popRegisters List from RegisterDependency API

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins build all

**Comment by 0xdaryl** [comment]
This PR has been further tested in OpenJ9 on both 64-bit and 32-bit platforms.

**Comment by 0xdaryl** [comment]
@BradleyWood : would you mind reviewing this PR please?

**Comment by 0xdaryl** [comment]
Jenkins build all

**Comment by 0xdaryl** [comment]
Testing has passed.  Is there anything more to do here?

**Comment by BradleyWood** [comment]
Sorry, I missed this one. I will try to review today.

**Comment by 0xdaryl** [comment]
ping @vijaysun-omr

**Comment by vijaysun-omr** [comment]
I don't see a review from @BradleyWood that he is okay with this PR. I will wait for that before I merge.

**Comment by 0xdaryl** [comment]
Oh, sorry. I though I had seen that.  No problem.

**Comment by BradleyWood** [comment]
LGTM

**Review by vijaysun-omr — APPROVED** [review]

**Review by vijaysun-omr — APPROVED** [review]

**Pull request merged**
