### PR TITLE
Replace occurrences of J9ZTPF guard macro with OMRZTPF in OMR repo

### PR DESCRIPTION
**Pull request by jjohnst-us**
Minor update which affects z/TPF runtime only when building J9 signal handling features.  The wrong configuration is used when building for J9 because the J9 guard macro for z/TPF is not specified.

### CODE REVIEW

**Comment by babsingh** [comment]
`J9ZTPF` should not be used in the OMR repo since the naming suggests that it is specific to the OpenJ9 (upstream) project. OMR project should only use `OMRZTPF`, and `J9ZTPF` should be restricted to the OpenJ9 project. When OMR is built with OpenJ9, both `OMRZTPF` and `J9ZTPF` flags should be enabled.

I notice other places in the OMR repo where `J9ZTPF` is used. **Why are we mixing the use of `OMRZTPF` and `J9ZTPF` in the OMR repo?**

The change in this PR suggests that `OMRZTPF` is disabled while `J9ZTPF` is enabled, which doesn't seem correct.

**Comment by jjohnst-us** [comment]
@babsingh 

Apologies for the delay.

Good point, I change this PR to remove all occurrences of J9ZTPF reference in the OMR repo.

**Comment by jjohnst-us** [comment]
@babsingh

I just realized due to a push error, I apparently triggered a bunch of unnecessary reviewers, its up to you if you want to dismiss them, I don't have write access.

**Comment by babsingh** [comment]
LGTM. Minor nit: As per the [commit guidelines](https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md#commit-guidelines), the title in the commit message should preferably not end with a period. Can we  remove the period from the commit message's title?

**Comment by jjohnst-us** [comment]
@babsingh
Done.  Thank you!

**Review by babsingh — APPROVED** [review]
- Merging without builds since OMR Jenkins doesn't have z/TPF machines.
- OSX failure is unrelated and known: https://github.com/eclipse/omr/issues/7181.

**Pull request merged**
