### PR TITLE
Add edges on regions

### PR DESCRIPTION
**Pull request by efferifick**
Adds an interface to allow adding edges on a specific memory region.
Outline common code between the different `addEdge` and `addExceptionEdge` methods.

This contributes to [this](https://github.com/eclipse/openj9/issues/6099) openj9 issue

### CODE REVIEW

**Comment by andrewcraik** [comment]
Hmm, I'm not sure the design of allowing edges to vary in their destination regions is really the right design from a public API perspective - would it be better for the CFG to hold a reference to the region and to use that when it is asked to allocate nodes? That way only the root CFG needs to have its region set and there is no possibility of varying lifetimes for the parts of a CFG?

I just worry this kind of API is likely to lead to CFG element memory lifetime bugs....

**Comment by efferifick** [comment]
@andrewcraik Yeah, that is a good idea. I hadn't considered that. I'll make the changes!

**Comment by andrewcraik** [comment]
@efferifick should this be closed now you have opened #4022 ?

**Comment by efferifick** [comment]
Yes you are right, this PR is now the same as #4022.

**Pull request closed without merging**
