### PR TITLE
Fix mixed mode compile error

### PR DESCRIPTION
**Pull request by gacholio**
Spelling mistake in the currently uncompiled path.

[ci skip]

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
Related: https://github.com/eclipse/openj9/issues/643

**Comment by charliegracie** [comment]
No further testing required.  Once the AppVeyor build finishes this can be merged

**Comment by gacholio** [comment]
I've just mistakenly pushed more changes to this branch, so testing is likely required now.

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by charliegracie** [comment]
AIX machines are down.  Merging with the current test coverage

**Pull request merged**
