### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by mstoodle**
Two changes, both of which have potential to break builds:
1) the tril project doesn't currently check its dependence on testcompiler so now it will assert if not also enabled (not sure our build scripts currently do this)
2) set the linkage on all JitBuilder method symbols to use TR_System convention (currently uses default which, at least on some platforms, is TR_Private).

### CODE REVIEW

**Comment by mstoodle** [comment]
Hoping these won't broadly break the builds as they're both Good Thing(tm)s to do...

**Comment by mstoodle** [comment]
jenkins build all

**Comment by mstoodle** [comment]
I have run this PR locally on MacOS Aarch64, so I think this should be good to go. Maybe @0xdaryl could review, when you have a moment, please?

**Comment by AdamBrousseau** [comment]
Sorry, going to hijack your PR to test that amac has been added to `all`. All platforms in this PR are green as of now.

**Comment by AdamBrousseau** [comment]
jenkins build all

**Comment by AdamBrousseau** [comment]
Looks good.

**Comment by 0xdaryl** [comment]
I remember coming across the default `TR_Private` vs `TR_System` difference a few years ago and tried to fix it in the obvious place [1] then (since there really isn't a notion of "private linkage" in OMR).  However, I recall running into complications (perhaps in OpenJ9) that were discouraging enough to prevent me from proceeding, but I really don't remember many details beyond that.  I do remember thinking this should be corrected with a refactoring of the MethodSymbol/ResolvedMethodSymbol hierarchies.

Your approach to correct it at the call-site seems like it would be a safer fix and unlikely to cause problems in OpenJ9.

[1] https://github.com/eclipse/omr/blob/2148df2e8c76592cf7da37019e0060eab3c202d5/compiler/il/OMRResolvedMethodSymbol.cpp#L111

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
