### PR TITLE
Remove genericCallHash from OMRSymbolReferenceTable

### PR DESCRIPTION
**Pull request by arwinneil**
- Removed `_genericCallHash` and all references from OMR::SymbolReferenceTable.

Closes: #2129

Signed-off-by: Arwin Neil Baichoo <arwinneil@gmail.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
genie-omr build all

**Comment by arwinneil** [comment]
Sure, here you go.

**Comment by 0xdaryl** [comment]
genie-omr build all

**Comment by 0xdaryl** [comment]
Sorry for the delay in getting back to this (I was on vacation).  Thanks for making the changes!

**Pull request merged**
