### PR TITLE
Re-introduce TR_j2iTransition helper for OpenJ9

### PR DESCRIPTION
**Pull request by 0dvictor**
Request by OpenJ9, re-introducing the helper TR_j2iTransition,
it will eventually superset all TR_icallVMprJavaSendStatic*.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by Leonardo2718** [comment]
@genie-omr build all

**Comment by Leonardo2718** [comment]
@0dvictor Could you elaborate on the reason why OpenJ9 needs this to be reintroduced?

**Comment by 0dvictor** [comment]
`TR_j2iTransition` is introduced to superset all `TR_icallVMprJavaSendStatic{*}` and `TR_icallVMprJavaSendNativeStatic`. In OpenJ9, all `icallVMprJavaSendStatic{*}` and `icallVMprJavaSendNativeStatic` are directly jump to j2iTransition; therefore it makes more sense to directly call `j2iTransition` instead. To achieve that, a new helper enum, `TR_j2iTransition`, is required. Then once OpenJ9 finishes its cleanup, OMR can remove all `TR_icallVMprJavaSendStatic{*}` and `TR_icallVMprJavaSendNativeStatic`. https://github.com/eclipse/openj9/pull/4598

`TR_j2iTransition` was introduced by #3543 for this purpose, but got accidentally deleted by #3557.

**Comment by Leonardo2718** [comment]
Oh! I see. So this will actually allow more Java specifics to be removed. Thanks for explaining @0dvictor!

**Pull request merged**
