### PR TITLE
Initial Tenure Age

### PR DESCRIPTION
**Pull request by amicic**
Initial Tenure Age will be a function of initial Nursery size. With
larger initial Nursery heaps, initial Tenure Age will be lower. This
helps promoting persistent objects (typically created at startup)
sooner, which reduces startup time and Nursery growth. See:
https://github.com/eclipse/omr/issues/3514

For Nursery Sizes of
256K, 512K, 1M, 2M, 4M, 8M, 16M, 32M, >=64M

initial Tenure Age is set respectively to:

9, 8, 7, 6, 5, 4, 3, 2, 1.

For OpenJ9, which starts with 2M Nursery, this will reduce the default
initial Tenure Age to 6 (from 10).

Signed-off-by: Aleksandar Micic <amicic@ca.ibm.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
The rate at which the initial tenure age is decreased seems very aggressive to me.  Most normal sized heap workloads (min/max heap set to 2G) would have a nursery of 512M.  This change would force an initial tenure age of 1 on all of those workloads.  

Since users can override the initial tenure age and still allow dynamic tenure age adjustment there is an easy "fix" if this causes issues.

**Comment by amicic** [comment]
Initial age 1 was intentionally set (even for not so large inital heaps). Measurements here (https://github.com/eclipse/omr/issues/3514#issuecomment-457635715) for initial heap size of about 40M Nursery clearly show that age 1 helped. Similar experiment was done with age 3 (not shown in the issue though), but it did not help as much.

I've also done some informal measurements of GC times for a known Java benchmark with larger initial heaps (order of GB Nursery) and it demonstrated a drop in pauses for the first few GC cycle (except first one which is same, since all objects are flipped at least once) till age converges to a somewhat stable value. 

Possibly age 1 is optimal across all initial sizes (even as low as 1M Nursery or so), but due to lack of data for very small initial Nursery sizes (order of 1M),  I just left it somewhere in between what we used to have and aggressive setting of 1. 

Btw, I'm unsure what you meant by 'this' in you last statement. Did you mean issue with this change or issue with high current default age value of 10 (ie are you endorsing the change or not)?

**Comment by charliegracie** [comment]
the `this` was this change.  I was sort of endorsing the change :)

With your further explanation I am ok with the change.

**Comment by charliegracie** [comment]
@genie-omr build all

**Pull request merged**
