### PR TITLE
Check array element type loads in constrainIaload

### PR DESCRIPTION
**Pull request by jdmpapin**
VP (value propagation) attempts in `constrainIaload()` to constrain the
class that results from an `aloadi` of the array component type from a
known class. Care must be taken to ensure that the known class really
represents an array type, since it might be a non-array type in cases
where VP is looking at a dead path.

Signed-off-by: Devin Papineau <devinmp@ca.ibm.com>

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
Does this need to be back ported to older service streams as well ?

**Comment by vijaysun-omr** [comment]
I would like @andrewcraik to review this

**Comment by jdmpapin** [comment]
> Does this need to be back ported to older service streams as well ?

This change prevents the incorrect load in two places:
1. at the call to `getComponentClassFromArrayClass()`, and
2. at the call to `constrainCompileTimeLoad()`.

My impetus for this change was noticing the bug at (1), which is in new code. But now that you mention it, I realize that I found (2) only after fixing (1) (by adding the check that `isArray()==TR_yes`). So the fix for (2) may need to be ported. I'll try my test case.

**Comment by mstoodle** [comment]
@vijaysun-omr @jdmpapin discussing older service streams is something IBMers should probably do internally rather than in the OMR project.

**Pull request merged**
