### PR TITLE
Change lower case to sentence case in CONTRIBUTING

### PR DESCRIPTION
**Pull request by mgaudet**
This matches the example good commit, and also the suggested advice from
Chris Beams.

[ci-skip] Documentation change.

### CODE REVIEW

**Comment by mgaudet** [comment]
Changed to sign-off commit.

**Comment by youngar** [comment]
Looks good to me, but I think it should have been `[ci skip]` instead of `[ci-skip]`, the build still ran :P.

**Comment by fjeremic** [comment]
@youngar You beat me to it. You are correct however. Here is the documentation: https://docs.travis-ci.com/user/customizing-the-build/#Skipping-a-build

**Comment by mgaudet** [comment]
Good to note! Did you want me to reword this commit for that, or should we just put this as a 'next time' note -- and maybe add to Contributing?

**Comment by youngar** [comment]
Might as well re-word the commit I guess.  We should put something in CONTRIBUTING.md, I like how you provided justification beside the `[skip ci]` tag.

**Pull request merged**
