### PR TITLE
CMake: Add support for pasm2asm on NASM source files

### PR DESCRIPTION
**Pull request by dnakamura**
Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by dnakamura** [comment]
`.pnasm` files do exist in OpenJ9. (https://github.com/eclipse/openj9/blob/master/runtime/compiler/x/runtime/X86PicBuilder.pnasm)

It looks like its just so that it can consume `j9cfg.h`

**Comment by 0xdaryl** [comment]
I believe there is only one #define that's needed from j9cfg.h.  @nbhuiyan planned on modifying the jilconsts generator to add the needed definition in there to avoid this dependency.  That work is planned for by end of October.  The initial version, however, still relies on the C preprocessor unfortunately.

**Comment by charliegracie** [comment]
From a quick look at `jilconsts.h` and `jilconsts.c` it would be a smaller change to add this one define to be written out in `writeConstants` than it would be to make this change.  This change is small but adding 3 lines to jilconsts.c would be just as easy and would happen in the project that requires the code and not pus work down onto OMR which technically does not belong in this project.

I could be missing something about jilconsts?

**Comment by charliegracie** [comment]
I would personally prefer to see new work for a downstream project happen in the downstream project and not in OMR whenever possible. If it is a matter of adding 1 new constant to `jilconsts` would that actually be easier / simpler than making a change in OMR and forcing cpp to be run on the files?

**Comment by 0xdaryl** [comment]
@nbhuiyan : you've studied that code more than I have.  Is the change that straightforward?  If so, please make it in OpenJ9 so we can avoid this OMR dependence.

**Comment by nbhuiyan** [comment]
@0xdaryl @charliegracie @dnakamura eclipse/openj9#3243 would remove the need for the C preprocessor for NASM files.

**Comment by 0xdaryl** [comment]
Thanks.  This PR should be closed then.

**Comment by charliegracie** [comment]
Closing as per the comment from @nbhuiyan

**Pull request closed without merging**
