### PR TITLE
Inhibit array splitting in Scavenger backout

### PR DESCRIPTION
**Pull request by ktbriggs**
This was previously done for the RS overflow case but also needs to
be done in non-RS overflow backout. This fix covers both cases. The
boolean backOutFlag member has been extended to 3 states to distinguish
backOutFlagsRaised and backOutStarted conditions. Array splitting is 
inhibited only in backOutStarted state.

Signed-off-by: Kim Briggs <briggs@ca.ibm.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
@ktbriggs Can you limit the first line of the commit message to 50 characters please?  Also why did so many lines in Scavenger.hpp change? Is it the line endings?

**Comment by ktbriggs** [comment]
@charliegracie I added another commit pending Dmitri's review. Will squash and shorten commit message when change is approved and tested. As for Scavenger.hpp diff, yes it appears to be line endings, append "?w=1" to githib diff url to suppress lineend differences. Not sure how lineends got whacked -- usually egit/eclipse takes care of that.

**Comment by ktbriggs** [comment]
@charliegracie this has been reviewed by Aleks & Dmitri and is ready (squashed, reworded) to go.

**Comment by charliegracie** [comment]
@ktbriggs Scavenger.hpp still has every line changed.  Can you resolve this and push again?  I know I can ignore the whitespace changes but it is better to not have them.

**Comment by ktbriggs** [comment]
@charliegracie Line endings in Scavenger.hpp have been fixed and squashed into last commit.

**Pull request merged**
