### PR TITLE
Update Slack invite link

### LINKED ISSUE #4358: Slack invite link in README is inactive
I would like to join the OMR Slack workspace and become more active in this project.  There are no invite links to the workspace from the webpage, and the one in the README appears to no longer active.  

These are unnecessary barriers to entry, which I may try to fix as I attempt to become more active in this project.

[Slack workspace link](https://join.slack.com/t/eclipse-omr/shared_invite/enQtMzg2ODIwODc4MTAyLTk4ZjJjNTZlZmMyMGRmYTczOTkzMGJiNTQ4NTA3YTA1NGU4MmJjNWI4NTBjOGNkNmNjMWQ3MmFmYjA4OGZjZjM) from line 140 of the README.md file says it is no longer active

Screen Shot 2019-09-24 at 10 15 13 PM

### PR DESCRIPTION
**Pull request by smlambert**
Fixes #4358 
Signed-off-by: smlambert <slambert@gmail.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Thanks... Now please squash your commits into a single commit.

**Comment by 0xdaryl** [comment]
That previous comment of mine sounds snarky, but it wasn't intended to be.  My apologies.   :-(

**Comment by smlambert** [comment]
No worries, apparently my attempt to rebase went awry.  Will address tomorrow.

**Comment by smlambert** [comment]
https://github.com/eclipse/omr/pull/4374 replaces this... impatient to monkey with git squash activity.

**Pull request closed without merging**
