### PR TITLE
Add a few more SSE instructions on x86

### PR DESCRIPTION
**Pull request by cathyzhyi**
Add PCMPGTW, PCMPGTB, PADDW, PADDB, PSUBB, PSUBW, PTEST and PANDN

Signed-off-by: Yi Zhang <yizhang@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
@cathyzhyi I think you have a whitespace issue in the commit. It seems the line endings were changed in the entire file? I'm not sure if the file was LF to begin with but can you check to make sure if you've changed the line endings to something other than LF?

**Comment by cathyzhyi** [comment]
@fjeremic Hi Filip, the file was with CRLF line terminators before my changes and I changed it to LF. I split the changeset to 2 commits to separate the change for line ending and the actual change.

**Comment by cathyzhyi** [comment]
@0xdaryl Thanks a lot! Changed according to the comment.

**Comment by andrewcraik** [comment]
LGTM from me

**Comment by andrewcraik** [comment]
@0xdaryl could you review again please?

**Comment by 0xdaryl** [comment]
This is an x86-specific change.  A genie build is not required.

**Pull request merged**
