### PR TITLE
Propagate known object info to aload node

### PR DESCRIPTION
**Pull request by gita-omr**

### CODE REVIEW

**Comment by gita-omr** [comment]
@jdmpapin could you take a look please?

**Comment by jdmpapin** [comment]
Could you please restrict this to apply less often? I'd prefer for it to require that both
1. `node` is an auto/parm load (so its symref is not "improvable"), and
2. its symref doesn't already have a known object index (which it might if it's a known object temp)

The reason for this is that I intend to remove the per-node known object index later on, so I'd like the symref to remain the main place to check for a known object index, and I think it would be more in keeping with that if we could avoid the per-node known object index when it could be (or is) on the symref instead

**Comment by gita-omr** [comment]
Sorry, pushed too early.

**Comment by jdmpapin** [comment]
Thanks! LGTM, but I requested this change, so I'd like a review from somebody else. @vijaysun-omr, could you please review?

**Comment by vijaysun-omr** [comment]
Jenkins build all

**Comment by jdmpapin** [comment]
Yes, auto symrefs can't be improved the same way as e.g. shadows because they're expected to have trivial aliasing

**Comment by vijaysun-omr** [comment]
I'll wait for Devin to answer the last question before I continue review. I'll restart the "failed" aix text to see if it passes.

**Comment by vijaysun-omr** [comment]
Jenkins build aix

**Comment by jdmpapin** [comment]
> All nodes of label ‘compile:aix’ are offline

**Comment by gita-omr** [comment]
Agree, let's do it for auto and parms only for now.

**Comment by vijaysun-omr** [comment]
The aliasing argument makes sense to me, for why we needed to cache known object info on the node for autos/parms. Thanks.

**Pull request merged**
