### PR TITLE
Set nodeCountThreshold to 16k for >= hot compilations

### PR DESCRIPTION
**Pull request by r30shah**
Set nodeCountThreshold to 16k for hot or above method compilations.

### CODE REVIEW

**Comment by r30shah** [comment]
@mpirvu  Can I get your review on this change ?

**Review by mpirvu — APPROVED** [review]
LGTM

**Comment by r30shah** [comment]
Jenkins build all

**Review by vijaysun-omr — APPROVED** [review]

**Comment by r30shah** [comment]
@AdamBrousseau  Seems like riscV 64 build is stuck waiting for nodes which are offline  (https://ci.eclipse.org/omr/job/PullRequest-linux_riscv64_cross/1400/), is there a workaround for that?

**Comment by r30shah** [comment]
@vijaysun-omr  Seems like only remaining build is riscv-64 for which both machine where it can be run are offline which not sure will be resolved soon.
As it is the simple change, I have not ran internal testing builds and only have ran ODM-ILOG and Liberty for verification. Can launch ones internally if you want me to.

**Comment by vijaysun-omr** [comment]
Given the comments from Rahil, and my review of this purely heuristic change to the inliner, I feel it is very likely that the testing on RISC-V would not throw up any new issues.  I am merging this change on that basis rather than hold up for infra reasons.

**Comment by JamesKingdon** [comment]
Hi @r30shah , could you give me some background on the motivation for this change? According to https://github.com/eclipse/omr/pull/7240 it looks like the larger limit would already be the default in openJ9?

**Comment by r30shah** [comment]
Hi @JamesKingdon , yes I believe the main intention of the change in https://github.com/eclipse/omr/pull/7240 was to lower the count for all compiles and let the consumer like OpenJ9 to set the threshold for the compiles, but we do not do that in OpenJ9 and it is only done when an environment option `TR_EnableExpensiveOptsAtWarm` is set which would only set higher count for warm and below. For hot and above compilations, it should have node count threshold high enough so that the resources we put in to deciding and started compiling method at hot or above opt level can get most out of it.

**Pull request merged**
