### PR TITLE
Replace method in VPHandlers.cpp with equivalent method in VP

### PR DESCRIPTION
**Pull request by hzongaro**
`isArrayCompTypeValueType` was originally defined as a static function in `VPHandlers.cpp`, but an equivalent virtual method that downstream projects can override is now defined in `OMR::ValuePropagation`.  This change eliminates the function in `VPHandlers.cpp` and has that file use the method in `ValuePropagation` instead.

This change depends on pull request #5909, and a pending downstream implementation of `ValuePropagation::isArrayCompTypeValueType`

### CODE REVIEW

**Comment by hzongaro** [comment]
Now that the downstream implementation of `ValuePropagation::isArrayCompTypeValueType` has been merged, `constrainArrayStoreCHK` can use that method instead of its own similar static method, `isArrayCompTypeValueType`.  Marked this as ready for review.

**Comment by 0xdaryl** [comment]
Jenkins build all

**Review by a7ehuo — APPROVED** [review]

**Review by vijaysun-omr — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Jenkins build riscv

**Comment by 0xdaryl** [comment]
Jenkins build riscv

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
