### PR TITLE
Fix dselect IL opcode properties (and add tests)

### PR DESCRIPTION
**Pull request by janvrany**

### CODE REVIEW

**Comment by mstoodle** [comment]
The tests look pretty reasonable to me, though would appreciate @Leonardo2718 also giving his "blessing".

**Comment by mstoodle** [comment]
@genie-omr build all

**Comment by Leonardo2718** [comment]
It looks like there might be a bug in the Z evaluators so the tests might have to be disabled there as well. (FYI @fjeremic)

**Comment by mstoodle** [comment]
Yeah, the `fselect` results seem to be the reverse of what the test is expecting and an exception is thrown inside the dselect evaluator and ...
fselect:
```
10:01:19  29: [0;32m[----------] [m28 tests from SelectTest/FloatSelectInt32CompareTest
10:01:19  29: /home/jenkins/workspace/PullRequest-linux_390-64/fvtest/compilertriltest/SelectTest.cpp:493: Failure
10:01:19  29:       Expected: param.oracle(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 0
10:01:19  29: To be equal to: entry_point(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 1
10:01:19  29: [0;31m[  FAILED  ] [mSelectTest/FloatSelectInt32CompareTest.UsingLoadParam/2, where GetParam() = ((2147483647, -2147483648), (1, 0), 0x81318560) (1 ms)
10:01:19  29: /home/jenkins/workspace/PullRequest-linux_390-64/fvtest/compilertriltest/SelectTest.cpp:493: Failure
10:01:19  29:       Expected: param.oracle(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 1
10:01:19  29: To be equal to: entry_point(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 0
10:01:19  29: [0;31m[  FAILED  ] [mSelectTest/FloatSelectInt32CompareTest.UsingLoadParam/3, where GetParam() = ((2147483647, -2147483648), (0, 1), 0x81318560) (1 ms)
10:01:19  29: /home/jenkins/workspace/PullRequest-linux_390-64/fvtest/compilertriltest/SelectTest.cpp:493: Failure
10:01:19  29:       Expected: param.oracle(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 0
10:01:19  29: To be equal to: entry_point(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 1
10:01:19  29: [0;31m[  FAILED  ] [mSelectTest/FloatSelectInt32CompareTest.UsingLoadParam/4, where GetParam() = ((-2147483648, -2147483648), (1, 0), 0x81318560) (1 ms)
10:01:19  29: /home/jenkins/workspace/PullRequest-linux_390-64/fvtest/compilertriltest/SelectTest.cpp:493: Failure
10:01:19  29:       Expected: param.oracle(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 1
10:01:19  29: To be equal to: entry_point(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 0
10:01:19  29: [0;31m[  FAILED  ] [mSelectTest/FloatSelectInt32CompareTest.UsingLoadParam/5, where GetParam() = ((-2147483648, -2147483648), (0, 1), 0x81318560) (1 ms)
10:01:19  29: /home/jenkins/workspace/PullRequest-linux_390-64/fvtest/compilertriltest/SelectTest.cpp:493: Failure
10:01:19  29:       Expected: param.oracle(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 0
10:01:19  29: To be equal to: entry_point(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 1
10:01:19  29: [0;31m[  FAILED  ] [mSelectTest/FloatSelectInt32CompareTest.UsingLoadParam/8, where GetParam() = ((0, -2147483648), (1, 0), 0x81318560) (1 ms)
10:01:19  29: /home/jenkins/workspace/PullRequest-linux_390-64/fvtest/compilertriltest/SelectTest.cpp:493: Failure
10:01:19  29:       Expected: param.oracle(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 1
10:01:19  29: To be equal to: entry_point(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 0
10:01:19  29: [0;31m[  FAILED  ] [mSelectTest/FloatSelectInt32CompareTest.UsingLoadParam/9, where GetParam() = ((0, -2147483648), (0, 1), 0x81318560) (1 ms)
10:01:19  29: /home/jenkins/workspace/PullRequest-linux_390-64/fvtest/compilertriltest/SelectTest.cpp:493: Failure
10:01:19  29:       Expected: param.oracle(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 0
10:01:19  29: To be equal to: entry_point(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 1
10:01:19  29: [0;31m[  FAILED  ] [mSelectTest/FloatSelectInt32CompareTest.UsingLoadParam/12, where GetParam() = ((2147483647, 0), (1, 0), 0x81318560) (1 ms)
10:01:19  29: /home/jenkins/workspace/PullRequest-linux_390-64/fvtest/compilertriltest/SelectTest.cpp:493: Failure
10:01:19  29:       Expected: param.oracle(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 1
10:01:19  29: To be equal to: entry_point(param.c1, param.c2, param.v1, param.v2)
10:01:19  29:       Which is: 0
10:01:19  29: [0;31m[  FAILED  ] [mSelectTest/FloatSelectInt32CompareTest.UsingLoadParam/13, where GetParam() = ((2147483647, 0), (0, 1), 0x81318560) (1 ms)
10:01:19  29: [0;32m[----------] [m28 tests from SelectTest/FloatSelectInt32CompareTest (22 
```

dselect:
```
10:01:19  29: Assertion failed at /home/jenkins/workspace/PullRequest-linux_390-64/compiler/z/codegen/OMRInstruction.cpp:89: cg->comp()->target().cpu.getSupportsArch(_opcode.getMinimumALS())
10:01:19  29: 	Processor detected does not support instruction VGBM
10:01:19  29: 
10:01:19  29: compiling file:line:name at level: warm
10:01:19  29: #0: function TR_LinuxCallStackIterator::printStackBacktrace(TR::Compilation*)+0x42 [0x81a9960a]
10:01:19  29: #1: function TR_Debug::printStackBacktrace()+0x38 [0x81797bf8]
10:01:19  29: #2: /home/jenkins/workspace/PullRequest-linux_390-64/build/fvtest/compilertriltest/comptest() [0x81554722]
10:01:19  29: #3: /home/jenkins/workspace/PullRequest-linux_390-64/build/fvtest/compilertriltest/comptest() [0x81554868]
10:01:19  29: #4: /home/jenkins/workspace/PullRequest-linux_390-64/build/fvtest/compilertriltest/comptest() [0x81554a18]
10:01:19  29: #5: function OMR::Z::Instruction::Instruction(TR::CodeGenerator*, OMR::InstOpCode::Mnemonic, TR::Node*)+0x1d0 [0x81bce970]
10:01:19  29: #6: function TR::Instruction::Instruction(OMR::InstOpCode::Mnemonic, TR::Node*, TR::CodeGenerator*)+0x4c [0x81ac556c]
10:01:19  29: #7: function TR::S390RegInstruction::S390RegInstruction(OMR::InstOpCode::Mnemonic, TR::Node*, TR::Register*, TR::CodeGenerator*)+0x52 [0x81ac59e2]
10:01:19  29: #8: function TR::S390VInstruction::S390VInstruction(TR::CodeGenerator*, OMR::InstOpCode::Mnemonic, TR::Node*, TR::Register*)+0x58 [0x81b25fe8]
10:01:19  29: #9: function TR::S390VRIInstruction::S390VRIInstruction(TR::CodeGenerator*, OMR::InstOpCode::Mnemonic, TR::Node*, TR::Register*, unsigned short, unsigned char, unsigned char, unsigned char, unsigned char)+0x58 [0x81b262b8]
10:01:19  29: #10: function TR::S390VRIaInstruction::S390VRIaInstruction(TR::CodeGenerator*, OMR::InstOpCode::Mnemonic, TR::Node*, TR::Register*, unsigned short, unsigned char)+0x8e [0x81b264b6]
10:01:19  29: #11: function generateVRIaInstruction(TR::CodeGenerator*, OMR::InstOpCode::Mnemonic, TR::Node*, TR::Register*, unsigned short, unsigned char)+0xa0 [0x81b10dc0]
10:01:19  29: #12: function OMR::Z::TreeEvaluator::dselectEvaluator(TR::Node*, TR::CodeGenerator*)+0x4a2 [0x81ac4c9a]
10:01:19  29: #13: function OMR::CodeGenerator::evaluate(TR::Node*)+0x2e4 [0x8182def4]
10:01:19  29: #14: function OMR::Z::TreeEvaluator::returnEvaluator(TR::Node*, TR::CodeGenerator*)+0x134 [0x81abcef4]
10:01:19  29: #15: function OMR::CodeGenerator::evaluate(TR::Node*)+0x2e4 [0x8182def4]
10:01:19  29: #16: function OMR::CodeGenerator::doInstructionSelection()+0x64e [0x818329f6]
10:01:19  29: #17: function OMR::Z::CodeGenerator::doInstructionSelection()+0x26 [0x817dee0e]
10:01:19  29: #18: function OMR::CodeGenPhase::performInstructionSelectionPhase(TR::CodeGenerator*, TR::CodeGenPhase*)+0x17a [0x818455ca]
10:01:19  29: #19: function OMR::CodeGenPhase::performAll()+0x182 [0x81843c02]
10:01:19  29: #20: function OMR::CodeGenerator::generateCode()+0xe8 [0x81835718]
10:01:19  29: #21: function OMR::Compilation::compile()+0xe36 [0x8145e5fe]
10:01:19  29: #22: function compileMethodFromDetails(OMR_VMThread*, TR::IlGeneratorMethodDetails&, TR_Hotness, int&)+0x790 [0x8148c3e0]
10:01:19  29: #23: function Tril::SimpleCompiler::compileWithVerifier(TR::IlVerifier*)+0x39a [0x813b936a]
10:01:19  29: #24: function Tril::SimpleCompiler::compile()+0x26 [0x813b8fb6]
10:01:19  29: #25: function DoubleSelectInt32CompareTest_UsingLoadParam_Test::TestBody()+0x56e [0x81317096]
10:01:19  29: #26: function void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)+0x78 [0x814045e0]
10:01:19  29: #27: function void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*)+0x72 [0x813fc6a2]
10:01:19  29: #28: function testing::Test::Run()+0x104 [0x813d7a6c]
10:01:19  29: #29: function testing::TestInfo::Run()+0x15a [0x813d85b2]
```

**Comment by janvrany** [comment]
OK, two more tweaks to the tests - see 5419108:

  1) **do not skip** `...UsingConst` tests as this should be optimized out
  2) **do skip `...UsingLoadParam` also on `S390` and `S390X` as `KnownBug`

Anything else?

**Comment by mstoodle** [comment]
@genie-omr build all

**Comment by mstoodle** [comment]
Opened #4953 for the Z failures.

**Comment by mstoodle** [comment]
zos face planted for reasons unrelated to PR, I'll restart and hope it can be cleared

**Comment by mstoodle** [comment]
@genie-omr build zos

**Pull request merged**
