### PR TITLE
x86: Enable dual TLH by default

### PR DESCRIPTION
**Pull request by BradleyWood**

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
I would appreciate a review from @0xdaryl on this to make sure we have considered what we need to, before making this change

**Comment by vijaysun-omr** [comment]
I would also advise a small unit test in this case where you have an allocation of each kind, one that needs zeroing and one that does not, and check the generated code sequences to make sure that it is all as expected (i.e. we use the two TLHs in the expected way).

**Comment by vijaysun-omr** [comment]
Also FYI, @mpirvu for any memory footprint impacts

**Review by vijaysun-omr — APPROVED** [review]

**Comment by vijaysun-omr** [comment]
I am only approving the fact that the enablement looks okay. I'll wait for Daryl's review and run tests.

**Comment by vijaysun-omr** [comment]
jenkins build all

**Comment by BradleyWood** [comment]
MacOS failure is #7181

Windows Failed due to:

```
ChannelClosedException: Channel "hudson.remoting.Channel@4b2b57a4:win2019x64-openj9-2": Remote call on win2019x64-openj9-2 failed. The channel is closing down or has closed down
```

**Comment by knn-k** [comment]
Dual TLH is disabled by default on AArch64 now.  PR #7243.

**Comment by vijaysun-omr** [comment]
Is batch clearing enabled by default on AArch64 ? If not, is it being considered to be enabled by default ?

**Comment by knn-k** [comment]
@vijaysun-omr TLH batch clearing is enabled by default on AArch64.  See my comment in https://github.com/eclipse-openj9/openj9/issues/18870#issuecomment-1935213335.

**Pull request closed without merging**
