### PR TITLE
Add ARM64ExceptionInstruction kind

### PR DESCRIPTION
**Pull request by 0xdaryl**
Create the instruction kind for AArch64 exception generating instructions.

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@knn-k, please review.

**Comment by 0xdaryl** [comment]
WIP only because it depends on #4166.

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Comment by knn-k** [comment]
Looks good to me.
I assume the new instruction kind is used for instructions such as `brk` and `svc`.

**Comment by 0xdaryl** [comment]
> I assume the new instruction kind is used for instructions such as `brk` and `svc`.

Yes, for software breakpoints.

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Comment by 0xdaryl** [comment]
@Leonardo2718 @mstoodle @andrewcraik : would one of you mind reviewing and merging please?

**Comment by Leonardo2718** [comment]
Change seems reasonable and tests have passed. Merging.

**Pull request merged**
