### PR TITLE
Remove unneeded content from FrontEnd.hpp

### PR DESCRIPTION
**Pull request by 0xdaryl**
* eliminate unnecessary includes and forward declarations
* fix up other files to accommodate removed includes and declarations

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
WIP only because it is waiting for downstream dependencies to merge.

I was originally only intending to eliminate the unneeded List.hpp dependency due to a compile error I was receiving elsewhere.  But I figured I might as well clean up the rest of the unused code in here as well.

**Comment by 0xdaryl** [comment]
Un-WIPing as downstream dependencies have merged.  Rebasing and re-running CI.

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Review by Leonardo2718 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
