### PR TITLE
Direct old-to-old-reference callback

### PR DESCRIPTION
**Pull request by amicic**
Bypass hook API tp reduce overhead, mostly by avoiding the hook internal
stats counter (which is using an atomic increment).

Signed-off-by: Aleksandar Micic <amicic@ca.ibm.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
@amicic do downstream projects also have to be modified since we removed a hook?

**Comment by charliegracie** [comment]
@genie-omr build zlinux plinux zos

**Comment by amicic** [comment]
Perhaps yes - you should know better. I can leave the hook, if needed.

**Comment by amicic** [comment]
Well, I'd be really surprised that anybody else would be using this hook. This hook is for a very specific purpose (Scavenger to Concurrent Global GC interaction), and all that code resides within OMR.

**Comment by charliegracie** [comment]
No I do not see any references either.

**Pull request merged**
