### PR TITLE
Guard adaptiveThreadingEnabled() for OMR_GC_MODRON_SCAVENGER only

### PR DESCRIPTION
**Pull request by 0xdaryl**
When `OMR_GC_MODRON_SCAVENGER` is not enabled the GC fails to compile.

Also, correct the spelling in the function name and fixup references.

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@RSalman : I'd appreciate a review please.

This moves the function `isAdaptiveThreadingEnabled()` behind a `OMR_GC_MODRON_SCAVENGER` ifdef, and corrects the spelling of `Threading` in the function name.

This was causing builds to fail unless they had `OMR_GC_MODRON_SCAVENGER` defined.

**Review by RSalman — APPROVED** [review]
LGTM, thanks for the correction.

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
BTW, the reason this doesn't show up in the OMR CI builds is because the build configs all enable `OMR_GC_MODRON_SCAVENGER`.  It might be worth doing builds that don't enable that flag.

**Comment by 0xdaryl** [comment]
Jenkins build all

**Comment by 0xdaryl** [comment]
The AArch64 failure is unrelated and fixed in #5877 .

**Pull request merged**
