### PR TITLE
AArch64: Improve *cmp*-*select instruction sequence

### PR DESCRIPTION
**Pull request by knn-k**
This is a follow-up of PR #7361, adding support for select nodes with other kinds of cmp nodes as the first child, such as icmpne and acmpgt.

### CODE REVIEW

**Comment by knn-k** [comment]
Jenkins build aarch64,amac

**Comment by knn-k** [comment]
Jenkins build amac

**Comment by knn-k** [comment]
Jenkins build amac

**Comment by knn-k** [comment]
I ran OpenJ9 sanity.functional with this change on AArch64 macOS.
Ready for review.  @0xdaryl

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
