### PR TITLE
x86: Fix redundant compare elimination

### PR DESCRIPTION
**Pull request by BradleyWood**
Redundant compare elimination is a code
generation optimization that attempts to drop
redundant compare instructions before a jump.
This can happen when the the previous
instruction sets condition code flags and is
compared with 0. However, some instructions
such as DIV and IDIV can modify these flags
in undefined ways. This commit lets the code
the code generator know that these instructions
may modify condition code flags. In addition,
the code generator should check if the
instruction that modifies these flags belongs
to the expected node.

Fixes: eclipse-openj9/openj9#17496

### CODE REVIEW

**Comment by BradleyWood** [comment]
jenkins build all

**Comment by BradleyWood** [comment]
@0xdaryl Can you review?

**Comment by 0xdaryl** [comment]
Can you explain why you restrict the search to only instructions generated from the current node?

Minor nits:
- first sentence in the commit message needs some work to improve grammar
- "code-generation" or "code-generator" should be "code generation" or "code generator" throughout for consistency with rest of code base.

**Comment by BradleyWood** [comment]
> Can you explain why you restrict the search to only instructions generated from the current node?
> 
> Minor nits:
> 
> * first sentence in the commit message needs some work to improve grammar
> * "code-generation" or "code-generator" should be "code generation" or "code generator" throughout for consistency with rest of code base.

`node` in this case is the node (such as sub or add) that we expect to have set the condition code flags. If any other instructions set those flags and do not belong to that node, removing the comparison would not make sense.

**Comment by BradleyWood** [comment]
Changed commit message

**Comment by 0xdaryl** [comment]
Jenkins build xlinux,osx,win

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
