### PR TITLE
Deprecate XPLINKCallDescriptorSnippet

### PR DESCRIPTION
**Pull request by fjeremic**
Now that eclipse/openj9#8739 has been merged we can finally deprecate
the compilation units for the XPLINKCallDescriptorSnippet. This is the
last piece of work from #4890 which we couldn't complete there due to
downstream dependencies.

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@genie-omr build zos

**Comment by fjeremic** [comment]
@genie-omr build zos

**Comment by vijaysun-omr** [comment]
Straightforward code cleanup and checks have passed. Merging.

**Pull request merged**
