### PR TITLE
Switch to using a label for StartPC in the Power codegen

### PR DESCRIPTION
**Pull request by aviansie-ben**
Currently, the Power codegen has a decent amount of special handling to deal with trying to load the StartPC of the current method, including a particularly egregious hack in `ConstantDataSnippet` that would cause the address of StartPC itself to be patched on the instructions rather than the address of a slot in the snippet from which to load. In addition to being generally very confusing and inconsistent, this hack makes modifications to this snippet (such as those required for #5367) quite difficult without inadvertently breaking things.

Since this functionality was introduced, the Power codegen has become capable of generating and relocating a sequence to load the address of an arbitrary label into a register in a much more reasonable manner. By instead generating a label at StartPC and then using this more general method of loading its address, not only can the `ConstantDataSnippet` hack be eliminated but we also gain the ability to load this address from the pTOC where applicable.

### CODE REVIEW

**Comment by gita-omr** [comment]
LGTM but @zl-wang could you please take a look as well?

**Comment by zl-wang** [comment]
there is a reason to load an address constant from snippet, instead of in-instruction-stream assembling the constant. namely, if you want to patch/relocate at runtime that address atomically.  fixedLoadLabelAddressIntoReg cannot replace loadaddressconstantinsnippet for that scenario. 

I am not 100% sure under how many cases this atomicity is required of.  Maybe HCR.  you need to do some more investigations as for if there are such case(s), before this can be committed.

**Comment by aviansie-ben** [comment]
> there is a reason to load an address constant from snippet, instead of in-instruction-stream assembling the constant. namely, if you want to patch/relocate at runtime that address atomically. fixedLoadLabelAddressIntoReg cannot replace loadaddressconstantinsnippet for that scenario.

So, the thing is that it was never _actually_ the case that we were loading the StartPC from the ConstantDataSnippet itself. This whole thing was just an elaborate hack that would end up patching the StartPC directly into mainline code using the 5 instruction sequence. What was happening was that we would _pretend_ to use an `addi` to load the address of a dummy slot within the snippet, then the snippet's patching mechanism would perform its own check and patch the StartPC address directly instead of the address of the slot within the snippet. So we never actually supported atomic patching in the first place, as we do not need it for this symbol, but instead were just taking a very confusing code path.

**Comment by fjeremic** [comment]
@genie-omr build plinux,aix

**Pull request merged**
