### PR TITLE
CMake: If build type is not specified default to release /w debug info

### PR DESCRIPTION
**Pull request by dnakamura**
Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
@youngar and @rwy0717 thoughts? I am happy with the change

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by dnakamura** [comment]
I have to take a deeper look at the compiler failures, but IIRC there is an issue with certain warnings only appearing when optimizations are enabled

**Comment by 0xdaryl** [comment]
Any update on this @dnakamura ?

**Comment by youngar** [comment]
@genie-omr build all

**Comment by youngar** [comment]
Fixing the problem

**Comment by fjeremic** [comment]
Looks like some issues here. Just a note to clean up the merge commit before merging this once the issues are fixed.

**Comment by fjeremic** [comment]
@dnakamura is this something we still want to pursue? Does this close #4211?

**Pull request closed without merging**
