### PR TITLE
Consolidate some optimizer trace options

### PR DESCRIPTION
**Pull request by fjeremic**
This PR is a series of commits, similar to that of #5165, which consolidates some of the optimizer trace options. Each commit has as part of the commit message the justification for why the change was made. Some further details on the background for this initiative can be found in eclipse/openj9#9428.

There is no trace statements removed as part of this PR (except one I think), only the options used to enable some of the tracing has changed.

### CODE REVIEW

**Comment by andrewcraik** [comment]
Thanks for this clean-up work @fjeremic . I am still going through the changes so will likely have more comments.

One fold I would prefer not to make for the time being is folding the trace of partialInlining with the rest of the inliner tracer. Partial inclining is not enabled in OpenJ9 (where the code controlled by all that lives) and it was only ever really an experiment. We are still deciding what to do with it and folding the tracing will make removal harder if we decide that is the path to take. As a result, I'd like to leave that trace configuration alone for the time being.

The change to the traceTempUsage will mean we can only enable this tracing on a debug or prod w/ assumes build since the debug regex is disabled outside of those builds. I see what you are doing and it does make some sense, but should we prohibit this for prod buids?

**Comment by fjeremic** [comment]
> One fold I would prefer not to make for the time being is folding the trace of partialInlining with the rest of the inliner tracer. Partial inclining is not enabled in OpenJ9 (where the code controlled by all that lives) and it was only ever really an experiment. We are still deciding what to do with it and folding the tracing will make removal harder if we decide that is the path to take. As a result, I'd like to leave that trace configuration alone for the time being.

How about something mid-way. Looking at the commits related to partial inlining they are 36dc8f2 in this PR and [`65cf911f`](https://github.com/eclipse/openj9/pull/9520/commits/65cf911f08ad436538ca0b5e223cecf906b9f05c) in the OpenJ9 PR. The footprint of code is really small to justify a whole tracing option. How about I modify the OpenJ9 commit to prefix all the tracing with "PARTIAL INLINING: " so that we can still easily identify the trace options while getting the benefit of a reduced set of trace options? Does that sound like a reasonable mid-way solution?

> The change to the traceTempUsage will mean we can only enable this tracing on a debug or prod w/ assumes build since the debug regex is disabled outside of those builds. I see what you are doing and it does make some sense, but should we prohibit this for prod buids?

I'd like to still eliminate the footprint of the tracing option. Do you think turning it into a environment variable check instead and allowing it to be enabled on prod builds is reasonable compromise?

**Comment by fjeremic** [comment]
@andrewcraik let me know if you think the above proposal is acceptable and I will implement it promptly.

**Comment by andrewcraik** [comment]
how about we keep the macro etc and just convert the option to an env var since it is not a supported mode and likely to be removed? If you want to add a prefix in the macro I'm fine with that, but I'd rather do the partial inline clean up in one fell swoop once we are sure that is what we want to do. This way the inliner code isn't really changed, but you can clean up the option which is overkill in this case...

**Comment by andrewcraik** [comment]
>The change to the traceTempUsage will mean we can only enable this tracing on a debug or prod w/ assumes build since the debug regex is disabled outside of those builds. I see what you are doing and it does make some sense, but should we prohibit this for prod buids?
> > I'd like to still eliminate the footprint of the tracing option. Do you think turning it into a environment variable check instead and allowing it to be enabled on prod builds is reasonable compromise?

So a more meta question since we are doing this - should we have an option that is a flags like regex/glob like debug that we can use for undocumented options rather than just using getenv? I'm not sure... I think a downgrade to an env or something else makes sense; I just don't want it compiled out under prod like it would be if it became a debug flag...

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@andrewcraik I've made the following changes:

- The two commits 36dc8f2 in this PR and [`65cf911f`](https://github.com/eclipse/openj9/pull/9520/commits/65cf911f08ad436538ca0b5e223cecf906b9f05c) in the OpenJ9 PR have been removed
- I've added a new commit 9893435 which just uses an envvar as per your suggestion
- I've changed tracing of temp usage to an envvar in 05a1ae9

Please see the [force-push](https://github.com/eclipse/omr/compare/257c4c97ef2badaf599c669b2bece5dc530a27f9..9893435b4234e2d8e67bd67f3e195a8110874a07) for the small set of changes described above.

**Comment by fjeremic** [comment]
@andrewcraik is the above an acceptable solution?

**Comment by vijaysun-omr** [comment]
@andrewcraik this is awaiting another review from you I think.

**Comment by andrewcraik** [comment]
With the changes I think this looks good - have asked for a second person to look at one of the changes in OpenJ9, but my concerns here have been addressed I think.

**Comment by fjeremic** [comment]
Could we tag the other person here to see if we can get a review to push this one through?

**Comment by fjeremic** [comment]
@vijaysun-omr anything left to address for this one?

**Comment by fjeremic** [comment]
@vijaysun-omr anything left to address for this one?

**Comment by vijaysun-omr** [comment]
Looks like good cleanup to ensure we have a more unified story for tracing options in the optimizer. Checks and reviews are done. Merging.

**Pull request merged**
