### PR TITLE
Add macOS on AArch64

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
Jenkins build amac

**Comment by AdamBrousseau** [comment]
Jenkins build amac

**Comment by AdamBrousseau** [comment]
@0xdaryl can you give this a review please? I copied the mac x64 spec and only changed the spec name and machine label.

**Comment by AdamBrousseau** [comment]
Jenkins build amac

**Comment by AdamBrousseau** [comment]
Jenkins build amac

**Comment by AdamBrousseau** [comment]
https://ci.eclipse.org/omr/job/PullRequest-osx_aarch64/5/console
```
00:08:40.056  59% tests passed, 12 tests failed out of 29
00:08:40.056  
00:08:40.056  Total Test time (real) = 196.17 sec
00:08:40.056  
00:08:40.056  The following tests FAILED:
00:08:40.056  	  3 - conditionals_example_as_test (SEGFAULT)
00:08:40.056  	  5 - iterfib_example_as_test (SEGFAULT)
00:08:40.056  	  6 - nestedloop_example_as_test (SEGFAULT)
00:08:40.056  	  7 - pow2_example_as_test (SEGFAULT)
00:08:40.056  	  8 - simple_example_as_test (SEGFAULT)
00:08:40.056  	  9 - worklist_example_as_test (SEGFAULT)
00:08:40.056  	 14 - porttest (Failed)
00:08:40.056  	 25 - JitBuilderTest (SEGFAULT)
00:08:40.056  	 26 - CompilerTest (SEGFAULT)
00:08:40.056  	 27 - triltest (SEGFAULT)
00:08:40.056  	 28 - comptest (SEGFAULT)
00:08:40.056  	 29 - compunittest (SEGFAULT)
00:08:40.056  Errors while running CTest
```

**Comment by 0xdaryl** [comment]
See issue #6716 to track failures.

**Comment by babsingh** [comment]
Can this be merged? Let's not include it in the `build all` trigger on Jenkins until segfaults are fixed. But it will help us to compile and selectively run tests as fixes are merged: `amac(env:'GTEST_FILTER=<TEST_REGEX>')`.

**Comment by AdamBrousseau** [comment]
I'll wait and rebase once #6724 is merged.

**Comment by 0xdaryl** [comment]
Please rebase.

**Comment by 0xdaryl** [comment]
Jenkins build amac

Mainly testing the trigger.  I expect some of these test jobs will fail.

**Comment by 0xdaryl** [comment]
Jenkins build amac

**Comment by 0xdaryl** [comment]
@AdamBrousseau : the trigger doesn't seem to be working.

**Comment by AdamBrousseau** [comment]
Jenkins build amac

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Ooops.  Forgot one thing.

Can you add this new target to the table in the Committer Guide please? https://github.com/eclipse/omr/blob/master/doc/GuideForCommitters.md

**Pull request merged**
