### PR TITLE
Explicity state endianess of UTF-16 encoding

### PR DESCRIPTION
**Pull request by dnakamura**
Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by ashu-mehra** [comment]
@dnakamura Hi Devin, I appreciate for promptly creating this PR, but it looks like this could have been addressed in the original PR https://github.com/eclipse/omr/pull/4327 itself, unless we think it is a critical fix that cannot be delayed.

**Comment by dnakamura** [comment]
@ashu-mehra  I don't have an issue if you implement the fix in your pr. I wanted to suggest the change, but only committers can actually suggest a code change (and its a trivial enough change that its significantly easier to suggest via code than to try and express in words)

**Comment by ashu-mehra** [comment]
> but only committers can actually suggest a code change

Is that so? I think anyone can review a PR and discuss and suggest changes.
If you have not, I suggest you give it a try and review PR #4327. 
It will also help fellow developers to learn something, and obviously you get the credit for reviewing the PR.

**Comment by youngar** [comment]
@genie-omr build all

**Comment by youngar** [comment]
@bharathappali does this change look good to you?

**Comment by bharathappali** [comment]
@youngar I was discussing with @ashu-mehra, As these things may exist in future where any other OS on a particular arch might not support `UTF-16LE` or `UTF-16BE`. So we came up with a solution to make it generic, by adding a check at runtime for system endianess and the stream endianess (based on [BOM](https://tools.ietf.org/html/rfc2781)) and then if there is a mismatch we could swap the bytes to make the endianess of system and stream the same ?

I was thinking of something like this https://github.com/bharathappali/omr/commit/354dc82a87b41b8fb0eb074a63c90f8696e2f04e

**Comment by dnakamura** [comment]
I don't think we want to be doing a runtime check and doing a runtime byte swapping seems like it would add noticeable overhead to the string operations.  If we are really paranoid about the issue, we could do a configure-time check to see if `UTF-16xE` is supported.

**Comment by rwy0717** [comment]
I agree with @dnakamura, testing the iconv implementation at configure-time (IE in cmake) makes more sense.

**Comment by bharathappali** [comment]
Yeah @dnakamura @rwy0717 A configure-time check will be a good solution.

**Comment by rwy0717** [comment]
@genie-omr build all

**Pull request merged**
