### PR TITLE
DirectJNI is not supported in fsd mode

### PR DESCRIPTION
**Pull request by cathyzhyi**
Only enable direct JNI for ARM for non fsd mode

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
To be clear, is this bringing ARM in line with what is already the case on our other platforms ?

**Comment by cathyzhyi** [comment]
that's correct.

**Comment by andrewcraik** [comment]
Yes that is correct - the other platforms are handled in a downstream project, but the ARM codegen is not yet factored that way so we are making the equivalent change here.

**Comment by vijaysun-omr** [comment]
FYI @JBKingdon @0xdaryl and @andrewcraik

**Comment by andrewcraik** [comment]
LGTM from me.

**Comment by Leonardo2718** [comment]
The change LGTM.

One question for completeness, how was this tested (since the Travis builds do not currently test ARM)?

**Comment by JamesKingdon** [comment]
Interesting, directToJNI is one of two features I had to disable last night to get further in my testing.

**Comment by andrewcraik** [comment]
@Leonardo2718 The ARM change was not directly run. We do know from talking to the VM guys that the sequence used for direct JNI is not supported under FSD and testing on the other code generators showed that to be the case. directJNI is an optimization to increase performance so turning it off can leave perf on the table, but will not be functionally incorrect. The change is to keep inline with the platforms directly tested - we are making the structurally equivalent change.

@JamesKingdon it is possible that recent changes in the code to handle this in the downstream project consuming this codegen could have introduced bugs leading to directJNI failing to operate correctly in all cases.

**Comment by Leonardo2718** [comment]
@andrewcraik thank you for the explanation.

**Pull request merged**
