### PR TITLE
Fix incorrect CPU detection for Linux 32-bit

### PR DESCRIPTION
**Pull request by amitin**
Fix incorrect host machine CPU detection for Linux 32-bit.
Fix typo for cmake variable.
Signed-off-by: Alexander Mitin <Alexander.Mitin@gmail.com>

### CODE REVIEW

**Comment by amitin** [comment]
I re-created my pull request with proper sign off record. No idea why it still fails the check though. Feel free to close this pull request and add my changes by yourself.

**Comment by rwy0717** [comment]
Hi @amitin, thanks for the patch!

Here are the steps to get the ip-check to pass:

1. [Create an account at Eclipse](https://dev.eclipse.org/site_login/createaccount.php).
2. Add your GitHub user name in your account settings.
3. [Log into the projects portal](https://projects.eclipse.org/) and sign the ["Eclipse ECA"](https://projects.eclipse.org/user/sign/cla).
4. Ensure that you [_sign-off_](https://wiki.eclipse.org/Development_Resources/Contributing_via_Git#Signing_off_on_a_commit) your Git commits.

I'm guessing you don't have an eclipse developer account.

**Comment by amitin** [comment]
I'm an [Eclipse contributor](https://accounts.eclipse.org/users/amitin) since 2011 actually (even earlier). :-)
I double-checked my Eclipse account and my ECA settings. I have bound my github account (this one) to my Eclipse account long time ago. I provided 'Signed-off-by' field with a valid value as the last line of my commit message. But ip-validation still rejects my pull request and given all above I don't understand why.

**Comment by rwy0717** [comment]
Oh it looks like the commit author is `Alexander Mitin <amitin@users.noreply.github.com>`, You have to use the same email everywhere.

**Pull request closed without merging**
