### PR TITLE
Separate compact reason for rasdump

### PR DESCRIPTION
**Pull request by amicic**
The COMPACT_FORCED_GC reason was reused what indicated that an explicit
command line option was specified confusing GCMV parser to incorrectly
conclude there was an option while there was only a RAS dump.

Now we use a dedicated reason with a different string issued by Verbose
GC.

Signed-off-by: Aleksandar Micic <Aleksandar_Micic@ca.ibm.com>

### CODE REVIEW

**Comment by amicic** [comment]
@ dmitripivkine please, review

**Comment by amicic** [comment]
@dmitripivkine please, review

**Review by dmitripivkine — APPROVED** [review]

**Comment by dmitripivkine** [comment]
Please fix the typo in the commit comment

**Comment by dmitripivkine** [comment]
@babsingh Would you please help to merge?

**Comment by babsingh** [comment]
jenkins build all

**Comment by babsingh** [comment]
A known failure is seen in the riscv build, which is unrelated to this PR: https://github.com/eclipse/omr/issues/6905.

**Review by babsingh — APPROVED** [review]

**Pull request merged**
