### PR TITLE
Add scalar FMA opcodes for X86 Compiler

### PR DESCRIPTION
**Pull request by shivammittal99**
RegRegReg and RegRegMem versions of:

VFMADD213SS, VFMADD231SS, VFMSUB213SS, VFMSUB231SS
VFMADD213SD, VFMADD231SD, VFMSUB213SD, VFMSUB231SD
VFNMADD213SS, VFNMADD231SS, VFNMSUB213SS, VFNMSUB231SS
VFNMADD213SD, VFNMADD231SD, VFNMSUB213SD, VFNMSUB231SD

RegRegMem version of:

VFMADD132SS, VFMSUB132SS, VFNMADD132SS, VFNMSUB132SS
VFMADD132SD, VFMSUB132SD, VFNMADD132SD, VFNMSUB132SD

Signed-off-by: Shivam Mittal <shivammittal99@gmail.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@0dvictor, could you give this the once-over please?

**Comment by 0dvictor** [comment]
The proposed change by itself looks good; however, encoding of `RegRegMem` instruction is still under development it may causes confusion if these instructions is introduced before the encoding is ready.

**Comment by 0xdaryl** [comment]
@0dvictor, I imagine that's ok.  Can you clarify what the source of the confusion is?  This is just introducing the instructions and their encodings and properties.  If the properties need to change as a result of the encoding code then these entries need to be update.

**Comment by 0dvictor** [comment]
@0xdaryl All the new instructions look correct, and the properties should work. However, if a developer sees these instructions in the table, he/she may have the impression that they are supported, but they do not work now. It may take quite a while to figure out that `RegRegMem` instruction is not supported yet. I plan to enable it in 1-2 weeks as the `RegRegReg` one has been merged.

**Comment by 0dvictor** [comment]
Sure, we can merge this pull request now, the changes are correct.
I'll make `RegRegMem` support top of my list.

**Comment by 0xdaryl** [comment]
A genie build is not needed as this is an x86-specific change.

**Pull request merged**
