### PR TITLE
Implement evaluators for different Vector Opcodes

### PR DESCRIPTION
**Pull request by r30shah**
Implement evaluators for following different opcodes on Z to vectorize
the operation when platform support is available.
1. VFMA
2. VSQRT
3. VABS

Signed-off-by: Rahil Shah <rahil@ca.ibm.com>

### CODE REVIEW

**Comment by r30shah** [comment]
@joransiu Can I please get your review on this change?

**Review by joransiu — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Jenkins build zlinux,zos

**Comment by 0xdaryl** [comment]
See Z Linux build failure.

**Comment by 0xdaryl** [comment]
Jenkins build zlinux,zos

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
