### PR TITLE
Update IBM copyright notices to remove last-modified year

### LINKED ISSUE #6879: Stop maintaining a last-modified year in copyright notices
All of our source files start with a copyright notice containing two years, like the following:

```Copyright (c) 2000, 2019 IBM Corp. and others```

The first year tells us when the file contents were first written, and the second tells us when they were last modified.

Because the copyright notices are in this form, the second year needs to be updated the first time each file is modified in a given year. These updates are a widespread paper cut that affect many contributions, as contributors generally need to manually carry them out. Furthermore, committers need to ensure that the year is updated appropriately, and remembering to do so is so error prone that we have had to develop an automated check that runs in each PR. When the check fails, before merging we have to wait for (roughly speaking) a round trip through two humans. Sometimes it can be combined with another round trip that was necessary anyway, i.e. when review has found problems that need to be addressed, but sometimes it can't be. Finally, setting aside raw efficiency, some (many?) of us find dealing with these updates to be a hassle. It's annoying to have to appease a failing copyright check.

Recently there have been [rumblings](https://hynek.me/til/copyright-years/) online about the (lack of) necessity of updating copyright years in this way for open source projects, which prompted me to look into why we do this. It turns out that maintaining the last-modified year was a requirement from IBM (my current employer) at the time of open-sourcing. However, IBM has since dropped that requirement, so it's simply no longer necessary.

As such, I propose changing our copyright notices to the following format (which is acceptable to IBM):

```Copyright IBM Corp. and others <initial-year>```

For instance, the example copyright notice from above would become:

```Copyright IBM Corp. and others 2000```

By removing the last-modified year, it no longer needs to be maintained, and we can all save a little bit of time and be a little bit less annoyed.

I would be happy to personally carry out this change. I'd like to update all of the files at once so that we aren't still left with the problem of making sure that they are updated piecemeal as other changes flow into them. The only disruption would be some (extremely easy to resolve) merge conflicts in in-flight changes that already include updates to the year in the copyright notice.

Any objections?

### PR DESCRIPTION
**Pull request by jdmpapin**
With the last-modified year removed, PRs no longer need to ensure that it is up-to-date.

The bulk of this change is in the last commit, which has been generated based on a regex substitution. It modifies the vast majority of files in the repository (though only one line in all but a few). There are some much smaller commits leading up to that one. The full list of commits is as follows:
- Update documentation to reflect changes to copyright notices
- Delete the (now unnecessary) Jenkins copyright check script
- Fix a few files to use UNIX line endings
- Delete trailing whitespace from a few files
- Use the new single-year IBM copyright notice format in cppgen.py
- Make a few IBM copyright notices consistent with the others
- Update IBM copyright notices to remove last-modified year

Because the last commit touches so many files, it's tricky to review. Rather than reading the whole thing, I recommend skimming a few of the changes to get the flavour of them, and then doing one or both of the following:
- Review [my regex substitution script](https://github.com/eclipse/omr/files/10926652/ibm-copyrights-gen-commit.txt), run it to repeat the substitution yourself starting from the same parent commit, then diff the results; and/or
- Review and run [my diff filtering script](https://github.com/eclipse/omr/files/10926719/ibm-copyrights-check-commit.txt), and review its output. It shows the diff but excluding any files in which the changes are exactly as expected, i.e. with exactly one occurrence changed near the start of the file.

~I'd like to request that the whitespace/line endings check be ignored for this PR. This change is big enough without also fixing all pre-existing whitespace errors.~

In the event of conflicts, I will rebase and regenerate the last commit.

Fixes #6879

### CODE REVIEW

**Comment by jdmpapin** [comment]
Once this PR is merged, any in-flight changes that already contain an update to the last-modified year in at least one copyright notice will conflict. When rebasing such a change, fixing the conflict should be trivial: simply use the new copyright notice format. Alternatively, commits can be amended to leave the copyright notice unchanged, which will prevent the conflict. (Anyone who has any hooks that automatically update copyright dates should remove them before trying either of these.)

However, if an in-flight change has many such copyright year updates, then updating them could get quite tedious. I've written a [script](https://github.com/eclipse/omr/files/10933317/ibm-copyrights-restore.zip) for this case that will automatically amend a series of commits to leave copyright notices unchanged. To use it, unzip the two files into a single directory, make sure they're executable, check out your branch, and run:
```
$ bash /path/to/ibm-copyrights-restore-series <upstream-branch>
```
If the upstream branch is already configured in git, it doesn't have to be specified.

**Comment by jdmpapin** [comment]
> I'd like to request that the whitespace/line endings check be ignored for this PR. This change is big enough without also fixing all pre-existing whitespace errors.

Never mind. There aren't very many files with whitespace errors that show up in the check, so I'll just fix them.

**Comment by jdmpapin** [comment]
Fixed the whitespace errors

**Comment by jdmpapin** [comment]
Jenkins build all

**Comment by jdmpapin** [comment]
Mac failure is #6516

**Comment by jdmpapin** [comment]
RISC-V failure is a hang in threadtest RWMutex, which is known. See #6913

**Comment by jdmpapin** [comment]
All other builds passed, though there are conflicts now

**Comment by jdmpapin** [comment]
Rebased to resolve conflicts. [Range diff](https://jdmpapin.github.io/range-diffs/omr-copyright-no-last-mod-v0-v1.html) (relative to eclipse:master) against the previous revision, which is still available [here](https://github.com/jdmpapin/omr/commit/copyright-no-last-mod-pr-v0).

**Comment by dsouzai** [comment]
The only new changes (i.e., commits not from this PR) introduced from [Force push](https://github.com/eclipse/omr/compare/2f23442b9e7eb586981ba575ad5978a7982ca7e6..67911a01672c49e056a3ae17733e8f327cb59372) come from https://github.com/eclipse/omr/pull/6921. 

I also reviewed a relatively big sample of the files manually, as well as reviewed the script used to generate the commit that updates the copyrights and ran the script that verifies the changes. Also I ran the script used to generate the copyrights and verified that the commit it generates is exactly the same as [Update IBM copyright notices to remove last-modified year](https://github.com/eclipse/omr/pull/6923/commits/67911a01672c49e056a3ae17733e8f327cb59372). Also the previous builds succeeded, so I don't see the point in running new ones since, given that only comments were changed (aside from some whitespace difference) the builds will only serve to (re)test https://github.com/eclipse/omr/pull/6921.

**Review by dsouzai — APPROVED** [review]

**Pull request merged**
