### PR TITLE
Relicense under EPLv2 & Apache v2

### PR DESCRIPTION
**Pull request by keithc-ca**
Update the license as per the outcome of the vote in issue #1596.

This can't be accepted until all contributors in #1606 have signed off on the relicensing their contributions.

This addresses files in the ddr, doc, example and fvtest folders.

### CODE REVIEW

**Comment by charliegracie** [comment]
There were last minute changes to the copyright header which will need to be incorporated into these changes.  You can see this change in #1606

**Comment by keithc-ca** [comment]
Rebased with updated license text.

**Comment by mstoodle** [comment]
The requirement in #1606 has been met: when it's ready, this PR can be merged.

**Comment by keithc-ca** [comment]
Closing: changes are included in https://github.com/eclipse/omr/pull/1629.

**Pull request closed without merging**
