### PR TITLE
Add an option to disable guarded static final field folding

### PR DESCRIPTION
**Pull request by liqunl**
Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@andrewcraik Can I have a review? I'll add code to set the option bit in openj9

**Comment by andrewcraik** [comment]
I'm fine with adding this option - usage will be reviewed in OpenJ9 where it is being used for the time being.

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by liqunl** [comment]
CI build failure on aarch64 is caused by https://github.com/eclipse/omr/pull/2875, fixed by https://github.com/eclipse/omr/pull/2975. Rebased to pick up the fix.

**Pull request merged**
