### PR TITLE
FIX #59 : Use GNU feature macros before including any system header files

### LINKED ISSUE #59: Use GNU feature macros before including any system header files
Fix needed for the following files:
port/linux386/omrsignal_context.c
port/linuxarm/omrsignal_context.c

### PR DESCRIPTION
**Pull request by youngar**
Issue: #59 
Signed-off-by: Andrew Young <youngar17@gmail.com>

### CODE REVIEW

**Comment by alin00** [comment]
Please add the '#' before the issue number in the commit comment. GitHub uses that tag to cross-ref commit to issue.

**Comment by alin00** [comment]
It's disappointing that we seem to be using this internal macro __USE_GNU in lots of places. I believe _GNU_SOURCE is preferred.

Since you have access to our pre-git source code history, can you see whether there is any rationale for specifically using __USE_GNU here?

**Comment by youngar** [comment]
I do not see anything obvious in the history related to our use of __USE_GNU, however there are several in code comments which partly explain.

OMR has a non-standard interaction with GlibC feature test macros.  The standard way to use feature test macros is to define the macro before any system header files are included, and never undefine it.  OMR will define __USE_GNU, #include a glibc header, and then undefine __USE_GNU (see omrsignal_context.h).  This means that __USE_GNU is only defined for some included system headers.  I believe that this has been used to get around technical limitations when using Glib C with the Xlc compiler on AIX.

Changing all our uses of __USE_GNU to _GNU_SOURCE in our source code causes compile failures. \<features.h\> is the Glib C header file which understands _GNU_SOURCE.  If _GNU_SOURCE is defined when \<features.h\> is preprocessed, it defines __USE_GNU. Since many times \<features.h\> has been included before we define our feature macro, using _GNU_SOURCE turns out to be ineffectual.  We could use _GNU_SOURCE if we defined it globally, but as noted above this will probably cause issues on other platforms.

**Comment by alin00** [comment]
What problems did you see, that motivated these changes?

**Comment by youngar** [comment]
I'm adding some new port library API regarding buffered file writing.  The original commit fixed the bare minimum needed to get my code to compile.  Now that I understand the issue a little bit better, I have updated this commit to fix a couple more 'easy' places.

**Comment by charliegracie** [comment]
@alin00 you made some comments on this issue.  Is something you are handling or do you want someone else to work on getting the PR accepted?

**Comment by alin00** [comment]
I can handle this one.

The topic rename to remove [WIP] didn't show up in my notifications list.

**Pull request merged**
