### PR TITLE
Remove deprecated J9 snippets on X86 [Phase 2/2]

### PR DESCRIPTION
**Pull request by 0dvictor**
Follow-up of #3190, deprecated J9 snippets are removed.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by 0dvictor** [comment]
The dependent OpenJ9 change has been merged, this pull request is ready to go.

**Comment by Leonardo2718** [comment]
@genie-omr build all

AppVeyor build failed because of infra problems so I restarted it.

**Comment by andrewcraik** [comment]
LGTM from me

**Comment by vijaysun-omr** [comment]
@0dvictor could you please fix the merge conflict in this PR ?

**Comment by 0dvictor** [comment]
Conflicts have been resolved.

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Pull request merged**
