### PR TITLE
Use importlibs for libdwarf and libz

### PR DESCRIPTION
**Pull request by youngar**

### CODE REVIEW

**Comment by youngar** [comment]
Going to fix libelf and diasdk to use imported libs as well

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by youngar** [comment]
Still need to find out what went wrong on [linux 390 ](https://ci.eclipse.org/omr/job/PullRequest-linux_390-64/1927/console)
```
  -- Found LibElf: /usr/lib/s390x-linux-gnu/libelf.so  
  CMake Error at /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
    Could NOT find LibZ (missing: LIBZ_LIBRARY ZLIB_H_INCLUDE_DIR)
  Call Stack (most recent call first):
    /usr/share/cmake-3.5/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
    cmake/modules/FindLibZ.cmake:35 (find_package_handle_standard_args)
    cmake/modules/FindLibDwarf.cmake:34 (find_package)
    ddr/lib/ddr-scanner/CMakeLists.txt:47 (find_package)
```

**Comment by youngar** [comment]
@genie-omr build linux

**Comment by youngar** [comment]
@genie-omr build xlinux zlinux

**Comment by youngar** [comment]
@genie-omr build xlinux zlinux

**Comment by youngar** [comment]
@genie-omr build all

**Comment by rwy0717** [comment]
@genie-omr build all

**Pull request merged**
