### PR TITLE
Remove J9_VERSION from JitBuilder and Test Compiler

### LINKED ISSUE #1651: Remove J9_VERSION from JitBuilder and Test Compiler
```
magaudet@ubuntu1604VM:~/open/omr $ ag J9_VERSION
jitbuilder/build/toolcfg/common.mk
20:J9_VERSION?=29

fvtest/compilertest/build/toolcfg/common.mk
1:J9_VERSION?=29
```

Not consumed, not useful.

### PR DESCRIPTION
**Pull request by nidhi1605**
Fixes #1651
Signed-off-by: Nidhi Gupta <itsnidhi16@gmail.com>

### CODE REVIEW

**Comment by Leonardo2718** [comment]
@nidhi1605 Can you please squash the commits together?

**Comment by nidhi1605** [comment]
@Leonardo2718  I have squashed the commits together.

**Comment by Leonardo2718** [comment]
@genie-omr build aarch64, arm, xcrlinux

**Comment by Leonardo2718** [comment]
No need to test cmake builds as this change only affects autotools.

**Pull request merged**
