### PR TITLE
Replace #pragmas mc_func and #reg_killed_by with gcc inline asm

### PR DESCRIPTION
**Pull request by midronij**
Since #pragma mc_func and #pragma reg_killed_by are no longer supported on AIX, any functions defined in this manner have been replaced with equivalent inline assembly code.

Signed-off-by: Jackie Midroni <jackie.midroni@mail.utoronto.ca>

### CODE REVIEW

**Comment by ymanton** [comment]
The lack of symbols makes it hard to know how accurate or not it was before and if what we have now is better or worse, to be honest.

I repeated variations of your experiment and looked at the core file in DBX and yours looks like what DBX produces so I'm satisfied. The current code looks like its showing an extra stack frame belonging to the stack walker's own implementation, which really doesn't have any usefulness so I'm OK with losing it.

**Comment by 0xdaryl** [comment]
@genie-omr build aix

**Comment by gita-omr** [comment]
> The current code looks like its showing an extra stack frame belonging to the stack walker's own implementation, which really doesn't have any usefulness so I'm OK with losing it.

I wonder why there would be any difference since new code seems to be doing exactly what pragmas did before...

**Comment by ymanton** [comment]
The compiler might be more willing to inline functions with `asm` statements than functions with `mc_func` calls which would result in fewer stack frames.

**Comment by gita-omr** [comment]
Right. Thanks @ymanton for your help!

**Pull request merged**
