### PR TITLE
Read system swappiness in omrsysinfo_get_memory_info()

### PR DESCRIPTION
**Pull request by ashu-mehra**
Update the code for omrsysinfo_get_memory_info() to read swappiness value
from proc fs or from cgroup fs when running on Linux OS.
On other platforms that don't have the concept of swappiness, it is set
to OMRPORT_MEMINFO_NOT_AVAILABLE.

Signed-off-by: Ashutosh Mehra <mehra.ashutosh@ibm.com>

### CODE REVIEW

**Comment by ashu-mehra** [comment]
This PR is required to help in resolving OpenJ9 issue https://github.com/eclipse/openj9/pull/9653

**Comment by ashu-mehra** [comment]
fyi - @mpirvu

**Comment by 0xdaryl** [comment]
Is this PR still active?  The previous reviewers comments haven't been addressed in almost 8 months.  I suggest we close it unless the author indicates they are still progressing it.

**Comment by ashu-mehra** [comment]
@0xdaryl thanks for bringing it to my notice. I have completely forgotten about this. I can resurrect it; hopefully this week. It shouldn't take much time.

**Comment by 0xdaryl** [comment]
Hi...  Sorry to poke again about any progress on this.  Thanks.

**Pull request closed without merging**
