### PR TITLE
Tril tests for i2f, etc.

### PR DESCRIPTION
**Pull request by knn-k**
This commit implements Tril test cases for i2f, etc.

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
This commit contains tests for integer->FP conversion.
I am planning to add tests for f2d, d2f, and FP->integer, but I need to wait for discussion in #3332 on how to pass FP values in `UsingConst` variants.

**Comment by Leonardo2718** [comment]
@genie-omr build all

**Comment by Leonardo2718** [comment]
The failure on ppc is due to #3369. @knn-k can you `#ifndef TR_TARGET_POWER` out the test case for power and then open an issue to remove the guard once #3369 is resolved?

**Comment by knn-k** [comment]
Opened Issue #3375 for removing the guard for ppc later.

**Pull request merged**
