### PR TITLE
OMR changes needed to support an OpenJ9 EA fix

### PR DESCRIPTION
**Pull request by klangman**
Signed-off-by: Kevin Langman <langman@ca.ibm.com>

### CODE REVIEW

**Comment by klangman** [comment]
This PR needs to be merge coordinated with the OpenJ9 PR: https://github.com/eclipse-openj9/openj9/pull/16119

**Comment by vijaysun-omr** [comment]
@hzongaro would you mind reviewing this since both Devin and I assisted in developing the fix ?

**Review by vijaysun-omr — APPROVED** [review]

**Review by hzongaro — APPROVED** [review]
Looks good

**Comment by vijaysun-omr** [comment]
Jenkins build all

**Review by 0xdaryl — APPROVED** [review]
CI failures are known issues.

**Pull request merged**
