### PR TITLE
AArch64: Implement lcmpeqEvaluator(), etc.

### PR DESCRIPTION
**Pull request by knn-k**
This commit implements lcmpeqEvaluator() and similar evaluators.

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
Tests are available in #3227.

**Comment by knn-k** [comment]
This passes the tests in #3310.

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Comment by 0xdaryl** [comment]
This is an AArch64-specific change.  A full genie build is not required.

**Pull request merged**
