### PR TITLE
Remove duplicate implementations of Monitor

### PR DESCRIPTION
**Pull request by noryb009**
There was previously two copies of the exact same Monitor class under Test compiler and JIT Builder. In addition, any projects using the OMR JIT would need to implement their own Monitor class, adding more duplicates.

Additionally, use OMR's MUTEX object instead of pthreads. Since Windows does not have pthreads, we instead use the cross-platform MUTEX object in the OMR library.

### CODE REVIEW

**Comment by lmaisons** [comment]
Where did operator new go?  You have created an operator delete, but seem to have removed operator new.  If we're going to deallocate from persistentAllocator, we need to allocate from it too.

**Comment by noryb009** [comment]
I am likely wrong, but does [this line](https://github.com/noryb009/omr/blob/a87a60da4b08d45f9ba54c5b83345e23633213b2/compiler/infra/OMRMonitor.cpp#L40) take care of not needing a special `new` implementation?

**Comment by lmaisons** [comment]
That line does work as advertised.  I am, however, somewhat loathe to recommend using placement new on construction while providing a redefinition of the 'standard' destruction mechanism.  We should either use the standard form at both ends, or explicitly acknowledge the use of placement new by manually calling the destructor then deallocating the memory.

**Comment by 0xdaryl** [comment]
Change looks good, but I do agree with @lmaisons comment around the asymmetry with the new and delete operators.  I would lean toward creating a new operator rather than continuing with the placement use.

**Comment by noryb009** [comment]
@0xdaryl @lmaisons I've cleaned up the new/delete operators.

**Pull request merged**
