### PR TITLE
Disable cpu asserts for outOfProcessCompilations

### PR DESCRIPTION
**Pull request by harryyu1994**
Disabled the cpu related asserts for outOfProcessCompilations. These asserts are meant to only test the correctness of new APIs against old APIs for a single host processor and they fall apart when we introduce remote target processors into the picture.

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by harryyu1994** [comment]
@fjeremic @mpirvu Could you guys help review this one?

**Comment by harryyu1994** [comment]
Actually I just found a way to keep the tests.

**Comment by fjeremic** [comment]
@harryyu1994 just confirming (probably for the 7th - sorry!) that these asserts are here only to "bake in" and ensure functional correctness of the OMR processor detection. Can you confirm they will be removed at some later point (say ~4 months from now)?

**Comment by harryyu1994** [comment]
> @harryyu1994 just confirming (probably for the 7th - sorry!) that these asserts are here only to "bake in" and ensure functional correctness of the OMR processor detection. Can you confirm they will be removed at some later point (say ~4 months from now)?

@fjeremic Yes, they are temporary asserts that will be removed when the old api goes away.

**Comment by fjeremic** [comment]
@genie-omr build all

**Pull request merged**
