### PR TITLE
AArch64: This Fixes duplicate opcode in ARM64Ops

### PR DESCRIPTION
**Pull request by jeanlego**
this should fix error #2761 
by renaming sturb and ldurb duplicate name
 for clarity we use the "_bt" notation when accessing a byte of the
register and only "b" when the target is the byte size fp register

Signed-off-by: jeanlego <jeanphilippe.legault@unb.ca>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
For the cases where the SIMD mnemonics are aliased with the non-SIMD mnemonics, what do you think about prefixing the SIMD-form instructions with a `v` instead?  It makes it somewhat consistent with the other vector (SIMD) instructions, and is more intuitive when choosing the right opcode (in my mind at least).  For instance,
```
vsturb (SIMD&FP)
sturb
```

**Comment by 0xdaryl** [comment]
^^^ @knn-k @jeanlego @aarongraham9 @JamesKingdon

**Comment by knn-k** [comment]
I agree with adding the prefix "v" for SIMD and FP instructions.

**Comment by jeanlego** [comment]
added the changes proposed by @0xdaryl 
should be good to go! @aarongraham9 ? @knn-k

**Comment by knn-k** [comment]
Looks good to me.

**Comment by aarongraham9** [comment]
LGTM as well @jeanlego and @0xdaryl.

**Pull request merged**
