### PR TITLE
WIP: Clean up linkage info

### PR DESCRIPTION
**Pull request by dsouzai**
Please do not merge until https://github.com/eclipse/openj9/pull/8785 is merged.

This PR cleans up the code that initializes the Linkage Info word that is found right before the interpreter entry point. Because OMR does not have an interpreter entry point, the OMR implementation is simplified; the OpenJ9 overrides the OMR implementation in https://github.com/eclipse/openj9/pull/8785.

`TR_LinkageInfo` is also deleted.

### CODE REVIEW

**Comment by dsouzai** [comment]
I haven't tested this extensively; however I'm opening it to get reviewers opinions on the approach I've taken.

**Comment by fjeremic** [comment]
@dsouzai thanks for this. It seems @0xdaryl has already started this work over in #4615. Can you coordinate with him who will finish this off and the stale PR can then be closed?

**Comment by dsouzai** [comment]
One subtle difference between this PR and #4615 is that in this PR, I did
```
start += cg()->getJitEntryOffset();
```
whereas in #4615, Daryl did:
```
targetAddress = cg()->getLinkage()->entryPointFromCompiledMethod();
```
While the latter is the better approach long term, it does require implementing `entryPointFromCompiledMethod` and `entryPointFromInterpretedMethod` in each of OpenJ9's private linkages. 

Additionally, I'm not even sure if OMR's implementations are correct as they all return `cg()->getCodeStart()` - I think OMR by default at least generates a 32-bit word before the startPC, so `cg->getCodeStart()` wouldn't be technically correct.

Therefore, I think in order to not explode the scope of this work, it's better to have the `getJitEntryOffset` API, which can later be replaced by the `entryPointFromCompiledMethod` API. 

What do you think @0xdaryl ?

**Comment by 0xdaryl** [comment]
Please either mark this as a WIP or move it into Draft state to prevent it from being accidentally merged if there is a downstream dependency.

**Comment by 0xdaryl** [comment]
The approach I was taking to clean up the LinkageInfo word was to truly make it a linkage concern, which undoubtedly it is.  A LinkageInfo word is only a requirement for some linkages (just one actually) and the question of what the method entry point addresses are for JIT->JIT and interpreter->JIT dispatches should best be answered by the linkage itself as the answer depends on it.  The pair of PRs (OMR #4615 and OpenJ9 eclipse/openj9#7901) that I opened were a step in that direction (and it's fairly clear I got distracted by other shiny things late in 2019 which caused me to lose track of them and not shepherd them forward :-)  My apologies for allowing them to slip through the cracks).

The one thing that is missing from my PRs is when and where the LinkageInfo word is actually emitted by PrivateLinkage.  Right now, it is emitted as a step in the code generation process, which it shouldn't be.  However, I believe it should actually be part of prologue generation and when any interpreter entry point code is laid down.  I don't recall off the top of my head what exactly needed to be changed to make that happen but I do recall it isn't quite that simple and the ordering of some events might have to change.

So, my preference (but I'm willing to hear other opinions) is to follow the path that I was on, which means that 7901/4615 should be merged first.  The follow-on work to emit the LinkageInfo word then needs to be implemented by someone.

**Comment by dsouzai** [comment]
Closing this PR; https://github.com/eclipse/openj9/pull/7863 cleans up the OpenJ9 side and so a followup PR will need to be opened to clean up the OMR side.

**Pull request closed without merging**
