### PR TITLE
Misc. allocator cleanup

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Remove allocator name fields
* Remove unused arena allocator factory function for LabelSymbol
* Remove unused allocator parameter from NodePool constructor

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@dsouzai : I'd appreciate a review from you please.

**Review by dsouzai — APPROVED** [review]
lgtm

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
@Leonardo2718 : when CI finishes, would you mind taking this one please?

**Review by Leonardo2718 — APPROVED** [review]
LGTM :+1:

**Comment by 0xdaryl** [comment]
Thanks @Leonardo2718 .  The RISC-V failure is a machine failure again.  This PR did not cause that.  I think it is safe to merge.

**Pull request merged**
