### PR TITLE
Clean up node flag tracing

### PR DESCRIPTION
**Pull request by jdmpapin**
- Print flags that have been missing from log output
- Clean up and likely speed up printing of node flags

Please see the individual commit messages.

### CODE REVIEW

**Review by vijaysun-omr — APPROVED** [review]

**Comment by vijaysun-omr** [comment]
Jenkins build all

**Comment by jdmpapin** [comment]
Jenkins build all

**Comment by vijaysun-omr** [comment]
Jenkins build all

**Comment by jdmpapin** [comment]
I can't tell what went wrong in the macOS build ("Build not found"), and it doesn't seem to be restarting when I hit "Re-run."

The Windows tests failed because a number of tests didn't run, and in every case it seems to have been because an executable was missing:
```
Unable to find executable: C:/omr/workspace/PullRequest-win_x86-64/Build/build/Debug/[...].exe
```
I can't tell why these files were missing, but I doubt it has to do with node flag tracing.

**Comment by jdmpapin** [comment]
I added and removed an empty commit to restart the checks, but it restarted the copyright check as well, so now I've updated the copyright dates.

**Comment by jdmpapin** [comment]
Jenkins build all

**Review by vijaysun-omr — APPROVED** [review]

**Review by vijaysun-omr — APPROVED** [review]

**Comment by vijaysun-omr** [comment]
I reviewed that all the queries passed in to the new `FLAG` routines matched what was being printed. Checks have passed. Merging.

**Pull request merged**
