### PR TITLE
Initial implementation of a SnippetDelegate hierarchy

### PR DESCRIPTION
**Pull request by 0xdaryl**
This is similar in design and purpose to the InstructionDelegate hierarchy (#3778).

This is a skeleton implementation only and contains no static member functions yet.

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@dsouzai : please review

**Comment by 0xdaryl** [comment]
Jenkins build all

**Comment by 0xdaryl** [comment]
RISC-V node is still down.

**Comment by 0xdaryl** [comment]
Not specifically for Snippets but it is the same idea as the Instruction delegates, described in #3778.  This is to enable project-specialized functions in a dynamic polymorphic hierarchy (i.e., one that is not an extensible class).

I was debating whether there should be just one "delegate" class where various different dynamic polymorphic hierarchies could put their specialized members.  While unity is nice, I was worried it would become a complete kitchen sink of concepts.  So I chose to keep them as separate "delegate" hierarchies for now and would reconsider a unified hierarchy later if they started to get out of hand.

**Review by dsouzai — APPROVED** [review]

**Pull request merged**
