### PR TITLE
When skipping global DSE for a single block, still run local DSE

### PR DESCRIPTION
**Pull request by jdmpapin**
Without running some DSE pass, obvious dead stores can make it all the way to code generation.

### CODE REVIEW

**Review by vijaysun-omr — APPROVED** [review]

**Comment by vijaysun-omr** [comment]
Jenkins build all

**Comment by 0xdaryl** [comment]
Test failures look real.

```
1973 [2023-02-17T22:02:48.788Z] 3: Assertion failed at /home/jenkins/workspace/Build/compiler/optimizer/OMROptimizer.cpp:1258: manager != NULL
 1974 [2023-02-17T22:02:48.788Z] 3:   Optimization manager should have been initialized for localDeadStoreElimination.
 1975 [2023-02-17T22:02:48.788Z] 3: compiling /home/jenkins/workspace/Build/jitbuilder/release/cpp/samples/Conditionals.cpp:41:test_ifs at level: warm
 1976 [2023-02-17T22:02:48.788Z] 3: #0: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(_ZN25TR_LinuxCallStackIterator19printStackBacktraceEPN2TR11Compi      lationE+0x50) [0x5631239f66e0]
 1977 [2023-02-17T22:02:48.788Z] 3: #1: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(_ZN8TR_Debug19printStackBacktraceEv+0x34) [0x56312385e97e]
 1978 [2023-02-17T22:02:48.788Z] 3: #2: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(+0x3a650e) [0x56312381a50e]
 1979 [2023-02-17T22:02:48.788Z] 3: #3: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(+0x3a6624) [0x56312381a624]
 1980 [2023-02-17T22:02:48.788Z] 3: #4: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(_ZN2TR9assertionEPKciS1_S1_z+0x129) [0x56312381a752]
 1981 [2023-02-17T22:02:48.788Z] 3: #5: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(_ZN3OMR9Optimizer19performOptimizationEPK20OptimizationStrategyi      ii+0xad) [0x5631239abfb5]
 1982 [2023-02-17T22:02:48.788Z] 3: #6: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(_ZN3OMR9Optimizer19performOptimizationEPK20OptimizationStrategyi      ii+0x10bb) [0x5631239acfc3]
 1983 [2023-02-17T22:02:48.788Z] 3: #7: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(_ZN3OMR9Optimizer8optimizeEv+0x6ff) [0x5631239ab591]
 1984 [2023-02-17T22:02:48.788Z] 3: #8: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(_ZN3OMR11Compilation20performOptimizationsEv+0x71) [0x5631238f89      f9]
 1985 [2023-02-17T22:02:48.788Z] 3: #9: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(_ZN3OMR11Compilation7compileEv+0x9a8) [0x5631238f828e]
 1986 [2023-02-17T22:02:48.788Z] 3: #10: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(_Z24compileMethodFromDetailsP12OMR_VMThreadRN2TR24IlGeneratorMe      thodDetailsE10TR_HotnessRi+0x66c) [0x563123914f61]
 1987 [2023-02-17T22:02:48.788Z] 3: #11: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(_ZN3OMR13MethodBuilder7CompileEPPv+0x88) [0x563123808ace]
 1988 [2023-02-17T22:02:48.788Z] 3: #12: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(_Z29internal_compileMethodBuilderPN2TR13MethodBuilderEPPv+0x23)       [0x5631238a1fb2]
 1989 [2023-02-17T22:02:48.788Z] 3: #13: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(_Z20compileMethodBuilderPN3OMR10JitBuilder13MethodBuilderEPPv+0      x38) [0x5631237eeff7]
 1990 [2023-02-17T22:02:48.788Z] 3: #14: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(main+0xe3) [0x5631237e519e]
 1991 [2023-02-17T22:02:48.788Z] 3: #15: /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fb8366d5083]
 1992 [2023-02-17T22:02:48.788Z] 3: #16: /home/jenkins/workspace/Build/build/jitbuilder/release/conditionals(_start+0x2e) [0x5631237e46fe]
 1993 [2023-02-17T22:02:48.788Z] 3:
 1994 [2023-02-17T22:02:48.788Z]  3/49 Test  #3: conditionals_example_as_test ........SIGTRAP***Exception:   0.03 sec
```

**Comment by jdmpapin** [comment]
Wow, OK. Somehow things find a way to break no matter how incredibly safe they may look. I'll check into what's going on here

**Comment by jdmpapin** [comment]
Updated to create an optimization manager for local DSE in JitBuilder.

When running the tests locally I ran into an unrelated assertion failure from `snprintfNoTrunc()` in `DefineLine(const char*)`, which expects a formatted line number, but was instead provided with a source file name. It turns out that the `ThunkBuilder` constructor had swapped `DefineFile()` with `DefineLine()`, so I've fixed that as well.

**Comment by vijaysun-omr** [comment]
Jenkins build all

**Review by vijaysun-omr — APPROVED** [review]

**Review by vijaysun-omr — APPROVED** [review]

**Pull request merged**
