### PR TITLE
Fixed shift calculations for shift right on Power

### PR DESCRIPTION
**Pull request by IBMJimmyk**
In some cases when attempting a shift right calculation, a rotate left instruction is used instead on Power. For this to work, the shift value needs to be convered to be (data width - shift amount).

eg. Shift right by 4 on a 32 bit value becomes a rotate left and mask by (32-4=) 28.

However, this doesn't work when trying to shift right by 0. It gets converted to a rotate left and mask by 32 (for 32 bit values) which is not a legal encoding of the instruction.

This has now been updated to take the modulo by data width after the old version of the conversion. This will catch cases of a shift right by 0 and convert to a rotate left and mask by 0.

### CODE REVIEW

**Comment by IBMJimmyk** [comment]
@zl-wang Could you take a look at this?

**Comment by zl-wang** [comment]
I would prefer to special-casing evaluation of 0 shift-amount:  i.e.  no instruction or a register copy (of the source register)  will be emitted, if the shift-amount is 0.

**Review by zl-wang — CHANGES_REQUESTED** [review]
i supposed the motivation to do rotate (when canClobberNodesRegister is not true) instead of register copy is:  mr has the same cost in pipeline as a rotate?

that might not be true in general.  actually, it is implementation-specific. it is more common that mr (ori with 0) is optimized to be simply a register renaming action.

**Comment by IBMJimmyk** [comment]
I added the case where no instruction is generated if the source register can be clobbered and the shift value is 0. If the source can not be clobbered, it is a move register instead.

There is also an optimization in the area where a mask and shift operation can be combined. In this case, both the shift has to be 0 and the mask must cover the entire width of the data to remove the instruction. Similarly, if the source register can not be clobbered, a move register is used.

**Comment by zl-wang** [comment]
it is hard to understand why there is a distinction between signed and unsigned re full-mask and partial-mask.  isn't it incorrect either for unsigned shift-0, if the mask is partial?

**Comment by IBMJimmyk** [comment]
`rldicl` and `rlwinm` effectively performs a logical shift right operation since they will always shift in a 0 bit. So the value being shifted either needs to be an unsigned value or a positive signed value. Since an unsigned value is always okay, there's no problem if the mask does not clear the sign bit. A positive signed value can be guaranteed if we know the constant value mask operation always clears the sign bit. Negative signed values are also okay if the shift amount is 0 since no bits are shifted in.

**Comment by zl-wang** [comment]
> rldicl and rlwinm effectively performs a logical shift right operation since they will always shift in a 0 bit.

that is not correct.  rotate instruction just rotates the other-end's register bits to this-end.  0 bits are really provided by the right masking.  e.g.   010101  rotate-left by 1 position results in:  101010     value-1 is actually rotated into the sign-bit

**Comment by IBMJimmyk** [comment]
Sorry, my explanation was bad. What you say is correct. The bits are being rotated but by setting the mask bits to 0 it acts as if 0 bits are being shifted in.

**Comment by zl-wang** [comment]
such that: testing mask in signed case and not testing mask in unsigned case is not necessarily warranted, since both cases are using the same rotate instructions.

**Comment by IBMJimmyk** [comment]
Logical and Algebraic cases can be different.

Case 1:
32 bit value `0xFE000000`. No mask or `0xFFFFFFFF` mask. Shift by 0.
Expected result `0xFE000000`
eg. `rlwinm RA, RS, 0, 0xFFFFFFFF`

Case 2:
32 bit value `0xFE000000`. No mask or `0xFFFFFFFF` mask. Logical right shift by 4.
Expected result `0x0FE00000`
eg. `rlwinm RA, RS, (32-4), 0x0FFFFFFF`

Case 3:
32 bit value `0xFE000000`. No mask or `0xFFFFFFFF` mask. Algebraic right shift by 4.
Expected result `0xFFE00000`
**`rlwinm` can not be used.**

Case 4:
32 bit value `0xFE000000`. `0x0FFFFFFF` mask. Shift by 0.
Expected result `0x0E000000`
eg. `rlwinm RA, RS, 0, 0x0FFFFFFF`

Case 5:
32 bit value `0xFE000000`. `0x0FFFFFFF` mask. Logical right shift by 4.
Expected result `0x00E00000`
eg. `rlwinm RA, RS, (32-4), 0x00FFFFFF`

Case 6:
32 bit value `0xFE000000`. `0x0FFFFFFF` mask. Algebraic right shift by 4.
Expected result `0x00E00000`
eg. `rlwinm RA, RS, (32-4), 0x00FFFFFF`

Case 3 does not work with a `rlwinm` instruction since it can't shift in 1s due to being an Algebraic shift on a negative number.

For case 5 and 6, since the mask operation clears the sign bit, the Algebraic shift and Logical are the same. Also this lets `rlwinm` be used for the Algebraic shift case as well.

**Comment by zl-wang** [comment]
understand them. but, correspondingly it is incorrect either for 0-shift with partial-mask logical/unsigned case:
32 bit value 0xFE00000F. No mask or 0xFFFFFFF0 mask. Shift by 0.
Expected result 0xFE000000
eg. register-copy or src-register are all incorrect.

unless we are going to say this-case is impossible (checked in higher level code).

**Comment by IBMJimmyk** [comment]
Re: 32 bit value 0xFE00000F. 0xFFFFFFF0 mask. Shift by 0.

First there is a call to `isMaskThenShiftRightCandidate`.
https://github.com/IBMJimmyk/omr/blob/23e4c177a0a57260948dd0894fd69aaf8ac8b1a8/compiler/p/codegen/BinaryEvaluator.cpp#L2686
https://github.com/IBMJimmyk/omr/blob/23e4c177a0a57260948dd0894fd69aaf8ac8b1a8/compiler/p/codegen/BinaryEvaluator.cpp#L2627-L2664

This checks to see if it is possible to combine the mask and shift into a single instructions.
On top of checking if the mask and shift amounts are okay. It also looks at reference counts to check if the result from just the mask is needed elsewhere.
For this particular case:
-the mask bits are contiguous
-the shift amount is 0
So the mask and shift amounts pass all the checks. So the follow instruction is produced:
`rlwinm RA, RS, 0, 0xFFFFFFF0`

If the check fails (for example due to reference counts issues), there is a check to see if this is a Logical shift:
https://github.com/IBMJimmyk/omr/blob/23e4c177a0a57260948dd0894fd69aaf8ac8b1a8/compiler/p/codegen/BinaryEvaluator.cpp#L2686
I just realized this can be expanded to include shifts by 0 as well so at the moment it doesn't.

For this case, the mask and shift are not combined. The evaluator is called on the mask node to handle the masking. This evaluator will only handle the shift by 0.
https://github.com/IBMJimmyk/omr/blob/23e4c177a0a57260948dd0894fd69aaf8ac8b1a8/compiler/p/codegen/BinaryEvaluator.cpp#L2749-L2805
That will either generate a register move or no instruction depending on if the source register can be clobbered.
The mask instruction was already generated to change `0xFE00000F` -> `0xFE000000`. So this is no problem with a register move or no instruction.

**Comment by zl-wang** [comment]
i meant:  if i can arrange a similar case(above) to go this ...
https://github.com/IBMJimmyk/omr/blob/23e4c177a0a57260948dd0894fd69aaf8ac8b1a8/compiler/p/codegen/BinaryEvaluator.cpp#L2765-L2780

regCopy or src-reg are all incorrect results, aren't they?

**Comment by IBMJimmyk** [comment]
That section of code only handles shifting. So if the shift value is 0, then a reg copy or no instruction is correct behavior. 

The `mask` here is used to clear bits that were rotated in from the left. In the case of a 0 shift, the mask covers the entire width of the input data:
https://github.com/IBMJimmyk/omr/blob/23e4c177a0a57260948dd0894fd69aaf8ac8b1a8/compiler/p/codegen/BinaryEvaluator.cpp#L2753

**Review by zl-wang — APPROVED** [review]
Looks good ...

**Comment by IBMJimmyk** [comment]
I squashed and rebased my changes on the latest master branch. I also made one change:

https://github.com/IBMJimmyk/omr/blob/41354118781251579b547556f2e6ee5d6ff51fac/compiler/p/codegen/BinaryEvaluator.cpp#L2749C41-L2749C41

Signed shifts by 0 aren't any different than an unsigned shift by 0 because no shifting actually occurs. So I changed this line to allow that case and prevent generating an instruction (or generate a register move instead).

All the tests I ran have passes so this is good to go if everything looks good.

**Comment by IBMJimmyk** [comment]
If there are no other requests or comments, can this get merged in?

**Comment by 0xdaryl** [comment]
Jenkins build plinux,aix

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
