### PR TITLE
Add additional X86 generate instruction functions

### PR DESCRIPTION
**Pull request by 0xdaryl**
Add additional APIs for:
* X86RegInstruction
* X86CallMemInstruction

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@genie-omr build xlinux,win,osx,x32linux

**Comment by 0xdaryl** [comment]
@genie-omr build xlinux,win,osx,x32linux

**Comment by 0xdaryl** [comment]
@genie-omr build xlinux,win,osx,x32linux

**Comment by vijaysun-omr** [comment]
Looks safe enough in that this just added two apis without anyone actually starting to use them yet (may happen in some downstream project, that's ok). Was it just oversight that these apis were not added alongside some other very similar apis in the past ? i.e. is there a chance to clean up some code as a result of having these new apis now and eliminating logic that was doing the equivalent thing in multiple places ? or is it just that no one has had a need for the use case handled by these new apis ?

**Comment by 0xdaryl** [comment]
I think it is the latter.  These APIs appear to be generated on an as-needed basis.  This probably isn't the right approach, but it is the state of the world right now.  Longer term it would be nice to produce generate functions for each public API and then consistently use them throughout OMR and downstream projects.

**Comment by vijaysun-omr** [comment]
Checks have passed. Merging.

**Pull request merged**
