### PR TITLE
Add guarding macro when including OS specific header

### PR DESCRIPTION
**Pull request by jamesgua**
Signed-off-by: Tao Guan <james_mango@yahoo.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Can you provide more details on what this PR is trying to achieve or the problem it is trying to fix?  Thanks.

**Comment by jamesgua** [comment]
The purpose of this PR is simply to add a macro guard in header CallStack.hpp since it's purely included by CallStack.cpp for Windows OS, so I define the macro in CallStack.cpp instead of the header. Usually we expect such a macro guard in header file.
There's no specific issue to fix, just for improvement (in my opinion).

**Comment by 0xdaryl** [comment]
OK, thanks for spotting that.  But why don't you just add the proper guard around the entire header file like we do for all the others as well as adding an OS-specific guard.  For example:

```
<copyright header>

#ifndef CALLSTACK_INCL
#define CALLSTACK_INCL

#if defined(OMR_OS_WINDOWS) && defined(TR_HOST_X86) && defined(TR_HOST_32BIT)

body of CallStack.hpp

#endif

#endif
```

**Comment by 0xdaryl** [comment]
Jenkins build win

**Review by 0xdaryl — APPROVED** [review]
I also did a successful sniff test integrating with OpenJ9.

**Pull request merged**
