### PR TITLE
Remove remaining remnants of strictFP

### PR DESCRIPTION
**Pull request by 0xdaryl**
Feature has been deprecated and no longer applies.

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins build all

**Comment by 0xdaryl** [comment]
@BradleyWood : would you mind reviewing this PR please?

**Comment by 0xdaryl** [comment]
Jenkins build riscv

**Comment by BradleyWood** [comment]
LGTM

**Comment by 0xdaryl** [comment]
@dsouzai : would mind merging this minor cleanup item please?

**Review by dsouzai — APPROVED** [review]

**Pull request merged**
