### PR TITLE
Fail Travis builds if CMake builds fail

### PR DESCRIPTION
**Pull request by mgaudet**
This will be an important step towards productizing our CMakeLists

Signed-off-by: Matthew Gaudet <magaudet@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
I'm fine with this, but won't merge until knowing the thumb orientation of at least one of @charliegracie @rwy0717 @dnakamura .

**Comment by charliegracie** [comment]
Waiting for @rwy0717 or @dnakamura as I believe they are also working on CMake changes right now.

**Comment by dnakamura** [comment]
LGTM. doesn't conflict with anything I have in the pipe

**Comment by rwy0717** [comment]
lgtm

**Comment by youngar** [comment]
As soon as the latest travis build finishes I'll merge this

**Comment by mgaudet** [comment]
Did that job get restarted or something (I see nothing but green ✔️ here)

**Comment by youngar** [comment]
No, I think there is a problem related to the -pthread change I just merged: https://travis-ci.org/eclipse/omr/jobs/254967590

**Comment by charliegracie** [comment]
The offending PR was reversed so this should be ready to go

**Pull request merged**
