### PR TITLE
Change LoopVersioner var/function names for awrtbari

### PR DESCRIPTION
**Pull request by cathyzhyi**
Change the variable and function names from iwrtbar to awrtbari

Signed-off-by: Yi Zhang <yizhang@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
looks fine to me and makes sense now the opcode has changed name

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by vijaysun-omr** [comment]
Renaming of several methods to match renamed IL opcode. No behaviour change as such. Merging.

**Pull request merged**
