### PR TITLE
Create a disableZEC12 alias for disableZHelix

### PR DESCRIPTION
**Pull request by fjeremic**
To stay consistent with all the other processor options we create a
disableZEC12 option and mark the previous disableZHelix as deprecated.
Unfortunately there are references on the web to the disableZHelix
option so we cannot completely remove it at this moment.

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
@joransiu could you please review?

**Comment by fjeremic** [comment]
> LGTM. Minor typo in commit message: "disalbeZEC12"

Fixed in 3d0f4f4.

**Comment by fjeremic** [comment]
Very minor change so preemptively launching a build for whomever gets to be a committer on this one.

@genie-omr build all

**Comment by charliegracie** [comment]
@genie-omr build aix

**Pull request merged**
