### PR TITLE
Remove declaration and definition of movedObjectHashCode

### PR DESCRIPTION
**Pull request by KenCox94**
Signed-off-by: Kenneth cox <differentialcalc1050@gmail.com>

### CODE REVIEW

**Comment by KenCox94** [comment]
Apologies for all the problems with this. I had changed my email address but Git was still associating my signature with my old one.

**Comment by KenCox94** [comment]
[this](https://github.com/eclipse/omr/issues/5851) is the issue for this pull request

**Comment by 0xdaryl** [comment]
Minor nit:  please remove the "." from the end of your commit and PR title per the Contributor Guidelines.

Code changes look good to me.

**Comment by 0xdaryl** [comment]
Jenkins build all

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Thanks for the contribution!

**Pull request merged**
