### PR TITLE
Assorted improvements to RISC-V backend

### PR DESCRIPTION
**Pull request by janvrany**
This PR contains various tiny improvements to RISC-V backend here and there.

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Also, please make sure the leading copyright date on each file modified is 2020.

**Comment by janvrany** [comment]
> Also, please make sure the leading copyright date on each file modified is 2020.

Okay. These commits were actually made last year (Oct, Dec) - now I only pushing them. Shall I  also modify commit dates?

**Comment by 0xdaryl** [comment]
Yes (please), because 2020 is when you are introducing them to the public repo.

**Comment by janvrany** [comment]
Okay, no problem. I just pushed an updated version, hope it's all right. If there's anything left, let me know. Thanks!

**Pull request merged**
