### PR TITLE
AArch64: Use madd and msub instructions when applicable

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds code generation for madd and msub instructions to
iadd/ladd/isub/lsubEvaluators.
It also removes an unused function addOrSubInteger() from
BinaryEvaluator.cpp.

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
I can't help but wondering whether the checks for whether to do the fused multiply add/sub would be better done in `generateMaddOrMsub` as it would clean up a lot of redundant code (and save some code space).  I think you would have to additionally pass in the multiply IL opcode you're pattern matching for, and you'd have to have `generateMaddOrMsub` return NULL if it didn't do a transformation.

Of course, the drawback of this is that you'd always do the call to `generateMaddOrMsub` whether the pattern is matched or not (it probably isn't that frequent relative to a normal add/sub).  However, if you exit early it may not be too bad.  The cleanliness of the code and the size reduction might trump any small compile-time overhead by always doing the call.  What do you think?

**Comment by knn-k** [comment]
Updated the code moving the common code into `generateMaddOrMsub()`.

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Pull request merged**
