### PR TITLE
RISC-V: implement copyParametersToHomeLocation()

### PR DESCRIPTION
**Pull request by janvrany**
This code is basically a copy from AArch64.

### CODE REVIEW

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
> continuous-integration/eclipse-omr/pr/linux_riscv64_cross Pending — Build started for merge commit.

🎉

**Comment by 0xdaryl** [comment]
Jenkins build linux_riscv64_cross

**Comment by janvrany** [comment]
Polite ping. 
Is there anything to be improved before this can get merged?

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
