### PR TITLE
CMake DDR: fix bug where cmake was re-run unnecessarily

### PR DESCRIPTION
**Pull request by dnakamura**
Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by charliegracie** [comment]
@dnakamura can you explain quickly what the fix is?

**Comment by dnakamura** [comment]
To handle ddrgen we generate a new `CMakeLists.txt`, however, due to limitation in cmake this is generated at the end of the configure stage. This means we need to run `cmake` on the newly generated project as part of the build. In order to ensure that we only ran cmake once we have a `config.stamp` depend (ie running ddrgen depends on `config.stamp`, and the rule to run cmake  lists `config.stamp` as an output). However due to an oversight on my part, we never actually create the `config.stamp` file, meaning every time we go to run ddrgen, we re-run cmake on the generated file

**Comment by dnakamura** [comment]
Also fixed in this PR: Apparently before I forgot to actually add the command which runs ddrgen, ie `COMMAND ${CMAKE_COMMAND} --build "${DDR_BIN_DIR}"`

**Pull request merged**
