### PR TITLE
Disable Integer modulo instruction on Power

### PR DESCRIPTION
**Pull request by bhavanisn**
Disabling the modulo instructions due to the performance issues.

Signed-off by: bhavani.sn@ibm.com

### CODE REVIEW

**Review by ymanton — COMMENTED** [review]
Change looks fine. Can we perhaps use an `#ifdef` to guard the code? That way all one has to do is rebuild if they want to test it in the future.

**Comment by ymanton** [comment]
Also lets add some details about why the instruction is being disabled (which CPUs and inputs are slow, etc) in the commit message.

**Comment by ymanton** [comment]
Jenkins test sanity.functional plinux,aix jdk8,jdk17

**Review by ymanton — CHANGES_REQUESTED** [review]
Sorry, I did not realize that this code is in OMR. The `J9_ENABLE_INTMODULO` define is not really appropriate for OMR; can you change it to `OMR_ENABLE_POWER_INTMODULO` or similar?

**Review by ymanton — APPROVED** [review]
LGTM.

**Comment by dsouzai** [comment]
jenkins build plinux,aix

**Review by dsouzai — APPROVED** [review]

**Pull request merged**
