### PR TITLE
Add setter for TR::Options::_bigCalleeScorchingOptThreshold

### PR DESCRIPTION
**Pull request by 0xdaryl**
Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins build all

**Comment by 0xdaryl** [comment]
@vijaysun-omr : please review

**Review by vijaysun-omr — APPROVED** [review]

**Comment by vijaysun-omr** [comment]
Jenkins build aix

**Comment by vijaysun-omr** [comment]
Jenkins build aix

**Review by vijaysun-omr — APPROVED** [review]

**Comment by vijaysun-omr** [comment]
This is a very simple change to just add a setter. There appears to be an infrastructural issue with AIX for the past couple of days that prevents builds from running there.. I am merging this change based on the trivial nature and the fact that Power Linux testing did in fact pass.

**Review by vijaysun-omr — APPROVED** [review]

**Pull request merged**
