### PR TITLE
Remove helper symbols for String.compress() and some other methods

### PR DESCRIPTION
**Pull request by knn-k**
This commit removes the following helper symbols for p and x platforms:

- compressString
- compressStringNoCheck
- compressStringJ
- compressStringNoCheckJ
- andORString

### CODE REVIEW

**Comment by knn-k** [comment]
Jenkins build aix,plinux

**Comment by knn-k** [comment]
Related PR in OpenJ9: https://github.com/eclipse-openj9/openj9/pull/20280

**Comment by knn-k** [comment]
https://github.com/eclipse-openj9/openj9/pull/20280 needs to be merged first.  There is no need for coordinated merge.

**Comment by knn-k** [comment]
FYI.  @hzongaro

**Review by hzongaro — APPROVED** [review]
Looks good.  Thanks!

**Comment by hzongaro** [comment]
Jenkins build all

**Pull request merged**
