### PR TITLE
Make double map true as default option 

### PR DESCRIPTION
**Pull request by bragaigor**
For more information: https://github.com/eclipse/openj9/pull/5318

Related to issue: https://github.com/eclipse/openj9/issues/8349

Signed-off-by: Igor Braga <higorb1@gmail.com>

### CODE REVIEW

**Comment by bragaigor** [comment]
@genie-omr build all

**Comment by youngar** [comment]
cc @amicic @dmitripivkine

**Comment by amicic** [comment]
@rwy0717 or @youngar 
Please, revert this change. It's causing intermittent failures in OpenJ9 testing, which we don't think we'll be able to solve quickly.

**Comment by rwy0717** [comment]
Done.

**Pull request merged**
