### PR TITLE
Add option to enable Code Cache disclaiming

### PR DESCRIPTION
**Pull request by gita-omr**

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Should "cold" be in the option name if this is specific to **cold** code cache disclaiming?  i.e., `enableColdCodeCacheDisclaiming`

**Comment by 0xdaryl** [comment]
>  I deliberately made it more general in case we want to experiment and disclaim warm code as well.

OK, but I'm worried we won't remember to update the option description in the future if and when that happens.  If that's your plan, can you drop "cold" from the option description text then?

**Comment by gita-omr** [comment]
Removed "cold" from option description.

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Only change since CI last ran was to the contents of a C string.  Re-running CI is not necessary.

**Pull request merged**
