### PR TITLE
Add tests for fcmp??u / dcmp??u

### PR DESCRIPTION
**Pull request by janvrany**

### CODE REVIEW

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by janvrany** [comment]
Hmm...looks like XLC does not have `std::isnan()`. Shall we resort to `<math.h>`'s `isnan()`?

**Comment by fjeremic** [comment]
> Shall we resort to `<math.h>`'s `isnan()`?

Yeah we need to do this unfortunately.

**Comment by aviansie-ben** [comment]
There's already a hack for this exact problem in [ArithmeticTest.cpp](https://github.com/eclipse/omr/blob/e93965e40837b28f43d71f7667bd5584e5362087/fvtest/compilertriltest/ArithmeticTest.cpp#L28-L33) that you should be able to copy to fix this.

**Comment by janvrany** [comment]
Thanks, @aviansie-ben ! 
I need `std::isnan()` in PR #5121 so I fixed it there first and will postpone this PR until PR #5121 is (ideally) merged.

**Comment by janvrany** [comment]
@fjeremic : Another chapter in floating-point story. May I kindly ask you to poke genie again to see what fails now?

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@genie-omr whitelist janvrany

**Comment by janvrany** [comment]
@genie-omr build all

**Comment by janvrany** [comment]
@genie-omr build all

**Comment by janvrany** [comment]
Okay, all checks have passed. Is there anything to improve?

**Pull request merged**
