### PR TITLE
Move SwitchAnalyzer from OpenJ9 to OMR

### PR DESCRIPTION
**Pull request by charliegracie**
Recent testing using JB Switch did not show the performance I was
expecting. Moving the SwitchAnalyzer from OpenJ9 to OMR provides
a 25-30% improvement to my testing.

Signed-off-by: Charlie Gracie <charlie.gracie@gmail.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
@0xdaryl this PR likely needs changes to ensure it happens correctly.  This was the simple change that got my performance improvement.

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by vijaysun-omr** [comment]
@andrewcraik a quick review please since this is in the optimizer.

**Comment by andrewcraik** [comment]
An init of the optimization in the OMROptimizer.cpp would be standard for an optimization living at the OMR level. Normally you would need the opt enum to move as well but the enum seems to already be in OMR for whatever reason. Otherwise seems like a standard move of code upwards.

Moving this code up may require changes in OpenJ9 to keep things compatible.

**Comment by charliegracie** [comment]
I believe I updated all of @andrewcraik comments. I will try to check out whether or not downstream projects need a change.  I do not think any down stream projects use CMake for their builds so they will not use the new copy of SwitchAnalyzer. I believe the OpenJ9 project does do a single build that builds using CMake so I may just have to add this file to it's blacklist.

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by andrewcraik** [comment]
Rather than black listing the OMR version wouldn't it be more correct to switch it to consume the OMR version? I guess you mean you will blacklist, then this will go in and then you will do the switch?

**Comment by charliegracie** [comment]
That is what I was thinking so that the changes could flow independently.

**Pull request merged**
