### PR TITLE
Move platform code to platform files

### PR DESCRIPTION
**Pull request by mgaudet**
Extract Windows and z/OS platform code to their respective platform files.

### CODE REVIEW

**Comment by charliegracie** [comment]
@rwy0717 and @dnakamura any comments?

**Comment by rwy0717** [comment]
I think the windows configuration code needs to be better split between os/win and toolcfg/msvc. A lot of the flag configuration is msvc only.

I like the introduction of the macro for importing os config. It's another step forward.

**Comment by mgaudet** [comment]
Moved the windows setup code to the MSVC file. Altered the macro system a touch.

**Comment by rwy0717** [comment]
LGTM

**Pull request merged**
