### PR TITLE
Centralize opcode enum - allow downstream extensions

### PR DESCRIPTION
**Pull request by fjeremic**
This PR is an extension of #4915. It make several modifications which allows downstream projects to hook into the centralized opcode enum defined in OMR via the extensible enums concept. This PR allows downstream project to seamlessly generate the various tables which eliminates cross-project dependencies.

Please see individual commits for explanations of what was done. There will be follow-on work following this to further eliminate some `J9_PROJECT_SPECIFIC` guarded code which needs to be properly extended. This is all but a first step in the direction of hopefully eliminating breakages in downstream projects by changes within OMR.

Issue: #4519

This PR needs to be merged concurrently with eclipse/openj9#11169.

### CODE REVIEW

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@oneturkmen FYI in case you'd like to review, since you contributed the original change.

**Comment by oneturkmen** [comment]
LGTM!

**Comment by fjeremic** [comment]
@Leonardo2718 any comments on these changes?

**Review by Leonardo2718 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
