### PR TITLE
Rename OMR::Z::Machine::getS390RealRegister()

### PR DESCRIPTION
**Pull request by samolisov**
Rename the `OMR::Z::Machine::getS390RealRegister()` method to
`OMR::Z::Machine::getRealRegister()` in order to get the strength
of polymorphism.

P.S. The method `geS390RealRegister()` is still remaining for backward compatibility.

Issue: #2645

### CODE REVIEW

**Comment by fjeremic** [comment]
@samolisov thanks! This one slipped my radar as it was marked WIP when I assigned to myself. Unfortunately GitHub doesn't give me notifications when PRs are renamed so to avoid waiting so long in the future please feel free to @ me in a comment to get my attention if something goes from WIP to ready. Thanks again for your contribution!

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by samolisov** [comment]
@fjeremic thank you very much for the comment. I agree to @ the committer/assignee is a good idea. I see the builds are passed, so when the commits are merged, I'll be able to consolidate register iterators.

**Comment by fjeremic** [comment]
> @fjeremic thank you very much for the comment. I agree to @ the committer/assignee is a good idea. I see the builds are passed, so when the commits are merged, I'll be able to consolidate register iterators.

All done! Thanks again. I'll take care of the OpenJ9 dependency meanwhile and we can even fold the existing APIs then.

**Pull request merged**
