### PR TITLE
Improve dwarfdump attribute value parsing

### PR DESCRIPTION
**Pull request by keithc-ca**
Recognize and handle simple expressions by skipping `"DW_OP_plus_uconst"` when present for field offsets.

Verify that attribute values are reasonable; insist that at least some (normally all) of the string is consumed.

Ignore attributes where the value begins with `'<'`, e.g.
```
  DW_AT_const_value (<0x04> 00 00 80 3f )
```
These have been seen in relation to inlined functions and provide the value of a formal parameter given at the call site: we don't need that information.

### CODE REVIEW

**Comment by 0xdaryl** [comment]
I suspect the x86-64 macOS test failures are not related to this PR.  Do you agree @keithc-ca ?

https://dev.azure.com/eclipse-omr/ea4519db-b27e-4d19-a971-f01491f803e3/_apis/build/builds/5673/logs/43

**Comment by keithc-ca** [comment]
I agree that those failures are unrelated to this change. The modified file is not involved in those tests.

**Comment by keithc-ca** [comment]
In https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_x86-64_mac_Personal_testList_0/122 we can see that with this change, the test failure noted in https://github.com/eclipse-openj9/openj9/issues/15104 has been remedied:
```
11:28:03  cmdLineTester_callsitedbgddrext_openj9_0_PASSED
```

**Comment by 0xdaryl** [comment]
Jenkins build all

**Pull request merged**
