### PR TITLE
Issue #87 ddrgen tool initial contribution

### PR DESCRIPTION
**Pull request by jason-hall**
Signed-off-by: Jason Hall <jasonhal@ca.ibm.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
Do all of the new files end with an empty line where appropriate?  Not sure if the diff tool is not displaying the new line.

As this is a large contribution I will need to open an Eclipse CQ to accept this.  Can you provide a zip file with all of the files modified / added?  You can upload the zip to box.com or something similar and provide the link.  Thanks

**Comment by jason-hall** [comment]
Yes.

https://ibm.box.com/s/iukl6me7dgq34bvvc573ktqui7b14be9

**Comment by charliegracie** [comment]
Eclipse IP CQ created here:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11620

Once the initial scan has been completed and we get the go ahead to commit I will accept the merge request

**Comment by charliegracie** [comment]
There are some binary files and .out files that I am not sure should be checked in.  Can you verify that they all need to be there and provide an explanation?  The binary files will really bloat the repo

**Comment by jason-hall** [comment]
I removed the libraries which were accidentally checked in. The 6kb "superset.out" file is the expected output for the tests. The other file listed as binary is the documentation diagram.

**Comment by charliegracie** [comment]
the superset.out is actually a text file right?  Can we switch it to be listed as a text file so that if there are changes in the future it doesn't require a full copy of the file but just the changed text?

**Comment by jason-hall** [comment]
It looks like it is listed as a text file.

**Pull request merged**
