### PR TITLE
Downgrade to VS 10 as this is our minimum supported version

### PR DESCRIPTION
**Pull request by charliegracie**
Signed-off-by: Charlie Gracie <charlie.gracie@gmail.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Any background on why this is needed would be helpful.

**Comment by charliegracie** [comment]
It is the current minimum VS level we support.  The project constantly gets Issues about breaking this old version of the compiler so we should be testing it.  *If* we could remove this as a supported version I would be happy to use a newer version as our standard compiler.

**Comment by charliegracie** [comment]
I am going to open an Issue to have documentation written describing the minimum compiler levels we support on each platform.  It will also discuss what versions we test in our CI builds.

**Comment by charliegracie** [comment]
Closing as there are some compiler issues with how we do CMake builds on windows that I need to investigate.  I will re-open once I have a working solution.

**Pull request closed without merging**
