### PR TITLE
Add NaN and infinity cases to floating point opcode tests

### PR DESCRIPTION
**Pull request by janvrany**

### CODE REVIEW

**Comment by janvrany** [comment]
FYI: @Leonardo2718 , @jdmpapin

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by janvrany** [comment]
New version should fix compilation failures using XLC on Z and AIX/PPC (I hope)

I have also reworked how one asserts that result is `NaN`, instead of handling it in each test, 
new version provides specialized comparators to GTest that handles `NaN == NaN` as true
(in `ASSERT_EQ()` and `EXPECT_EQ()`). 

What remains is whether `dmax 1.0 NaN` is `1.0` or `NaN`. Linux / PPC returns `NaN` whereas Z returns `1.0`. 

@fjeremic May I kindly ask you to poke genie to rebuild?

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by janvrany** [comment]
Changes in 4b1665f:

1. Move definition if `std::isnan()` on Z and AIX from `ArithmeticTest.cpp` to `JitTest.hpp` (as suggested by @aviansie-ben in PR #5123)
2. Fix and improve GTest comparators for floating point types (see commit 6fbf16f)
3. Simplify assertions in `ArithmeticTest.cpp`, taking advantage of `ASSERT_EQ()` / `EXPECT_EQ()` handling `NaN` cases (see commit b99e625)

@fjeremic May I kindly ask you to poke genie to rebuild again? I'm sorry, I'll probably need few more iterations :-(

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by janvrany** [comment]
Looking at latest test failures:
1. Linux/PPC64 fails because (for example) `dcmpne nan 95` returns `1` whereas it should return `0` 
(at least that's what we concluded with @jdmpapin and what Linux/x86_64 returns). Therefore I consider it a bug in POWER codegen, file in an issue and `SKIP_IF(power & isnan(exp))`

2. Linux/390 fails because of `?min` / `?max`. What these should return is not clear to me. Any idea, @jdmpapin?

3. AIX/PPC64 and ZOS fails at runtime with:
    ```
    20:40:31  26: Assertion failed: FloatingPoint == _type, file: /openzdk/jenkins/workspace/Build/fvtest/tril/tril/ast.hpp, line: 114
   20:40:31  26: CEE5207E The signal SIGABRT was received.
   20:40:31  26/26 Test #26: comptest ..........................***Exception: Other 16.86 sec
   ```
   I don't have idea what's wrong but I guess commit e380990 is the culprit (that commit is a horrible  hack, I agree). Interestingly, on GCC it seem to work. Any idea @Leonardo2718 ?

**Comment by jdmpapin** [comment]
> 2\. Linux/390 fails because of `?min` / `?max`. What these should return is not clear to me. Any idea, @jdmpapin?

Unfortunately I'm not very familiar with `[fd]max`/`[fd]min`, and from a quick look I haven't been able to spot any code that generates those operations, so I don't know what the expected behaviour is w.r.t. NaN

**Comment by fjeremic** [comment]
> 2\. Linux/390 fails because of `?min` / `?max`. What these should return is not clear to me. Any idea, @jdmpapin?

The `fmax` evaluator on Z uses the `CEBR` instruction to perform the comparison. According the the _Principles of Operation_ documentation for that instruction it says the following:

> If either or both operands are QNaNs and neither
operand is an SNaN, the comparison result is unordered,
and condition code 3 is set.

> If either or both operands are SNaNs, an IEEE invalid-
operation exception is recognized. If the IEEE
invalid-operation mask bit is one, a program interruption
for a data exception with DXC 80 hex (IEEE
invalid operation) occurs. If the IEEE-invalid-operation
mask bit is zero, the IEEE-invalid-operation flag
bit is set to one, and instruction execution is completed
by setting condition code 3.

> Resulting Condition Code:
> 0 Operands equal
> 1 First operand low
> 2 First operand high
> 3 Operands unordered

We generate a branch on high, so we look for condition code 2. We don't seem to consider condition code 3 at all at the moment. It seems this may be a bug on the Z evaluator. Do we have expectations on the result of comparisons with QNaNs? It sounds like we may need to check condition code 3 and do something special.

**Comment by janvrany** [comment]
> Do we have expectations on the result of comparisons with QNaNs?
Yes, this is exactly what I'm asking, What `[fd]max` / `[fd]min` suppose to return if at least one operand is `NaN`?

**Comment by fjeremic** [comment]
> Yes, this is exactly what I'm asking, What `[fd]max` / `[fd]min` suppose to return if at least one operand is `NaN`?

Given the heritige of OMR math evaluators being modeled after Java, I would suppose those evaluators should return NaN if either operand is NaN according to [1].

[1] https://docs.oracle.com/javase/8/docs/api/java/lang/Math.html#max-float-float-

**Comment by aviansie-ben** [comment]
I took a quick look at the failure on AIX and I think I found the problem... It seems that under AIX, the Tril code for the failing test ends up being:

```
(method return=Int32
  (block
    (ireturn
      (fcmpeq
        (fconst 0.000000)
        (fconst INF)))))
```

On other systems, the `snprintf` call to generate the Tril code will output `inf` instead, which is handled correctly. I assume z/OS probably has the same problem.

**Comment by janvrany** [comment]
Changes in 703d74d:
1. Skipped tests if POWER && `(if)[fd]cmpne` && NaN (see 703d74d)
2. Handle `NaN` in `[fd]min` / `[fd]max` test oracles - if any operand is `NaN`, result should be `NaN`
3. Also handle uppercase `INF` and `NAN` in TRIL parser - thanks! @aviansie-ben 

@fjeremic: May I kindly ask you to poke genie to rebuild again?

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@janvrany still some failures. On the Z ones we'll need to disable comparing against NaN due to https://github.com/eclipse/omr/pull/5121#issuecomment-621318470. Can you do that and open up a backing issue referencing that comment. I'll get someone to fix the evaluators on Z and re-enable the tests.

Not sure why Power is failing again or if these are the same issues as before.

**Comment by aviansie-ben** [comment]
I've looked into the Power failures again. The PPC64LE failure is caused by a failure to check for all Power architectures. You need to be checking for `OMRPORT_ARCH_PPC64` and `OMRPORT_ARCH_PPC64LE` in addition to the existing check. However, I'd strongly recommend using the `SKIP_ON_PPC`, `SKIP_ON_PPC64`, and `SKIP_ON_PPC64LE` macros under an if statement that checks the operands for NaN instead. Maybe we should consider adding more generic macros to skip all variants of each architecture, such as `SKIP_ON_P`, to make these kinds of mistakes less likely?

It looks like the AIX failure is caused by NaN values being printed as `NaNQ`. I have no idea why AIX does this, since it's clearly in violation of the C99 standard, but that's what seems to be happening. This time I went through and double-checked and it seems like that's the only other strange format specifier behaviour I'm getting on the AIX system I'm running this on. This does underscore a need for a way to generate Tril code programmatically without having to rely on ad-hoc use of `snprintf`, which clearly has strange behaviour on certain platforms in corner cases.

**Comment by janvrany** [comment]
> ... `SKIP_ON_PPC`, `SKIP_ON_PPC64`, and `SKIP_ON_PPC64LE` macros under an if statement that checks the operands for NaN instead. Maybe we should consider adding more generic macros to skip all variants of each architecture, such as `SKIP_ON_P`, to make these kinds of mistakes less likely?

Ah, I see. I agree, I'll introduce `SKIP_ON_POWER()` and use that in inside an `if` as you suggested. 

> It looks like the AIX failure is caused by NaN values being printed as `NaNQ`. I have no idea why AIX does this, since it's clearly in violation of the C99 standard, but that's what seems to be happening. 

Thanks! I'll try to add `NaNQ` to list of NaNs and see whether it works. 

> This does underscore a need for a way to generate Tril code programmatically without having to rely on ad-hoc use of `snprintf`, which clearly has strange behaviour on certain platforms in corner cases.

I agree, however this seem like a big task in itself. Maybe we can get away using our own `snprintf()` implementation? Anyways, I'll leave this to another PR / issue.

**Comment by janvrany** [comment]
Changes in 74ed644:
* Use `SKIP_ON_POWER()` inside an `if` statement to skip tests on POWER  - 86fd132  , e22662d , dc68643 
* Skip `[fd]min` / `[fd]max` tests on Z  - 74ed644
* Handle `NaNQ` - 0c3ce41 

@fjeremic: May I kindly ask you to poke genie to rebuild again?

**Comment by andrewcraik** [comment]
@genie-omr build all

**Comment by janvrany** [comment]
zOS is still failing. I suspect this is due to non-standard `nan` formatting, like on AIX. 
@fjeremic : May I kindly ask you to compile and run attached [snprintf-nan.cpp.txt](https://github.com/eclipse/omr/files/4595738/snprintf-nan.cpp.txt) on zOS and paste me the output? I don't have access to such (interesting) machine.

**Comment by fjeremic** [comment]
@janvrany apologies for the delay. I had to make slight changes to your test to make it work. I had to add the `using ::snprintf` prick we do in the Google test header. To remain as close to what we do on the build system I built OMR, made a whitespace change in MinMaxTest.cpp and compiled again with `make -j1 --trace` to get the exact commandline used to build that file. I then just modified the commandline to point it to your unit test. Here is the final command and the output:

```
:/tmp/fjeremic>/sysroot/bin/xlc -D_ALL_SOURCE -D_ISOC99_SOURCE -D_LONG_LONG -D_OPEN_THREADS=2 -D_POSIX_SOURCE -D_XOPEN_SOURCE_EXTENDED -DBITVECTOR_BIT_NUMBERING_MSB -DBITVECTOR_64BIT -DJITTEST -DJ9ZOS390 -DJ9ZOS39064 -DLONGLONG -DOMR_EBCDIC -DPROD_WITH_ASSUMES -DSUPPORTS_THREAD_LOCAL -DTEST_PROJECT_SPECIFIC -DTR_HOST_S390 -DTR_HOST_64BIT -DTR_TARGET_S390 -DTR_TARGET_64BIT -DZOS -I/tmp/fjeremic/omr/util/a2e/headers -I/usr/lpp/cbclib/include -I/tmp/fjeremic/omr/fvtest/omrGtestGlue/. -I/tmp/fjeremic/omr/third_party/gtest-1.8.0/include -I/tmp/fjeremic/omr/include_core -I/tmp/fjeremic/omr/build -I/tmp/fjeremic/omr/fvtest/compilertest/z -I/tmp/fjeremic/omr/fvtest/compilertest -I/tmp/fjeremic/omr/compiler/z -I/tmp/fjeremic/omr/compiler -I/tmp/fjeremic/omr -I/tmp/fjeremic/omr/fvtest -I/tmp/fjeremic/omr/build/fvtest/tril/tril -I/tmp/fjeremic/omr/fvtest/tril/tril -I/include_core  "-Wc,xplink" "-Wc,rostring" "-Wc,FLOAT(IEEE,FOLD,AFP)" "-Wc,enum(4)" "-Wa,goff" "-Wc,NOANSIALIAS" "-Wc,TARGET(zOSV1R13)" -Wc,lp64 "-Wa,SYSPARM(BIT64)" -+ "-Wc,ARCH(7)" "-Wc,TUNE(10)" "-Wc,langlvl(extended)" -qlanglvl=extended0x   -DGTEST_ENV_HAS_STD_TUPLE_ -D__IBMCPP_TR1__ -DYYLMAX=1000 -Wa,asa -Wc,EXH -qhaltonmsg=CCN6102 -qnocsect -o snprintf-nan snprintf-nan.cpp
"./snprintf-nan.cpp", line 1.1: CCN5857 (W) The macro name "_LONG_LONG" is reserved but the directive is processed.
:/tmp/fjeremic>chmod 755 snprintf-nan
:/tmp/fjeremic>./snprintf-nan
(method return=Int32 (block (ireturn (dcmpeq (dconst NaNQ(1)) (dconst -NaNQ(1))))))
(method return=Int32 (block (ireturn (fcmpeq (fconst NaNQ(1)) (fconst -NaNQ(1))))))
```

It is definitely printing something unwanted I would think.

**Comment by janvrany** [comment]
@fjeremic No problem, I'm also busy.
Thanks for the changes. And yes, `-NaNQ(1)` is the problem. I guess this is where TRIL parse chokes and raises some exception, which is what we see in test output. 

How to fix it is another story. Since it contains parenthesis, fix / workaround is not so straightforward. As @aviansie-ben pointed out, the proper thing to do is to not rely on `snprintf()`. This is big enough to require more discussion and certainly deserve its own Issue / PR. 

So, for now I'm tempted to `SKIP_IF()` all tests with `NaN` values on Z. Would that be okay with you? Any other idea?

**Comment by fjeremic** [comment]
> So, for now I'm tempted to `SKIP_IF()` all tests with `NaN` values on Z. Would that be okay with you? Any other idea?

I'm ok with that, except can we only skip them on z/OS, since that is the platform causing the issue. Things seem to work fine on Linux on Z where we use gcc.

**Comment by janvrany** [comment]
This is what I meant. I'll do it.

**Comment by janvrany** [comment]
Changes in 816b3d7:
* Skip all tests with NaN values on zOS. 

@fjeremic May I kindly ask you to poke genie to rebuild again?

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
The PR is a few weeks old already but just in case I'll wait until tomorrow to merge just to give others a chance to review if they wish to do so. Otherwise the change looks fine to me. Thanks for this @janvrany!

**Pull request merged**
