### PR TITLE
Revert "Replace sprintf() with snprintf()"

### PR DESCRIPTION
**Pull request by knn-k**
Reverts eclipse/omr#6862

### CODE REVIEW

**Review by 0xdaryl — APPROVED** [review]

**Comment by keithc-ca** [comment]
Can I request that the merged branch be deleted? Thanks.

**Comment by knn-k** [comment]
I deleted the branch.
I haven't realized that the "Revert" button in PRs makes a branch in https://github.com/eclipse/omr/branches .
I won't use the "Revert" button when I need to revert a commit next time.

**Comment by pshipton** [comment]
There is nothing wrong with using the revert button. But then the person who created the PR should use the delete branch button after the PR is merged.

**Comment by pshipton** [comment]
I think the committer who merged the PR can also do it.

**Pull request merged**
