### PR TITLE
CMake: Work around XLC compiler error on z/OS

### PR DESCRIPTION
**Pull request by dnakamura**
Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by dnakamura** [comment]
Jenkins build all

**Comment by 0xdaryl** [comment]
For these kinds of fixes, it would be extremely useful to document more details on what the problem you are working around is. The reason is that these kinds of workarounds tend to stay in the code long after the toolchain bug has actually been fixed.  When the workaround is discovered 5 or 10 years down the road no one remembers what the problem was and what compiler version was affected.  At the very least, please document this information in a separate issue that we will tag "toolchain bug".  Thanks.

**Comment by 0xdaryl** [comment]
Sorry, I take that back (partially):  is this a compiler bug, or a difference in the toolchains where xlC reports something as an error when other compilers don't?

**Comment by dnakamura** [comment]
This is a compiler bug. When generating minimal debug info with optimizations enabled results in a compiler crash.

**Comment by 0xdaryl** [comment]
OK, thanks.  Then my request above still applies.

**Comment by dnakamura** [comment]
@0xdaryl  comment is updated

**Comment by dnakamura** [comment]
@fjeremic  can you take a look at this?

**Comment by 0xdaryl** [comment]
The buggy compiler version would also be useful too.

**Comment by dnakamura** [comment]
Closing as I can't seem to reproduce the issue anymore.

**Pull request closed without merging**
