### PR TITLE
WIP: Add enhanced-ascii option on z/OS

### PR DESCRIPTION
**Pull request by dnakamura**
Replace usage of a2e library with the compiler ehananced ascii support.
This is gated globably with the --enable-enhanced-ascii configure option,
and enabled on a target level with TARGET_ENHANCED_ASCII makefile varaible

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by dnakamura** [comment]
Note: should compile and work as-is. However, if auto file-tagging is enabled, tracegen/tracemerge will output in ascii rather than ebcidic.

**Comment by keithc-ca** [comment]
Do you plan to also address ddrgen and related tools?

**Comment by dnakamura** [comment]
I can take a look at them, but its probably an issue for another PR

**Comment by keithc-ca** [comment]
> I can take a look at them, but its probably an issue for another PR
Not if this change breaks those tools.

**Comment by dnakamura** [comment]
it will not. 
>and enabled on a target level with TARGET_ENHANCED_ASCII makefile varaible
if you dont set the `TARGET_ENHANCED_ASCII` variables in the target-specific makefiles, everything continues to behave as before

**Comment by youngar** [comment]
@dnakamura I believe that this was completed under a different PR

**Comment by charliegracie** [comment]
Closing as this was completed under another PR. If this is incorrect please re-open @dnakamura

**Pull request closed without merging**
