### PR TITLE
Eliminate and fold disableCommoningOfVolatiles

### PR DESCRIPTION
**Pull request by gpadasal**
Eliminate and fold disableCommoningOfVolatiles query that only returns false.

### CODE REVIEW

**Comment by andrewcraik** [comment]
@gpadasal thank you for your contribution to the project, The title of your pull request is misleading - your change is to remove constant code and not change any of the volatile commoning behaviour of the compiler. You should also provide a description in the Pull Request message to explain the overall affect of the change. You may find the [CONTRIBUTING.md](https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md) file in the root of the project helpful in crafting descriptive pull request and commit messages to make reviewing easier. The overall affect of the change looks reasonable based on the issues you referenced.

**Comment by vijaysun-omr** [comment]
@gpadasal could you please respond to @andrewcraik's comment ?

**Comment by vijaysun-omr** [comment]
@gpadasal could you please rebase ?

**Comment by gpadasal** [comment]
@vijaysun-omr , rebase done .  The checks are triggered again .

**Comment by vijaysun-omr** [comment]
Thanks @gpadasal. Merging.

**Pull request merged**
