### PR TITLE
Add initial support for metal c files

### PR DESCRIPTION
**Pull request by rwy0717**
Signed-off-by: Robert Young <rwy0717@gmail.com>

### CODE REVIEW

**Comment by rwy0717** [comment]
@genie-omr build zos xlinux

**Comment by rwy0717** [comment]
@genie-omr build zos

**Comment by rwy0717** [comment]
@genie-omr build zos

**Comment by youngar** [comment]
@genie-omr build zos

**Comment by rwy0717** [comment]
@genie-omr build zos

**Comment by rwy0717** [comment]
@genie-omr build zos

**Comment by rwy0717** [comment]
@genie-omr build zos

**Comment by rwy0717** [comment]
@genie-omr build zos

**Comment by rwy0717** [comment]
@genie-omr build zos

**Comment by rwy0717** [comment]
@genie-omr build zos

**Comment by rwy0717** [comment]
@genie-omr build zos

**Comment by fjeremic** [comment]
Should we be adding such support to CMake itself rather than to OMR? Not blocking what is being done here as we can do it via custom commands first and transition later, however compiling metal C files to me is analogies to compiling C or C++ files which I think should be handled at the CMake level.

**Comment by rwy0717** [comment]
That was the original plan, but when I started looking at it, using a command like this seemed like it would just be a lot easier. I can take another look at adding metal c as a language.

**Comment by fjeremic** [comment]
> That was the original plan, but when I started looking at it, using a command like this seemed like it would just be a lot easier. I can take another look at adding metal c as a language.

I would agree using a custom command may be a lot easier to just get us going. Perhaps we should continue down this route and add a metal C as a language as part of another task. If you agree we can open up an issue to track this.

**Comment by rwy0717** [comment]
Pushing a version that adds mc as a language.
@genie-omr build zos

**Comment by rwy0717** [comment]
@genie-omr build zos

**Comment by rwy0717** [comment]
@genie-omr build zos

**Comment by rwy0717** [comment]
infra issue: @genie-omr build zos

**Comment by rwy0717** [comment]
It's a little disappointing, but after some investigation and consideration, I've decided that custom commands are a better fit than adding a new language. It essentially boils down to the fact that the metal-c toolchain has a different set of flags for each stage in compilation, which the cmake language framework doesn't support.

**Comment by rwy0717** [comment]
@genie-omr build zos

**Comment by fjeremic** [comment]
@genie-omr build zos

**Pull request merged**
