### PR TITLE
Use addAtomic for incrementing counters of OMRMemCategory

### PR DESCRIPTION
**Pull request by Akira1Saitoh**
Use addAtomic for incrementing counters of OMRMemCategory instead of
spinning with compareAndSwapUDATA.
Similarly, use subtractAtomic for decrementing counters.

Signed-off-by: Akira Saitoh <saiaki@jp.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Can you provide an explanation justifying the need for this change?  It will help reason about behaviour changes and other side effects.

@babsingh : please review.

**Comment by babsingh** [comment]
1. `addAtomic` invokes `VM_AtomicSupport::add`

https://github.com/eclipse/omr/blob/dd1373f8fbe46759cc02c3c6386dbee9ce30ce5e/util/omrutil/AtomicFunctions.cpp#L56-L60

2. `VM_AtomicSupport::add` also spins on `lockCompareExchange`:
https://github.com/eclipse/omr/blob/dd1373f8fbe46759cc02c3c6386dbee9ce30ce5e/include_core/AtomicSupport.hpp#L576-L588

3. `compareAndSwapUDATA` invokes `VM_AtomicSupport::lockCompareExchange`:
https://github.com/eclipse/omr/blob/dd1373f8fbe46759cc02c3c6386dbee9ce30ce5e/util/omrutil/AtomicFunctions.cpp#L26-L30

4. So, the **spin loop** with `compareAndSwapUDATA` is identical to the **spin loop** in `VM_AtomicSupport::add`.
5. There should be no change from a functional and performance perspective.
6. The code looks clean and is easy to read with `addAtomic` and `subtractAtomic`.

**Comment by babsingh** [comment]
Jenkins build all

**Comment by babsingh** [comment]
The commit message should reflect @0xdaryl's feedback: https://github.com/eclipse/omr/pull/6035#issuecomment-850418810. The code looks good to me.

**Comment by Akira1Saitoh** [comment]
Thank you for reviewing @babsingh, the intention of this change is to make omrmemcategories.c to use existing implementation of atomic add/subtract and make it possible to optimize atomic add/subtract in a single file (AtomicSupport.hpp).
Actually, `compareAndSwapUDATA` called from `omrmem_categories_increment_counters` (and similar functions to increment/decrement shared counter) seems to be a bottleneck for some benchmarks in OpenJ9 on AArch64.

I force-pushed the commit with additional commit message.

**Comment by babsingh** [comment]
Jenkins build all

**Review by babsingh — APPROVED** [review]
LGTM. The code has not changed. The commit message has been updated. Rerunning builds for final verification.

**Comment by 0xdaryl** [comment]
Jenkins build aarch64

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
