### PR TITLE
Constrain VFT of ClassObject to be java/lang/Class

### PR DESCRIPTION
**Pull request by jdmpapin**
It was already so constrained in cases where the class represented by
the ClassObject is known exactly, but the represented class is
irrelevant here. Now (isClassObject() == TR_yes) takes precedence over
isFixedClass() so a location of {JavaLangClassObject} is sufficient to
cause VP to create the constraint.

### CODE REVIEW

**Comment by Leonardo2718** [comment]
@genie-omr build all

**Comment by andrewcraik** [comment]
@Leonardo2718 looks like something is up with the test builds - lots are still pending...

**Comment by Leonardo2718** [comment]
@genie-omr build all

**Comment by vijaysun-omr** [comment]
The enhancement to the type propagation logic here looks valid in the case when base object is a ClassObject. The rest of the changes are primarily rearranging the code which also look equivalent to me.

**Comment by vijaysun-omr** [comment]
Is the title accurate ? The VFT load is not a java/lang/Class and is not being constrained as such in the code.

**Comment by jdmpapin** [comment]
> Is the title accurate ? The VFT load is not a java/lang/Class and is not being constrained as such in the code. I think maybe you mean the type of a ClassObject value is being constrained to java/lang/Class ?

Right, I don't mean that the VFT is _a_ `java/lang/Class`, but rather than it is the _`J9Class` of_ `java/lang/Class` (in J9 terms). Commit titles are very cramped and in this case I don't know that I can squeeze that distinction into the space available. I don't think I'd say the title is inaccurate though: in a certain way the constraint says that the VFT is `java/lang/Class` itself.

**Pull request merged**
