### PR TITLE
Remove deprecated codegen Relocations

### PR DESCRIPTION
**Pull request by 0xdaryl**
Not used in OMR nor any downstream project:

* LoadLabelRelative16BitRelocation
* LoadLabelRelative32BitRelocation
* LoadLabelRelative64BitRelocation
* LabelTable32BitRelocation

Also removed some obviously deprecated debugging code from Relocation.hpp and unused typedefs.

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
The CI failure is #5581 and not related to this PR.

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Review by fjeremic — APPROVED** [review]

**Pull request merged**
