### PR TITLE
Add arraylet double map request field

### PR DESCRIPTION
**Pull request by bragaigor**
This update is required by eclipse/openj9#8254
Related to issue: #4703

Signed-off-by: Igor Braga <higorb1@gmail.com>

### CODE REVIEW

**Comment by bragaigor** [comment]
@genie-omr build all

**Comment by bragaigor** [comment]
@genie-omr build aarch64

**Comment by youngar** [comment]
linux_arm build failed due to a hudson exception.  relaunching.
@genie-omr build arm

**Comment by amicic** [comment]
ideally, the field should be under #ifdef for double mapping. you can update that in one of next changes.

**Pull request merged**
