### PR TITLE
Implement NULLCHKEvaluator for AArch64

### PR DESCRIPTION
**Pull request by hsoontie**
This code adds a version of NULLCHKEvaluator to AArch64.

Signed-off-by: Hillary Soontiens <hsoontie@unb.ca>

### CODE REVIEW

**Comment by hsoontie** [comment]
@0xdaryl Here is the continued implementation of NULLCHKEvaluator. This builds off of @aarongraham9's work from #4091, and follows the comments given there about how to proceed. Please take a look when you have a chance!
The `ARM64HelperCallSnippet` header file has been edited here because having no function body for the two pure virtual functions at the bottom of the class caused build errors.

**Comment by knn-k** [comment]
@hsoontie You don't need to edit `ARM64HelperCallSnippet.hpp`.  `ARM64HelperCallSnippet.cpp` in the same directory has the bodies of those functions.

**Comment by knn-k** [comment]
I guess you are building with CMake.
I found `ARM64HelperCallSnippet.cpp` was missing in `CMakeLists.txt`, and opened #4190.

**Comment by hsoontie** [comment]
@knn-k Yes, that's correct! Thanks for opening that, I will revert the changes on the .hpp file.

**Comment by aarongraham9** [comment]
Any further thoughts on this one @0xdaryl and/or @knn-k?

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Comment by 0xdaryl** [comment]
@knn-k , fyi

**Pull request merged**
