### PR TITLE
OMR codegen full support for certain evaluators

### PR DESCRIPTION
**Pull request by 0dvictor**
integerPairMulEvaluator
integerPairShlEvaluator
integerPairRolEvaluator
integerPairShrEvaluator
integerPairUshrEvaluator

For integerPairMulEvaluator, it does not handle the case
with non-constant multiplicand when TR_NoInlineLongMultiply
is set. The env var is purely for backing off to deprecated
code. Hence the path is removed.

For the shift evaluators, the whole code paths handling
non-constant shift amount are missing. Therefore, this commit
implements them.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
I haven't reviewed this in detail (yet), but in your commit message can you elaborate on what you changed to give these evaluators "full support" ?  Presumably, code on some paths were missing.  Can you try and generalize a description of those changes?

**Comment by 0dvictor** [comment]
For integerPairMulEvaluator, it does not handle the case with non-constant multiplicand when TR_NoInlineLongMultiply is set. The env var is purely for backing off to long deprecated code. Hence the path is removed.

**Comment by mgaudet** [comment]
(Pretty good summaries: Can you put all that into the commit message?)

**Comment by andrewcraik** [comment]
Discussion of the testing performed is needed for these changes.

**Comment by 0dvictor** [comment]
Both OMR testjit and J9 sanity tests passed and showed the correct instruction sequence. In addition, it passed all internal tests.

**Comment by andrewcraik** [comment]
Looks like another good change - @0xdaryl over to you - I'd appreciate a second opinion on the code as relates to 32bit since I'm less familiar with the 32bit platform and I think you know it a bit better.

**Comment by 0dvictor** [comment]
I have also enabled ShiftOrRolTest for long type as this changeset introduces support for these evaluators.

**Pull request merged**
