### PR TITLE
WIP: Remove old Jenkins pipelines

### PR DESCRIPTION
**Pull request by AdamBrousseau**
Follows #4992

Signed-off-by: Adam Brousseau <adam.brousseau88@gmail.com>

### CODE REVIEW

**Comment by janvrany** [comment]
I gave it a run and the build failed for `linux_riscv64`, see
[consoleText-Linux-riscv64.txt](https://github.com/eclipse/omr/files/4445305/consoleText-Linux-riscv64.txt). 

One issue I see with new pipeline is the choice of a workspace - it seems to me it is hardcoded to 
`$JENKINS_HOME/workspace/Build` (see https://github.com/eclipse/omr/blob/bedf978179457b97f5efefc60edd832ca5202b3b/buildenv/jenkins/omrbuild.groovy#L280).

This is problematic at least on my setup - for each merge commit I run a pipeline for linux-x86_64 and for linux-riscv64-cross. Both may run at the same tam and they (often) lrun on the same slave (my linux-x84_64 slave is the only one having RISC-V64 linux crosscompiler) so they would compete over the same directory. 
Moreover, I have several jobs that build for linux-x86_64 and linux-riscv64, one builds eclipse master, other builds each branch from my fork. Again, they would compete over the same workspace.

Finally, I understand this issue may be wrong place for comments like this, is there any better place
(given that #4992 is merged)?

**Comment by AdamBrousseau** [comment]
Yes that ws name was hardcoded because of the LIBPATH on zOS needs to include a dir in the ws. We could adjust that code so it only uses a custom ws name on zOS. We only ever use 1 executor on our nodes so that didn't cross my mind. I know Jenkins is usually smart enough to suffix an `@2` etc when the same ws name is trying to be used on the same machine. I wonder if it works in this case. Although I guess that would defeat the purpose of trying to set it to a known value.

I see why your build failed.
https://github.com/eclipse/omr/blob/master/buildenv/jenkins/omrbuild.groovy#L123
That should be `cmakeBuildDir`.  I can open a PR if you want or we can wait and see if there's further issues.

**Comment by janvrany** [comment]
> I know Jenkins is usually smart enough to suffix an `@2` etc when the same ws name is trying to be used on the same machine. I wonder if it works in this case. Although I guess that would defeat the purpose of trying to set it to a known value.

Yes, it should do it, but as you said, that defeats the purpose. 
Generally, I'd like the pipeline definition to be generic enough to be used on other CI instances than eclipse ones (like I do for RISC-V and/or for my fork). Having this workaround only on zOS will make things more straightforward. 

> 
> I see why your build failed.
> https://github.com/eclipse/omr/blob/master/buildenv/jenkins/omrbuild.groovy#L123
> That should be `cmakeBuildDir`. I can open a PR if you want or we can wait and see if there's further issues.

Yeah, I realized that later. There are more glitches through. 

I suggest: let me have a closer look, try things and I'll open a new fixup PR with changes that work for me. We can continue there. (Might take day or two, though, things are tad crazy here)

**Comment by janvrany** [comment]
I'll try to include fix for hardcoded workspace in that PR, I've got an idea.

**Comment by AdamBrousseau** [comment]
genie-omr build all

**Comment by AdamBrousseau** [comment]
genie-omr build all

**Comment by AdamBrousseau** [comment]
genie-omr build all

**Comment by AdamBrousseau** [comment]
genie-omr build riscv

**Comment by AdamBrousseau** [comment]
genie-omr build riscv

**Comment by AdamBrousseau** [comment]
genie-omr build xlinux

**Comment by AdamBrousseau** [comment]
jenkins build all

**Comment by 0xdaryl** [comment]
@AdamBrousseau : the bulk of this PR is already done.  Can this be closed?

**Pull request closed without merging**
