### PR TITLE
RISC-V: implement directCallRequiresTrampoline()

### PR DESCRIPTION
**Pull request by janvrany**

### CODE REVIEW

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by 0xdaryl** [comment]
Please see the CI build failure.

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by janvrany** [comment]
@0xdaryl Sorry, it passes now. It depended on #6499 which is now merged but I forgot to mention that.

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
