### PR TITLE
Move class CompilationController declaration to header

### PR DESCRIPTION
**Pull request by jamesgua**
update impacted cpp files accordingly

Signed-off-by: Tao Guan <james_mango@yahoo.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
This change will break downstream projects (confirmed with an OpenJ9 build).  This is due in part to the fact that OpenJ9 introduces its own "CompilationController.hpp" that replaces (not includes) the OMR version and therefore the definitions that you moved are not visible.  I'll have to look at what changes are needed from the OpenJ9 side to accommodate the change you want to make.

**Comment by 0xdaryl** [comment]
While I'm doing that, there is no reason to shorten "header" to "hdr" in the commit message and PR title.  Please change that.

**Comment by jamesgua** [comment]
Jenkins build all

**Comment by jamesgua** [comment]
Jenkins build all

**Comment by jamesgua** [comment]
As discussed this morning with Daryl, I'll close this PR and create new PRs to split class declaration from OptimizationPlan.hpp and move them into matching headers accordingly.

**Pull request closed without merging**
