### PR TITLE
Remove unused IL opcodes and cleanup

### PR DESCRIPTION
**Pull request by 0xdaryl**
See issue #5914 for the complete list of opcodes removed, and the individual commits for details.

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins build all

**Comment by fjeremic** [comment]
@0xdaryl looks like we have a valid linter failure:
```
make[1]: *** No rule to make target '../../compiler/z/codegen/TranslateEvaluator.cpp', needed by '../../compiler/z/codegen/TranslateEvaluator.cpp.linted'.  Stop.
```

We probably just need to remove these lines:
https://github.com/eclipse/omr/blob/22a4853acdef7c7851e9482ba2f0ce1f17aed708/jitbuilder/build/files/target/z.mk#L49

https://github.com/eclipse/omr/blob/22a4853acdef7c7851e9482ba2f0ce1f17aed708/fvtest/compilertest/build/files/target/z.mk#L48

**Comment by 0xdaryl** [comment]
Jenkins build all

**Comment by 0xdaryl** [comment]
> looks like we have a valid linter failure

Thanks.  Fixed in force push.

**Comment by 0xdaryl** [comment]
Jenkins build all

Re-based to pick up DDR CMake fix so that downstream testing runs successfully.

**Comment by 0xdaryl** [comment]
Un-WIPing as downstream testing has passed.

**Review by fjeremic — APPROVED** [review]

**Pull request merged**
