### PR TITLE
Print S390InterfaceCallDataSnippet correctly in trace

### PR DESCRIPTION
**Pull request by NigelYiboYu**
The debug utility class is now able to print S390InterfaceCallDataSnippet
in the right format.

Signed-off-by: Nigel Yu <yunigel@ca.ibm.com>

### CODE REVIEW

**Comment by NigelYiboYu** [comment]
Marking this WIP until fully tested.

**Comment by NigelYiboYu** [comment]
As an example, the interface call snippet now looks like this:

```
000003FFDFC532F8 000001fe                                                 Snippet Label L0035:          ; Interface call cache data snippet
     0x3ffdfc532f8 000001fe                      00 00 03 ff df c5 31 90    DC          0x00000000dfc53190  # Call site RA
     0x3ffdfc53300 00000206                      00 00 00 00 00 19 82 80    DC          0x0000000000198280  # Address of constant pool
     0x3ffdfc53308 0000020e                      00 00 00 00 00 00 00 0b    DC          0x000000000000000b  # CP index
     0x3ffdfc53310 00000216                      00 00 00 00 00 00 00 00    DC          0x0000000000000000  # Interface class
     0x3ffdfc53318 0000021e                      00 00 00 00 00 00 00 00    DC          0x0000000000000000  # Method index
     0x3ffdfc53320 00000226                      00 00 00 00 00 00 00 00    DC          0x0000000000000000  # flags
     0x3ffdfc53328 0000022e                      00 00 03 ff df c5 33 30    DC          0x00000000dfc53330  # last cached slot
     0x3ffdfc53330 00000236                      00 00 03 ff df c5 33 40    DC          0x00000000dfc53340  # first slot
     0x3ffdfc53338 0000023e                      00 00 03 ff df c5 33 70    DC          0x00000000dfc53370  # last slot
     0x3ffdfc53340 00000246                      00 00 00 00 00 00 00 00    DC          0x0000000000000000  # class pointer 0
     0x3ffdfc53348 0000024e                      00 00 00 00 00 00 00 00    DC          0x0000000000000000  # method pointer 0
     0x3ffdfc53350 00000256                      00 00 00 00 00 00 00 00    DC          0x0000000000000000  # class pointer 1
     0x3ffdfc53358 0000025e                      00 00 00 00 00 00 00 00    DC          0x0000000000000000  # method pointer 1
     0x3ffdfc53360 00000266                      00 00 00 00 00 00 00 00    DC          0x0000000000000000  # class pointer 2
     0x3ffdfc53368 0000026e                      00 00 00 00 00 00 00 00    DC          0x0000000000000000  # method pointer 2
     0x3ffdfc53370 00000276                      00 00 00 00 00 00 00 00    DC          0x0000000000000000  # class pointer 3
     0x3ffdfc53378 0000027e                      00 00 00 00 00 00 00 00    DC          0x0000000000000000  # method pointer 3
```

**Comment by fjeremic** [comment]
@genie-omr build zlinux,zos

**Comment by fjeremic** [comment]
No need to wait for AppVeyor builds since this is a Z only change.

**Pull request merged**
