### PR TITLE
Disable ResumableTraps when TR_DisableTraps option is set

### PR DESCRIPTION
**Pull request by dchopra001**
Signed-off-by: Dhruv Chopra <Dhruv.C.Chopra@ibm.com>

### CODE REVIEW

**Comment by dchopra001** [comment]
@ymanton

**Comment by ymanton** [comment]
jenkins test sanity ppc64le_linux,ppc64le_linux_xl,ppc64_aix jdk8,jdk13

**Comment by 0xdaryl** [comment]
@genie-omr build plinux,aix

**Comment by dchopra001** [comment]
@0xdaryl Done!

**Comment by 0xdaryl** [comment]
CI testing already passed on Power before minor comment change.  No need to re-run.  Merging.

**Pull request merged**
