### PR TITLE
Fix iu2l not being evaluated on z systems

### PR DESCRIPTION
**Pull request by NigelYiboYu**
iu2l was not evaluated and resulted in incorrect array indexing in
BigInteger Multiplication operations.

This is fixed by calling generic load helper if the input is unsigned; and
we skip the node evaluations only if the nodes are signed and already
sign exnended.

Signed-off-by: Nigel Yu <yunigel@ca.ibm.com>

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
Could you please elaborate on "why" the iu2l was not being evaluated ? This would allow me to review the fix with proper context.

**Comment by vijaysun-omr** [comment]
I would like @zlwang and @joransiu to review.

**Comment by joransiu** [comment]
The proposed change LGTM.   The register flag "childRegister->alreadySignExtended()" is set in iRegStoreEvaluator to signify that the value was **sign** extended.   The existing code uses that flag to determine whether to skip the genericLoadHelper which would generate the sign extension instruction.  In this case, we incorrectly skipped generation, as iu2l would require a **zero** extension instead.

**Comment by NigelYiboYu** [comment]
Added the following comment to this commit:
```
 A load (for proper type conversion) is required if the node is unsigned, not sign extended and
 not marked as unneeded conversion.

 For example, codegen can encounter the following tree:

 n4188n   (  0)  iRegStore GPR6  (Unsigned NeedsSignExt privatizedInlinerArg )
 n4109n   (  3)    l2i
 n19339n  (  1)      ==>lRegLoad (in GPR_3616) (highWordZero X>=0 cannotOverflow SeenRealReference )
  .....
 n4182n   (  0)      iu2l (in GPR_3616) (highWordZero X>=0 )
 n4109n   (  0)        ==>l2i (in GPR_3616)

 In this case, a load is needed to zero the high half of the long to corretly convert iu to l.
```

**Comment by vijaysun-omr** [comment]
Thanks for the explanation @joransiu and also for your "negatives packed" explanation @NigelYiboYu. I have never seen so many "un" and "not" used in such a small amount of text (just kidding) :-) I will merge now.

**Comment by zl-wang** [comment]
isSourceTypeSigned  is really confusing.  It is more appropriate to call it isTargetTypeSigned (i.e.  the result type is signed or unsigned).   It is a correct fix though, when you are looking for a signed result and the child register is sign-extended already.

A potential more generic fix:  TargetTypeSigned-ness == childTypeSigned-ness, and child register is extended already (be it zero or sign extended).  Leave it for the future (e.g.  something like ui2ul).

**Comment by zl-wang** [comment]
This bug happened in the situation:  you are looking for an unsigned result but the childRegister is sign-extended, and skipping the necessary action.

**Pull request merged**
