### PR TITLE
Remove deprecated element privatization from FieldPrivatizer

### PR DESCRIPTION
**Pull request by 0xdaryl**
This is a legacy optimization that has never been enabled and not
immediately useful to OMR or any known downstream projects.

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
@vijaysun-omr FYI

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
@genie-omr build zos,zlinux

**Comment by 0xdaryl** [comment]
@genie-omr build zos,zlinux

**Comment by vijaysun-omr** [comment]
Safe cleanup and checks have passed. Merging.

**Pull request merged**
