### PR TITLE
Add option for class chain validation caching

### PR DESCRIPTION
**Pull request by dsouzai**
This option is to enable an optimization related to class chain
validation in OpenJ9 (https://github.com/eclipse/openj9/pull/9403)

Signed-off-by: Irwin D'Souza <dsouzai.gh@gmail.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
@genie-omr  build all

**Comment by dsouzai** [comment]
@andrewcraik changing to WIP because I figure I might as well add another option for class chain sharing; since this PR is just adding the option bit in OMR for OpenJ9, I figure I might as well add the second option that will likely have to be added in the future anyway.

**Comment by dsouzai** [comment]
@andrewcraik good for review/merging

**Comment by andrewcraik** [comment]
@genie-omr build all

**Comment by dsouzai** [comment]
@andrewcraik could you merge if everything looks good to you?

**Pull request merged**
