### PR TITLE
Use entryPointFromCompiledMethod linkage API for recursive calls

### PR DESCRIPTION
**Pull request by 0xdaryl**
Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
The macOS failure is #5581.

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
Un-WIPing as testing is complete.

**Review by fjeremic — APPROVED** [review]

**Pull request merged**
