### PR TITLE
Fix int/long division with MIN_INT/MIN_LONG divisors

### PR DESCRIPTION
**Pull request by 0xdaryl**
The division by a constant optimization in the x86 backend does not work
for the MIN_INT/MIN_INT and MIN_LONG/MIN_LONG case.  Provide a special
sequence that does work for those boundary values.

Fixes: #4942
Fixes: #1482

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@genie-omr build xlinux,win,osx,x32linux

**Comment by 0xdaryl** [comment]
@mstoodle, would you mind reviewing please?

**Comment by mstoodle** [comment]
The change looks good, though the diff didn't present very well :( . I'll give it a try on the local branch of #4914 to verify it resolves the test failures there. Will get that result by EOD.

**Comment by 0xdaryl** [comment]
> The change looks good, though the diff didn't present very well :( 

Sorry.  Try changing to the Unified view for diffs.

**Comment by mstoodle** [comment]
Thanks @0xdaryl !

**Pull request merged**
