### PR TITLE
Add badges for Eclipse OMR CI builds

### PR DESCRIPTION
**Pull request by charliegracie**
Documentation only [ci skip]

Signed-off-by: Charlie Gracie <charlie.gracie@gmail.com>

### CODE REVIEW

**Comment by mgaudet** [comment]
Maybe prefix or suffix with the name of the build 

```
Linux 390-64 [![Linux 390-64Build Status](https://ci.eclipse.org/omr/job/Build-linux_390-64/badge/icon)](https://ci.eclipse.org/omr/job/Build-linux_390-64/)
Linux PPCLE-64 [![Linux PPCLE-64](https://ci.eclipse.org/omr/job/Build-linux_ppc-64_le_gcc/badge/icon)](https://ci.eclipse.org/omr/job/Build-linux_ppc-64_le_gcc/)
```

**Comment by charliegracie** [comment]
I did that but it looks weird because the others do not have it.  I looked at adding them for all of the badges but the list of specs for travis is really long and became ugly as well.

**Comment by mgaudet** [comment]
I find two generic "Build Passing" badges a little odd. 

[Linux 390-64Build Status](https://ci.eclipse.org/omr/job/Build-linux_390-64/)
[Linux PPCLE-64](https://ci.eclipse.org/omr/job/Build-linux_ppc-64_le_gcc/)

**Comment by charliegracie** [comment]
The image is not modifiable without updating the Jenkins plugin that provides the supprt

**Comment by mgaudet** [comment]
Maybe we need a table of builds. But that can be future work if need be.

**Comment by youngar** [comment]
I agree, it is a little weird to have identical build badges, but this is a step forward.

**Pull request merged**
