### PR TITLE
Restrict checkcast and profiled guard coalescer cold merge special case

### PR DESCRIPTION
**Pull request by jdmpapin**
...to instances where the conditional on the passing side of the guard does not evaluate any indirect loads. If the conditional does evaluate an indirect load, the transformation must be abandoned just as though an indirect load were found in an earlier tree.

The failure mode against which this PR protects is theoretical and has not been observed. It's unclear whether it's even possible to cause an indirect load to appear in such a position. Nonetheless, it's prudent to check.

Also elaborate a bit on one of the comments in the pass.

### CODE REVIEW

**Comment by jdmpapin** [comment]
@vijaysun-omr, would you mind reviewing this? It's just a small addendum to #6430

**Comment by vijaysun-omr** [comment]
jenkins build all

**Comment by vijaysun-omr** [comment]
jenkins build zos

**Comment by vijaysun-omr** [comment]
jenkins build zos

**Comment by vijaysun-omr** [comment]
jenkins build zos

**Review by vijaysun-omr — APPROVED** [review]

**Pull request merged**
