### PR TITLE
AArch64: Add support for mustNormalizeNanValues in fbits2i/dbits2l

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds support for mustNormalizeNanValues in fbits2i/dbits2l evaluators for AArch64.

Closes: #6789

Signed-off-by: KONNO Kazuhiro <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
Jenkins build aarch64,amac

**Comment by knn-k** [comment]
The NormalizeNan tests finished successfully as intended.

```
[2022-11-01T01:22:37.361Z] 28: [0;32m[----------] [m33 tests from TypeConversionTest/FloatNormalizeNan
[2022-11-01T01:22:37.361Z] 28: [0;32m[----------] [m33 tests from TypeConversionTest/FloatNormalizeNan (9 ms total)
[2022-11-01T01:22:37.361Z] 28: 
[2022-11-01T01:22:37.361Z] 28: [0;32m[----------] [m33 tests from TypeConversionTest/DoubleNormalizeNan
[2022-11-01T01:22:37.361Z] 28: [0;32m[----------] [m33 tests from TypeConversionTest/DoubleNormalizeNan (17 ms total)
```

**Comment by knn-k** [comment]
Jenkins build aarch64,amac

**Comment by knn-k** [comment]
Jenkins build amac

**Comment by knn-k** [comment]
Jenkins build amac

**Comment by knn-k** [comment]
Jenkins build amac

**Comment by knn-k** [comment]
https://ci.eclipse.org/omr/job/PullRequest-osx_aarch64/38/consoleText

```
[2022-11-02T01:55:16.111Z] 28: [0;32m[----------] [m33 tests from TypeConversionTest/FloatNormalizeNan
[2022-11-02T01:55:16.111Z] 28: [0;32m[----------] [m33 tests from TypeConversionTest/FloatNormalizeNan (8 ms total)
[2022-11-02T01:55:16.111Z] 28: 
[2022-11-02T01:55:16.111Z] 28: [0;32m[----------] [m33 tests from TypeConversionTest/DoubleNormalizeNan
[2022-11-02T01:55:16.111Z] 28: [0;32m[----------] [m33 tests from TypeConversionTest/DoubleNormalizeNan (9 ms total)
```

**Review by 0xdaryl — APPROVED** [review]

**Comment by 0xdaryl** [comment]
Remaining CI failures on macOS are expected.

**Pull request merged**
