### PR TITLE
Add method meta data sym ref alias bit vector

### PR DESCRIPTION
**Pull request by a7ehuo**
Add method meta data sym ref alias bit vector

### CODE REVIEW

**Comment by a7ehuo** [comment]
This change will be used by https://github.com/eclipse-openj9/openj9/pull/17310

**Comment by a7ehuo** [comment]
@jdmpapin May I ask you to review this change? Thanks!
@0xdaryl fyi

**Comment by a7ehuo** [comment]
`x86-64 macOS` failed with the following message. Looks to be https://github.com/eclipse/omr/issues/6968
```
46: [----------] 156 tests from VectorArithmetic/ParameterizedBinaryVectorArithmeticTest
46: Assertion failed at /Users/runner/work/1/s/compiler/x/codegen/UnaryEvaluator.cpp:55: shrEncoding != OMR::X86::Bad
46: 	vabs: No encoding method for shift opcode
46: compiling file:line:name at level: warm
...
The following tests FAILED:
	 46 - comptest (SIGTRAP)
Errors while running CTest
```

**Comment by jdmpapin** [comment]
Is it possible to keep this change to OpenJ9?

**Comment by a7ehuo** [comment]
>Is it possible to keep this change to OpenJ9?

As you suggested in https://github.com/eclipse-openj9/openj9/pull/17310#issuecomment-1530275095, I think we can update `J9::AliasBuilder::createAliasInfo` to set just `CurrentThread` sym ref to `defaultMethodDefAliases()`

**Comment by jdmpapin** [comment]
With the update to eclipse-openj9/openj9#17310, can this PR be closed now?

**Comment by a7ehuo** [comment]
> With the update to https://github.com/eclipse-openj9/openj9/pull/17310, can this PR be closed now?
Yes

Close as the fix is only needed to be in OpenJ9

**Pull request closed without merging**
