### PR TITLE
Permanently enable OMR_GC_SCAVENGER_DELEGATE

### PR DESCRIPTION
**Pull request by rwy0717**
Effectively turn on the OMR_GC_SCAVENGER_DELEGATE flag.

Any code ifdef'd under this flag was rewritten to assume the flag is
enabled, and dead code was deleted.

The flag remains in the build system temporarily, as a settable option,
but should have no effect on the source code.

Signed-off-by: Robert Young <rwy0717@gmail.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by rwy0717** [comment]
There was a typo in the example's ScavengerDelegate, fixed by #3582

**Comment by youngar** [comment]
@genie-omr build all

**Comment by rwy0717** [comment]
Looks like an infra problem.

**Comment by youngar** [comment]
@genie-omr build all

**Comment by rwy0717** [comment]
@youngar build all

**Comment by charliegracie** [comment]
@genie-omr build xcrlinux

**Pull request merged**
