### PR TITLE
Misc. cleanup and removal of OpenJ9-specific functionality

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Remove _liveRestrictValues
* Delete live monitors TR_BitVector from CodeGenerator
* Relocate TR_SetMonitorStateOnBlockEntry to OpenJ9

### CODE REVIEW

**Comment by 0xdaryl** [comment]
As this PR involves moving code into OpenJ9, it will remain a WIP until eclipse/openj9#623 is merged.

**Comment by 0xdaryl** [comment]
I'd appreciate a review from at least one of @fjeremic @ymanton please.

**Comment by ymanton** [comment]
LGTM.

**Comment by 0xdaryl** [comment]
eclipse/openj9#623 is merged.  Removing the WIP.

**Pull request merged**
