### PR TITLE
WIP : Remove _compressedRefs from  OMR::CodeGenerator

### PR DESCRIPTION
**Pull request by SwathiKalahastri**
OMR part of the fix for 1896.

Issue: #1896
Signed-off-by: Swathi Kalahastri <swkalaha@in.ibm.com>

### CODE REVIEW

**Comment by SwathiKalahastri** [comment]
This is the dependent change that effects into Openj9 and  OMR. Will also work on the Openj9 part.

**Comment by 0xdaryl** [comment]
Thank you for your contribution.

The code changes look fine to me.  I won't approve until WIP is removed.

**Comment by SwathiKalahastri** [comment]
Unable to find any test issues with this PR so removed WIP, Please approve. Thanks Swathi

**Comment by 0xdaryl** [comment]
This cleanup was driven by OpenJ9, but the work in the OpenJ9 project to move this field there has not been completed yet (as far as I can tell).  Hence, if I merge this then OMR will be fine but OpenJ9 will break.

Please mark this as a WIP until the corresponding OpenJ9 piece is done.

**Comment by 0xdaryl** [comment]
genie-omr build all

**Comment by SwathiKalahastri** [comment]
Marking  this as a WIP until the corresponding OpenJ9 piece is done.

**Comment by 0xdaryl** [comment]
@SwathiKalahastri , FYI to mark this as a WIP please prefix the pull request title with the text `WIP:` .  Thanks.

**Comment by 0xdaryl** [comment]
Do you have an update on the progress of this?

**Comment by 0xdaryl** [comment]
It has been over 2 months since progress was made on this pull request.  Can you please provide an update on its status and the progress to move the field to OpenJ9?  I will close this PR in one week unless you say otherwise.  If that does happen, you can continue to work on it in your own fork.

**Comment by 0xdaryl** [comment]
Closing per comment on January 24.  Please re-open if more progress is made.

**Pull request closed without merging**
