### PR TITLE
Revert part of fix incorrect usage of TR::Options

### PR DESCRIPTION
**Pull request by harryyu1994**
- Backing out this commit because of 2% performance regression on daytrader

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by charliegracie** [comment]
Can you provide more details on how this change caused a performance regression?  Was it getting the options wrong? The change should effectively be the same so more details would be appreciated.  Thanks

**Comment by harryyu1994** [comment]
The original change(Fix incorrect usage of TR::Options) exposed a bug somewhere that will be investigated later. I haven't located which line of change it is that changed the program behavior, so I'm reverting to get rid of the regression for now. Somewhere in the program TR::Options::getCmdLineOptions()->getOptions(TR_XXX) and options->getOptions(TR_XXX) are giving different results and DayTrader didn't like the result from options->getOptions(TR_XXX). @charliegracie

**Comment by harryyu1994** [comment]
FYI @vijaysun-omr, Hi Vijay, since you merged the original commit, could you review&merge this one too?

**Comment by harryyu1994** [comment]
@mpirvu FYI; Hi Marius, due to the urgent situation, I'm going to revert this change for now and investigate further later. Could you help reviewing this as well? thanks!

**Comment by vijaysun-omr** [comment]
Looks ok to me. Merging.

**Comment by pshipton** [comment]
fyi original change was #2715

**Pull request merged**
