### PR TITLE
AArch64: Add support for ARM64 in Debug.cpp

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds some more code for aarch64 in the common Debug.cpp
and related files.

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
See also my change in Debug.cpp in #3007

**Comment by knn-k** [comment]
The change in `CMakeLists.txt` depends on #3000.

**Comment by knn-k** [comment]
Removed "WIP:".

**Comment by knn-k** [comment]
AppVeyor build failed with "MSBUILD : error MSB4017: The build stopped unexpectedly because of an unexpected logger failure."
I believe it is not caused by the change in this PR.

**Comment by knn-k** [comment]
Rebased to the latest level, and pushed the commit again.

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Pull request merged**
