### PR TITLE
AArch64: Use OMR::ARM64::InstOpCode instead of TR_ARM64OpCode

### PR DESCRIPTION
**Pull request by knn-k**
Change the name space TR_ARM64OpCode:: to OMR::ARM64::InstOpCode::
for aligning to OMR style.

Issue: #2754

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
I moved the `enum` members of `ARM64Ops.hpp` to `OMRInstOpCodeEnum.hpp`.  It still has the same issue of duplicated symbols in #2761.  I am going to remove `ARM64Ops.hpp` when this is merged.

I also corrected non-ASCII characters used in `OMRInstOpCodeEnum.hpp` and `OpBinary.cpp`.

FYI @aarongraham9 and @jeanlego

**Comment by 0xdaryl** [comment]
If this depends on #2779, can you mark it as a WIP until that is merged?

**Comment by knn-k** [comment]
I will update `OMRInstOpCodeEnum.hpp` when #2779 is merged.

**Comment by knn-k** [comment]
I updated the files with #2779 being merged.

**Comment by 0xdaryl** [comment]
The AppVeyor build will not exercise these changes so there's no need to wait for it.  Merging.

**Pull request merged**
