### PR TITLE
Remove the redundant implementation of findSingleImplementer

### PR DESCRIPTION
**Pull request by a7ehuo**
`findSingleImplementer()` is already implemented in `PersistentCHTable`. Remove the one defined in OMR which didn't consider `enterHeuristicRegion` and could trigger the assert `SVM_ASSERT_ALREADY_VALIDATED` in `addVirtualMethodFromOffsetRecord()`.

(Thanks to @dsouzai for root-causing the assert.)

Signed-off-by: Annabelle Huo <Annabelle.Huo@ibm.com>

### CODE REVIEW

**Comment by a7ehuo** [comment]
@dsouzai Ready for review. Thanks!

**Comment by dsouzai** [comment]
@vijaysun-omr could you please review.

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by vijaysun-omr** [comment]
@a7ehuo there is a change to VP that does not seem to be described in the PR/commit message. Is this intentional ?

**Comment by a7ehuo** [comment]
> there is a change to VP that does not seem to be described in the PR/commit message. Is this intentional ?

Could you elaborate on which change to VP is referred on the above? This commit removes the local implementation of `findSingleImplementer()` in `VPHandlers.cpp` and replaces it with
```c++
virtual TR_ResolvedMethod * PersistentCHTable::findSingleImplementer(TR_OpaqueClassBlock * thisClass, int32_t cpIndexOrVftSlot, TR_ResolvedMethod * callerMethod, TR::Compilation * comp, bool locked, TR_YesNoMaybe useGetResolvedInterfaceMethod, bool validate = true);
```

**Comment by vijaysun-omr** [comment]
Sorry I just meant the small change in logic with disableCHOpts.

**Comment by vijaysun-omr** [comment]
I'm fine with this change, and checks have passed. Merging.

**Pull request merged**
