### PR TITLE
Fix CMake build fails on ParallelGlobalGC.cpp / Scavenger.cpp compilation

### PR DESCRIPTION
**Pull request by RSalman**
Fix for Issue https://github.com/eclipse/omr/issues/2404

Signed-off-by: Salman Rana <salman.rana@ibm.com>

### CODE REVIEW

**Comment by amicic** [comment]
_masterThreadTenureTLHRemainderBase/Top actually belongs to GCExtensions (which sort of be called GCExtensionsStandard).

**Comment by charliegracie** [comment]
@samolisov Can you verify that this fixes your issue?  Thanks!

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by samolisov** [comment]
I will be able to check only in the tomorrow morning (MSK).

**Comment by RSalman** [comment]
Minor change after talking with @amicic - wrap entire thread walk with OMR_GC_MODRON_SCAVENGER

**Comment by samolisov** [comment]
@RSalman thank you for the fixes

@RSalman @charliegracie I've observed a strange result of the running of fvtest on my machine:

```bash
> cmake -DCMAKE_CXX_COMPILER=clang-cl -DCMAKE_C_COMPILER=clang-cl -DCMAKE_LINKER:STRING=lld-link -DOMR_FVTEST=ON -DOMR_GC=ON -DOMR_DDR=ON -DOMR_JITBUILDER=OFF .. -G"Ninja"

> cmake --build . (build is OK)

> ctest -V

83% tests passed, 2 tests failed out of 12

Total Test time (real) = 183.72 sec

The following tests FAILED:
          2 - gctest (Failed)
          3 - porttest (Failed)
Errors while running CTest
```

If both  `OMR_GC_MODRON_CONCURRENT_MARK` and `OMR_GC_MODRON_SCAVENGER` are enabled, the test results are the following:

```bash
> cmake -DCMAKE_CXX_COMPILER=cl -DCMAKE_C_COMPILER=cl -DOMR_FVTEST=ON -DOMR_GC=ON -DOMR_DDR=ON -DOMR_JITBUILDER=OFF -DOMR_GC_MODRON_CONCURRENT_MARK=ON -DOMR_GC_MODRON_SCAVENGER=ON .. -G"Ninja"

> cmake --build .

> ctest -V

92% tests passed, 1 tests failed out of 12

Total Test time (real) = 182.44 sec

The following tests FAILED:
          3 - porttest (Failed)
Errors while running CTest
```
So, some GC tests work only if `OMR_GC_MODRON_CONCURRENT_MARK` and `OMR_GC_MODRON_SCAVENGER` are enabled.

I'm not sure this is directly related to this issue, maybe another one should be opened.

**Comment by charliegracie** [comment]
I would open another issue since that is almost certainly a long standing issue, but it is something we should fix.

**Pull request merged**
