### PR TITLE
Add helper functions for ternary select node

### PR DESCRIPTION
**Pull request by r30shah**
This PR involved two changes. 
1. Add helper functions to generate ternary select nodes
2. Add tracing options for jProfiling (J9 specific optimization)

### CODE REVIEW

**Comment by r30shah** [comment]
@andrewcraik  Can I please get review on this? This commit adds helper function to generate ternary select node as per data type and also tracing options for jProfiling optimizations.

**Comment by andrewcraik** [comment]
change looks good to me

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
AppVeyor seems to be having some queuing issues as we've been pending for half a day. I'm comfortable merging this given the change and the other checks.

**Pull request merged**
