### PR TITLE
Replaced deprecated function readdir_r()

### PR DESCRIPTION
**Pull request by Varun-garg**
In newer versions of glibc (2.24 onwards) function `readdir_r()` has been deprecated. I have replaced it with function `readdir()` which should thread safe on Linux port (compiling with glibc). 

According to `readdir_r()` documentation: 
> In  the current POSIX.1 specification (POSIX.1-2008), readdir(3) is not required to be thread-safe. However, in modern implementations (including the glibc implementation), concurrent calls to readdir(3) that specify different directory streams are thread-safe. Therefore,  the  use  of readdir_r() is generally unnecessary in multithreaded programs.  

**Tests**
On my system 198 tests ran successfully before and after making these changes.

Issue: #305 
Signed-off-by: Varun Garg <varun.10@live.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
genie-omr build all

**Comment by Varun-garg** [comment]
@charliegracie Thanks for running extra tests. Error on power pc 64bit little endian is

```compiling src/Call.cpp:46:test_calls at level: warm
#0: ./call() [0x1037773c]
#1: ./call() [0x100d2780]
#2: ./call() [0x10038470]
#3: ./call() [0x100386f8]
#4: ./call() [0x10309384]
#5: ./call() [0x1030477c]
#6: ./call() [0x102a2524]
#7: ./call() [0x1029fcac]
#8: ./call() [0x1029d1bc]
#9: ./call() [0x100b5ee0]
#10: ./call() [0x102abfa4]
#11: ./call() [0x1002b2f4]
#12: ./call() [0x10003254]
#13: /lib/powerpc64le-linux-gnu/libc.so.6(+0x2309c) [0x3fff8e90309c]
#14: function __libc_start_main+0xb8 [0x3fff8e903298]

call: ../compiler/infra/Assert.cpp:72: void TR::trap(): Assertion `0' failed.
Step 1: initialize JIT
Step 2: define type dictionary
Step 3: compile Call method builder
make[2]: Leaving directory '/home/jenkins/jenkins-agent/workspace/PullRequest-linux_ppc-64_le_gcc/perftest/gctest'
Aborted (core dumped)
Makefile:334: recipe for target 'test_calls.o' failed
make[2]: *** [test_calls.o] Error 134
```

However, I am unable to reproduce it on my system as `jitbuilder/release/call` runs fine here.

**Comment by charliegracie** [comment]
It is unrelated to your changes.  It is being investigated in #1748

**Comment by charliegracie** [comment]
Would you be able to rebase on on head if master?  I would like to see the testing pass on Linux ppc le to make sure the readdir is working there. Thanks

**Comment by Varun-garg** [comment]
Sure @charliegracie.

**Comment by Varun-garg** [comment]
Hey @charliegracie commit ts now at head of master.

**Comment by Varun-garg** [comment]
genie-omr build all

**Comment by charliegracie** [comment]
genie-omr build all

**Pull request merged**
