### PR TITLE
Change configure flags for JIT components

### PR DESCRIPTION
**Pull request by noryb009**
Add separate configure flags for the Test compiler and JitBuilder; `--enable-TEST_COMPILER` and `--enable-JITBUILDER` respectively. These were picked to be consistent with other configure flags.

Issue: #285

### CODE REVIEW

**Comment by charliegracie** [comment]
I think there should still be on overall JIT flag.  These new flags should only be usable if the main JIT flag is also enabled.

**Comment by noryb009** [comment]
I'm definitely open to changing the flag hierarchy, but I'm not convinced adding this dependency is beneficial, especially since the OMR_JIT flag doesn't do anything right now (in fact, I think it should be removed - but that's out of the scope of this pr). Is there a benefit that I'm missing?

**Comment by charliegracie** [comment]
Actually looking into this deeper I see that there are basically no makefiles in the compiler directory and it is the responsibility of the consumer to figure out which files to compile.  Due to that I think the 2 separate configure flags make sense and I would agree that we should delete the OMR_JIT flag for now.

**Comment by 0xdaryl** [comment]
@charliegracie : any objections to merging this as-is then?

The pull request is a little stale, so perhaps a rebase from @noryb009 prior to merging would be prudent.

**Comment by charliegracie** [comment]
As soon as the build passes I will accept it

**Pull request merged**
