### PR TITLE
Quiet output of rfib test

### PR DESCRIPTION
**Pull request by dnakamura**
Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
I think I would prefer just removing the prints from the test unless they are valuable for a developer that might run the test locally.  @mstoodle do you have any opinion?  I do think we want to do something here as this test adds about 4K lines of output.

**Comment by smlambert** [comment]
Can you use the logger that is used by some of the other tests (and set most/all output to debug level?) #163

**Comment by charliegracie** [comment]
It would be difficult to add the FV test logger to these examples since they are JitBuilder examples and only have a dependency of the JitBuilder library.  At this point I do not think we want to make them depend on any of the FV libraries.  @dnakamura I think if you just remove the 5 `Call("print*` calls (and also those functions) this test will be as quiet as it should be.  After looking into the code more I can not see any reason why we would want this output.  You could easily wrap those calls and their callers with a `#if defined(RFIB_DEBUG_OUTPUT)` and by default we do not have that enable we will not get the output.

**Comment by charliegracie** [comment]
@dnakamura any update

**Pull request merged**
