### PR TITLE
Remove the --gtest_filter=${porttest_filter} option for porttest

### PR DESCRIPTION
**Pull request by babsingh**
1. Remove the `--gtest_filter=${porttest_filter}` option for porttest

    When `${porttest_filter}` is an empty string, no tests from `porttest` are
run. `${porttest_filter}` is never set in OMR so it will always be an
empty string. Also, `--gtest_filter=${porttest_filter}` conflicts with
the `GTEST_FILTER` environment variable used by `omrbuild.groovy`. To avoid
the conflict and correctly run `porttest`, the `--gtest_filter=${porttest_filter}`
option is removed. `porttest` should consistently rely upon the `GTEST_FILTER`
environment variable.

   Changed `--gtest_filter="Cuda*"` to `--gtest_filter=*Cuda*`. 0 tests are run.
This allows `cuda_porttest` to work correctly.

2. Disable `*_create_dump_*` tests for the "x86-64 Linux" job in Azure

    These tests are disabled because core files cannot be generated on Linux
in the Azure pipeline.

Fixes: https://github.com/eclipse/omr/issues/6486

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by babsingh** [comment]
I used the following reference: https://github.com/google/googletest/blob/main/docs/advanced.md#running-a-subset-of-the-tests. The intent of adding an asterisks at the start and end is to increase test coverage: `*Cuda*` and `*${porttest_filter}*`. This will allow tests to be named and filters to be enforced more flexibly.

**Comment by babsingh** [comment]
jenkins build all

**Comment by babsingh** [comment]
> eclipse.omr (x86-64 Linux) https://dev.azure.com/eclipse-omr/omr/_build/results?buildId=5433&view=logs&j=196c4937-6990-58b5-7d18-234ac2f0888b&t=66cbe35e-0143-5803-340e-78910b4c9fcb

@AdamBrousseau @jdekonin Are the OMR machines configured to generate core files correctly?

```
The following tests FAILED:
	 31 - porttest (Failed)

31: [  FAILED  ] PortDumpTest.dump_test_create_dump_with_NO_name
31: [  FAILED  ] PortDumpTest.dump_test_create_dump_with_name
31: [  FAILED  ] PortDumpTest.dump_test_create_dump_from_signal_handler

31: /home/vsts/work/1/s/fvtest/porttest/omrdumpTest.cpp line  173: omrdump_test_create_dump_with_NO_name omrdump_create returned: 1, with filename: The core file created by child process with pid = 16910 was not found. Expected to find core file with name "core"
```

**Comment by babsingh** [comment]
> https://ci.eclipse.org/omr/job/PullRequest-win_x86-64/3231/

`sysinfo_test_get_tmp3` is excluded on Windows. The PR build script sets the `GTEST_FILTER` environment variable. Setting `--gtest_filter=*` in `fvtest/porttest/CMakeLists.txt` conflicts with the environment variable, and reincludes `sysinfo_test_get_tmp3` on Windows.

```
15:28:23  The following tests FAILED:
15:28:23  	 13 - porttest (Failed)

15:26:59  13: [  FAILED  ] PortSysinfoTest.sysinfo_test_get_tmp3 (0 ms)
```

https://github.com/eclipse/omr/blob/7abfd05e8d911a44fc6ce4cba97584f9065444a7/buildenv/jenkins/omrbuild.groovy#L265

**Comment by babsingh** [comment]
jenkins build all

**Comment by jdekonin** [comment]
> Are the OMR machines configured to generate core files correctly?

The bulk of the existing systems in jenkins were setup prior to either @AdamBrousseau or my involvement with the OMR project.  A quick spot check of a few would have me answer no, I don't believe they are and that needs an issue for deeper review.  Can you please open an issue to track?

**Comment by AdamBrousseau** [comment]
If you're asking about the machines on azure, we don't own those resources. I'm not sure if we have the ability to control things like core settings on those. Someone would have to look at the azure doc.

**Comment by babsingh** [comment]
I tried to add the below cmds in [azure-pipelines.yml](https://github.com/eclipse/omr/pull/6487/commits/68e52e0e0175333015da2afa1187cb88a0db0dd6):
```
### For core generation
     sudo echo "core.%p" > /proc/sys/kernel/core_pattern
     sudo echo "kernel.core_pattern=core.%p" >> /etc/sysctl.conf
     sudo systemctl disable apport
     ulimit -c unlimited
     ulimit -n 1048576
     ulimit -u unlimited

### Does not work: privileged cmds cannot be invoked
     /home/vsts/work/_temp/788c8a55-2e55-4912-9795-f8c5bedd2b80.sh: line 1: /proc/sys/kernel/core_pattern: Permission denied
     /home/vsts/work/_temp/788c8a55-2e55-4912-9795-f8c5bedd2b80.sh: line 2: /etc/sysctl.conf: Permission denied
     apport.service is not a native service, redirecting to systemd-sysv-install.
```

**Comment by babsingh** [comment]
jenkins build all

**Comment by babsingh** [comment]
With these changes, `porttest` is correctly run.

> Run from this PR: https://ci.eclipse.org/omr/job/PullRequest-linux_x86-64/3268/consoleFull
```
10:54:06        Start 31: porttest
10:54:06  
10:54:06  31: Test command: /home/jenkins/workspace/Build/build/fvtest/porttest/omrporttest "--gtest_output=xml:/home/jenkins/workspace/Build/build/fvtest/porttest/omrporttest-results.xml"
10:54:06  31: Test timeout computed to be: 9.99988e+06
10:54:06  31: [==========] Running 254 tests from 22 test cases.
10:54:06  31: [----------] 1 test from PortInitializationTest
10:54:06  31: [----------] 1 test from PortInitializationTest (0 ms total)
10:54:06  31: 
10:54:06  31: [----------] 2 tests from PortFileTest
10:54:06  31: [----------] 2 tests from PortFileTest (1 ms total)
10:54:06  31: 
10:54:06  31: [----------] 8 tests from PortHeapTest
10:54:06  31: [----------] 8 tests from PortHeapTest (838 ms total)
10:54:06  31: 
10:54:06  31: [----------] 8 tests from PortTest
10:54:06  31: [----------] 8 tests from PortTest (2 ms total)
10:54:06  31: 
10:54:06  31: [----------] 10 tests from PortMemTest
10:54:06  31: [----------] 10 tests from PortMemTest (720 ms total)
...
```

> Another PR build: https://ci.eclipse.org/omr/job/PullRequest-linux_x86-64/3269/consoleFull
```
11:28:01        Start 31: porttest
11:28:01  
11:28:01  31: Test command: /home/jenkins/workspace/Build/build/fvtest/porttest/omrporttest "--gtest_output=xml:/home/jenkins/workspace/Build/build/fvtest/porttest/omrporttest-results.xml" "--gtest_filter="
11:28:01  31: Test timeout computed to be: 9.99988e+06
11:28:01  31: Note: Google Test filter = 
11:28:01  31: [==========] Running 0 tests from 0 test cases.
11:28:01  31: [==========] 0 tests from 0 test cases ran. (0 ms total)
11:28:01  31: [  PASSED  ] 0 tests.
11:28:01  31: [  ALL TESTS PASSED  ] 
11:28:01  31/48 Test #31: porttest ............................   Passed    0.01 sec
```

**Comment by babsingh** [comment]
jenkins build all

**Comment by babsingh** [comment]
@janvrany Can you provide feedback on these changes since `--gtest_filter=${porttest_filter}` was added by you in https://github.com/eclipse/omr/commit/bd501fbc6ad11f6626d4d0478a45a6a55e08c6dd?

@0xdaryl Requesting your feedback as well. In the current state, `porttest` runs 0 tests. Open PRs, such as https://github.com/eclipse/omr/pull/6465 and https://github.com/eclipse/omr/pull/6479, with port library changes cannot be merged since they will need changes from this PR to enable testing in PR builds.

**Comment by janvrany** [comment]
@babsingh : LGTM. Thanks! 

It actually seems to me that `--gtest_filter` option was overlooked leftover from some attempt to run at least some port tests under QEMU before we gave up.

**Comment by babsingh** [comment]
This PR needs to be merged. It is preventing cgroup v2 PRs from being tested: 
- https://github.com/eclipse/omr/pull/6465 (review completed; ready for testing)
- https://github.com/eclipse/omr/pull/6479 (review completed; ready for testing)
- https://github.com/eclipse/omr/pull/6494 (review in progress)

Cgroup v2 support is targeted for OpenJ9's 0.33 release. D-cut is end of May 22. More PRs for cgroup v2 support will follow. So, we should avoid cgroup v2 PRs from piling up.

fyi @pshipton @tajila

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
