### PR TITLE
Bump Azure x64 build to ubuntu-latest

### PR DESCRIPTION
**Pull request by AdamBrousseau**

### CODE REVIEW

**Comment by AdamBrousseau** [comment]
@0xdaryl for review.
Some test(s) failed.

**Comment by knn-k** [comment]
The porttest failure on x86-64 Linux.:

```
2023-03-01T14:37:40.8319602Z 32: [----------] 1 test from PortSignalExtendedTests
2023-03-01T14:37:40.8352197Z 32: 	/home/vsts/work/1/s/fvtest/porttest/omrsignalExtendedTest.cpp line  488: omrsig_ext_test1 	main thread mask was modified (old=0x8, new=0x8), D8
2023-03-01T14:37:40.8353308Z 32: 
2023-03-01T14:37:40.8353975Z 32: 			LastErrorNumber: -108
2023-03-01T14:37:40.8354520Z 32: 			LastErrorMessage: No such file or directory
2023-03-01T14:37:40.8354976Z 32: 
2023-03-01T14:37:40.8355487Z 32: 	omrsig_ext_test1	:test stopped with errors
2023-03-01T14:37:40.8356136Z 32: /home/vsts/work/1/s/fvtest/porttest/omrsignalExtendedTest.cpp:593: Failure
2023-03-01T14:37:40.8356699Z 32: Failed
2023-03-01T14:37:40.8357206Z 32: [  FAILED  ] PortSignalExtendedTests.sig_ext_test1 (3 ms)
2023-03-01T14:37:40.8357911Z 32: [----------] 1 test from PortSignalExtendedTests (3 ms total)
2023-03-01T14:37:40.8358417Z 32: 
2023-03-01T14:37:40.8358924Z 32: [----------] 13 tests from PortSigTest
2023-03-01T14:37:41.0197021Z 32/48 Test #32: porttest ............................Subprocess aborted***Exception:  10.96 sec
```

  I reran the test, and PortSignalExtendedTests.sig_ext_test1 failed again.

**Comment by janvrany** [comment]
> The porttest failure on x86-64 Linux.:
> ...
> I reran the test, and PortSignalExtendedTests.sig_ext_test1 failed again.

@knn-k, @AdamBrousseau  : I hunted this one down yesterday - see PR #6938

**Comment by knn-k** [comment]
@janvrany Thank you for your investigation and fix.

**Comment by knn-k** [comment]
Azure Ubuntu 18.04 image will be fully unsupported by 2023/04/01.
See https://github.com/actions/runner-images/issues/6002

**Review by knn-k — APPROVED** [review]

**Pull request merged**
