### PR TITLE
Remove OpenJ9 functionality from innerConstrainAcall

### PR DESCRIPTION
**Pull request by 0xdaryl**
Functionality has been migrated to OpenJ9.  OMR default implementation
simply returns the node.

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
A WIP only while awaiting downstream dependencies to merge.

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
Downstream dependencies have merged.  Un-WIPing this.

**Comment by vijaysun-omr** [comment]
Good job "sinking" this project specific functionality downstream and removing it from OMR. Checks have passed and so I am merging.

**Pull request merged**
