### PR TITLE
AArch64: Disable GRA for vector types

### PR DESCRIPTION
**Pull request by Akira1Saitoh**
Disable GRA for vector and mask types.

Signed-off-by: Akira Saitoh <saiaki@jp.ibm.com>

### CODE REVIEW

**Comment by Akira1Saitoh** [comment]
@gita-omr FYI

**Comment by knn-k** [comment]
Jenkins build aarch64,amac

**Comment by knn-k** [comment]
Jenkins build amac

**Review by knn-k — APPROVED** [review]

**Comment by knn-k** [comment]
See #6516 and #6716 for the failures on AArch64 macOS.

**Pull request merged**
