### PR TITLE
Remove misc. dead x87 code

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Remove x87 assignFPRegisters() from RegisterDependency
* Remove x87 AllFPRegisters RegisterDependency special register
* Remove x87 X86FPRemainderRegRegInstruction class
* Remove x87 X86FPArithmeticRegRegInstruction class
* Remove x87 numReferencedFPRegisters()

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins build xlinux,osx,win,x32linux

**Comment by 0xdaryl** [comment]
Jenkins build xlinux,osx,win,x32linux

**Comment by 0xdaryl** [comment]
@BradleyWood : would you mind reviewing this PR please when you have a moment?

**Comment by BradleyWood** [comment]
LGTM

**Comment by 0xdaryl** [comment]
@dsouzai : would you mind merging this PR please?

**Review by dsouzai — APPROVED** [review]

**Pull request merged**
