### PR TITLE
Enable RISC-V cross-compile and comptest Jenkins job

### PR DESCRIPTION
**Pull request by fjeremic**
- Add `testCmd` to allow the test command to be configurable
- Modify `linux_riscv64_cross` for cross compile
- Enable `comptest` to run on the RISC-V emulated image

Fixes: #4641

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
@genie-omr build riscv

**Comment by fjeremic** [comment]
@jdekonin @AdamBrousseau any ideas on the issue in the RISC-V build? I know for certain when I run it manually on the machine it does segfault at some point. Could this be the reason we get the Jenkins message:

```
20:19:20  [----------] 4800 tests from CompareTest/DoubleIfCompare (9405 ms total)
20:19:20  
20:19:21  [----------] 6498 tests from CompareTest/FloatCompareOrUnordered
20:20:53  Cannot contact deb10-x64-1: java.lang.InterruptedException
```

**Comment by fjeremic** [comment]
Trying again. So far 2/2 builds failed the same way. Third time is the charm? Seems to happen at different points.

@genie-omr build riscv

**Comment by fjeremic** [comment]
@janvrany checking if the `CompareTest/FloatCompareOrUnordered` is known to have problems on RISC-V?

**Comment by janvrany** [comment]
@fjeremic 
I'll check tomorrow. 

Also, please hold on with merging this PR, I have other idea on how to run tests. Will try on Monday.

**Comment by AdamBrousseau** [comment]
genie-omr build riscv

**Comment by AdamBrousseau** [comment]
genie-omr build riscv

**Comment by janvrany** [comment]
@fjeremic 
> checking if the CompareTest/FloatCompareOrUnordered is known to have problems on RISC-V?

No, this one seems all right on my system: 
```
jv@sao:~/Projects/J9/omr/build/riscv64-linux/fvtest/compilertriltest$ git log -1
commit 7be07cef85af553c607279cf70005fe299834e95 (HEAD -> master, upstream/master)
Merge: 1e6353161 f4a99dd14
Author: Daryl Maier <maier@ca.ibm.com>
Date:   Fri Jan 15 14:28:27 2021 -0500

    Merge pull request #5747 from ymanton/ccdata
    
    Remove inline from CCData static member funcs

jv@sao:~/Projects/J9/omr/build/riscv64-linux/fvtest/compilertriltest$ qemu-riscv64 ./comptest --gtest_filter=*FloatCompareOrUnordered*
Note: Google Test filter = *FloatCompareOrUnordered*
[==========] Running 6498 tests from 1 test case.
[----------] 6498 tests from CompareTest/FloatCompareOrUnordered
[----------] 6498 tests from CompareTest/FloatCompareOrUnordered (58034 ms total)

[==========] 6498 tests from 1 test case ran. (58105 ms total)
[  PASSED  ] 6498 tests.
[  ALL TESTS PASSED  ] 
```

**Comment by janvrany** [comment]
Native build on RISC-V hardware passes `CompareTest/FloatCompareOrUnordered` too.

**Comment by janvrany** [comment]
Still working on alternative way of running cross-compiled tests (my CMake-fu is poor, will continue later today)

**Comment by AdamBrousseau** [comment]
genie-omr build riscv

**Comment by fjeremic** [comment]
> No, this one seems all right on my system:

I get the same thing on the emulated system too. Filtering does not seem to make it fail. I suspect we may be running out of memory. I know the TRIL tests do leak memory as we chug along. Going to check for this now.

**Comment by fjeremic** [comment]
@genie-omr build riscv

**Comment by fjeremic** [comment]
I kicked off a build and monitored `vmstat` as the build progressed. Here is what happened about 1 minute before we get the failure message on Jenkins:

```
 1  0  74872 346548  21060 256536    0    0     0     0  414  263 24  1 75  0  0
 1  0  74872 340784  21060 256536    0    0     0     4  369  235 24  1 75  0  0
 1  0  74872 333160  21060 256536    0    0     0     0  385  250 25  1 75  0  0
 1  0  74872 327616  21084 256536    0    0    16    16  443  325 24  2 74  0  0
 1  0  74872 322324  21084 256536    0    0     0     0  376  258 25  0 75  0  0
 1  0  74872 316528  21084 256536    0    0     0     0  467  427 25  1 74  0  0
 1  0  74872 310512  21084 256536    0    0     0     0  469  670 26  1 73  0  0
 1  0  74872 304684  21084 256536    0    0     0     4  369  227 24  1 75  0  0
 1  0  74872 296852  21092 256536    0    0     0    16  419  313 25  1 74  0  0
 1  0  74872 291308  21092 256536    0    0     0     0  399  263 24  1 75  0  0
 1  0  74872 285512  21092 256536    0    0     0     0  365  229 25  1 75  0  0
 1  0  74872 279716  21092 256536    0    0     0     0  399  294 24  1 75  0  0
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 2  0  74872 273668  21092 256536    0    0     0     0  444  330 25  1 75  0  0
 1  0  74872 267872  21092 256588    0    0    52     4  469  422 25  1 74  0  0
 1  0  74872 262108  21100 256588    0    0     0    16  392  274 24  1 75  0  0
 1  0  74872 256564  21100 256588    0    0     0     0  419  273 24  1 75  0  0
 1  0  75128 265884  21100 252892    0  416     0   416 1521  404 24  3 72  0  0
 1  0  75128 259836  21100 252892    0    0     0     0  404  305 25  1 74  0  0
 1  0  75128 252496  21100 252892    0    0     0     0  397  260 25  1 75  0  0
 1  0  75128 246700  21108 252892    0    0     0    24  386  274 24  1 74  0  0
 1  0  75128 241156  21108 252892    0    0     0     0  397  270 24  1 75  0  0
 1  0  75128 235644  21108 252892    0    0     0     0  430  333 25  1 74  0  0
 1  0  75128 230352  21108 252892    0    0     0     0  445  452 25  1 75  0  0
 1  0  75128 224020  21108 252892    0    0     0     0  409  284 25  1 75  0  0
 1  0  75128 218476  21116 252896    0    0     0    16  425  292 25  1 75  0  0
 1  0  75128 212680  21116 252896    0    0     0    12  391  295 25  1 75  0  0
 1  0  75128 206664  21116 252896    0    0     0     0  414  264 25  1 75  0  0
 1  0  75128 200868  21116 252896    0    0     0     0  428  279 25  1 75  0  0
 1  0  75128 195072  21116 252896    0    0     0     0  386  257 24  1 75  0  0
 1  0  75128 189244  21116 252896    0    0     0     0  396  250 24  1 75  0  0
 1  3  75128 182944  21120 252896    0    0     0    24  405  245 25  1 41 34  0
 1  4  75128 177148  21120 252896    0    0     0     0  392  244 24  1 25 50  0
 1  4  75128 171636  21120 252896    0    0     0     0  515  488 25  2 24 49  0
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  4  75128 165336  21120 252896    0    0     0     0  396  256 24  1 25 50  0
 1  4  75128 159540  21120 252896    0    0     0     0  378  222 25  0 25 50  0
 1  1  75128 153996  21124 252896    0    0     0     8  423  321 25  1 48 27  0
 1  1  75128 148168  21124 252896    0    0     0     0  371  202 25  1 50 25  0
 1  1  75128 142372  21124 252896    0    0     0     0  376  220 24  1 50 25  0
 1  1  75128 136576  21124 252896    0    0     0     0  416  253 25  1 50 25  0
 1  1  75128 130780  21124 252896    0    0     0     0  366  203 24  1 50 25  0
 1  1  75128 124984  21124 252896    0    0     0     0  356  195 25  0 50 25  0
 2  2  75128 118936  21124 252864    0    4     0     4  427  274 24  1 45 30  0
 2  2  75128 113140  21124 252864    0    0     0     0  367  215 24  1 25 50  0
 1  2  75128 106336  21124 252864    0    0     0     0  370  220 24  1 25 50  0
 0  4  75384 102808  21124 252848    0    8     0     8  341  371 12  1 19 69  0
 1  0  82552 150064  19040 208360    0 7308     0  7348 2365 3975 27  7 67 269108225  1
 1  0  82552 142440  19040 208360    0    0     0     0  383  235 24  1 75  0  0
 1  0  82552 136888  19040 208360    0    0     0     0  413  277 24  1 75  0  0
 1  0  82552 131596  19040 208492    0    0   108     0  407  268 24  1 75  0  0
 1  0  82552 126304  19040 208492    0    0     0     0  360  211 24  0 75  0  0
 1  0  82552 118492  19048 208492    0    0     0    16  436  310 24  1 74  1  0
 1  0  85864 131768  15960 196556    0 3336     0  3336  817  352 24  2 74  0  0
 1  0  85864 126224  15960 196556    0    0     0     0  367  242 24  1 75  0  0
 1  0  85864 120088  15960 196556    0    0     0     0  425  289 24  1 75  0  0
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 2  0  86376 139688  11320 175596    0  640   132   644  475  429 25  2 74  0  0
 1  0  86376 133892  11320 175596    0    0     0     0  379  222 24  1 75  0  0
 1  2  86376 128640  11324 175604    0    0     8    12  409  288 24  1 27 47  0
 1  3  86376 123096  11324 175604    0    0     0     0  408  465 25  1 25 50  0
 1  4  86376 126088  10416 167312    0    4     0     4  580  232 25  1 25 50  0
 1  0  86632 132348   9920 157948    0  172   104   176  713  517 24  2 45 28  0
 1  0  86632 127196   9920 158092    0    0     0     4  413  440 25  1 75  0  0
 1  0  86632 121652   9920 158092    0    0     0     0  362  220 25  1 75  0  0
 1  0  95608 147500   8264 135116    8 8896    24  8924  979  359 25  3 72  0  0
 1  0  95608 139372   8524 135296    0    0   396     0  435  523 25  1 74  1  0
 1  0  95608 133828   8524 135296    0    0     0     0  373  238 24  1 75  0  0
 1  0  95864 136608   3884 124292    0  324   472   324  629  301 24  3 74  0  0
 3  0 124860 120224    808 122504   12 28856  9036 28856 6881 1366 22 11 63  3  0
 1  0 178808 126556    380 120688   24 53924  3228 54012 11724  818 21 14 61  3  0
 0  4 203796 112696    316 119160   12 25008    52 25008 5663  522 19  7 50 24  0
 1  0 248440 135092    276 109308   88 44692  2568 44692 9558 1367 17 14 60  8  1
 1  0 282232 125296    252 106508  152 33996   192 33996 8124 1003 21 10 68  0  0
 1  0 335480 135124    252 105948   60 53196   596 53196 13303  842 22 12 66  1  0
 0  8 344440 115996    256 108384   44 9120  3000  9152 2975 1206 12  6 33 49  0
 2  1 372856 127588    256 111212 2992 28284  5948 28484 1171 1449  3  6 60 31  0
 4  2 406524 121800    256 111588 4380 34488  6496 34488 10276 3427 21 17 56  6  0
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 4  0 473588 143440    256 114068 6176 68068 11980 68068 17262 3881 23 22 41 14  1
 1  0 496588 119908    256 116212  340 23680  2020 23680 6546 1056 22  8 69  2  0
 0  6 521848 123052    252 111704   40 25744   332 25772 9919  936 16 12 48 23  0
 1  0 536696 122152    252 114696  124 14888  3004 14896 3549 1189  6  5 38 51  0
 1  0 577656 120892    252 115644   52 41300  2148 41300 11247 1877 22 11 65  1  0
 2  0 617044 120672    252 114924   68 40200   448 40420 10225 1086 20 12 67  1  0
 1  1 688480 155684    248 112468   20 71744   488 71744 18656 1713 22 17 58  3  0
 0  3 691576 136264    256 112740 3952 7264  4144  7296 2514 1310 13  6 65 15  0
 1  0 691576 134028    256 115140   76    0  2544     0  588 1037  2  1 48 49  0
 1  0 691320 127444    256 115396   72    0   308     0  787  974 24  1 74  0  0
 1  0 691320 121648    256 115392  100    0   100     0  720  948 25  1 74  0  0
 1  0 700280 124200    256 115212   36 9120    92  9120 3089 1056 25  3 71  1  0
 2  0 707300 125208    264 114784   28 6796    96  6812 2390  958 25  2 72  1  0
 2  0 712824 125460    264 115184   40 6220   264  6220 2175 1101 26  2 71  1  0
 1  0 712824 119664    264 115176   48    0    48     0  639  769 24  1 74  0  0
 1  0 725624 128696    264 114864   36 13024   116 13024 4078 1020 24  4 71  1  0
 1  0 725624 122908    264 114948   16    0    16     0  640  747 24  1 74  0  0
 1  0 737400 126940    264 114620   32 11644    32 11644 3550 1078 25  3 71  1  0
 5  0 740480 119380    272 119192 3748 6224  8600  6240 3429 3793 22  9 57 12  0
 1  0 757920 131604    272 118528   88 17440   596 17440 6055 3940 27  5 67  1  0
 1  0 757920 127352    272 118516   32    0    32     0  538  583 25  1 75  0  0
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 2  0 757920 121036    272 118580    4    0     4     0  692  775 24  2 74  0  0
 1  0 771472 128564    272 118152    0 13824     0 13824 4158  705 25  3 71  1  0
 1  0 771472 124028    272 118148   16    0    16     0  616  744 25  1 74  0  0
 2  0 781176 128312    280 117976   24 9648    24  9664 2892  693 24  3 72  1  0
 1  0 785456 125824    280 117996   24 4328    24  4328 1206  740 25  2 73  1  0
 1  0 785456 120028    280 117996   20    0    20     0  557  613 25  1 74  0  0
 1  0 793156 122500    280 117788   20 7820    28  7820 2639  693 25  2 72  1  0
 1  0 799508 125036    280 117684   32 6380    32  6472 2126  887 25  2 72  1  0
 1  0 799508 119240    280 117916   60    0   300     0  619  745 24  1 75  0  0
 1  0 814712 124060    288 118344   16 15112   976 15140 3857 1922 23  7 66  4  0
 1  0 814712 119776    288 118512   24    0    24     0  589  668 24  1 74  0  0
 1  0 830312 125036    288 120788  348 15944  2936 15944 5031 1558 24  6 65  5  0
 1  0 830312 119980    288 120872   48    0    48     0  568  622 23  2 74  0  0
 1  0 845968 129604    288 120356   48 16196    48 16196 4670 1064 24  4 70  2  0
 1  0 845968 124564    296 120352   28    0    28    16  518  585 24  1 73  2  0
 2  0 845712 118224    296 120472   20    0   140     0  538  527 24  1 74  0  0
 1  0 854344 120248    296 120336    4 8664     4  8664 2714  617 23  3 73  1  0
 1  0 863236 123556    296 120160   16 9048    16  9048 2940  742 24  3 73  1  0
 1  0 863236 118012    296 120160   16    0    16     0  569  707 24  2 74  0  0
 1  0 874456 122516    296 120112   20 11360   128 11360 3499  944 25  3 71  1  0
 1  0 879736 122516    304 120036   24 5472    24  5488 1948  582 24  2 73  1  0
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 2  0 879840 120332    304 120116   32  108   116   108  691  783 24  2 74  1  0
 1  0 892440 123612    304 119920   48 12528    48 12528 3787 1073 25  3 71  1  0
 1  0 895584 120840    304 119876   16 3304    16  3304 1442  691 24  3 74  0  0
 1  0 904568 123612    304 119640   12 8800    12  8800 2867  743 25  2 72  1  0
 1  0 904568 117564    304 119640   12    0    12     0  491  493 24  2 75  0  0
 1  0 911620 120084    312 119320    4 8840     4  8856 2674  706 25  2 71  2  0
 1  0 920212 122384    444 119124   28 8644   216  8644 2851  762 24  4 72  0  0
 2  0 928756 124620    444 118808    0 8660     0  8660 2796  719 25  3 72  1  0
 1  0 929012 119360    444 118840   12  176    12   176  529  447 24  2 74  0  0
 2  0 943332 123108    440 121612   92 17988  4392 17988 5287 2831 25  8 63  4  0
 1  0 952076 125344    440 122416   28 8536   688  8536 3063 2465 26  4 70  1  0
 1  0 952076 120084    448 122416    4    0     4    16  487  458 25  0 74  1  0
 1  0 982044 144268    432 120144    8 30084   100 30096 8193 1114 25  7 66  2  0
 1  0 982044 138512    432 120128    0    0    20     0  565  625 25  1 74  0  0
 1  0 982044 135456    432 120132   16    0    16     0  524  519 25  0 74  0  0
 1  0 982044 130952    432 120128   32    0    32     0  593  756 25  1 74  0  0
 1  0 981788 125912    432 120128    0    0     0     0  485  458 24  1 75  0  0
 1  0 981788 120084    440 120128    8    0     8    28  486  452 25  1 73  1  0
 1  0 996880 126888    440 119804   24 15828    24 15828 4849 1134 26  4 68  2  0
 1  0 996868 121092    440 119804   12    0    12     0  503  513 24  1 75  0  0
 1  0 998396 123392    336 113180   12 1536   160  1536  986  608 24  2 73  0  0
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 2  0 998388 119580    256 112216   44   36  3976    52  986 1229 25  3 71  1  0
 3  2 998396 121612    228 106568    8   16 55796    20 2277 3614 13 10 68  9  0
 1  1 998388 107784    232 119216    8    0 46424    28 1625 2892 13  8 68 10  0
 1 12 998396 122012    228 102296   68   68 912436    88 19958 30405  3 32 32 33  0
 2 11 998396 121508    224 102552   28   28 2277712    48 130095 201981  0 37 23 39  0
 2 14 998396 121996    232 102440  172  128 1406848   156 78210 123743  0 36 23 41  0
```

**Comment by fjeremic** [comment]
Swap space was increased:

```
root@deb10-x64-1:~# free -h
              total        used        free      shared  buff/cache   available
Mem:          7.8Gi       724Mi       6.5Gi       8.0Mi       647Mi       6.8Gi
Swap:         5.0Gi          0B       5.0Gi
```

Let's hope for the best now 🤞 

@genie-omr build riscv

**Comment by fjeremic** [comment]
Success! Seems increasing swap space did the trick. The tests chug a long a lot slower after we run out of real memory, but we still proceed. We hit the same problem that I encounter on my own machine (with more than enough real memory):

https://ci.eclipse.org/omr/job/PullRequest-linux_riscv64_cross/10/consoleFull

```
18:26:45  [----------] 450 tests from SelectCompareTest/Int32SelectInt8CompareTest
18:26:45  Assertion failed at /home/jenkins/workspace/Build/compiler/riscv/codegen/OMRTreeEvaluator.cpp:114: false
18:26:45  	Opcode bcmpeq is not implemented
18:26:45  
18:26:45  compiling file:line:name at level: warm
18:26:45  #0: function TR_LinuxCallStackIterator::printStackBacktrace(TR::Compilation*)+0x2a [0x40017112f4]
18:26:45  #1: function TR_Debug::printStackBacktrace()+0x28 [0x40014f2f42]
18:26:45  #2: ./fvtest/compilertriltest/comptest(+0x133a28e) [0x400133a28e]
18:26:45  #3: ./fvtest/compilertriltest/comptest(+0x133a366) [0x400133a366]
18:26:45  #4: function TR::assertion(char const*, int, char const*, char const*, ...)+0xac [0x400133a416]
18:26:45  #5: function OMR::RV::TreeEvaluator::unImpOpEvaluator(TR::Node*, TR::CodeGenerator*)+0x56 [0x4001523796]
18:26:45  #6: function OMR::CodeGenerator::evaluate(TR::Node*)+0x1a2 [0x4001540254]
18:26:45  #7: function OMR::RV::TreeEvaluator::iselectEvaluator(TR::Node*, TR::CodeGenerator*)+0x6e [0x4001723a96]
18:26:45  #8: function OMR::CodeGenerator::evaluate(TR::Node*)+0x1a2 [0x4001540254]
18:26:45  #9: function genericReturnEvaluator(TR::Node*, OMR::RealRegister::RegNum, TR_RegisterKinds, TR_ReturnInfo, TR::CodeGenerator*)+0x4e [0x4001722790]
18:26:45  #10: function OMR::RV::TreeEvaluator::ireturnEvaluator(TR::Node*, TR::CodeGenerator*)+0x42 [0x40017228c6]
18:26:45  #11: function OMR::CodeGenerator::evaluate(TR::Node*)+0x1a2 [0x4001540254]
18:26:45  #12: function OMR::CodeGenerator::doInstructionSelection()+0x5e6 [0x400154364e]
18:26:45  #13: function OMR::CodeGenPhase::performInstructionSelectionPhase(TR::CodeGenerator*, TR::CodeGenPhase*)+0xd4 [0x40015516f6]
18:26:45  #14: function OMR::CodeGenPhase::performAll()+0x122 [0x400155048e]
18:26:45  #15: function OMR::CodeGenerator::generateCode()+0xdc [0x40015456b4]
18:26:45  #16: function OMR::Compilation::compile()+0xc2e [0x4001286cb4]
```

I suspect we just need to skip those tests on RISC-V for now. Going to figure out which tests need to be disabled next.

**Comment by fjeremic** [comment]
@genie-omr build riscv

**Comment by janvrany** [comment]
See my alternative implementation of running tests under QEMU: #5755

**Comment by fjeremic** [comment]
Closing this PR since it is superseded by #5755.

**Pull request closed without merging**
