### PR TITLE
Don't overwrite the _callNode of a mapped callsite

### PR DESCRIPTION
**Pull request by cathyzhyi**
findAndUpdateCallSiteInGraph maps the callNode generated in actual ilgen
to a callsite created when doing estimate code size baseed on byte code
info. There is a potential problem if there are more than one callNode at
the same byte code index. For now, we always choose to inline the first
callNode with matching byte code info.

This change also changes the location of the trace message
"before findAndUpdateCallSiteInGraph" so that it actually appears
before the callsite gets updated.

Signed-off-by: Yi Zhang <yizhang@ca.ibm.com>

### CODE REVIEW

**Comment by cathyzhyi** [comment]
@andrewcraik Hey Andrew, can you review this PR? It's needed for fixing https://github.com/eclipse/openj9/issues/7684

**Comment by cathyzhyi** [comment]
depends on https://github.com/eclipse/openj9/pull/9158

**Comment by andrewcraik** [comment]
Are we sure the callNode field is being properly zero initialized in all cases?

**Comment by cathyzhyi** [comment]
> Are we sure the callNode field is being properly zero initialized in all cases?

Yes, they are either initialized with a proper callNode or with NULL.

**Comment by andrewcraik** [comment]
@genie-omr build all

**Pull request merged**
