### PR TITLE
Remove initalize from ObjectScanner

### PR DESCRIPTION
**Pull request by youngar**
Functionality from this function is moved into the constructor.
OpenJ9 side of this must be merged first: https://github.com/eclipse/openj9/pull/7896
cc @dmitripivkine

### CODE REVIEW

**Comment by youngar** [comment]
@genie-omr build all

**Comment by rwy0717** [comment]
This looks good to me. The initialization code can not fail, so it should be moved into the constructor. There is no need for two-phase initialization.

**Comment by dmitripivkine** [comment]
@amicic FYI

**Comment by dmitripivkine** [comment]
You need to care about OpenJ9 side as well. You can remove `GC_ObjectScanner::initialize(env);` from `GC_MixedObjectScanner`. However it is not so easy for `GC_PointerArrayObjectScanner`

**Comment by dmitripivkine** [comment]
My opinion if this initialize() call not on your way do not touch it. Leaf implementations like `GC_PointerArrayObjectScanner` or `GC_MixedObjectScanner` have `newInstance()` method where initialize() can fail. Probably it is better to keep it for consistence

**Pull request closed without merging**
