### PR TITLE
Add hasSlotSharingOrDeadSlotsInfo to OSRMethodData

### PR DESCRIPTION
**Pull request by cathyzhyi**
Add this API to query whether there is information about slots sharing or dead slots stored in OSRMethodData

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
@cathyzhyi could you please add in a message to the commit as well ?

**Comment by andrewcraik** [comment]
The commit message and pull request should describe the intent of the change on its own without reference to other projects or changes. I think another iteration would make the message much more clear what this is doing.

**Comment by andrewcraik** [comment]
The actual API makes sense to me.

**Comment by cathyzhyi** [comment]
@andrewcraik Thanks for pointing this out. Changed the commit msg.

**Pull request merged**
