### PR TITLE
Runtime compressed refs work

### PR DESCRIPTION
**Pull request by gacholio**
Add new constructor to ForwardedHeader in preparation for the real work.

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by gacholio** [comment]
```
19:12:53  In file included from /home/jenkins/jenkins-agent/workspace/PullRequest-linux_390-64/gc/base/AddressOrderedListPopulator.cpp:26:0:
19:12:53  /home/jenkins/jenkins-agent/workspace/PullRequest-linux_390-64/gc/base/ObjectHeapIteratorAddressOrderedList.hpp: In member function ‘virtual Object* GC_ObjectHeapIteratorAddressOrderedList::nextObject()’:
19:12:53  /home/jenkins/jenkins-agent/workspace/PullRequest-linux_390-64/gc/base/ObjectHeapIteratorAddressOrderedList.hpp:151:13: error: unused variable ‘compressed’ [-Werror=unused-variable]
19:12:53    bool const compressed = _extensions->compressObjectReferences();
```

I'll fix.

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by gacholio** [comment]
Let's try that again...

**Comment by rwy0717** [comment]
@genie-omr build all

**Pull request merged**
