### PR TITLE
DDR: allow ddr-scanner to handle exe/dll files

### PR DESCRIPTION
**Pull request by dnakamura**
If filename does not end with '.pdb', assume the file is an exe/dll file

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by charliegracie** [comment]
The commit message explains the actual change but I am curious as to why we need the change?

**Comment by charliegracie** [comment]
@dnakamura is the plan to include the debug data in the exe/dll instead of creating pdb files?

**Comment by dnakamura** [comment]
The debug info always lives in .pdb files, however the .exe/.dll files has info which points to the location of the pdb file

**Comment by charliegracie** [comment]
Ahhh that makes sense.  Thanks!

**Pull request merged**
