### PR TITLE
Add base setupPointerArrayScanner() implementation

### PR DESCRIPTION
**Pull request by jason-hall**
Signed-off-by: Jason Hall <jasonhal@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@rwy0717 or @youngar : can you review this please?

**Comment by youngar** [comment]
It seems to me that this code is Java specific.  Is there a reason that we are moving this out of the Java glue `MarkingDelegate`, and in to the OMR `MarkingScheme`?

**Comment by jason-hall** [comment]
> It seems to me that this code is Java specific. Is there a reason that we are moving this out of the Java glue `MarkingDelegate`, and in to the OMR `MarkingScheme`?

Thanks, you're right. That was in error. MarkingScheme should call the glue for that rather than the other way around. The idea here is that the MetronomeMarkingScheme can implement its own version.

**Comment by jason-hall** [comment]
@youngar If you could take another look, this is now a very small change

**Comment by youngar** [comment]
@genie-omr build all

**Pull request merged**
