### PR TITLE
Deprecate getFirstReadWriteMemoryReference

### PR DESCRIPTION
**Pull request by fjeremic**
This function is no longer used and is not needed.

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
@genie-omr build zlinux,zos

**Comment by 0xdaryl** [comment]
Please change the copyright header to 2020.

**Comment by fjeremic** [comment]
> Please change the copyright header to 2020.

Fixed in cda8169

@genie-omr build zlinux,zos

**Comment by 0xdaryl** [comment]
The previous CI testing passed, and the recent commit is only a minor comment change.  Merging.

**Pull request merged**
