### PR TITLE
WIP: Move Metronome to OMR from OpenJ9

### PR DESCRIPTION
**Pull request by jason-hall**
Added notes to Issue #2949. Change requires review. I think I've got it reasonably fixed up.

This OpenJ9 commit depends on this: https://github.com/jason-hall/openj9/commit/79a3758cb009413cd0acc1f3ff66427bf273c9d3

### CODE REVIEW

**Comment by mstoodle** [comment]
I don't suppose you could provide a little bit more context for why you want to move this entire collector out of OMR?

**Comment by 0xdaryl** [comment]
Thank you for the contribution.  I believe a change of this magnitude also requires an Eclipse CQ (https://projects.eclipse.org/projects/technology.omr) before it can be merged.

**Comment by charliegracie** [comment]
I will open the CQ for this later today. 

I am working my way through the review.... @youngar and @dmitripivkine can you take a look through as well?  Thanks

**Comment by Leonardo2718** [comment]
@jason-hall and @charliegracie any updates?

**Comment by amicic** [comment]
Commiters, please close this PR. This work was broken down into a series of smaller changes.

**Pull request closed without merging**
