### PR TITLE
Use a deque for collecting internal labels

### PR DESCRIPTION
**Pull request by lmaisons**
The isInternalControlFlowOneEntryOneExit helper function in the z
version of OMRInstruction.cpp uses a CS2::ArrayOf local to accumulate
known labels for use in determining whether or not branch instructions'
targets are either local or non-local.  This change set replaces that
container with a TR::deque, and changes the iteration of the container
from using an integer index to using iterators.  Finally, this change
adds a break statement if we find a matching label to avoid needlessly
continuing through the container after we have a confirmed match.

Signed-off-by: Luc des Trois Maisons <lmaisons@ca.ibm.com>

### CODE REVIEW

**Comment by lmaisons** [comment]
@fjeremic A change in z/codegen/OMRInstruction.cpp that you may want to review.

**Comment by fjeremic** [comment]
LGTM. Small typo in the commit message: accumulate**d** should be accumulate.

**Comment by lmaisons** [comment]
The typo should be fixed now.

**Comment by vijaysun-omr** [comment]
Looks good. I will merge now.

**Pull request merged**
