### PR TITLE
FIX #3 Test GLIBC version for sigvec macros

### LINKED ISSUE #3: omrsig fails to build against glibc 2.21 or newer

### PR DESCRIPTION
**Pull request by youngar**
The BSD signal API, sigvec, has been removed from GLIBC since version
2.21.

Issue: #3

### CODE REVIEW

**Comment by alin00** [comment]
This check could also have been done by configure.

**Comment by charliegracie** [comment]
@alin00 you made some comments on this issue.  Is something you are handling or do you want someone else to work on getting the PR accepted?

**Comment by youngar** [comment]
Here is it with autoconf, please let me know if it is preferred. https://github.com/youngar/omr/commit/15e814c735b80284d6d1767647a2c8ff189d10f1

**Comment by alin00** [comment]
I prefer the autoconf approach, but I don't think we need the --enable/disable option to allow the user to override.

**Comment by alin00** [comment]
This fix doesn't completely address the comment raised by @rwy0717 in #3:

>  ... sigvec is still exported by glibc. ... So in the case where a native was compiled against an older version of glibc, omrsig can be defeated.

We haven't got a story for how to also require an omrsig built on an older glibc.

I do think this PR improves the status quo, so I will accept this fix approach.

**Comment by alin00** [comment]
Sigh, I have a bad feeling that AC_CHECK_FUNC() might not work if we're cross-compiling (e.g. Linux ARM).  Can you test this?  If AC_CHECK_FUNC() doesn't work, then your original approach of testing glibc version will have to do.

**Comment by alin00** [comment]
@youngar tells me that AC_CHECK_FUNC() works fine when cross-compiling, but doesn't work when we're _cross-configuring_.  Cross-configuring is a weird build mode that we use for building the J9 JVM.  So we'll have to go with the originally proposed patch, with the glibc version check.

Patch 19a61fa looks ok.  I'll just run it through some testing before merging.

**Pull request merged**
