### PR TITLE
Adding helper functions for crc32 special routines to enable optimizations in AOT

### PR DESCRIPTION
**Pull request by bhavanisn**
This issue was caused as one of the special crc32 routine was not AOT-enabled. Adding code to enable AOT for all related methods.

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Jenkins build all

**Comment by 0xdaryl** [comment]
Jenkins build xlinux,x32linux

**Comment by 0xdaryl** [comment]
The code changes are fine.  A couple of minor requests:
1) Remove the "Closes: 17444" message from the PR which will cause that issue to close once this PR is merged.  I don't think this PR alone fixes that problem.
2) Please add a more meaningful commit message to the commit describing the change you're making in the OMR code base.  "Fix the regression..." does not describe the change you made.

**Comment by 0xdaryl** [comment]
Thanks for changing the PR text, but can you make the same changes to the commit message itself (i.e., in 6002ca73699c8412ff527752ac565d5fec2661c20 )?   Also, a commit title of "Adding helper functions for crc32 special routines" should be sufficient for that commit.

**Comment by bhavanisn** [comment]
> Thanks for changing the PR text, but can you make the same changes to the commit message itself (i.e., in 6002ca73699c8412ff527752ac565d5fec2661c20 )? Also, a commit title of "Adding helper functions for crc32 special routines" should be sufficient for that commit.

@0xdaryl Done the changes to the commit msg.

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
