### PR TITLE
Fix qualified name enum warnings in OMRLinkage.hpp

### PR DESCRIPTION
**Pull request by ishakbhatt**
Closes: #5171

Signed-off-by: Isha Bhatt <ibhatt@umich.edu>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Almost there!  Please squash your commits into one and I will launch CI tests.

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by ishakbhatt** [comment]
They have been merged into one commit.

**Comment by 0xdaryl** [comment]
Thanks  After you squashed your original commit messages are concatenated in the squashed commit.  Sorry for being pedantic, but could you edit the message to just use the second one?  i.e.,

```
Fix qualified name enum warnings in OMRLinkage.hpp

Closes: #5171
```

Thanks.

**Comment by ishakbhatt** [comment]
Done!

**Comment by ishakbhatt** [comment]
This was my first time making a PR. Learned some more stuff about git along the way that will help me at work. Thanks again for the help :)

**Pull request merged**
