### PR TITLE
AArch64: Add function to load address constant for relocation

### PR DESCRIPTION
**Pull request by Akira1Saitoh**
This commit adds `loadAddressConstantRelocatable` which is called
by `loadAddressConstant` when compiling relocatable code.

Signed-off-by: Akira Saitoh <saiaki@jp.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@dsouzai : would you mind reviewing at least the relocation parts of this please?

**Comment by Akira1Saitoh** [comment]
@dsouzai Thanks for your comment.
I think we do not have a plan to have different fixed sequences.

**Comment by Akira1Saitoh** [comment]
@dsouzai I changed the function not to use seq kind and TR_RelocationRecordInformation. Would you mind reviewing again? Thank you.

**Comment by knn-k** [comment]
@0xdaryl Could you merge this, please?

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Pull request merged**
