### PR TITLE
AArch64: Implement ifiucmpeq, iflcmpeq, iflucmpeq, etc.

### PR DESCRIPTION
**Pull request by knn-k**
This commit implements conditional branches of 32-bit unsigned
integer, and 64-bit signed/unsigned integer.

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
This depends on a change in #3386.

**Comment by knn-k** [comment]
Tests will be available in #3388.

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Comment by 0xdaryl** [comment]
This is an AArch64-specific change.  A full genie build is not required.

**Pull request merged**
