### PR TITLE
Implement ARM non-equality address comparisons

### PR DESCRIPTION
**Pull request by knn-k**
… and acmple.

Closes: #2133

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
This change looks good - thanks @knn-k! Could you please review your commit message and follow the guidelines in the Contributing.md in the root of the project? The summary should be a single line less than 50 characters with an additional informative message after. As a suggestion a summary along the lines of "Implement ARM non-equality address comparisons" with a detailed message would be one way to go.

**Comment by charliegracie** [comment]
genie-omr build all

**Comment by knn-k** [comment]
I modified the commit message following @andrewcraik's suggestion.

**Comment by 0xdaryl** [comment]
I'm sorry I didn't notice this until now, but could you squash the 3 commits in this PR into one prior to merging please?

**Comment by andrewcraik** [comment]
@knn-k the commit message in the new commit is much nicer - thank you! Please use that when you squash.

**Comment by 0xdaryl** [comment]
This is an ARM code generator specific change.  It is impossible that the zOS CI failures are related to this.  Merging.

**Pull request merged**
