### PR TITLE
Move all x86 mnemonics into the TR::InstOpCode class

### PR DESCRIPTION
**Pull request by fjeremic**
This is a continuation of #6020 which eliminates the ".temp.defines" file and finishes off moving all the x86 instruction mnemonics inside the `TR::InstOpCode` class. In addition we remove some x86 defined pseudo-instructions in favour of the cross platform ones. See each commit comment to understand what was done. Each individual commit builds on its own.

### CODE REVIEW

**Comment by fjeremic** [comment]
Most of the work here was automated using a quick and dirty script which for each opcode did a global search replace in the repo, and then I manually went in and verified every occurrence was correct. Here is the command used for one particular mnemonic:

```
grep -rl "SubRegImms" * | xargs gsed -i 's/\bSubRegImms\b/TR::InstOpCode::SubRegImms/g'
```

**Comment by fjeremic** [comment]
Jenkins build all

**Review by dsouzai — COMMENTED** [review]
Overall LGTM. I could be wrong, but should the last two commits be squashed (since I believe the second-last commit won't build since those methods got moved into the InstOpCode class)?

**Comment by fjeremic** [comment]
> Overall LGTM. I could be wrong, but should the last two commits be squashed (since I believe the second-last commit won't build since those methods got moved into the InstOpCode class)?

Yes we can do that. I separated them because I ran a script over the entire directory structure to patch up all the use cases, so then I could easily revert the false-positive hits in the OMRInstOpCode.hpp file, because the `TR` namespace does not exist there, and we have to use the `OMR` namespace in that file.

Do you want me to squash it now or wait for reviews from others?

**Comment by dsouzai** [comment]
> Do you want me to squash it now or wait for reviews from others (anyone else want to review?)?

I don't know if anyone else is currently reviewing, so if you'd like you can wait till tomorrow. Also if you're going to squash, you can also update the copyrights; most of the changed files haven't been updated to 2021.

I'll do the coordinated merge tomorrow.

**Comment by fjeremic** [comment]
> I don't know if anyone else is currently reviewing, so if you'd like you can wait till tomorrow. Also if you're going to squash, you can also update the copyrights; most of the changed files haven't been updated to 2021.

Squashed the two commits and fixed up the copyrights in a [force-push](https://github.com/eclipse/omr/compare/c37b7d335937c793e2ae96d0fface38e94e65cc8..f7368dd82e95798fb4eb3c713d2437ebd1a05caa).

**Comment by fjeremic** [comment]
Jenkins build all

**Comment by fjeremic** [comment]
Jenkins build riscv

**Pull request merged**
