### PR TITLE
Reduce use of OMR_HOST_OS

### PR DESCRIPTION
**Pull request by keithc-ca**
* prefer flags over string comparisons

Flag            | Replaces
:---            | :-------
OMR_OS_AIX      | OMR_HOST_OS STREQUAL "aix"
OMR_OS_BSD      | OMR_HOST_OS STREQUAL "bsd"
OMR_OS_LINUX    | OMR_HOST_OS STREQUAL "linux"
OMR_OS_OSX      | OMR_HOST_OS STREQUAL "osx"
OMR_OS_WINDOWS  | OMR_HOST_OS STREQUAL "win"
OMR_OS_ZOS      | OMR_HOST_OS STREQUAL "zos"

See OmrDetectSystemInformation.cmake.
See also eclipse/openj9#12048.

### CODE REVIEW

**Review by fjeremic — APPROVED** [review]

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by keithc-ca** [comment]
Added missing space after `AND`.

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
OSX failure is due to infra.

**Pull request merged**
