### PR TITLE
Runtime compressed refs work

### PR DESCRIPTION
**Pull request by gacholio**
Add instance APIs to adjust the slot address in SlotObject.

Signed-off-by: Graham Chapman <graham_chapman@ca.ibm.com>

### CODE REVIEW

**Comment by gacholio** [comment]
@dmitripivkine @amicic

**Comment by gacholio** [comment]
Can I get some action here?

**Comment by amicic** [comment]
What's a larger plan here  - to remove static API (including downstream projects) eventually?

**Comment by gacholio** [comment]
For this PR, the goal is to remove the instantiation of SlotObject in loops - create one outside the loop and update it.

I'm not sure this will matter if we split enough of the code earlier, but it seems like a sensible direction to go.

**Comment by rwy0717** [comment]
@genie-omr build all

**Pull request merged**
