### PR TITLE
Resolve zOS linking issue

### PR DESCRIPTION
**Pull request by charliegracie**
By default the xlc compiler on zOS requires the object files to
appear last on the link line.

[ci skip] [skip ci] zOS only

Signed-off-by: Charlie Gracie <charlie.gracie@gmail.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
genie-omr build zos

**Comment by charliegracie** [comment]
genie-omr build zos

**Comment by charliegracie** [comment]
genie-omr build zos

**Comment by charliegracie** [comment]
genie-omr build zos

**Comment by joransiu** [comment]
genie-omr build zos

**Comment by joransiu** [comment]
genie-omr build zos

**Comment by joransiu** [comment]
genie-omr build zos

**Comment by joransiu** [comment]
genie-omr build zos

**Comment by joransiu** [comment]
genie-omr build zos

**Comment by joransiu** [comment]
genie-omr build zos

**Comment by joransiu** [comment]
genie-omr build zos

**Comment by charliegracie** [comment]
@joransiu successfully got the zOS build working! This PR is ready to go

**Pull request merged**
