### PR TITLE
RISC-V: call generateVFTMaskInstruction() from aloadEvaluator()

### PR DESCRIPTION
**Pull request by janvrany**
In OpenJ9, classes are aligned on 256-bit boundaries, and the low 8
bits of the class pointer in the object header are used for flags.
So to get the proper class pointer we have to clear the flags using
(OpenJ9 specific) generateVFTMaskInstruction().

### CODE REVIEW

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by janvrany** [comment]
@0xdaryl , @mstoodle : may I kindly ask for review?

**Review by 0xdaryl — CHANGES_REQUESTED** [review]
I'm not super thrilled about introducing an OpenJ9-specific macro, but this is how the other architectures have implemented it.

Can you fix the copyright header to 2023 please?

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by janvrany** [comment]
> I'm not super thrilled about introducing an OpenJ9-specific macro, but this is how the other architectures have implemented it.

I know. I considered overriding `aloadEvaluator` in OpenJ9 but that would duplicate this method only with that one `if` added so in the end I fell back to "what everybody else is doing". 
Is there better way? If so, I'm happy to rewrite the code. 

> 
> Can you fix the copyright header to 2023 please?

Done.

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by janvrany** [comment]
Last two CI runs failed due to a problem in thread tests, probably this issue: https://github.com/eclipse/omr/issues/6706

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by janvrany** [comment]
RISC-V build failed because of unrelated failure in `PortSignalExtendedTests` that should be fixed by #6938

**Comment by janvrany** [comment]
jenkins build riscv

**Comment by janvrany** [comment]
#6938 has been merged so tests are all passing, maybe this can be merged now?

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
