### PR TITLE
Remove J9 from omrsig* code [Part 1]

### PR DESCRIPTION
**Pull request by babsingh**
J9 was removed or renamed to OMR in the internal structures, functions and comments used in the omrsig library.

These changes don't impact external projects.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by babsingh** [comment]
@youngar can you please review these changes? the renaming is done for internal structures so downstream projects such as OpenJ9 aren't impacted.

fyi - @DanHeidinga @charliegracie

**Comment by youngar** [comment]
Thanks for taking the time to do this @babsingh

**Comment by babsingh** [comment]
Forgot to update the year in the copyrights. I will create a new pull request to update the copyrights.

**Pull request merged**
