### PR TITLE
Removed some unused functions in the code

### LINKED ISSUE #2452: AArch32: remove unused functions from Register class
Remove unused functions from `arm/codegen/OMRRegister.hpp`:
```
bool isFlippedCCR()
void setFlippedCCR()
void resetFlippedCCR()

   enum
      {
      FlipBranchOffThisCCR          = 0x4000, // PPC may have swapped register positions in compare
      };
```

### PR DESCRIPTION
**Pull request by PeXXeR**
Removed some of the unused code from Register class for arm

Fixes #2452

Signed-off-by: Somesh Sharma <someshsharma0312@gmail.com>

### CODE REVIEW

**Comment by PeXXeR** [comment]
@Leonardo2718 Thanks for reviewing the changes.
Just one thing - The contribution guidelines say use "Closes: #2452".
So, is it Closes or Fixes.
Can you please confirm ?

**Comment by fjeremic** [comment]
> @Leonardo2718 Thanks for reviewing the changes.
> Just one thing - The contribution guidelines say use "Closes: #2452".
> So, is it Closes or Fixes.
> Can you please confirm ?

@PeXXeR any of them will work. Please see [1] for details on how GitHub handles these keywords.

[1] https://help.github.com/articles/closing-issues-using-keywords/

**Comment by Leonardo2718** [comment]
@genie-omr build arm

**Comment by Leonardo2718** [comment]
This is an arm specific change so testing on other platforms is not required. Merging.

**Pull request merged**
