### PR TITLE
Create patch site for merged OSR guard for X and Z

### PR DESCRIPTION
**Pull request by liqunl**
Patch site is missed on a runtime guard merged with OSR guard, resulting
a missing of class redefinition assumption in nextGenHCR.

Signed-off-by: Liqun Liu <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@fjeremic @andrewcraik Can you review? Will remove the WIP once the pbuild finishes and passes. @gita-omr @JamesKingdon Correct me if I'm wrong, the logic for creating site on merged HCR or OSR guard is missing on p and arm, you may need to put the logic in your codegen.

**Comment by liqunl** [comment]
Change has been fully tested.

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by gita-omr** [comment]
@liqunl thanks for letting know. We will check what needs to be done on Power.

**Pull request merged**
