### PR TITLE
Replace uses of CS2::ArrayOf and CS2::StaticArrayOf from TR_Dominators

### PR DESCRIPTION
**Pull request by lmaisons**

### CODE REVIEW

**Comment by 0xdaryl** [comment]
The changes in each of these commits look good to me.  Good work untangling and replacing this logic.  @vijaysun-omr  @andrewcraik , do you want to review?

**Comment by vijaysun-omr** [comment]
@lmaisons Do you have a sense re: performance differences/tradeoffs in using the TR::deque vs the CS2 structures being replaced ? 
I presume there will be similar changes in other files that use CS2 at present and so I wanted to get your view on what your general expectation is, performance-wise.

**Comment by lmaisons** [comment]
The CS2::ArrayOf implementation uses fixed-size blocks allocated one-to-one with the number of elements in the container.  The std::deque implementation is close to or the same to this, though the size of the chunks varies significantly from platform to platform.

I don't expect a significant performance impact of replacing CS2::ArrayOf with std::deque, though I would like to test this once we have a likely critical mass of them replaced.  Perhaps combining these changes with the outstanding changes to UseDefInfo would be appropriate for testing.

**Comment by vijaysun-omr** [comment]
Okay thanks. I would appreciate a performance test once you combine these changes with pull request 512. I will merge this in now.

**Pull request merged**
