### PR TITLE
Delete zeroOutAutoOnEdge implementation

### PR DESCRIPTION
**Pull request by nanjekyejoannah**
This PR deletes the zeroOutAutoOnEdge supporting code (functions, fields, data structures, etc.) from OMR.

This follows a [PR I opened](https://github.com/eclipse/openj9/pull/3426)  to move the zeroOutAutoOnEdge functionality to OpenJ9. 

Please note that the PR on OpenJ9 should be merged before this one.

Closes: #1866
Signed-off-by: nanjekyejoannah <nanjekyejoannah@gmail.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Thanks for addressing this @nanjekyejoannah. The change is good, however we need some small stylistic changes to the formatting so as to keep the commit history in healthy condition by having consistent commit formatting. We'll need some changes to the commit according to the contribution guidelines [1]:

> The first line should be less than 70 characters, where reasonable, and should be written in sentence case preferably _not ending in a period_. Leave a blank line between the first line and the message body.

I've amended your PR description to speed up the process. The "Closes" tag does not work if you have anything other than the PR number after it, so the "OMR" is confusing it. See [2] for more details.

[1] https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md#commit-guidelines
[2] https://help.github.com/articles/closing-issues-using-keywords/

**Comment by nanjekyejoannah** [comment]
Thanks for the insight @fjeremic I will note for next PRs.

**Comment by fjeremic** [comment]
> Thanks for the insight @fjeremic I will note for next PRs.

Awesome, just confirming you'll need to amend the commit message (no to be confused with PR description and title) before we can approve.

**Comment by nanjekyejoannah** [comment]
@fjeremic Just confirming, Am I to make the commit message the same as the PR I opened on openJ9? i. e"Move zeroOutAutoOnEdge to OpenJ9"

**Comment by fjeremic** [comment]
> @fjeremic Just confirming, Am I to make the commit message the same as the PR I opened on openJ9? i. e"Move zeroOutAutoOnEdge to OpenJ9"

It doesn't have to be, but it is usually intuitive this way. When you forge your commit you typically add all the information into the commit message itself. Then when you go to GitHub to open up the PR GitHub will automatically extract the contents of your commit and create the same PR title and description. This only works if you have a single commit in your PR (such as this one).

**Comment by fjeremic** [comment]
@genie-omr build all

**Pull request merged**
