### PR TITLE
Improve/fix certain multiplication evaluators on Z

### PR DESCRIPTION
**Pull request by NigelYiboYu**
Improve/fix certain multiplication evaluators on Z

    -- Add MFY and MHY as recognized instructions

    -- Let z codegen emit MH, which can be adjusted to MHY

    -- Fix imulh and iumulh evaluator so that it generates correct
    instructions

    -- Add compilertest test cases for imulh and iumulh

    Issue: 462

    Signed-off-by: Nigel Yu <yunigel@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
LGTM.

**Comment by mstoodle** [comment]
Thanks @NigelYiboYu. It's really nice to see a compiler change made along with new tests related to the change! I didn't look very carefully at the values used for the tests you added for mulh; I assume you checked that they do produce results that are nonzero in the upper 32-bits?

Would you please add an Issue: 462 line to your commit message (assuming I'm connecting the right issue & PR). And is the task number absolutely necessary, given that's an IBM internal number that doesn't mean anything in the OMR project?

Thanks for the review @fjeremic .

**Comment by NigelYiboYu** [comment]
@mstoodle Yes, the new test cases I added check multiplication results and make sure imulh/iumulh produce high order 32 bits of the 64-bit multiply results.

I've added the 'Issue: 462' line and removed the 'Task: #' line.

**Comment by mstoodle** [comment]
Ack! Sorry @NigelYiboYu I lost track of this one (you should have pinged me about it!).

**Pull request merged**
