### PR TITLE
Revert "DDR: add support for xlc/xlclang version 16"

### PR DESCRIPTION
**Pull request by keithc-ca**
This causes problems for building openj9 on AIX (all versions) and on OSX.
I expect updating the AIX build machines with the new version of `dump` required for use with xlclang 16 with fix that platform, but I'd like to understand the OSX problem rather than doing anything hasty.

Reverts eclipse/omr#4620

### CODE REVIEW

**Comment by keithc-ca** [comment]
@youngar - FYI

**Comment by youngar** [comment]
You can sign the commit with `git commit --amend -s`

**Comment by keithc-ca** [comment]
Commit amended as requested.

**Comment by youngar** [comment]
thanks @keithc-ca

**Pull request merged**
