### PR TITLE
Code cleanup - reduce compilation warnings

### PR DESCRIPTION
**Pull request by 0dvictor**
Eliminated compilation warnings related to X86 binary encoding.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
why so many whitespace changes mixed with the functional changes? it is a bit hard to review...

**Comment by 0dvictor** [comment]
They are actually not whitespace changes. The property querying functions are changed from `TYPE FUNC()` to `inline TYPE FUNC() const`.

**Comment by andrewcraik** [comment]
I see that there are real changes, they are just intermixed with whitespace changes which just makes reviewing harder.

**Comment by 0dvictor** [comment]
Good point, I've separate them into two commits.

**Comment by andrewcraik** [comment]
The refactored commits diff very nicely - I think this is LGTM. @0xdaryl can you please review?

**Comment by andrewcraik** [comment]
The warnings in the x86 builds a quite annoying due to their verbosity could we please get this reviewed for merging to get the builds cleaned up please @0xdaryl ?

**Pull request merged**
