### PR TITLE
Provide options to enable read-only code generation

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Provide options to specify generating a read-only code cache
* Set Compilation flag enabling read only code

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by vijaysun-omr** [comment]
Is the plan to generate calls to different run time helpers depending on this compilation flag ? i.e. different run time helpers that would not do code patching for example ?

**Comment by 0xdaryl** [comment]
That's one way it could be used.  Typically, the code leading up to calling those runtime helpers would need to change too.  For example, in the OpenJ9 project that uses self-modifying code in its polymorphic inline caches for interface and virtual dispatches the shape of those PICs would have to change in addition to calling different runtime helpers.

These commits don't specify how these flags are consumed by a language runtime, but simply introduce them.

**Comment by vijaysun-omr** [comment]
Thanks, this is a safe change to add some options and flags that will be used for generating read-only code. Test have passed and so I'm merging.

**Pull request merged**
