### PR TITLE
WIP: update copyrights on util/ & tools/ to EPLv2 & Apache v2

### PR DESCRIPTION
**Pull request by DanHeidinga**
Update the license as per the outcome of the vote in issue #1596.

This can't be accepted until all contributors in #1606 have signed off on the relicensing their contributions.

Signed-off-by: Dan Heidinga <daniel_heidinga@ca.ibm.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
This will need to be rebased.

There were last minute changes to the copyright header which will need to be incorporated into these changes.  You can see this change in #1606 

The failure on OSX is not real so do not worry about it.

**Comment by charliegracie** [comment]
Also for updating the configure file did you just update the configure.ac and run autoconf or did you manually update it?

**Comment by DanHeidinga** [comment]
For configure.ac, I manually updated the file.  I've basically been running a massive search/replace over the code base

**Comment by DanHeidinga** [comment]
Closing this in favour of #1622 which has the correct copyrights.

**Pull request closed without merging**
