### PR TITLE
Only unblock an asynchronous signal if it is used 

### PR DESCRIPTION
**Pull request by babsingh**
Currently, all supported asynchronous signals are unblocked during
startup. A signal is unblocked even when a signal handler is not
installed for it. This conflicts with an OMR consumer, who wants to
block a set of signals. The OMR consumer blocks a set of signals but the
OMR signal library unblocks those signals at startup. OMR signal library
should only unblock a signal if a signal handler is registered for it.
In other words, a signal should not be unblocked if it is not used i.e.
a signal handler is not registered for it. 

**Related:**
1. [Customer Issue (IntelliJ IDE doesn't receive signals; 28th Oct. 2018)](https://github.com/eclipse/openj9/issues/3468)
2. [OMR Fix (Handle signals blocked by a parent process; 23rd Nov. 2018)](https://github.com/eclipse/omr/pull/3225)
3. [Add support for new signals (SIGUSR1, SIGUSR2, ...; 15th April 2019)](https://github.com/eclipse/omr/pull/3737)

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by babsingh** [comment]
## Performance Results

### Compile the micro-benchmark
```
gcc -pthread -O3 benchmark_pthread_sigmask.c -o benchmark_pthread_sigmask
```

### Run the micro-benchmark
```
/usr/bin/time -v ./benchmark_pthread_sigmask <ITERATIONS>
```

### Elapsed time
| Number of ITERATIONS | Elapsed time (m:ss) |
---- | ----
| 1 | 0:00.00 |
| 10 | 0:00.00 |
| 100 | 0:00.00 |
| 1000 | 0:00.01 |
| 1000 | 0:00.14 |

Currently, `pthread_sigmask` is invoked once at startup for all the supported signals. With this fix, `pthread_sigmask` will be invoked everytime a signal handler is installed for a signal. Generally, a master handler is only installed once for a signal. Before this fix, `pthread_sigmask` is invoked once. After this fix, `pthread_sigmask` will be invoked ~32 times (== number of signals). 

Each iteration of the micro-benchmark invokes `pthread_sigmask` 32 times. **The above results for the elapsed time suggest that this fix will have negligible impact on performance.**

### Micro-benchmark (benchmark_pthread_sigmask.c):
```
#include <stdio.h>
#include <signal.h>
#include <stdlib.h>

static int
unblockSignal(int signal)
{
	int rc = 0;
	sigset_t signalSet;

	rc = sigemptyset(&signalSet);
	if (0 != rc) {
		goto exit;
	}

	rc = sigaddset(&signalSet, signal);
	if (0 != rc) {
		goto exit;
	}

	/* Unblock the signal. */
	rc = pthread_sigmask(SIG_UNBLOCK, &signalSet, NULL);
exit:
	return rc;
}

int main(int argc,char* argv[]) 
{
	int i = 0;
	int j = 0;
	int rc = 0;
	int iterations = 0;
	int signals[] = {SIGHUP, SIGINT, SIGQUIT, SIGILL, SIGTRAP, SIGABRT, SIGBUS, SIGFPE, SIGKILL, SIGUSR1, SIGSEGV, SIGUSR2, SIGPIPE, SIGALRM, SIGTERM, SIGSTKFLT, SIGCHLD, SIGCONT, SIGSTOP, SIGTSTP, SIGTTIN, SIGTTOU, SIGURG, SIGXCPU, SIGXFSZ, SIGVTALRM, SIGPROF, SIGWINCH, SIGIO, SIGPWR, SIGSYS};
	int numSignals = (int)sizeof(signals)/sizeof(signals[0]);
	if (argc !=2) {
		printf("Error: Number of iterations not provided.\n");
		exit(-1);
	}
	
	iterations = atoi(argv[1]);
	if (iterations <= 0) {
		printf("Error: Number of iterations is not a valid positive integer\n");
		exit(-1);
	}

	for (i = 0; i < iterations; i++) {
		for (j = 0; j < numSignals; j++) {
			rc = unblockSignal(signals[j]);
			if (0 != rc) {
				printf("Error: Unable to unblock signal=%d j=%d\n", signals[j], j);
				exit(-1);
			}
		}
	}

	return rc;
}
```

**Comment by babsingh** [comment]
Initial testing looks good. Awaiting for test results from customer's nightly build. Code is ready-to-be-reviewed. But it should not be merged until test results from customer's nightly build are received.

**Comment by babsingh** [comment]
The failures have been resolved in the customer's nightly build. So, this pull request can be merged after the code-review.

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by Leonardo2718** [comment]
FYI: I'm manually stopping some tests for this PR that look like they've been hanging since November 18.

**Comment by babsingh** [comment]
@rwy0717 Unrelated errors were happening in the CI build jobs. Can you please retry the builds?

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by youngar** [comment]
@genie-omr build x32linux

**Pull request merged**
