### PR TITLE
Build liveness with real uses on OSR points

### PR DESCRIPTION
**Pull request by cathyzhyi**
OSRUses under prepareForOSR prolong the live range of autos and
pending push temps. Especially, those fake uses can cause many
autos and temps appear to be alive at the method entry and requires
zero initialization in the method prologue which is big overhead.

A way to solve this problem is to find out the real uses
of those autos and pending push temps at each OSRPoint and use them
during liveness analysis. The real uses can be found by figuring
out which symbols are needed to calculate the auto or temps at each
prepareForOSRCall and combining this with the liveness information
for the autos and temps from original bytecode.

This changeset changes liveness analysis to consider real uses at
each OSRPoint.

Signed-off-by: Yi Zhang <yizhang@ca.ibm.com>

### CODE REVIEW

**Comment by cathyzhyi** [comment]
This PR is dependent on https://github.com/eclipse/omr/pull/2006

**Comment by andrewcraik** [comment]
I'll take a look, but an opinion from @ncough would also be helpful.

**Comment by ncough** [comment]
LGTM

**Comment by vijaysun-omr** [comment]
genie-omr build all

**Comment by cathyzhyi** [comment]
This change has passed tests and ready to be merged.

**Comment by vijaysun-omr** [comment]
Could you please re-base this change ? I can merge once you do so.

**Comment by cathyzhyi** [comment]
@vijaysun-omr  Rebased to the newest version. Thanks!

**Comment by vijaysun-omr** [comment]
Tests have passed. Merging.

**Pull request merged**
