### PR TITLE
WIP: Avoid generating redundant gotos in simplifier

### PR DESCRIPTION
**Pull request by jdmpapin**
Simplifier's partialRedundantCompareElimination() could sometimes
generate redundant gotos, if the fallthrough successor of the original
conditional is just a goto. Now in that case it will try to skip over
the intermediate goto.

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by vijaysun-omr** [comment]
This looks okay on it's own but is'nt this kind of thing cleaned up by the rest of the optimizer afterwards ? Maybe it's just that in the specific case you were looking at, there is no pass afterwards in the opt strategy and it's easy enough to clean this up at the source, that you felt you should just clean it up.

**Comment by jdmpapin** [comment]
In the case I saw, it doesn't yet get cleaned up afterwards. I was in the process of adding a very late pass of redundant goto elimination (see #2444), but with the intention that it should run only on particular blocks discovered by dead trees elimination. Since this goto is already redundant, it won't be discovered that way.

However, it turns out that there's already a later pass of redundant goto elimination in my case, and that pass also doesn't fix the gotos. The reason is that there's one predecessor that falls through, so redundant goto elimination can't delete the block from the CFG. I've since addressed that elsewhere: "Remove redundant gotos more opportunistically" in #2444 allows redundant goto elimination to redirect all of the *other* predecessors. So perhaps that change obviates this one.

**Comment by vijaysun-omr** [comment]
Just checking : do you still want to go ahead with this change then ?

**Comment by jdmpapin** [comment]
I've marked this WIP for the time being. Later depending on #2444 I'll either close this one or remove WIP.

**Comment by jdmpapin** [comment]
Closing since #2444 has been merged, and as mentioned above one of its commits makes this unnecessary

**Pull request closed without merging**
