### PR TITLE
Remove deprecated restricted register support from Z

### PR DESCRIPTION
**Pull request by 0xdaryl**
Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@genie-omr build zlinux,zos

**Comment by 0xdaryl** [comment]
@joransiu : this is the corresponding OMR PR for eclipse/openj9#2265.  Please review.

**Comment by 0xdaryl** [comment]
Is there anything preventing this from being merged @vijaysun-omr ?

**Comment by vijaysun-omr** [comment]
Safe change to do clean up.

**Pull request merged**
