### PR TITLE
Consolidate data size check helpers on X86

### PR DESCRIPTION
**Pull request by 0dvictor**
Move data size check helpers into shared header file: env/jittypes.h

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
I wonder if such macros would be generally useful outside of the x86 codegen (there's nothing x86-specific about them).  Perhaps relocating them to `env/jittypes.h` would be a better place?

**Comment by 0dvictor** [comment]
> I wonder if such macros would be generally useful outside of the x86 codegen (there's nothing x86-specific about them). Perhaps relocating them to `env/jittypes.h` would be a better place?

Good suggestion, I've moved them into `env/jittypes.h`. Note that I did not move `IS_32BIT_RIP` as it is a X86-specific query.

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
Please update the copyright header in jittypes.h

**Comment by 0dvictor** [comment]
> Please update the copyright header in jittypes.h

Updated.

**Comment by 0xdaryl** [comment]
@genie-omr build all

Sorry, I have to restart these as they were lost once the new commit was pushed and I didn't have a chance to see what their status was after the first set of builds.

**Pull request merged**
