### PR TITLE
Fix sched_getaffinity and sched_setaffinity errors

### PR DESCRIPTION
**Pull request by bharathappali**
This PR is a part of the group of PR's that were/will be raised as a fix for issue #3774

In musl environment the OMR build fails with :
```
./linux/omrthreadnuma.c: In function 'omrthread_numa_init':
./linux/omrthreadnuma.c:292:19: error: missing binary operator before token "("
 #if __GLIBC_PREREQ(2,4) || defined(LINUXPPC)
                   ^
./linux/omrthreadnuma.c:300:32: error: passing argument 2 of 'sched_getaffinity' makes integer from pointer without a cast [-Werror=int-conversion]
  if (0 != sched_getaffinity(0, &defaultAffinityMask))
                                ^
In file included from ./linux/omrthreadnuma.c:36:0:
/usr/local/x86_64-linux-musl/include/sched.h:82:5: note: expected 'size_t {aka long unsigned int}' but argument is of type 'cpu_set_t * {aka struct cpu_set_t *}'
 int sched_getaffinity(pid_t, size_t, cpu_set_t *);
     ^~~~~~~~~~~~~~~~~
./linux/omrthreadnuma.c:300:11: error: too few arguments to function 'sched_getaffinity'
  if (0 != sched_getaffinity(0, &defaultAffinityMask))
           ^~~~~~~~~~~~~~~~~
In file included from ./linux/omrthreadnuma.c:36:0:
/usr/local/x86_64-linux-musl/include/sched.h:82:5: note: declared here
 int sched_getaffinity(pid_t, size_t, cpu_set_t *);
     ^~~~~~~~~~~~~~~~~
./linux/omrthreadnuma.c: In function 'omrthread_numa_set_node_affinity_nolock':
./linux/omrthreadnuma.c:391:19: error: missing binary operator before token "("
 #if __GLIBC_PREREQ(2,4) || defined(LINUXPPC)
                   ^
./linux/omrthreadnuma.c:399:44: error: passing argument 2 of 'sched_setaffinity' makes integer from pointer without a cast [-Werror=int-conversion]
    if (0 != sched_setaffinity(thread->tid, &affinityCPUs))
                                            ^
In file included from ./linux/omrthreadnuma.c:36:0:
/usr/local/x86_64-linux-musl/include/sched.h:83:5: note: expected 'size_t {aka long unsigned int}' but argument is of type 'cpu_set_t * {aka struct cpu_set_t *}'
 int sched_setaffinity(pid_t, size_t, const cpu_set_t *);
     ^~~~~~~~~~~~~~~~~
./linux/omrthreadnuma.c:399:13: error: too few arguments to function 'sched_setaffinity'
    if (0 != sched_setaffinity(thread->tid, &affinityCPUs))
             ^~~~~~~~~~~~~~~~~
In file included from ./linux/omrthreadnuma.c:36:0:
/usr/local/x86_64-linux-musl/include/sched.h:83:5: note: declared here
 int sched_setaffinity(pid_t, size_t, const cpu_set_t *);
     ^~~~~~~~~~~~~~~~~
./linux/omrthreadnuma.c: In function 'omrthread_numa_get_node_affinity':
./linux/omrthreadnuma.c:460:19: error: missing binary operator before token "("
 #if __GLIBC_PREREQ(2,4) || defined(LINUXPPC)
                   ^
./linux/omrthreadnuma.c:468:44: error: passing argument 2 of 'sched_getaffinity' makes integer from pointer without a cast [-Werror=int-conversion]
    if (0 == sched_getaffinity(thread->tid, &affinityCPUs))
                                            ^
In file included from ./linux/omrthreadnuma.c:36:0:
/usr/local/x86_64-linux-musl/include/sched.h:82:5: note: expected 'size_t {aka long unsigned int}' but argument is of type 'cpu_set_t * {aka struct cpu_set_t *}'
 int sched_getaffinity(pid_t, size_t, cpu_set_t *);
     ^~~~~~~~~~~~~~~~~
./linux/omrthreadnuma.c:468:13: error: too few arguments to function 'sched_getaffinity'
    if (0 == sched_getaffinity(thread->tid, &affinityCPUs))
             ^~~~~~~~~~~~~~~~~
In file included from ./linux/omrthreadnuma.c:36:0:
/usr/local/x86_64-linux-musl/include/sched.h:82:5: note: declared here
 int sched_getaffinity(pid_t, size_t, cpu_set_t *);
     ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[5]: *** [../omrmakefiles/rules.mk:372: omrthreadnuma.o] Error 1
make[4]: *** [GNUmakefile:284: thread] Error 2
make[4]: *** Waiting for unfinished jobs....
```

**Note:**
I have added the code in a view that `-DMUSL` is added to the complier flags.

**Build System Changes**
Flags to be added : `-DMUSL`

This item is still **Work In Progress** as only compile error are being resolved as of now, Will be ready to be reviewed after checking if no runtime errors are found as well after completing musl support

Signed-off-by: bharathappali <bharath.appali@gmail.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
I do not believe this is the correct fix. The missing MACRO could be defined on GLOBC platforms that does not have the macro or the macro could be replaced with a check on the major and minor version directly.

**Comment by rwy0717** [comment]
If we can, I would like to remove this ifdef entirely, and only support 3-arg getaffinity.

The problem with 2-argument getaffinity is, it was only available for a single bugfix/patch release, before returning to 3 arguments. The manpage for sched_getaffinity says:

> The system call wrappers were introduced in glibc 2.3. Initially, the glibc interfaces included a cpusetsize argument, typed as unsigned int. In glibc 2.3.3, the cpusetsize argument was removed, but was then restored in glibc 2.3.4, with type size_t.

glibc does not provide a macro to test the patchlevel. If we cannot remove the ifdefs entirely, it may be enough to test for glib 2.3. That way, code like this:

```c++
#if defined(OMR_MUSL_CLIB)
	if (0 != sched_getaffinity(0, sizeof(cpu_set_t), &defaultAffinityMask))
#else
#if __GLIBC_PREREQ(2,4) || defined(LINUXPPC)
	/*
	 * LIR 902 : On Linux PPC, rolling up tool chain level to VAC 8 on RHEL 4.
	 * The libc version on RHEL 4 requires 3 arg to sched_setaffinity.
	 * Note: this will not compile/run properly on RHEL 3.
	 */
	if (0 != sched_getaffinity(0, sizeof(cpu_set_t), &defaultAffinityMask))
#else
	if (0 != sched_getaffinity(0, &defaultAffinityMask))
#endif
#endif /* defined(OMR_MUSL_CLIB) */
```

becomes something like this:

```c++
#if (__GLIBC__ == 2) && (__GLIBC_MINOR__ == 3)
	if (0 != sched_getaffinity(0, &defaultAffinityMask))
#else
	if (0 != sched_getaffinity(0, sizeof(cpu_set_t), &defaultAffinityMask))
#endif
```

and MUSL can have the correct implementation without specific handling.

**Comment by bharathappali** [comment]
@rwy0717 the new code looks good than the previous one, But i feel glibc specific macros might be missing in `MUSL`.

I need to check if `MUSL` has macro's which you mentioned `__GLIBC__` and `__GLIBC_MINOR__`

Will check it and get back to you. Thanks

**Comment by rwy0717** [comment]
What I'm hoping is that, these macros _will_ be missing, and MUSL will use the "good" code under the `#else` branch.

**Comment by 0xdaryl** [comment]
Closing per the [comment](https://github.com/eclipse/omr/issues/3774#issuecomment-776367630) in issue #3774.  Please feel free to continue to work on this in your private fork and re-open when you are ready to contribute again.

**Pull request closed without merging**
