### PR TITLE
Cmake: organize our utilities as cmake modules

### PR DESCRIPTION
**Pull request by rwy0717**
/cc @mgaudet @dnakamura
Signed-off-by: Robert Young <rwy0717@gmail.com>

### CODE REVIEW

**Comment by dnakamura** [comment]
LGTM

**Comment by mgaudet** [comment]
_nods_. I was thinking we ought to get to this at some point too. LGTM.

**Comment by rwy0717** [comment]
My thinking here is that this could help external projects consume our cmake utilities.

**Comment by charliegracie** [comment]
@rwy0717 this needs to be rebased I believe so that it can be auto merged.

**Comment by rwy0717** [comment]
Updated with rebase.

**Pull request merged**
