### PR TITLE
Build the Test compiler and JitBuilder on OS X

### PR DESCRIPTION
**Pull request by noryb009**
Build and test the Test compiler and JitBuilder on OS X using LLVM/clang. Currently, all tests pass.

Note that it is very likely there are more bugs on OS X which have not been caught by the small number of tests in the Test compiler and JitBuilder. These bugs will be triaged and fixed as they appear.

See the individual commit messages for explanations.

Issue: #223

### CODE REVIEW

**Comment by lmaisons** [comment]
>* `list::remove` in the C++ standard library tries to use the default   constructor for the allocator of the list. Since the allocator used in `TR::list` uses an allocator with a private constructor, this causes problems. Until this is resolved, implement `remove` ourselves.

Is there an upstream bug open for this?  This breaks using stateful allocators in STL containers which is supposed to be standard for at least C++11 onwards (and highly recommended for C++03)

**Comment by noryb009** [comment]
There isn't an upstream bug report yet, since I haven't had a chance to investigate whether the standard library or OMR is breaking the C++ standard.

**Comment by 0xdaryl** [comment]
Code changes look good.

Have you double checked every place in the omr/compiler code that references 'isLinux()' to check if there's anything that might need to be done for OSX?  Ditto for #ifdef's for the host or target LINUX macro.

The disposition of the `list::remove` code and your outreach to the LLVM community can be documented in the umbrella issue.

**Comment by noryb009** [comment]
I have looked at the guards: a few have been enabled, if it is known the associated code is supported (see the latest commit). However, many were left alone, since they are not tested at all in the Test compiler or JitBuilder - these will need to be revisited as downstream projects start to support OS X.

**Pull request merged**
