### PR TITLE
Z: Fix arraycmplen opcode error

### PR DESCRIPTION
**Pull request by ehsankianifar**
The isArrayCmpSign function accept only arraycmp opcode.
Removed from arraycmplen since sign doesnt mean anything there

Fix: #7136
Signed-off-by: ehsan kiani far ehsan.kianifar@gmail.com

### CODE REVIEW

**Comment by ehsankianifar** [comment]
Testing:
used ArrayTest in compiler tril tests and manually changed the code to enable SIM path. I can confirm that it can use vectorized instructions.
gdb output:
```
=> 0x3fffc6000fa:	stg	%r15,120(%r15)
   0x3fffc600100:	lay	%r15,-160(%r15)
   0x3fffc600106:	stg	%r2,176(%r15)
   0x3fffc60010c:	stg	%r3,184(%r15)
   0x3fffc600112:	stg	%r4,192(%r15)
   0x3fffc600118:	lg	%r1,184(%r15)
   0x3fffc60011e:	lg	%r3,176(%r15)
   0x3fffc600124:	lg	%r0,192(%r15)
   0x3fffc60012a:	slgfi	%r0,1
   0x3fffc600130:	lgr	%r2,%r0
   0x3fffc600134:	vll	%v16,%r0,0(%r1)
   0x3fffc60013a:	vll	%v17,%r0,0(%r3)
   0x3fffc600140:	vfenebs	%v18,%v16,%v17
   0x3fffc600146:	jlh	0x3fffc600164
   0x3fffc60014a:	la	%r1,16(%r1)
   0x3fffc60014e:	la	%r3,16(%r3)
   0x3fffc600152:	slgfi	%r0,16
   0x3fffc600158:	jnle	0x3fffc600134
   0x3fffc60015c:	aghi	%r2,1
   0x3fffc600160:	j	0x3fffc600172
```

**Review by r30shah — APPROVED** [review]
LGTM, @Spencer-Comin would appreciate, if you also review the change given that your recent work in this area.

@ehsankianifar , Can you rebase your change ?

**Review by Spencer-Comin — APPROVED** [review]

**Comment by Spencer-Comin** [comment]
LGTM

**Comment by r30shah** [comment]
Jenkins build zos,zlinux

**Comment by r30shah** [comment]
Just realized that couple of different commits are added in this PR. 
@ehsankianifar  After the above two build finishes, can you rebase your branch  ?

**Comment by ehsankianifar** [comment]
Fixed in https://github.com/eclipse/omr/pull/7228

**Comment by ehsankianifar** [comment]
fixed in https://github.com/eclipse/omr/pull/7228

**Pull request closed without merging**
