### PR TITLE
Fix gencon to work with flattened arrays

### PR DESCRIPTION
**Pull request by OussamaSaoudi**
Implemented fix to allow gencon to work with flattened arrays.
Currently does not support partitioning for multithreaded scanning

Signed-off-by: Oussama Saoudi <oussama.saoudi@ibm.com>

### CODE REVIEW

**Comment by dmitripivkine** [comment]
@amicic This spot seems been missed originally when "forced non-split array scan" was introduced. I believe this spot was missed because originally `GC_ObjectScanner::indexableObjectNoSplit` flag has been used for RS scan (roots) only. Currently we are trying to disable split scan for Flattened Arrays temporary (and address this feature later) and this code disregards it. Would you please review?

**Comment by dmitripivkine** [comment]
This change should be submitted first before OpenJ9 part

**Comment by 0xdaryl** [comment]
Re-iterating @dmitripivkine's request for a review from @amicic .

**Comment by genie-omr** [comment]
Can one of the admins verify this patch?

**Comment by 0xdaryl** [comment]
> Depends on: eclipse/openj9#11618

@OussamaSaoudi : Thanks for your first contribution!   I'm not sure if this statement above is true or not, but nothing in OMR should depend on a change in a downstream project.  If you meant that it is co-dependent with a change in the OpenJ9 project then that kind of dependency needs to be managed from the OpenJ9 PR.  As far as OMR is concerned, all PRs should stand on their own.

**Review by amicic — APPROVED** [review]

**Comment by dmitripivkine** [comment]
> > Depends on: [eclipse/openj9#11618](https://github.com/eclipse/openj9/pull/11618)
> 
> @OussamaSaoudi : Thanks for your first contribution! I'm not sure if this statement above is true or not, but nothing in OMR should depend on a change in a downstream project. If you meant that it is co-dependent with a change in the OpenJ9 project then that kind of dependency needs to be managed from the OpenJ9 PR. As far as OMR is concerned, all PRs should stand on their own.

Thank you @0xdaryl This PR does not depend on OpenJ9 downstream project but fixing incomplete OMR code to support Split Array scan in Scavenger. The question is it an optimum solution is a subject of discussion and review

@OussamaSaoudi Please remove "Related" and "Depends" lines from PR Description

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
