### PR TITLE
Remove Unused Options

### PR DESCRIPTION
**Pull request by AlenBadel**
TR_EnableLargePages and TR_EnableLargeCodePages are not being used anywhere. They might be remnants of removed code.

Signed-off-by: AlenBadel <Alen.Badel@ibm.com>

### CODE REVIEW

**Comment by AlenBadel** [comment]
Depends on clean up here https://github.com/eclipse/openj9/pull/7476

**Comment by 0xdaryl** [comment]
> Merging this will break downstream project OpenJ9 until the cleanup in the below issue is merged. eclipse/openj9#7476

If this PR is not ready to merge then please mark it WIP.

**Comment by AlenBadel** [comment]
I've created a new PR which just cleans up this option within OpenJ9. 
https://github.com/eclipse/openj9/pull/7563

Once that PR is merged, we can merge this.

**Comment by AlenBadel** [comment]
FYI @gita-omr

**Comment by AlenBadel** [comment]
@0xdaryl The downstream PR was merged, this can be reviewed and safely merged.

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
@nbhuiyan fyi

**Pull request merged**
