### PR TITLE
Revert "Collector STW flag"

### PR DESCRIPTION
**Pull request by amicic**
Reverts eclipse/omr#5112

### CODE REVIEW

**Comment by amicic** [comment]
Causing intermittent failures in OpenJ9

**Comment by amicic** [comment]
https://github.com/eclipse/openj9/issues/9352

**Comment by rwy0717** [comment]
@amicic, you'll need to sign off on the commit before it will pass the ECA check.

**Comment by rwy0717** [comment]
@genie-omr build all

**Pull request merged**
