### PR TITLE
Code cleanup - remove deprecated code

### PR DESCRIPTION
**Pull request by 0dvictor**
As a result of code cleanup of downstream projects, code related to blow
became dead code. Removing them.

1. Flags related to CG inlining of j/l/System.currentTimeMillis();
2. Options related to outlined prologues and prologue pushes;
3. Per compilation temp slot for conversions and currentTimeMillis();
4. Thunk address of AMD64Imm64SymInstruction;
5. No-longer-used helper enums:
   TR_IA32jitThrowCurrentException
   TR_IA32GetTickCount
   TR_IA32arrayCmp
   TR_IA32getTimeOfDay
   TR_IA32GetSystemTimeAsFileTime
   TR_AMD64doubleToLong
   TR_AMD64doubleToInt
   TR_AMD64floatToLong
   TR_AMD64floatToInt
   TR_AMD64jitThrowCurrentException
   TR_AMD64getTimeOfDay
   TR_AMD64GetSystemTimeAsFileTime
   TR_AMD64currentTimeMillis
   TR_AMD64QueryPerformanceCounter
   TR_AMD64GetTickCount
   TR_AMD64arrayCmp
6. Out-dated comments on unused options.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0dvictor** [comment]
@0xdaryl Good point, I've updated the commit message to summarize all removed deprecated code.

**Comment by 0xdaryl** [comment]
Thanks for the details @0dvictor .

**Comment by 0dvictor** [comment]
The AppVeyor failure is infra and hence is not related to this changeset.

**Pull request merged**
