### PR TITLE
Enforce singleton property in JitBuilder::CodeCacheManager

### PR DESCRIPTION
**Pull request by sajidahmed21**
- Fatal assertion to enforce singleton property in JitBuilder::CodeCacheManager
- Fatal assertion to ensure that JitBuilder::CodeCacheManager::instance() never returns a null pointer

Signed-off-by: Sajid Ahmed <Syed.Sajid.Ahmed23@ibm.com>

### CODE REVIEW

**Comment by mstoodle** [comment]
unfortunately, the commit message titles both exceed the 50 character limit documented in our contribution guidelines. Would you please shorten them?

**Comment by sajidahmed21** [comment]
@mstoodle is the code cache manager currently being used in multi-threaded environments? If yes, isn't it absolutely necessary to place a lock inside the constructor right away?

**Comment by mstoodle** [comment]
Yes, there are. It just comes down to what is the contract. I would prefer not to penalize single threaded scenarios which just means that, in the multi-threaded case, it's up to the client to do the synchronization (for example, if using JitBuilder, acquire a monitor or mutex around the initializeJit() call).

We can revisit it in future if it's too much of a hassle for consumers.

**Comment by lmaisons** [comment]
>is the code cache manager currently being used in multi-threaded environments

Sort-of.  We are frequently constructing it under contexts that are essentially single-threaded, and subsequently accessing it in contexts that are multi-threaded.

**Pull request merged**
