### PR TITLE
Remove OMR_GC_DOUBLE_MAPPING_FOR_SPARSE_HEAP_ALLOCATION

### PR DESCRIPTION
**Pull request by LinHu2016**
OMR_GC_DOUBLE_MAPPING_FOR_SPARSE_HEAP_ALLOCATION and related APIs are not useful any more, 
remove them.

Signed-off-by: hulin <linhu@ca.ibm.com>

### CODE REVIEW

**Comment by LinHu2016** [comment]
@amicic please review the changes, Thanks

**Review by amicic — APPROVED** [review]

**Comment by amicic** [comment]
@babsingh please, proceed

**Comment by babsingh** [comment]
@LinHu2016 Please squash the commits.

**Comment by LinHu2016** [comment]
Hi @babsingh, I keep all of commits on purpose, in case we might need to check or roll back some commits independently.

**Comment by babsingh** [comment]
The [commit guidelines](https://github.com/eclipse/omr/blob/3223d8d0d584575eafb5ec462250baae92cd6084/CONTRIBUTING.md#commit-guidelines) are not satisfied: `The first line should be less than 70 characters`.

**Comment by babsingh** [comment]
jenkins build all

**Review by babsingh — APPROVED** [review]
All Jenkins Windows machines are offline. The Azure Windows build has passed. No need to wait for the Jenkins Windows build since it is identical to the Azure Windows build.

**Pull request merged**
