### PR TITLE
AArch64: Implement icmpeqEvaluator(), etc.

### PR DESCRIPTION
**Pull request by knn-k**
This commit implements icmpeqEvaluator() and similar evaluators for
aarch64.

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Comment by 0xdaryl** [comment]
@knn-k : see CI build failure

**Comment by knn-k** [comment]
Fixed the error caused by missing `#include` line for CodeGenerator.
That should have been added by #3139.

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Comment by 0xdaryl** [comment]
The code changes look fine.  What is the test plan for these opcodes?

**Comment by knn-k** [comment]
Tests are available in #3227.

**Pull request merged**
