### PR TITLE
Compile with xlc_r on AIX

### PR DESCRIPTION
**Pull request by rwy0717**
xlc_r is the reentrant version of xlc. Invoking the compiler changes
many default configuration, to produce thread-safe code. As well,
pthreads will be linked by default to each executable.

Signed-off-by: Robert Young <rwy0717@gmail.com>

### CODE REVIEW

**Comment by rwy0717** [comment]
This PR fixes a link error in omrsig, which occurs on the new AIX machines. In the CI, we should see that compilation will succeed, but the following four tests still fail:

```
         14 - rastest (ILLEGAL)
         15 - subscribertest (Failed)
         16 - traceoptiontest (Failed)
         26 - comptest (Child aborted)
```

Fixes for these tests will come in later PRs.

@genie-omr build aix

**Comment by rwy0717** [comment]
I put an extra space in the command line. I’ll let the build finish then I’ll  remove the space. If we're OK with it, I won't bother relaunching the build.

**Comment by rwy0717** [comment]
Well, that worked a little better than I expected, all the tests passed.
https://ci.eclipse.org/omr/job/PullRequest-aix_ppc-64/1871

**Comment by rwy0717** [comment]
I just pushed an update to remove the extra whitespace.

**Comment by Leonardo2718** [comment]
I don't see a need to re-run the build after a white-space change. There's no need to wait for the Travis CI and AppVeyor builds since this only affects AIX Jenkins builds. Merging.

**Pull request merged**
