### PR TITLE
CMake: update assembler handling for the compiler

### PR DESCRIPTION
**Pull request by dnakamura**
- Mark current .spp file handling logic as being ppc specific
- Add code to handle .spp files on aarch64
- Remove pasm2asm and masm2gas code as it is no longer required

Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by dnakamura** [comment]
@fjeremic  can you take a look at this?

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@dnakamura see build failures.

**Comment by dnakamura** [comment]
Oops my bad the flag is `OMR_ARCH_POWER` not `OMR_ARCH_PPC`
@genie-omr build all

**Comment by fjeremic** [comment]
Windows failure is due to #5100.

**Pull request merged**
