### PR TITLE
Maximum TLH for large machines (WIP)

### PR DESCRIPTION
**Pull request by kangyining**

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@amicic @dmitripivkine : could one of you review this please?

**Comment by babsingh** [comment]
@0xdaryl The PR doesn't seem ready to be reviewed (WIP).

**Comment by amicic** [comment]
This is WIP. I can't change the subject (not a committer) and @kangyining is on vacation.

**Comment by kangyining** [comment]
@0xdaryl Will close this PR until I get back

**Pull request closed without merging**
