### PR TITLE
CacheList Splitting Configuration Modification

### PR DESCRIPTION
**Pull request by jonoommen**
CacheList Splitting Configuration Modification. Adding arguments
to verbose logging and remove code duplication.

Signed-off-by: Jonathan Oommen <jon.oommen@gmail.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
This code is changing the parameters of a hook?  Will this break downstream consumers until the change their code using the hook to pass the new parameters?

**Comment by jonoommen** [comment]
I don't know about that, is there anyone that would know better the answer to this that I should ask?

**Comment by charliegracie** [comment]
Can you build OpenJ9 or other downstream projects with this change and no changes to their repos?

**Comment by jonoommen** [comment]
Yes I will do this, just to be clear, I should launch an openj9 personal build with Openj9 branch ibm_sdk and then this personal OMR branch? @charliegracie

**Comment by charliegracie** [comment]
If the change is ready can you remove the WIP please?

**Comment by charliegracie** [comment]
@genie-omr build all

**Comment by jonoommen** [comment]
Done 👍

**Pull request merged**
