### PR TITLE
AArch64: Separate OpCodeNames.hpp from ARM64Debug.cpp

### PR DESCRIPTION
**Pull request by knn-k**
This commit moves the array members of opCodeToNameMap[] in ARM64Debug.cpp
to a new file OpCodeNames.hpp for easier maintenance.

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by knn-k** [comment]
The idea of separation came from #3087.

**Comment by knn-k** [comment]
AppVeyor build failed with the following message:
```
winflexbison not installed. An error occurred during installation:
 The remote server returned an error: (503) Server Unavailable. Service Unavailable
```

**Comment by 0xdaryl** [comment]
This is an AArch64-specific change.  The AppVeyor failure can be ignored.

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

**Comment by 0xdaryl** [comment]
Apologies for being obtuse, but what is the purpose of this separation?  We've done this in other areas of the compiler that use extensible classes or enums, but in this particular case that doesn't appear to be why this is done.

I understand from #3087 that it was a comment of mine that motivated this, but I cannot remember what the comment was nor find a reference to it.

**Comment by knn-k** [comment]
I thought it would be clearer that OpCode names for debug also need to be updated when you add/change OpCodes in OpBinary.cpp and OMRInstOpCodeEnum.hpp.

**Comment by knn-k** [comment]
Cancelling this PR.

**Pull request closed without merging**
