### PR TITLE
Revert "Dispatcher Rework: Thread Selection & Hybrid Notification"

### PR DESCRIPTION
**Pull request by RSalman**
This reverts commit 298eb34aa69f3102d7c95c0e8e557dd263cfcd1e given https://github.com/eclipse/openj9/issues/10171

Signed-off-by: Salman Rana <salman.rana@ibm.com>

### CODE REVIEW

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by RSalman** [comment]
It looks like the Win build check failed due to infra issues:
`0>MSBUILD : error MSB4166: Child node "3" exited prematurely. Shutting down.` 

Could I please have it relaunched?

**Comment by youngar** [comment]
@genie-omr build win

**Comment by youngar** [comment]
@RSalman Did we test if this change fixes the hang?

**Comment by RSalman** [comment]
Yup, I've confirmed it. I'm looking into a fix.

**Comment by RSalman** [comment]
It's failing a test now, I don't think it's related. Is this a known issue:

```
20:00:12  13: [----------] 1 test from PortTtyTest
20:00:12  13/23 Test #13: porttest ..........................***Exception: SegFault 33.76 sec

...

20:01:36  The following tests FAILED:
20:01:36  	 13 - porttest (SEGFAULT)
```

**Comment by youngar** [comment]
That test has been segfaulting on windows a lot lately.. Since it doesn't have anything to do with this PR and we passed all the rest of the testing I'm merging this.

**Pull request merged**
