### PR TITLE
Removed dead PPC code

### PR DESCRIPTION
**Pull request by AgostonSzepessy**
Code that was commented out was removed.

### CODE REVIEW

**Comment by ymanton** [comment]
Looks good. Thanks.

**Comment by ymanton** [comment]
Although you should change the commit subject to refer to "Power" rather than "PPC".

**Comment by AgostonSzepessy** [comment]
I've changed the commit subject.

**Comment by vijaysun-omr** [comment]
Cleanup of commented out text. Merging.

**Pull request merged**
