### PR TITLE
WIP: Move StorageInfo into Z CodeGenerator

### PR DESCRIPTION
**Pull request by 0xdaryl**
This feature is used exclusively by the Z CodeGenerator.

Keep a stub file `codegen/StorageInfo.cpp` that simply includes the
relocated version to prevent downstream breakages.  This stub will be
removed once changes in known downstream projects are made.

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
WIP only because known downstream projects need modifications to prevent build breakages.  I'll un-WIP when those dependencies are resolved.

**Comment by 0xdaryl** [comment]
Downstream dependencies are a bit harder to resolve than I first suspected.  I'm closing this PR for now until those can be fixed cleanly.

**Comment by fjeremic** [comment]
@0xdaryl FYI this should likely live in OpenJ9 as that is where all the Packed Decimal IL lives. I don't think StorageInfo is relevant to OMR.

**Pull request closed without merging**
