### PR TITLE
PowerPC: Disable GRA for Vector Mask types

### PR DESCRIPTION
**Pull request by midronij**
Signed-off-by: midronij <jackie.midroni@ibm.com>

### CODE REVIEW

**Comment by midronij** [comment]
@gita-omr @r30shah

**Comment by midronij** [comment]
@knn-k when you have a chance, could you please review and (if everything looks alright) merge?

**Review by gita-omr — APPROVED** [review]

**Review by r30shah — APPROVED** [review]

**Comment by r30shah** [comment]
Jenkins build plinux,aix

**Review by knn-k — APPROVED** [review]
LGTM.

**Comment by knn-k** [comment]
I have a question, although I have already merged the commit.

What was the reason for disabling GRA for masks?  Is there any issue caused by GRA?  Please clarify.

**Comment by midronij** [comment]
> I have a question, although I have already merged the commit.
> 
> What was the reason for disabling GRA for masks? Is there any issue caused by GRA? Please clarify.

Essentially, since Mask types are new and there is limited support for them on Power, a little more work is required to get them to be handled properly by GRA. I believe it was causing some local crashes and test failures too

**Pull request merged**
