### PR TITLE
Remove clean TestJitConfig.cpp from compilertest

### PR DESCRIPTION
**Pull request by samolisov**
The translation module `fvtest/compilertest/runtime/TestJitConfig.cpp`
contains no executable code and looks only like a wrapper for
the `runtime/TestJitConfig.hpp` header. The file may be removed and this
won't break the compilation.

The commit was missing from #2546.

Signed-off-by: Pavel Samolysov <samolisov@gmail.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
@smlambert do you may recall the use for this file? Could you review?

**Comment by fjeremic** [comment]
@samolisov some typo fixes from your commit body:

```
The translation module fvtest/compilertest/runtime/TestJitConfig.cpp
contains no executable code and looks only like a wrapper for
the runtime/TestJitConfig.hpp header. The file may be removed and this
won't break the compilation.

The commit was missing from #2546.
```

**Comment by samolisov** [comment]
@fjeremic Thank you for the fixes, I've re-pushed the commit with new body and updated the PR messages as well.

**Comment by smlambert** [comment]
I do not recall, @sophia-guo, do you know of any reason to keep this file (was it an unused placeholder for something?)?

**Comment by sophia-guo** [comment]
Not sure. It was delivered as the initial part of Prototyping language independent JIT testing framework.

**Comment by fjeremic** [comment]
Doesn't sound like we have a use for this. Should be safe to remove.

@genie-omr build all

**Comment by charliegracie** [comment]
@genie-omr build zos

**Pull request merged**
