### PR TITLE
Stash use node to tree mapping in CopyProp

### PR DESCRIPTION
**Pull request by ncough**
The treetop containing a use node is often required
in CopyProp. The prior approach was to repeatedly
search the CFG for the corresponding treetop, however,
this was costly. Instead, a mapping is generated
early in copy prop and used throughout.

Signed-off-by: Nicholas Coughlin <cnic@ca.ibm.com>

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
Need a review from @andrewcraik

**Comment by andrewcraik** [comment]
LGTM

**Comment by vijaysun-omr** [comment]
Is the reason this solution works is because the key used in the new map you added is the node itself (value being the treetop) and transformations in copy propagation modify the node to have a different sym ref but never in fact change the tree that a particular node belongs to ?

**Comment by ncough** [comment]
Correct, the only significant optimizations that occur before the final use of the new map are `rematerializeIndirectLoadsFromAutos` and `replaceCopySymbolReferenceByOriginalIn`. Neither of these will move nodes to new trees. They may create or remove nodes, however, use nodes are fetched from UseDefInfo, which is not updated. As node pointer equality is used in the original implementation and the new, only those initial nodes that existing during UseDef analysis require mappings.

**Pull request merged**
