### PR TITLE
Complete relocating instruction pointers to CodeGenerator

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Rebase instruction pointer links from Compilation to CodeGenerator
* Relocate instruction pointer fields from Compilation to CodeGenerator

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Rebased and re-tested and all looks good.  Removing WIP.

**Comment by 0xdaryl** [comment]
I'd a appreciate a review from at least one of @fjeremic @ymanton please.

**Comment by ymanton** [comment]
LGTM.

**Comment by 0xdaryl** [comment]
@mstoodle @vijaysun-omr @charliegracie : reviewers have signed off.  Would one of you mind merging please?

**Comment by mstoodle** [comment]
genie-omr build all

**Pull request merged**
