### PR TITLE
New field TLHRemainderCount in CopyForwardStatsCore

### PR DESCRIPTION
**Pull request by LinHu2016**
Report how many TLHRemainder has been created during CopyForward.

Signed-off-by: Lin Hu <linhu@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@amicic @dmitripivkine : would one of you mind reviewing please?

**Comment by LinHu2016** [comment]
@amicic @dmitripivkine the change is ready for reviewing, thanks

**Comment by amicic** [comment]
@0xdaryl please proceed with final review/merge

**Comment by 0xdaryl** [comment]
Jenkins build all

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
