### PR TITLE
Revert "GRA changes to reduce JIT overhead at warm opt levels"

### PR DESCRIPTION
**Pull request by mpirvu**
Reverts eclipse/omr#7245
This PR is known to cause some intermittent test failures in a downstream project (OpenJ9)

### CODE REVIEW

**Comment by mpirvu** [comment]
Attn: @vijaysun-omr

**Comment by vijaysun-omr** [comment]
jenkins build all

**Comment by vijaysun-omr** [comment]
jenkins build riscv

**Comment by mpirvu** [comment]
riscv tests failed due to infra issues:
```
11:51:25  #14 [11/16] RUN wget -O /tmp/libfakeroot_1.31-1.2_riscv64.deb 	 http://ftp.ports.debian.org/debian-ports/pool-riscv64/main/f/fakeroot/libfakeroot_1.31-1.2_riscv64.deb
11:51:25  #14 0.381 --2024-02-02 11:51:25--  http://ftp.ports.debian.org/debian-ports/pool-riscv64/main/f/fakeroot/libfakeroot_1.31-1.2_riscv64.deb
11:51:27  #14 0.382 Resolving ftp.ports.debian.org (ftp.ports.debian.org)... 130.89.148.77, 2001:67c:2564:a119::77
11:51:27  #14 0.741 Connecting to ftp.ports.debian.org (ftp.ports.debian.org)|130.89.148.77|:80... connected.
11:51:27  #14 0.847 HTTP request sent, awaiting response... 404 Not Found
11:51:27  #14 0.952 2024-02-02 11:51:25 ERROR 404: Not Found.
11:51:27  #14 0.952 
11:51:27  #14 ERROR: process "/bin/sh -c wget -O /tmp/libfakeroot_1.31-1.2_riscv64.deb \t http://ftp.ports.debian.org/debian-ports/pool-riscv64/main/f/fakeroot/libfakeroot_1.31-1.2_riscv64.deb" did not complete successfully: exit code: 8
11:51:27  ------
11:51:27   > [11/16] RUN wget -O /tmp/libfakeroot_1.31-1.2_riscv64.deb 	 http://ftp.ports.debian.org/debian-ports/pool-riscv64/main/f/fakeroot/libfakeroot_1.31-1.2_riscv64.deb:
11:51:27  0.381 --2024-02-02 11:51:25--  http://ftp.ports.debian.org/debian-ports/pool-riscv64/main/f/fakeroot/libfakeroot_1.31-1.2_riscv64.deb
11:51:27  connected.
11:51:27  0.847 HTTP request sent, awaiting response... 404 Not Found
11:51:27  0.952 2024-02-02 11:51:25 ERROR 404: Not Found.
11:51:27  0.952 
11:51:27  ------
11:51:27  Dockerfile:78
11:51:27  --------------------
11:51:27    77 |     RUN apt-get install -y fakeroot
11:51:27    78 | >>> RUN wget -O /tmp/libfakeroot_1.31-1.2_riscv64.deb \
11:51:27    79 | >>> 	 http://ftp.ports.debian.org/debian-ports/pool-riscv64/main/f/fakeroot/libfakeroot_1.31-1.2_riscv64.deb
11:51:27    80 |     RUN wget -O /tmp/libfakechroot_2.20.1+ds-15_riscv64.deb \
11:51:27  --------------------
11:51:27  ERROR: failed to solve: process "/bin/sh -c wget -O /tmp/libfakeroot_1.31-1.2_riscv64.deb \t http://ftp.ports.debian.org/debian-ports/pool-riscv64/main/f/fakeroot/libfakeroot_1.31-1.2_riscv64.deb" did not complete successfully: exit code: 8
```

**Pull request merged**
