### PR TITLE
Fix bug in updating displacement field in RSY type instruction

### PR DESCRIPTION
**Pull request by r30shah**
In https://github.com/eclipse/omr/pull/6893, encoding on RSY type instruction was fixed to allow a immediate field to be used with RSY type instructions. In encoding routine for that instruction, miscalculation in updating location for DH2 field in instruction caused incorrect immediate value being encoded in the instruction.

Fixes: https://github.com/eclipse-openj9/openj9/issues/16969

### CODE REVIEW

**Comment by r30shah** [comment]
@joransiu In my previous fix for the RSY instruction encoding, I had a bug where it was updating incorrect field with the content of DH1 field in the instruction .  Looking into the testing environment (Which I still had luckily available, I had the fix but seems like I missed pushing that on original PR, I have verified the test again and it is fixed).  Can you review this change again? I apologize for missing this one.

**Review by joransiu — APPROVED** [review]

**Comment by r30shah** [comment]
Jenkins build zlinux,zos

**Comment by r30shah** [comment]
I was expecting with rebase, would get clean Mac failure, but it still fails, This change is Z specific change only so should not cause Mac failure. Launching another sanity Z build.

**Comment by r30shah** [comment]
Jenkins build zlinux,zos

**Comment by keithc-ca** [comment]
Perhaps we should also update (i.e. correct) the comment in `compiler/z/codegen/OMRInstOpCode.hpp`:
```
   RSY Format
    ________ ____ ____ ____ ____________ ________
   |Op Code | R1 | R3 | B2 |     D2     |Op Code |
   |________|____|____|____|____________|________|
   0         8   12   16   20           40       47
```
According to z/Architecture Principles of Operation ([1]), the `D2` field shown above is instead formatted as `DL2` and `DH2` (in that order), that is the high-order part of `D2` starts in bit 32, not in bit 20 as the comment currently suggests.
```
   RSY Format
    ________ ____ ____ ____ ____________ ________
   |Op Code | R1 | R3 | B2 | DL2 | DH2  |Op Code |
   |________|____|____|____|_____|______|________|
   0         8   12   16   20    32     40       47
```
[1] https://www.ibm.com/docs/en/SSQ2R2_15.0.0/com.ibm.tpf.toolkit.hlasm.doc/dz9zr006.pdf

**Comment by r30shah** [comment]
@keithc-ca  In regards to https://github.com/eclipse/omr/pull/6964#issuecomment-1529841340, thanks a lot for catching this. You are right, atleast for RSY instruction this is incorrect, and also it misses two different version of instruction format that we should document. (RSY-a and RSY-b where minor different between them is that b format would have Mask (M3) field instead on R3 operand. As a part of this PR I am adding another commit that updates it and adding a TODO in my list to go through the rest of the instruction format to make sure they are consistent and correct with respect to current Instruction referenfces.

**Comment by 0xdaryl** [comment]
Jenkins build zlinux,zos

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
