### PR TITLE
Add new helper induceOSRAtCurrentPCAndRecompile

### PR DESCRIPTION
**Pull request by cathyzhyi**
Add the new helper induceOSRAtCurrentPCAndRecompile to request both OSR
transition and method reompilation. When OSR is requested
because of invalidated code path the method body containing
the invalid code path should be dicarded and recompiled for better
performance.

The old helper induceOSRAtCurrentPC is still useful if only OSR
transition is needed.

Signed-off-by: Yi Zhang <yizhang@ca.ibm.com>

### CODE REVIEW

**Comment by cathyzhyi** [comment]
subprojects need corresponding changes for correctness.

**Comment by vijaysun-omr** [comment]
Could you please elaborate on the rationale for introducing the new helper and explain when the old helper TR_induceOSRAtCurrentPC and the new helper TR_induceOSRAtCurrentPCAndRecompile are meant to be used respectively ?

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by cathyzhyi** [comment]
> Could you please elaborate on the rationale for introducing the new helper and explain when the old helper TR_induceOSRAtCurrentPC and the new helper TR_induceOSRAtCurrentPCAndRecompile are meant to be used respectively ?

updated comments to elaborate the difference of the 2 helpers.

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by vijaysun-omr** [comment]
Thanks for the explanation. Looks okay to me since you just added the infrastructure changes to work with either one of the two OSR helpers you mentioned. I'll ask @andrewcraik for his review as well before merging.

**Comment by andrewcraik** [comment]
@vijaysun-omr I am fine with this

**Pull request merged**
