### PR TITLE
Removed single line annotation comments from #include directives

### PR DESCRIPTION
**Pull request by Rajlaxmi**
Removed annotation describing feature included from the file

Issue: #3521
Signed-off-by: Rajlaxmi <rajlaxmisah@gmail.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Thanks for your first contribution!  Two things:
* The IP check is failing because "rajlaxmisah@gmail.com" doesn't appear to have signed the ECA per the Contribution Guidelines.
* Please be sure the forward copyright date on each file is also updated to 2019.

**Comment by fjeremic** [comment]
@Rajlaxmi thanks for the contribution. Did you by any chance make these changes via a script of some sort? If you did would you mind posting the script here? I can apply the same change to OpenJ9. Unless you want to make the change there as well? I'm fine either way. Thanks!

**Comment by Rajlaxmi** [comment]
I have used sed in .hpp and .cpp files.
Expression: 
`
find . -type f \( -name "*.cpp" -o -name "*.hpp" \) -exec sed -i .bak 's/\(^\#include[ \t]*[<"].*[>"]\)[ \t]*\/\/[ \t]* for .*/\1/g' {} \;
find . -type f -name "*.bak" -exec rm '{}' \;
`

**Comment by 0xdaryl** [comment]
I confirmed that there now is a signed ECA for your email address.  Perhaps there was some delay before it became "visible".  I'm not sure why the IP check is still failing, but we can still merge despite that.

Can you squash the 3 commits into one please, and I'll launch the full CI tests on it?

**Comment by Rajlaxmi** [comment]
I have squashed the commits.

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
The code changes look good.  Thanks for taking care of this!

Please fix up the merge conflict, I'll re-run CI, and this should be good to go.  Thanks.

**Comment by Rajlaxmi** [comment]
I have fixed merge conflict, though this created another commit. Should I squash again?

**Comment by 0xdaryl** [comment]
Yes please.  This should all be one commit.

**Comment by Rajlaxmi** [comment]
I am having trouble squashing these two commits.
Using squash shows a lot more commits. Even when i check different commits between this branch and master branch i get a lot more commits [git log --oneline annotationcomment ^master]
Any pointers on how to squash them?

**Comment by Rajlaxmi** [comment]
Sorry, I had not pulled master from original repo. Now I get two different commits [git log --oneline annotationcomment ^master], though squashing is still causing issue.

Top commits:
```
9360e81d (HEAD -> annotationcomment, origin/annotationcomment) Merge branch 'master' into annotationcomment
d745bfdc (upstream/master, master) Merge pull request #3516 from dnakamura/travis_xenial
23a4471c Merge pull request #3488 from fjeremic/fix-31-bit-gpr64
7513865d Removed single line annotation comments from #include directives
5d31a9a7 (origin/master, origin/HEAD, test) Merge pull request #3520 from 0xdaryl/namespaces
```

**Comment by Leonardo2718** [comment]
@Rajlaxmi Did you pull upstream master into you're local `master` branch or into `annotationcomment`? Assuming the commits in this PR are current, it looks like the latter, which can cause this kind of problem. If you pull upstream changes to your local `master` branch and then rebase your `annotationcomment` on top of `master`, squashing the commits in the process, it should avoid the problem. For example:

```
git checkout master
git pull upstream master # assuming "upstream" is a remote that points to the main OMR repository
git checkout annotationcomment
git rebase -i master
```

Does that help? :slightly_smiling_face:

**Comment by Rajlaxmi** [comment]
Yes, that helps. Thanks.

**Comment by Leonardo2718** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
Thanks @Leonardo2718 and @Rajlaxmi !

**Comment by Rajlaxmi** [comment]
I had different email id set in git config. Updated the commit accordingly.

**Comment by Rajlaxmi** [comment]
@genie-omr build all

**Comment by Leonardo2718** [comment]
@genie-omr build all

**Comment by Leonardo2718** [comment]
@Rajlaxmi The build command only works if you're a committer to the project. :wink:

**Pull request merged**
