### PR TITLE
Add isNullRestricted field to TypeLayoutEntry

### PR DESCRIPTION
**Pull request by a7ehuo**
Add `isNullRestricted` field to `TypeLayoutEntry`

- [ ] Depends on https://github.com/eclipse-openj9/openj9/pull/18189

Related to: eclipse-openj9/openj9#18170

### CODE REVIEW

**Comment by a7ehuo** [comment]
@hzongaro May I ask you to review this change? Thanks! 

I'm keeping `WIP` for now because this PR depends on https://github.com/eclipse-openj9/openj9/pull/18189. My understanding is that it requires a coordinated merge

**Comment by hzongaro** [comment]
Jenkins build all

**Comment by a7ehuo** [comment]
[eclipse-omr/pr/win_x86-64 failure](https://ci.eclipse.org/omr/job/PullRequest-win_x86-64/3818/console): Not sure how it's related to this change.  [A previous PR build seems having similar failures](https://ci.eclipse.org/omr/job/PullRequest-win_x86-64/3812/console). 

```
22:32:54  The following tests FAILED:
22:32:54  	  2 - conditionals_example_as_test (Not Run)
22:32:54  	  3 - isSupportedType_example_as_test (Not Run)
22:32:54  	  4 - iterfib_example_as_test (Not Run)
22:32:54  	  5 - nestedloop_example_as_test (Not Run)
22:32:54  	  6 - pow2_example_as_test (Not Run)
22:32:54  	  7 - simple_example_as_test (Not Run)
22:32:54  	  8 - worklist_example_as_test (Not Run)
22:32:54  	  9 - power_example_as_test (Not Run)
22:32:54  Errors while running CTest
...
22:32:58  ERROR: Cannot delete workspace :Unable to delete 'c:\omr\workspace\PullRequest-win_x86-64\Build'. Tried 3 times (of a maximum of 3) waiting 0.1 sec between attempts. (Discarded 2 additional exceptions)
```

[x86-64 macOS failure](https://github.com/eclipse/omr/pull/7125/checks?check_run_id=17107508671): known issue https://github.com/eclipse/omr/issues/6516

```
/Users/runner/work/1/s/fvtest/porttest/omrsockTest.cpp:1209
      Expected: rc
      Which is: 1
To be equal to: 2
```
```
/Users/runner/work/1/s/fvtest/porttest/omrsockTest.cpp:51
      Expected: privateOmrPortLibrary->sock_bind(privateOmrPortLibrary, *serverSocket, serverSockAddr)
      Which is: -506
To be equal to: 0
```

**Comment by hzongaro** [comment]
Jenkins build osx,win

**Comment by hzongaro** [comment]
Jenkins build win

**Comment by hzongaro** [comment]
Jenkins build win

**Pull request merged**
