### PR TITLE
GRA changes to reduce JIT overhead at warm opt levels

### PR DESCRIPTION
**Pull request by mpirvu**
The commit introduces a new option `-Xjit:graFreqThresholdAtWarm=<NNN>` that can be used to control the JIT overhead for compilations performed at warm optimization level or below. The default value of the threshold is 500. A larger value leads to lower JIT overhead but also to potentially lower quality of the generated code. For hot compilations or in situations where we think we can afford more JIT overhead, the threshold is automatically set to 0.

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
jenkins build all

**Comment by vijaysun-omr** [comment]
jenkins build riscv

**Comment by mpirvu** [comment]
Personal build: https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/506/
There is one failure on MAC, though I don't believe it's due to this PR.
```
12:46:15  ===============================================
12:46:15  Running test cmdLineTester_getPid_0 ...
12:46:15  ===============================================
12:46:15  cmdLineTester_getPid_0 Start Time: Sat Apr  6 03:46:15 2024 Epoch Time (ms): 1712335575076
12:46:15  variation: NoOptions
12:46:15  JVM_OPTIONS:  
12:46:15  { \
12:46:15  	echo "";	echo "TEST SETUP:"; \
12:46:15  	"/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/jdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/jdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done"; \
12:46:15  	mkdir -p "/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/aqa-tests/TKG/../TKG/output_1712334816539/cmdLineTester_getPid_0"; \
12:46:15  	cd "/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/aqa-tests/TKG/../TKG/output_1712334816539/cmdLineTester_getPid_0"; \
12:46:15  	echo "";	echo "TESTING:"; \
12:46:15  	"/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/jdkbinary/j2sdk-image/bin/java" "-Xshareclasses:none" -DTESTDIR="/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/runtimemxbeanTests" -DEXE='"/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/jdkbinary/j2sdk-image/bin/java"  ' -DTESTSJARPATH="/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/runtimemxbeanTests/runtimemxbeanTests.jar" -jar "/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdline_options_tester/cmdlinetester.jar" -config "/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/runtimemxbeanTests/getPidTest.xml" -explainExcludes -nonZeroExitWhenError; \
12:46:15   		if [ $? -eq 0 ]; then echo "-----------------------------------"; echo "cmdLineTester_getPid_0""_PASSED"; echo "-----------------------------------"; cd /Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/aqa-tests/TKG/..; rm -f -r "/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/aqa-tests/TKG/../TKG/output_1712334816539/cmdLineTester_getPid_0"; else echo "-----------------------------------"; echo "cmdLineTester_getPid_0""_FAILED"; echo "-----------------------------------"; fi; \
12:46:15  	echo "";	echo "TEST TEARDOWN:"; \
12:46:15  	"/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/jdkbinary/j2sdk-image/bin/java" -Xshareclasses:destroyAll; "/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/jdkbinary/j2sdk-image/bin/java" -Xshareclasses:groupAccess,destroyAll; echo "cache cleanup done"; \
12:46:15  	 } 2>&1 | tee -a "/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/aqa-tests/TKG/../TKG/output_1712334816539/TestTargetResult";
12:46:15  
12:46:15  TEST SETUP:
12:46:15  JVMSHRC005I No shared class caches available
12:46:16  JVMSHRC005I No shared class caches available
12:46:16  cache cleanup done
12:46:16  
12:46:16  TESTING:
12:46:21  *** Starting test suite: getPid test ***
12:46:21  Testing: Compare RuntimeMXBean.getPid() with getting PID from system
12:46:21  Test start time: 2024/04/06 03:46:15 Australian Eastern Standard Time
12:46:21  Running command: perl /Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/runtimemxbeanTests/getPidTest.pl "/Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/jdkbinary/j2sdk-image/bin/java"   -cp /Users/jenkins/workspace/Test_openjdk17_j9_sanity.functional_aarch64_mac_Personal_testList_1/aqa-tests/TKG/../../jvmtest/functional/cmdLineTests/runtimemxbeanTests/runtimemxbeanTests.jar GetPid
12:46:21  Time spent starting: 17 milliseconds
12:46:21  Time spent executing: 5030 milliseconds
12:46:21  Test result: FAILED
12:46:21  Output from test:
12:46:21   [OUT] FAIL: RuntimeMXBean.getPID() returned 0 instead of 68172
12:46:21  >> Success condition was not found: [Output match: PASS]
```
On zLinux we have some known failure related to `-XX:-HandleSIGXFSZ`.

**Comment by mpirvu** [comment]
50x grinder for cmdLineTester_getPid_0 on mac has passed.

I will attempt another aix build.

**Comment by mpirvu** [comment]
AIX tests are also passing: https://openj9-jenkins.osuosl.org/job/Pipeline-Build-Test-Personal/507/

This PR is ready to be delivered.

**Pull request merged**
