### PR TITLE
Tril tests for icmpeq, etc.

### PR DESCRIPTION
**Pull request by knn-k**
This commit adds tril test cases for icmpeq and similar evaluators.

Signed-off-by: knn-k <konno@jp.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@genie-omr build aarch64

Now that #3171 has merged.

**Comment by 0xdaryl** [comment]
Duh...  This will still only test the builds, not runtime.

**Comment by knn-k** [comment]
Is my understanding below correct?

I need to add a new template class other than `BinaryOpTest` in `OpCodeTest.hpp` for writing test cases for opcodes like `lcmpeq`, which have different types with input (int64_t) and output (int32_t).
The same can be said for type conversion opcodes, such as `i2l`.

**Comment by Leonardo2718** [comment]
It's looking good @knn-k !

> Is my understanding below correct?
>
> I need to add a new template class other than BinaryOpTest in OpCodeTest.hpp for writing test cases for opcodes like lcmpeq, which have different types with input (int64_t) and output (int32_t).
The same can be said for type conversion opcodes, such as i2l.

Actually, you should be able to use `OpCodeTest` instead of `BinaryOpTest`. It's a variadic template so it can (in theory) handle an arbitrary number of arguments. The format for it is `OpCodeTest<ReturnT, Arg1T, Arg2T, etc.>`. So, in your case, you might use it like this:

```c++
class Int64Compare : public TRTest::OpCodeTest<int32_t,int64_t,int64_t> {};
```

I believe the `to_struct()` helper should still work.

Is this ready for merging, or are you planning on adding the lcmp tests in this PR?

**Comment by knn-k** [comment]
Thanks  @Leonardo2718.  I think I will add lcmp tests in another PR.

**Pull request merged**
