### PR TITLE
Add routine to disable countDecimalDigits transformation in IdiomRecognition

### PR DESCRIPTION
**Pull request by dchopra001**
This PR adds codegen routines to toggle support for the countDecimal IL transformation performed by Idiom Recognition.

### CODE REVIEW

**Review by r30shah — APPROVED** [review]
LGTM

**Comment by r30shah** [comment]
Jenkins build all

**Comment by r30shah** [comment]
@jdmpapin Can you please review this change from Dhruv?

**Comment by dchopra001** [comment]
Closing this PR based on review comment [here](https://github.com/eclipse-openj9/openj9/pull/16273#discussion_r1019529972).

**Pull request closed without merging**
