### PR TITLE
WIP: Make sure LoopVersioner creates various guard tests safely

### PR DESCRIPTION
**Pull request by ymanton**
`LoopVersioner` creates various guards unsafely. See #718 for one example. This PR will be used to fix other cases that appear problematic but that haven't caused any known issues yet.

### CODE REVIEW

**Comment by mstoodle** [comment]
What's the current status here, please?

**Comment by ymanton** [comment]
Currently on the back burner for a while. This is simply a clean up task to rewrite existing code that is not known to have any issue to use a new API. The one case that did have a bug in it has already been fixed via https://github.com/eclipse/omr/issues/718.

**Comment by mstoodle** [comment]
@ymanton so maybe we can close this PR until such time as it comes off the backburner?

**Comment by ymanton** [comment]
Sure, I'll keep track of this task elsewhere.

**Pull request closed without merging**
