### PR TITLE
Convert mutf8 to latin1

### PR DESCRIPTION
**Pull request by theresa-m**
- additional test for this case
- cleanup of code / comment error in nearby code

Created for https://github.com/eclipse/openj9/pull/1655 compatibility on zos

Signed-off-by: Theresa Mammarella <Theresa.T.Mammarella@ibm.com>

### CODE REVIEW

**Comment by theresa-m** [comment]
pending fix for the appveyor compile failure..

**Comment by pshipton** [comment]
Is there any outlook for getting this merged?

**Comment by theresa-m** [comment]
I'm bugging @charliegracie for a review :)

**Comment by charliegracie** [comment]
@genie-omr build all

**Pull request merged**
