### PR TITLE
Remove CFG frequency completion

### PR DESCRIPTION
**Pull request by lmaisons**
CFG frequency completion is a vestigial method of providing the
optimizer with block and edge frequencies based on a run-time profile.
It has no current use, and it furthermore has only ever historically
existed as a prototype of dubious correctness / validity.

Signed-off-by: Luc des Trois Maisons <lmaisons@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
CC @andrewcraik for review.

**Comment by vijaysun-omr** [comment]
I agree this code can be deleted since it never really moved past a prototype. 

There is a conflict reported for OMRCfg.cpp ?

**Comment by lmaisons** [comment]
The header was #included in OMRCfg.cpp.  I'll rebase.

**Comment by vijaysun-omr** [comment]
Thanks Luc, I will merge now since there are no more conflicts reported and all checks are passing.

**Pull request merged**
