### PR TITLE
Move all ARM mnemonics into the TR::InstOpCode class

### PR DESCRIPTION
**Pull request by fjeremic**
This is a continuation of #6055 which eliminates the ".temp.defines" file and finishes off moving all the ARM instruction mnemonics inside the TR::InstOpCode class. See each commit comment to understand what was done. Each individual commit builds on its own.

### CODE REVIEW

**Comment by fjeremic** [comment]
Jenkins build all

**Comment by fjeremic** [comment]
@dsouzai do you want to be a committer for this one too given the similarities with #6061?

**Comment by dsouzai** [comment]
@knn-k fyi

**Review by dsouzai — COMMENTED** [review]
Overall LGTM. One question though, why is the "and" op code `and_`? Is there an existing opcode it clashes with? If so, wouldn't we just use the common one?

**Comment by dsouzai** [comment]
Also there's a bunch of copyrights that need to be updated here.

**Comment by fjeremic** [comment]
> Overall LGTM. One question though, why is the "and" op code `and_`? Is there an existing opcode it clashes with? If so, wouldn't we just use the common one?

Little known fact but `and` is actually a keyword in C++! You can do things like:

```
if (x < y and x == 5) {
	std::cout << "x = " << x;
}
```

Example:
https://ideone.com/JkiR8U

Documentation:
https://en.cppreference.com/w/cpp/keyword/and

**Comment by fjeremic** [comment]
> Also there's a bunch of copyrights that need to be updated here.

[Force-pushed](https://github.com/eclipse/omr/compare/51b86355c092310d0c00004b8eed273af12597cf..7fe991d61b278cd5af361c5c531fc95ed070d481) the copyright updates.

**Review by dsouzai — APPROVED** [review]

**Pull request merged**
