### PR TITLE
WIP : TrivialDeadBlockRemover Documentation

### PR DESCRIPTION
**Pull request by Krovatkin**
Got a summary and skeleton for TrivialDeadBlockRemover.
Should be able to fill in the details over the next few days.

### CODE REVIEW

**Comment by mstoodle** [comment]
@Krovatkin Thanks for the write-up so far. Are you looking for a review at this point? Your last comment suggested there is more to come so we've been holding off looking at it...

**Comment by Krovatkin** [comment]
@mstoodle i'm still working on this PR. i'm very sorry that i didn't make much progress recently since the last couple months were **very** hectic 😕 . i should be able to finish it up sometime, early jan 📆  , and to hopefully move to a new opt :shipit:

**Comment by mstoodle** [comment]
May I ask after current status here, please? Are you finding value in having a WIP merge request open here, or could we close it until such time as you're ready to complete it?

Not trying to push you away, just not sure a lingering inactive PR is providing much value.

**Comment by Krovatkin** [comment]
@mstoodle 
Let's close it until I finish up the draft. I'm so terribly sorry; I didn't anticipate that I would be dragging my feet w/ this PR for nearly half a year :-(

**Comment by mstoodle** [comment]
@Krovatkin No worries, Nik. I hope life returns to "bearably hectic" :) for you and we look forward to your future contributions!

**Pull request closed without merging**
