### PR TITLE
Support signals needed by Jython

### PR DESCRIPTION
**Pull request by babsingh**
1. Comparing the [signals needed by Jython](https://github.com/jythontools/jython/blob/b9ff520f4f65231209d5200c22724516a72e75f2/Lib/signal.py#L56-L87) and signals supported by OMR, OMR needs to support the following signals:
```
- SIGINFO
- SIGIOT
- SIGPOLL
```

`ifdefs` are used since `SIGINFO`, `SIGIOT` and `SIGPOLL` are not available on all Unix platforms.

Jython also supports `SIGSTOP` and `SIGKILL`. Signal handlers cannot be registered for `SIGKILL` and `SIGSTOP`; `sigaction`/`signal` will throw `EINVAL` for them. With or without OMR support, OMR signal functions will return `OMRPORT_SIG_ERROR` for these two signals. So, OMR support is not added for `SIGSTOP`/`SIGKILL` since signal flags are limited in OMR and correct behavior is achieved for `SIGKILL`/`SIGSTOP` without utilizing the signal flags.

2. Update `ifdefs` to be platform agnostic and for consistency.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by babsingh** [comment]
@rwy0717 There was a compilation error, which has been fixed. The builds will need to be restarted.

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by DanHeidinga** [comment]
@rwy0717 builds have passed.  Can you do the needful and merge this?  I want to get the dependent OpenJ9 changes merged...

**Pull request merged**
