### PR TITLE
Use an int to store the output of ioctl FIONREAD

### PR DESCRIPTION
**Pull request by rwy0717**
All publicly available documentation indicates that FIONREAD outputs an
int, not a pointer-width value. Use an int, and avoid bad aliasing.
There is a comment indicating that _some_ devices output a 64 bit value,
but I cannot see how or when that would ever be true. This PR removes
that comment.

Fixes: #3145
Signed-off-by: Robert Young <rwy0717@gmail.com>

### CODE REVIEW

**Comment by rwy0717** [comment]
@pdbain-ibm There's a comment here that says some devices may output a 64bit value on an FIONREAD ioctl. As far as I can tell, that's not true, it's always an int. Do you have any idea when this could be true, or where this comment came from?

There are some documentation links to the original issue #3145 .

Thanks

**Comment by pdbain-ibm** [comment]
I don't know where the comment came from; it looks very old, given the PR number.

**Comment by rwy0717** [comment]
hehe yeah, I wonder if it was some old cell phone or something. Does this change look OK to you @pdbain-ibm ?

**Comment by pdbain-ibm** [comment]
Have you tested it on some BE platforms like AIX or z/OS?

**Comment by pdbain-ibm** [comment]
I would also check with @gacholio .

**Comment by youngar** [comment]
@genie-omr build all

**Comment by youngar** [comment]
@genie-omr build all

**Pull request merged**
