### PR TITLE
Add buildenv/jenkins/README.md

### PR DESCRIPTION
**Pull request by fjeremic**
This readme describes some of the subtleties of setting up Jenkins on
z/OS to work with pipelines which are checked into a git repository.

Signed-off-by: Filip Jeremic <fjeremic@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
Huge thanks to @AdamBrousseau for helping with debugging this issue.

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@genie-omr build all

**Comment by fjeremic** [comment]
@genie-omr build zlinux

**Comment by fjeremic** [comment]
@genie-omr build zos

**Comment by charliegracie** [comment]
Thank you for documenting this is the codebase so we do not lose it!

**Pull request merged**
