### PR TITLE
Remove deprecated gtest 1.7.0 source

### PR DESCRIPTION
**Pull request by Varun-garg**
Simply remove gtest 1.7 files in favor of 1.8.

Issue: #2176
Signed-off-by: Varun Garg <varun.10@live.com>

### CODE REVIEW

**Comment by youngar** [comment]
@smlambert Any reason we need to keep around the old gtest?

**Comment by youngar** [comment]
@genie-omr build all

**Comment by smlambert** [comment]
Believe no reason to keep, think that it was kept in case there were problems encountered with upgrading to 1.8 - FYI @renfeiw please correct me if I am wrong.

**Comment by youngar** [comment]
Thanks @Varun-garg!

**Comment by Varun-garg** [comment]
You're  welcome @youngar!

**Pull request merged**
