### PR TITLE
z/OS JIT code cache above 2GB bar #756

### PR DESCRIPTION
**Pull request by pdbain-ibm**
Port library changes for z/OS support for JIT code cache above 2GB bar

Add test to detect z/OS V2R3, which has support for RMODE64.
Add function reserve_memory_with_moservices() and modify omrvmem_reserve_memory_ex()
to call it.
Add tracepoints, unit test, and header changes.

Signed-off-by: Peter Bain <pdbain@ca.ibm.com>

### CODE REVIEW

**Comment by pdbain-ibm** [comment]
Commit comment reformatted.

**Comment by fjeremic** [comment]
@pdbain-ibm could you please amend the commit message to conform with our [commit guidelines](https://github.com/eclipse/omr/blob/master/CONTRIBUTING.md#example-commits). More specifically:

> The first line is meaningful and imperative. The body contains enough information that the reader understands the why and how of the commit, and it's relation to any issues. The **issue is properly tagged** and the commit is signed off.
>
>The following is a bad commit:
>
>```
>FIX #124: Changing a couple random things in CONTRIBUTING.md.
>Also, there are some bug fixes in the thread library.
>```
>
>The commit rolls unrelated changes together in a very bad way. There is not enough information for the commit message to be useful. The first line is not meaningful or imperative. The message is not formatted correctly, **the issue is improperly referenced**, and the commit is not signed off by the author.

**Comment by pdbain-ibm** [comment]
You mean "and its relation to" (no apostrophe).  "it's" is an abbreviation
of "it is". The possessive of "it" is "its" (again, no apostrophe).
Please update your documentation.

---------------------------------------------------------------------
Peter Bain
Software Designer, IBM Runtime Technologies
IBM Ottawa Software Lab
3755 Riverside Drive, Ottawa, Ontario, K1V 1B8
613-356-5452
pdbain@ca.ibm.com

**Comment by fjeremic** [comment]
> You mean "and its relation to" (no apostrophe). "it's" is an abbreviation of "it is". The possessive of "it" is "its" (again, no apostrophe). Please update your documentation.

@pdbain-ibm no I meant the bolded parts in my quote, i.e. the reference to the issue should not go in the commit header but in the commit body with a proper key value tag as in the example listed in the commit guidelines. Thanks for following up and fixing everything. Much appreciated!

**Pull request merged**
