### PR TITLE
Enable warnings as errors in compiler component on S390

### PR DESCRIPTION
**Pull request by fjeremic**
Address the last warning on z/OS and enable warnings as errors on all S390 platforms.

### CODE REVIEW

**Comment by fjeremic** [comment]
Jenkins build all

**Comment by fjeremic** [comment]
Leaving this in WIP state until I've ran all the testing possible to ensure we don't get build breaks from warnings being treated as errors.

**Comment by fjeremic** [comment]
Jenkins build zos

**Comment by fjeremic** [comment]
Jenkins build zos

**Comment by fjeremic** [comment]
Jenkins build zos

**Comment by fjeremic** [comment]
Jenkins build zos

**Comment by fjeremic** [comment]
Jenkins build zos

**Comment by fjeremic** [comment]
Jenkins build zos

**Comment by fjeremic** [comment]
Jenkins build zos

**Comment by fjeremic** [comment]
Jenkins build zos

**Comment by fjeremic** [comment]
Looks like we are good to go here finally. That last bug took forever to understand and fix.

Jenkins build all

**Comment by fjeremic** [comment]
Rebased to pick up latest fixes.

Jenkins build all

**Comment by fjeremic** [comment]
Removing WIP. This is ready for merge.

**Review by dsouzai — APPROVED** [review]

**Pull request merged**
