### PR TITLE
Use the Test Compiler with Tril tests instead of JitBuilder

### PR DESCRIPTION
**Pull request by Leonardo2718**
The dependency on JitBuilder is broken by only providing the Test
Compiler as a target link library. A few workarounds for JitBuilder's
new client API are also removed. Lastly, the function to initialize the
Test Compiler with specific options is also exposed.

Signed-off-by: Leonardo Banderali <leonardo2718@protonmail.com>

### CODE REVIEW

**Comment by Leonardo2718** [comment]
@genie-omr build all

**Comment by charliegracie** [comment]
Hmmm I thought originally tril was using the `testcompiler` but then it was moved to use `jitbuilder` as we were deprecating the `testcompiler`.  I could very well be confusing this with something different.

**Comment by charliegracie** [comment]
I am also not sure the `testcompiler` is properly compiled on all of the platforms where `jitbuilder` currently compiles.

**Comment by Leonardo2718** [comment]
> Hmmm I thought originally tril was using the `testcompiler` but then it was moved to use `jitbuilder` as we were deprecating the `testcompiler`.

Nope. Tril has always used `jitbuilder` as the default backend, though there was an option added a while ago to use the `testcompiler` as an alternative.

We're deprecated the `testcompiler` tests (IlInjector-based tests) in favour of Tril-based tests. However, the "compiler" part of the `testcompiler` is going to stay because it can still be useful for Tril. (I should really publicize what my plans are to avoid this kind of confusion :stuck_out_tongue: )

> I am also not sure the `testcompiler` is properly compiled on all of the platforms where `jitbuilder` currently compiles.

I'd be surprised if platform support was very different because there's a lot of duplicate code between them.

I believe the test failures we're seeing are due to a few things I just forgot to remove. :sweat_smile:

**Comment by Leonardo2718** [comment]
@genie-omr build plinux, zlinux

**Comment by Leonardo2718** [comment]
@genie-omr build plinux

**Comment by Leonardo2718** [comment]
@genie-omr build plinux

**Comment by Leonardo2718** [comment]
@genie-omr build zlinux

**Comment by Leonardo2718** [comment]
@genie-omr build zlinux

**Comment by Leonardo2718** [comment]
@genie-omr build zlinux, plinux

**Comment by Leonardo2718** [comment]
@genie-omr build zlinux, plinux

**Comment by Leonardo2718** [comment]
@genie-omr build all

**Comment by 0xdaryl** [comment]
Code changes look fine.  Please double check the copyright headers for 2019 on some of the files.

**Comment by Leonardo2718** [comment]
Fixed the few copyright headers I missed.

@genie-omr build all

**Comment by Leonardo2718** [comment]
(AppVeyor build failed because of infrastructural problems. Restarted)

**Pull request merged**
