### PR TITLE
Fix for assertion failure during OMR acceptance build

### PR DESCRIPTION
**Pull request by midronij**
Fixes https://github.com/eclipse-openj9/openj9/issues/15074

Signed-off-by: midronij <jackie.midroni@ibm.com>

### CODE REVIEW

**Comment by midronij** [comment]
@jdmpapin @knn-k when you have a chance could you review/merge? Thanks!

**Comment by jdmpapin** [comment]
Jenkins build plinux,aix

**Review by jdmpapin — APPROVED** [review]

**Comment by pshipton** [comment]
This did not fix the assertions, see the failures in https://openj9-jenkins.osuosl.org/job/Pipeline-OMR-Acceptance/276/
Example https://openj9-jenkins.osuosl.org/job/Test_openjdk8_j9_sanity.functional_ppc64_aix_OMR_testList_0/223/console

**Comment by midronij** [comment]
My bad, looks like I missed part of the problem. https://github.com/eclipse/omr/pull/6522 should fully fix it.

**Pull request merged**
