### PR TITLE
Properly set array related feature flags on X86

### PR DESCRIPTION
**Pull request by 0dvictor**
Guard following feature flags with "canGenerateArraylets":
1. SupportsArrayCmp
2. SupportsPrimitiveArrayCopy
3. SupportsArraySet
4. SupportsArrayTranslateTRTO
5. SupportsArrayTranslateTROT
6. SupportsArrayTranslateTROTNoBreak

Remove SupportsReferenceArrayCopy as OMR doesn't actually
fully support reference arraycopy.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by andrewcraik** [comment]
This change makes sense to me - I assume that the major downstream consumer of these features, OpenJ9, avoids seeing these opcodes by disabling the opts that generate them under arraylets which is why the feature flag misconfiguration wasn't seen by them or do they disable these features themselves?

**Comment by 0dvictor** [comment]
> I assume that the major downstream consumer of these features, OpenJ9, avoids seeing these opcodes by disabling the opts that generate them under arraylets which is why the feature flag misconfiguration wasn't seen by them or do they disable these features themselves?

Yes, consumers of these opcode always check `canGenerateArraylets` before generating the opcode. This proposed changeset won't affect the behavior of existing implementation.

**Comment by andrewcraik** [comment]
LGTM - @0xdaryl as the usual codegen committer could you have a look at this?

**Comment by 0xdaryl** [comment]
@genie-omr build xlinux,win

**Pull request merged**
