### PR TITLE
Cleanup unused Linkage fields and functions

### PR DESCRIPTION
**Pull request by 0xdaryl**
* Remove unused LocalsAreaBeginOffset and LocalsAreaEndOffset
* Remove unused get/setStackSizeCheckNeeded from Z linkage

### CODE REVIEW

**Comment by 0xdaryl** [comment]
Un-WIPing since downstream dependencies have merged.

**Comment by 0xdaryl** [comment]
Jenkins build zlinux,zos

**Comment by 0xdaryl** [comment]
Jenkins build zos

**Review by dsouzai — APPROVED** [review]

**Comment by dsouzai** [comment]
Gonna re-trigger z/OS just because it's been a while and also to see if the issue seen on https://github.com/eclipse/omr/pull/6362 shows up here too.

**Comment by dsouzai** [comment]
Jenkins build zos

**Comment by dsouzai** [comment]
The failing tests are the same as in https://github.com/eclipse/omr/pull/6362 so unrelated to the changes in this PR.

**Comment by dsouzai** [comment]
Opened https://github.com/eclipse/omr/issues/6368 for z/OS issues

**Pull request merged**
