### PR TITLE
Loop versioner support for dynamic checkcast

### PR DESCRIPTION
**Pull request by yanluo7**
Currently when collecting checkcast nodes for loop invariant detection, loop versioner asserts the cast class should always be a loadaddr. With the upcoming CFG simplifier change, the cast class child can be dynamic. So this restriction is removed to allow versioner to detect loop invariant for dynamic checkcast nodes as well. The existing infrastructure appears to be already in-place to handle the new cases.

Signed-off-by: Yan Luo <Yan_Luo@ca.ibm.com>

### CODE REVIEW

**Comment by yanluo7** [comment]
@jdmpapin hi Devin, could you review?

**Comment by andrewcraik** [comment]
looks good - over to @vijaysun-omr

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by yanluo7** [comment]
@vijaysun-omr should be ready to merge.

**Comment by vijaysun-omr** [comment]
I assume you have tested this new code path ? I doubt there is much testing in our existing buckets that even gets us to the point where such a checkcast without a constant class second child is generated.

**Comment by yanluo7** [comment]
@vijaysun-omr This has gone through personal builds which have dynamic checkcast enabled to test the code path.

**Comment by vijaysun-omr** [comment]
Thanks, checks have passed and reviews are done. Merging.

**Pull request merged**
