### PR TITLE
Revert "Link and compile with -pthread"

### PR DESCRIPTION
**Pull request by youngar**
Reverts eclipse/omr#1352

### CODE REVIEW

**Comment by charliegracie** [comment]
This is just reverting the previous change using the "revert PR" button so I am going to accept it without waiting for the build to complete.

**Comment by charliegracie** [comment]
The IP Test will always fail on the revert PRs so it is not expected to pass

**Comment by charliegracie** [comment]
eclipse/omr#1352 was breaking CMake builds.  Cmake builds are currently not make as required to pass so it was not noticed that they were broken.  This PR reverts the PR which was causing CMake failures and the original PR is being investigated by the committer to resolve the issue as it was CMake specific.

**Comment by charliegracie** [comment]
Here is a direct link to the failing travis build:
https://travis-ci.org/eclipse/omr/jobs/254967590

**Comment by rwy0717** [comment]
The issue was that `-pthread` wasn’t in the link flags, causing missing symbols.`add_definitions()` only affects the compile flags.

**Pull request merged**
