### PR TITLE
Remove cacheStringAppend from VPHandlersCommon

### LINKED ISSUE #4072: Remove cacheStringAppend from VPHandlersCommon.cpp
`cacheStringAppend` is a not-insignificant function in VPHandlersCommon.cpp that has been disabled for over 10 years (I did the archaeology on it prior to open source) and in fact has never been enabled.

https://github.com/eclipse/omr/blob/dc661ac3685e4b9c09020a286a56c987eccd0749/compiler/optimizer/VPHandlersCommon.cpp#L173

This should be enough justification for removing it and any supporting logic it needs.  @vijaysun-omr  @andrewcraik please confirm.

### PR DESCRIPTION
**Pull request by 0xdaryl**
Optimization is vestigal and not used.  Remove it and all associated
code and data structures.

Closes #4072 

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@vijaysun-omr @andrewcraik

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by vijaysun-omr** [comment]
I believe this code was only a prototype but can you point out the place where it used to be disabled by default ? This would reassure me that there are no side effects of the code being deleted at all.

**Comment by 0xdaryl** [comment]
The first statement of `cacheStringAppend` unconditionally returns 0, thereby circumventing all of its logic.  This return has been in place since the introduction of this code.

https://github.com/eclipse/omr/blob/b2ea2c7aadbfac03dc474b8a70db705ecddb6aa0/compiler/optimizer/VPHandlersCommon.cpp#L175

**Comment by vijaysun-omr** [comment]
Okay thanks, looks like fairly straightforward cleanup then. Merging.

**Pull request merged**
