### PR TITLE
Use failCompilation to fail compilations

### PR DESCRIPTION
**Pull request by dsouzai**
Before the error handling story of the OMR Compiler was changed to throw specific C++ exceptions, the outOfMemory call was used to do so. This call would first write a specified error message to the traceLog but would also write to stderr under an option before throwing a generic exception. This PR introduces a template method called failCompilation that will handle writing a specified message to the tracelog/stderr and throw an exception specified by the template parameter.

### CODE REVIEW

**Comment by dsouzai** [comment]
Since, this PR introduces a template method, I've verified that the size of the binary on various platforms are not greatly increased.

**Comment by dsouzai** [comment]
@mpirvu Could you please review.

**Comment by dsouzai** [comment]
It varied on different platforms. However, the maximum increase was ~4KB.

**Comment by mpirvu** [comment]
I am guessing that is size on disk so RSS increase could be lower.
I am ok with the change.

**Comment by dsouzai** [comment]
I can try doing some startup/footprint analysis to see what changes are there before I ask Vijay to accept these changes since the template method will also be used in the J9 Project code in addition to the code here in OMR.

**Comment by dsouzai** [comment]
I used Liberty to measure footprint on ppcle linux and it looks like this change doesn't have any impact on footprint size.

As such, @vijaysun-omr I believe it should be ok to accept this PR if everything looks good to you too.

**Pull request merged**
