### PR TITLE
Fix child handling in SIMDsplatsEvaluator on x86

### PR DESCRIPTION
**Pull request by IBMJimmyk**
The child of a vsplats node can return either a TR_GPR or TR_FPR register
on evaluation. Only the TR_FPR case was being handled correctly.

This change adds a MOVD / MOVQ instuction to transfer the data from the
TR_GPR register into a TR_VRF register which is compatible with the
pshufd instruction used to perform the actual splating.

Issue: #1465
Signed-off-by: jimmyk <jimmyk@ca.ibm.com>

### CODE REVIEW

**Comment by IBMJimmyk** [comment]
@0dvictor could you review this code change to make sure there aren't any problems?

**Comment by vijaysun-omr** [comment]
@0dvictor any update on reviewing this ?

**Comment by 0dvictor** [comment]
Sorry about the delay. The changes are simple and reasonable. LGTM.

**Comment by andrewcraik** [comment]
@vijaysun-omr back to you now that @0dvictor has approved it. LGTM from me too.

**Comment by vijaysun-omr** [comment]
Merging this since it looks straightforward to me too.

**Pull request merged**
