### PR TITLE
Change OMR::Options fields from private to protected

### PR DESCRIPTION
**Pull request by harryyu1994**
- need access to OMR::Options private fields in a downstream project

Signed-off-by: Harry Yu <harryyu1994@gmail.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
I'd like to see an explanation of why this is required in the commit body.

**Comment by harryyu1994** [comment]
FYI @mpirvu @0xdaryl

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Comment by harryyu1994** [comment]
The downstream project wants to have read access to log files, I'm wondering if we could allow this minor change.

**Comment by 0xdaryl** [comment]
@genie-omr build all

**Pull request merged**
