### PR TITLE
Begin to remove FrontEnd dependence on CCM

### PR DESCRIPTION
**Pull request by 0xdaryl**
Begin to eliminate `OMR::CodeCacheManager` dependence on deprecated FrontEnd functionality by either eliminating it outright or refactoring the FrontEnd functionality into it's own class.

### CODE REVIEW

**Comment by 0xdaryl** [comment]
I found a potential problem.  This isn't quite ready to merge yet.

**Comment by vijaysun-omr** [comment]
The 3 routines in VMMethodEnv currently were chosen because of their relationship to code cache management ? Would you be proactively moving more of the front end functionality to the class as well ?

**Comment by 0xdaryl** [comment]
Yes.  These were just the first few chosen based on their simplicity.  I have other PRs that will move more of the FrontEnd TR_OpaqueMethodBlock functions to this class.

**Comment by vijaysun-omr** [comment]
Thanks. Was there something about this class that made you consider making it extensible (as opposed to a class inheritance/virtual method approach ?) Just wanted to get that reasoning made explicit so that we can make a choice based on the right criteria in other cases in the future.

**Comment by 0xdaryl** [comment]
The decision to make this class extensible follows the same reasoning as many of the other compiler classes within the base OMR project:  for encapsulation and performance.

This technique uses static polymorphism and allows each compiler project derived from OMR to encapsulate its own custom functionality within its own extension class without introducing those functions in the topmost OMR layer.  By making it extensible it also follows the precedent of each of the other classes that compose a CompilerEnv class.

Making the functions in VMMethodEnv virtual would have also added an extra level of indirection on each function call (the first being to find the VMMethodEnv instance on the CompilerEnv structure, and the second being the dispatch through vtable for the function).  Using extensible classes makes each of these function calls direct and determinable at compile-time.

**Comment by vijaysun-omr** [comment]
Thanks for the summary. Merging now.

**Pull request merged**
