### PR TITLE
Add initializeStatusFromClassSymbol

### PR DESCRIPTION
**Pull request by liqunl**
Add enum and name string for initializeStatusFromClassSymbol.

Signed-off-by: liqunl <liqunl@ca.ibm.com>

### CODE REVIEW

**Comment by liqunl** [comment]
@andrewcraik Can you review this change when you have time?

**Comment by andrewcraik** [comment]
Since the lists you are modifying have not been made extensible yet, the change looks fine to me since the addition is a variation on the other entries around it there. @vijaysun-omr may have other thoughts though...

**Comment by andrewcraik** [comment]
@vijaysun-omr ping?

**Comment by vijaysun-omr** [comment]
Trivial change. Merging now that checks have also passed.

**Pull request merged**
