### PR TITLE
Update/Enable PortSigTest(s)

### PR DESCRIPTION
**Pull request by babsingh**
Refer to the individual commits for more details.

Signed-off-by: Babneet Singh <sbabneet@ca.ibm.com>

### CODE REVIEW

**Comment by youngar** [comment]
@genie-omr build all

**Comment by youngar** [comment]
```
020-06-11T17:01:31.6187381Z D:\a\1\s\fvtest\porttest\omrsignalTest.cpp(144): error C3861: 'kill': identifier not found [D:\a\1\s\build\fvtest\porttest\omrporttest.vcxproj]
2020-06-11T17:01:31.6193084Z D:\a\1\s\fvtest\porttest\omrsignalTest.cpp(175): error C3861: 'strtok_r': identifier not found [D:\a\1\s\build\fvtest\porttest\omrporttest.vcxproj]
2020-06-11T17:01:31.6194679Z D:\a\1\s\fvtest\porttest\omrsignalTest.cpp(178): error C3861: 'strtok_r': identifier not found [D:\a\1\s\build\fvtest\porttest\omrporttest.vcxproj]
2020-06-11T17:01:31.6197273Z D:\a\1\s\fvtest\porttest\omrsignalTest.cpp(181): error C3861: 'strtok_r': identifier not found [D:\a\1\s\build\fvtest\porttest\omrporttest.vcxproj]
2020-06-11T17:01:31.6198874Z D:\a\1\s\fvtest\porttest\omrsignalTest.cpp(185): error C3861: 'strtok_r': identifier not found [D:\a\1\s\build\fvtest\porttest\omrporttest.vcxproj]
2020-06-11T17:01:31.6346260Z D:\a\1\s\fvtest\porttest\omrsignalTest.cpp(1259): error C3861: 'getpid': identifier not found [D:\a\1\s\build\fvtest\porttest\omrporttest.vcxproj]
2020-06-11T17:01:31.6349810Z D:\a\1\s\fvtest\porttest\omrsignalTest.cpp(1267): warning C4244: '=': conversion from 'intptr_t' to 'int32_t', possible loss of data [D:\a\1\s\build\fvtest\porttest\omrporttest.vcxproj]
2020-06-11T17:01:31.6387242Z D:\a\1\s\fvtest\porttest\omrsignalTest.cpp(1306): error C3861: 'getpid': identifier not found [D:\a\1\s\build\fvtest\porttest\omrporttest.vcxproj]
2020-06-11T17:01:31.6395873Z D:\a\1\s\fvtest\porttest\omrsignalTest.cpp(1313): warning C4244: '=': conversion from 'intptr_t' to 'int32_t', possible loss of data [D:\a\1\s\build\fvtest\porttest\omrporttest.vcxproj]
2020-06-11T17:01:31.6596850Z D:\a\1\s\fvtest\porttest\omrsignalTest.cpp(1351): error C3861: 'getpid': identifier not found [D:\a\1\s\build\fvtest\porttest\omrporttest.vcxproj]
2020-06-11T17:01:31.7029623Z D:\a\1\s\fvtest\porttest\omrsignalTest.cpp(1358): warning C4244: '=': conversion from 'intptr_t' to 'int32_t', possible loss of data 
```

**Comment by youngar** [comment]
Please update copyright date in omrsignalTest.cpp

**Comment by babsingh** [comment]
@genie-omr build all

**Comment by babsingh** [comment]
@genie-omr build all

**Comment by babsingh** [comment]
@genie-omr build all

**Comment by babsingh** [comment]
@genie-omr build all

**Comment by babsingh** [comment]
@youngar The copyright has been updated. These changes are complete from my end. I had started the build jobs for the latest changes. Hoping that all the jobs will pass. Please let me know if you have any feedback. The PR has been divided into small easy-to-review commits.

**Summary:**
1) One old test, `sig_test_async_handler`, was modified to work on Windows. It was previously designed to run only on Unix platforms.
2) Three new tests are added which are a variant of `sig_test_async_handler`: `sig_test_single_async_handler`, `sig_test_mix_async_handler` and  `sig_test_mix_two_async_handlers`.
3) Other changes include formatting and extending support for the above tests across all platforms.
4) `OMR_PORT_ASYNC_HANDLER` couldn't be enabled on Windows due to a unrelated hang in `ThreadAbortDeathTest`, which is reported in https://github.com/eclipse/omr/pull/5304.

**Comment by keithc-ca** [comment]
This seems a little extreme: 23 commits to change two(2) files.

**Comment by babsingh** [comment]
> From keithc-ca, 1742 hrs, 17 Jun 20: This seems a little extreme: 23 commits to change two(2) files.

@keithc-ca It's a valid question, and it didn't need to be deleted. I did feel that some of the commits could be squashed, which would reduce the total number of commits. In this case, I didn't invest time to reduce the number of commits in order to save my time and redirect it towards other high priority tasks. Since a concern has been shown now, I will make sure that there is a balance between the commits, code changes and files edited in my future pull requests.

**Comment by babsingh** [comment]
> Why there are a high number of commits to start with?

There are no OMR/CMake personal builds. Also, I didn't have access to a Window's machine to build and test my OMR changes. I had to rely upon the PR builds to get a clean build on Windows. I was addressing Windows failures incrementally by re-running PR builds. During each rerun, I created a commit(s) to address the current failures. After many failures and reruns, the number of commits just exploded.

**Pull request merged**
