### PR TITLE
Detect new Intel X86 microarchitecture

### PR DESCRIPTION
**Pull request by 0dvictor**
1. Detect Skylake based Intel X86 CPU;
2. Inline logic querying old Intel CPUs.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by vijaysun-omr** [comment]
I assume "inlining logic querying old Intel CPUs" is a compile time savings attempt. How much did the change add to the JIT module size ? Just so that we keep an eye on that metric to ensure the tradeoff was a good one.

**Comment by 0xdaryl** [comment]
I agree with getting rid of the `isIntelOldMachine` query from OMR.  The naming isn't great because "Old" is very much a point-in-time statement, but that's to be dealt with in any code you're sinking this into.

**Comment by 0dvictor** [comment]
`isIntelOldMachine` is only used in one place and hence there should not be any footprint issue by inlining it.

**Comment by 0dvictor** [comment]
`isIntelOldMachine` is on the list of code cleanups. The code querying this function is actually being deprecated and will be removed soon. After that, `isIntelOldMachine` will be deleted as well.

**Pull request merged**
