### PR TITLE
Fold unnecessary FP to Integral type casts

### PR DESCRIPTION
**Pull request by gita-omr**
- fold ibits2f<=>fbits2i and lbits2d<=>dbits2l

### CODE REVIEW

**Comment by gita-omr** [comment]
Need to address some test failures...

**Comment by gita-omr** [comment]
Fixed cases where Nan value has to be normalized, indicated by `normalizeNanValues` flag.

**Comment by gita-omr** [comment]
Jenkins build all

**Comment by gita-omr** [comment]
Jenkins build zos

**Comment by gita-omr** [comment]
Jenkins build win

**Review by jdmpapin — APPROVED** [review]

**Comment by jdmpapin** [comment]
The Linux ppc64le failure is #6556

Jenkins build plinux

**Comment by jdmpapin** [comment]
Jenkins build plinux

**Comment by jdmpapin** [comment]
It doesn't look like we'll be able to dodge the AbsVPValueTest failure. Everything else has passed

**Pull request merged**
