### PR TITLE
Disable zNext on 31-Bit zLinux

### PR DESCRIPTION
**Pull request by r30shah**
Signed-off-by: Rahil Shah <rahil@ca.ibm.com>

### CODE REVIEW

**Comment by r30shah** [comment]
@joransiu  Can I get your review on this change?

**Review by joransiu — COMMENTED** [review]
LGTM.  Though, it's a bit odd from a readabiliy standpoint that the check is added as an else-if case for an unrelated `TR_UseIdleTime` option.

**Comment by r30shah** [comment]
Hmm, Adding a comment to explain this. You are right, it looks odd. But we already set the option for Non LoZ option, so in the else path  (That is LoZ), I just check if it is 31-Bit

**Comment by r30shah** [comment]
@joransiu  I added a comment mentioning that zNext is disabled by default on 31-Bit zLinux for readability. I have manually tested this out on all platform. This one is ready for review

**Review by joransiu — APPROVED** [review]
LGTM.  @0xdaryl , can I ask you to review and merge?

**Comment by 0xdaryl** [comment]
Jenkins build all

**Comment by fredg02** [comment]
jenkins build zos

**Comment by 0xdaryl** [comment]
Jenkins build zos

**Comment by r30shah** [comment]
I do not think z/OS failure is related to this.
```
11:21:57   > /u/jenkins/jenkins-zos/git fetch --tags --progress git@github.com:eclipse/omr.git +refs/pull/6421/merge:refs/remotes/origin/pr/6421/merge # timeout=30
11:18:13  ERROR: Error cloning remote repo 'origin'
11:18:13  hudson.plugins.git.GitException: Command "/u/jenkins/jenkins-zos/git fetch --tags --progress git@github.com:eclipse/omr.git +refs/pull/6421/merge:refs/remotes/origin/pr/6421/merge" returned status code 128:
11:18:13  stdout: FOTS1373 Permission denied (publickey).
11:18:13  fatal: Could not read from remote repository.
11:18:13  
11:18:13  Please make sure you have the correct access rights
11:18:13  and the repository exists.
```

Can we launch zOS build again?

**Comment by r30shah** [comment]
@0xdaryl  Can you launch a build on this change?

**Pull request merged**
