### PR TITLE
CMake: Fix typos in aarch64 spp handling

### PR DESCRIPTION
**Pull request by dnakamura**
Signed-off-by: Devin Nakamura <devinn@ca.ibm.com>

### CODE REVIEW

**Comment by dnakamura** [comment]
@genie-omr  build all

**Comment by dnakamura** [comment]
@genie-omr build all

**Comment by rwy0717** [comment]
@genie-omr build win

**Comment by dnakamura** [comment]
Note windows failure appears to be #5100

**Pull request merged**
