### PR TITLE
Add OMRRSSReport.cpp to all makefiles

### PR DESCRIPTION
**Pull request by gita-omr**

### CODE REVIEW

**Comment by gita-omr** [comment]
fyi: @keithc-ca @dsouzai

**Review by keithc-ca — APPROVED** [review]

**Comment by dsouzai** [comment]
Is this still needed given that https://github.com/eclipse/omr/pull/7406 was merged?

**Comment by keithc-ca** [comment]
> Is this still needed given that #7406 was merged?

After a second look, this doesn't appear to do anything in the context of #7406.

**Comment by gita-omr** [comment]
Sorry, did not see https://github.com/eclipse/omr/pull/7406.

**Pull request closed without merging**
