### PR TITLE
Add missing identity queries to IlType service API

### PR DESCRIPTION
**Pull request by 0xdaryl**
Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@mstoodle : would you mind reviewing this please?

**Comment by 0xdaryl** [comment]
Jenkins build all

**Comment by 0xdaryl** [comment]
Mild throat-clearance on this one @mstoodle.

**Review by mstoodle — APPROVED** [review]
Sorry @0xdaryl I completely missed this one :( . It lgtm

**Pull request merged**
