### PR TITLE
Remove unused and deprecated MayUseVMThread IL OpCode property

### PR DESCRIPTION
**Pull request by 0xdaryl**
Issue: #2256 

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by fjeremic** [comment]
I'm guessing this is a prerequisite on https://github.com/eclipse/openj9/pull/1080?

**Comment by 0xdaryl** [comment]
No.  eclipse/openj9#1080 should be merged first because it removes the use of the flag within OpenJ9.  This PR can merge after that (I'll remove the WIP when the OpenJ9 PR is merged).

**Comment by fjeremic** [comment]
> No. eclipse/openj9#1080 should be merged first because it removes the use of the flag within OpenJ9. This PR can merge after that (I'll remove the WIP when the OpenJ9 PR is merged).

Ah right. Meant to say *post*-requisite. Thanks for explaining.

**Comment by 0xdaryl** [comment]
Removed WIP now that dependent OpenJ9 PR is merged.

**Comment by fjeremic** [comment]
@genie-omr build all

**Pull request merged**
