### PR TITLE
Add specific error codes to replace current error codes in omrsock API

### PR DESCRIPTION
**Pull request by caohaley**
Add more specific error code for omrsock:

- Add all possible returned errno error codes to the omrsock
  port library error codes.
- Add a internal mapping function to map from errno to omrsock
  port library error codes.
- Modify current omrsock.c code to return the more specific error
  codes.

Signed-off-by: Haley Cao <haleycao88@hotmail.com>

### CODE REVIEW

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by rwy0717** [comment]
aix error:
```
[2020-07-13T15:40:43.825Z] "/home/jenkins/workspace/Build/port/unix/omrsock.c", line 271.14: 1506-052 (S) Duplicate case label for value 11. Labels must be unique.
```

**Comment by caohaley** [comment]
I think EWOULDBLOCK and EAGAIN has the same value in AIX. I will fix it and push again.

**Comment by caohaley** [comment]
@rwy0717 Could you run build all again?

**Comment by rwy0717** [comment]
@genie-omr build all

**Comment by rwy0717** [comment]
@genie-omr build all

**Pull request merged**
