### PR TITLE
Stop printing the CMAKE_SRC_DIR when running cmake

### PR DESCRIPTION
**Pull request by youngar**
The message was being printed as a diagnostic.

Signed-off-by: Andrew Young <youngar17@gmail.com>

### CODE REVIEW

**Comment by charliegracie** [comment]
@dnakamura thoughts?

**Comment by dnakamura** [comment]
i don't think we need the flexibility of `PROJECT_SOURCE_DIR`. The code in question checks that you haven't run `configure` in the source tree before, simply as a continence since it creates a lot of weird build failures

**Comment by youngar** [comment]
I removed the change to use `PROJECT_SOURCE_DIR`, since it was unnecessary.  The real point of this change is to remove the diagnostic message.  This is a part of a larger set of changes to clean up and reduce the output from when running cmake.

**Comment by charliegracie** [comment]
@genie-omr build all

**Pull request merged**
