### PR TITLE
Don't mark derived files as .PHONY

### PR DESCRIPTION
**Pull request by keithc-ca**
Marking files as .PHONY will cause make to assume the files have changed even if they have not, leading to unnecessary rebuilds.

### CODE REVIEW

**Comment by charliegracie** [comment]
Since the static makefiles are close to being obsolete is this change required? Hopefully we can remove the compiler component static makefiles and the OMR autotools support soon and only support CMake

**Comment by keithc-ca** [comment]
The static makefiles are still in use by openj9.

**Comment by Leonardo2718** [comment]
One thing I will note is that the makefiles modified in this PR are not actually used by OpenJ9 so they will be fairly straighforward to remove. Hopefully, I will be deleting them very soon once we have fully migrated to cmake.

That said, this change is small and unintrusive so I am ok with it. I just don't want anyone putting in any significant effort maintaining these files. :wink:

**Comment by charliegracie** [comment]
I see no reason why not to just merge this as is. @Leonardo2718 or @0xdaryl are you ok with this?

**Comment by youngar** [comment]
@genie-omr build all

**Comment by youngar** [comment]
Lots of connection problems to the test machines

**Comment by charliegracie** [comment]
@genie-omr build all

**Pull request merged**
