### PR TITLE
Changing default behavior for compilation aggressiveness level 3(AGGRESSIVE_AOT)

### PR DESCRIPTION
**Pull request by mpirvu**
The new default options provide a better balance between CPU
consumed for compilation and throughput.

Signed-off-by: Marius Pirvu <mpirvu@ca.ibm.com>

### CODE REVIEW

**Comment by mstoodle** [comment]
If this is meant to be just a good change, then I would prefer the title not refer to changing the IBM JDK. Maybe something like "Improve balance between CPU consumed and throughput for virtualized environments". Plus the commit message could describe in a bit more detail the configuration options that are being adjusted and why the changes improve the balance. Without referencing the IBM SDK for Java, if possible.

**Comment by mpirvu** [comment]
I had a hard time describing this change because it has little to do with OMR. 

It is misleading to say that the change improves behavior in a virtualized environment. All it does is to affect the behavior of Xtune:virtualized option which is decoupled from the presence of a virtualized environment (all 4 combinations are possible). Thus, I was compelled to mention about Xtune:virtualized.
Now, this option is meaningful only to the IBM JDK; OpenJDK does not have it and other languages don't use it (though in theory they could). I felt that, by not specifying IBM JDK, people might ask "where is this option coming from?" and "how does this change-set affect my application?".  Ideally I should have mentioned Open J9, but such a thing does not exist yet.

I can describe what configuration options are adjusted, though that is apparent from the code. The question is how much I should describe what those other options do. I was also debating whether or not to show concrete numbers on concrete benchmarks (I have a full RTC item on the topic, but what good is RTC in the open?). In the end I decided not to because the change is IBM Java specific. Even if other languages in the future will implement Xtune:virtualized, they will have to re-tune its behavior.

I'll come up with another commit message and run it by you.

**Comment by vijaysun-omr** [comment]
Could you please explain the movement of some of default option settings code to be earlier in jitPreProcess in this commit ?

It seems the travis-ci build was unsuccessful (?)

**Comment by mpirvu** [comment]
There are two reasons for moving some options up:
1) Keep all options related to inlining together
2) Setting default options values after the code that deals with aggressivenessLevels may override settings specific to a particular aggressivenessLevel.

travis-ci passed on my first attempt. In the second attempt I only changed the commit message and it failed with
Assertion failed at ../compiler/optimizer/GlobalRegisterAllocator.cpp:2829: 0
	couldn't find the global register
compiling src/StructArray.cpp:98:testReadStructArray at level: warm

I don't think this is due to my change.

**Comment by vijaysun-omr** [comment]
I think the GRA issue is unrelated to your changes and I believe that it is being worked on (I believe it only happens on OSX).

**Pull request merged**
