### PR TITLE
Remove TR_DebugExt

### PR DESCRIPTION
**Pull request by dsouzai**
See https://github.com/eclipse-openj9/openj9/issues/12520

This should not be merged before https://github.com/eclipse-openj9/openj9/pull/12765

Closes https://github.com/eclipse-openj9/openj9/issues/12520

### CODE REVIEW

**Comment by dsouzai** [comment]
@fjeremic do you mind being committer for this one?

**Review by fjeremic — APPROVED** [review]

**Comment by fjeremic** [comment]
Jenkins build all

**Comment by dsouzai** [comment]
```
22:32:15  24: Test command: /home/jenkins/qemu/build/qemu-riscv64 "-L" "/home/jenkins/riscv-debian/rootfs" "/home/jenkins/workspace/Build/build/fvtest/gctest/omrgctest" "--gtest_filter=gcFunctionalTest*" "--gtest_output=xml:/home/jenkins/workspace/Build/build/fvtest/gctest/omrgctest-results.xml"
22:32:15  24: Test timeout computed to be: 10000000
22:32:15  24: Note: Google Test filter = gcFunctionalTest*
22:32:15  24: [==========] Running 8 tests from 1 test case.
22:32:15  24: [----------] 8 tests from gcFunctionalTest/GCConfigTest
22:32:27  Terminated
22:32:27  script returned exit code 143
```
Does not look related to these changes.

**Comment by fjeremic** [comment]
Yeah seems fine. Just need to sort out downstream dependencies and we can get this in.

**Pull request merged**
