### PR TITLE
Add a direct method call relocation and clean up some related code

### PR DESCRIPTION
**Pull request by ymanton**
This PR adds a new relocation identifier, `TR_MethodCallAddress` and uses it during BinaryEncoding on x86 to create the corresponding project-specific relocation on direct call instructions. The implementation will be downstream, but the high level description is that it will be used to relocate direct calls where the call target is known at compile time but the address of the call instruction is not, thereby necessitating the use of a relocation to generate the appropriate relative offset for the call once its position is known.

Also included are some self-explanatory cleanups.

FYI @mpirvu.

### CODE REVIEW

**Comment by Leonardo2718** [comment]
The changes seems reasonable to me.

I don't quite see why the implementation needs to be downstream. From the description given, it seems like a general implementation usable by most downstream projects should be possible. I can see uses for this new relocation in OMR, so I'd like to understand what is limiting the implementation.

**Comment by ymanton** [comment]
The implementation is downstream because all of the other implementations are downstream. :grin:

What exists at the OMR level is the compile-time representation of external relocations of various kinds (i.e. the `TR::ExternalRelocation` class and the `TR_ExternalRelocationTargetKind` enum) and their creation at binary encoding time, but that alone isn't enough. There's no code in the OMR compiler to emit, consume, or apply any of these external relocations, that's all currently done per-downstream project.

**Comment by Leonardo2718** [comment]
> The implementation is downstream because all of the other implementations are downstream. :grin:

I see. I suppose that's a fair reason.

I would still like to see this functionality added to OMR eventually because there is a need for it.

That's said, I'm not familiar enough with the code to know whether it makes sense to do that in this change or whether it is even feasible. So, I won't push to hard for it here. :slightly_smiling_face:

**Comment by ymanton** [comment]
Copyrights have been updated.

**Comment by vijaysun-omr** [comment]
Is the addition of this direct call relocation something that non-X86 ones code generators need to be aware of ? I want to just understand if this is a functional requirement; maybe direct calls have to be treated as unresolved without this relocation and if so, it won't be a functional requirement...more of a way to improve AOT performance when done on the other codegens as well (?)

**Comment by ymanton** [comment]
No, other code generators and will not need to be aware of it, they need to explicitly create this relocation during their binary encoding passes. And yes, direct calls are currently treated as unresolved by all of the OpenJ9 codegens in AOT mode, so they won't ever reach this code unless/until they decide to take advantage of it.

**Comment by vijaysun-omr** [comment]
fyi @dsouzai @r30shah @gita-omr @fjeremic of this change and the AOT use case.

**Comment by dsouzai** [comment]
> And yes, direct calls are currently treated as unresolved by all of the OpenJ9 codegens in AOT mode, so they won't ever reach this code unless/until they decide to take advantage of it.

Actually, in AOT w/ SVM, direct calls are treated as a resolved interpreted call; with the SVM, nothing is implicitly unresolved under AOT.

**Pull request merged**
