### PR TITLE
Remove deprecated dumpInline() function

### PR DESCRIPTION
**Pull request by 0xdaryl**
This was deprecated in a downstream project and can now be removed
from OMR.

Signed-off-by: Daryl Maier <maier@ca.ibm.com>

### CODE REVIEW

**Comment by 0xdaryl** [comment]
@vijaysun-omr : would mind merging this minor cleanup item please?  Not urgent.  It is the OMR cleanup piece to removing the obsolete inlining dump in OpenJ9 we did last fall.

**Comment by vijaysun-omr** [comment]
jenkins build all

**Comment by vijaysun-omr** [comment]
jenkins build riscv

**Review by vijaysun-omr — APPROVED** [review]

**Comment by vijaysun-omr** [comment]
Cleanup work that has passed testing now. Merging.

**Pull request merged**
