### PR TITLE
Unify doRegisterAssignment on all platforms except x86

### PR DESCRIPTION
**Pull request by fjeremic**
See commit messages for details on what was done. Unfortunately on x86 we seem to be doing something completely different from all the other platforms, so in general tackling register allocation on x86 will need to be done separately.

Fixes: #5977

### CODE REVIEW

**Comment by fjeremic** [comment]
Jenkins build all

**Comment by fjeremic** [comment]
Jenkins build all

**Comment by fjeremic** [comment]
Tested internally as well. This is ready to go. Suggesting @0xdaryl as committer.

**Comment by fjeremic** [comment]
Jenkins build riscv

**Comment by fjeremic** [comment]
I have another RA related PR which is dependent on this getting merged. Looking forward to reviews. I will try my best to address things swiftly.

**Comment by fjeremic** [comment]
@0xdaryl putting this one on your radar as I have dependant work on this PR for more unification.

**Review by 0xdaryl — APPROVED** [review]

**Pull request merged**
