### PR TITLE
Introduce an enum entry for read barrier helper

### PR DESCRIPTION
**Pull request by 0dvictor**
Requested by OpenJ9, an new helper enum TR_readBarrier is introduced.

Signed-off-by: Victor Ding <dvictor@ca.ibm.com>

### CODE REVIEW

**Comment by 0dvictor** [comment]
@vijaysun-omr Could you review this change?

**Comment by vijaysun-omr** [comment]
@genie-omr build all

**Comment by 0dvictor** [comment]
AppVeyor failure is infra and hence not related to this change. OMR sanity tests all passed.

**Comment by vijaysun-omr** [comment]
Simple infrastructural change. Lone failing check is infra related. Merging.

**Pull request merged**
